SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO




CREATE proc [dbo].[cvsp_CMS_PR_UpdateSource] (@fromco smallint, @toco smallint, 
	@errmsg varchar(1000) output, @rowcount bigint output) 
as



/**

=========================================================================
Copyright © 2009 Viewpoint Construction Software (VCS)
The TSQL code in this procedure may not be reproduced, copied, modified,
or executed without written consent from VCS.
=========================================================================
	Title:		Update CMS source tables - PR
	Created:	10.25.09
	Created by:	JJH
	Revisions:	1. None
*/

set @errmsg='';
set @rowcount=0;

--Declare Variables for functions
Declare @JobFormat varchar(30)
Set @JobFormat =  (Select InputMask from vDDDTc where Datatype = 'bJob')





-- add new trans
BEGIN TRAN
BEGIN TRY

delete CV_CMS_SOURCE.dbo.PRTTCH where CHECKDATE=0;

update CV_CMS_SOURCE.dbo.PRTTCH set Mth =
convert(smalldatetime,(substring(convert(nvarchar(max),CHECKDATE),1,4)+'/'+substring(convert(nvarchar(max),CHECKDATE),5,2) +'/01'))
where CHECKDATE <> 0;
/*
update PRTTCE set Mth =
convert(smalldatetime,(substring(convert(nvarchar(max),CHECKDATE),1,4)+'/'+substring(convert(nvarchar(max),CHECKDATE),5,2) +'/01'))
where CHECKDATE <> 0;
*/
update CV_CMS_SOURCE.dbo.PRTMED set Mth =
convert(smalldatetime,(substring(convert(nvarchar(max),CHECKDATE),1,4)+'/'+substring(convert(nvarchar(max),CHECKDATE),5,2) +'/01'))
where CHECKDATE <> 0;

update CV_CMS_SOURCE.dbo.PRTMUN set Mth = 
convert(smalldatetime,(substring(convert(nvarchar(max),t.CHECKDATE),1,4)+'/'+substring(convert(nvarchar(max),t.CHECKDATE),5,2) +'/01'))
from CV_CMS_SOURCE.dbo.PRTMUN
left join (select COMPANYNUMBER, EMPLOYEENUMBER, CHECKNUMBER, CHECKDATE from CV_CMS_SOURCE.dbo.PRTHST
)as t on 
PRTMUN.COMPANYNUMBER=t.COMPANYNUMBER and PRTMUN.EMPLOYEENUMBER=t.EMPLOYEENUMBER 
and PRTMUN.CHECKNUMBER=t.CHECKNUMBER
where CV_CMS_SOURCE.dbo.PRTMUN.JOURNALDATE <> 0;


update CV_CMS_SOURCE.dbo.PRTMAJ set Mth = 
case 
when CV_CMS_SOURCE.dbo.PRTMAJ.CHECKDATE=0 then 
convert(smalldatetime,(substring(convert(nvarchar(max),t.CHECKDATE),1,4)+'/'+substring(convert(nvarchar(max),t.CHECKDATE),5,2) +'/01'))
else
convert(smalldatetime,(substring(convert(nvarchar(max),PRTMAJ.CHECKDATE),1,4)+'/'+substring(convert(nvarchar(max),PRTMAJ.CHECKDATE),5,2) +'/01'))
end
from CV_CMS_SOURCE.dbo.PRTMAJ
left join (select COMPANYNUMBER, EMPLOYEENUMBER, WEEKENDDATE, CHECKNUMBER, CHECKDATE from CV_CMS_SOURCE.dbo.PRTHST
 )as t on 
PRTMAJ.COMPANYNUMBER=t.COMPANYNUMBER and PRTMAJ.EMPLOYEENUMBER=t.EMPLOYEENUMBER 
and PRTMAJ.CHECKNUMBER=t.CHECKNUMBER
where PRTMAJ.JOURNALDATE <> 0;


update CV_CMS_SOURCE.dbo.PRTHST set Mth =
convert(smalldatetime,(substring(convert(nvarchar(max),CHECKDATE),1,4)+'/'+substring(convert(nvarchar(max),CHECKDATE),5,2) +'/01'))
where CHECKDATE <> 0;

update CV_CMS_SOURCE.dbo.HRTMBN set Mth =
convert(smalldatetime,(substring(convert(nvarchar(max),CHECKDATE),1,4)+'/'+substring(convert(nvarchar(max),CHECKDATE),5,2) +'/01'))
where CHECKDATE <> 0;







--Add Week End Date - used for insurance earnings (regular not negative)
--PRPDED WkEndDate
update CV_CMS_SOURCE.dbo.PRPDED set WkEndDate=substring(convert(nvarchar(max),DDTUL),5,2) 
				+ '/' + substring(convert(nvarchar(max),DDTUL),7,2) + '/' 
				+ substring(convert(nvarchar(max),DDTUL),1,4)
FROM CV_CMS_SOURCE.dbo.PRPDED
where DDTUL<>0


/************************** Begin Update Pay Sequences *********************/

--PRTTCH
update CV_CMS_SOURCE.dbo.PRTTCH set PaySeq=S.PAYSEQ
from CV_CMS_SOURCE.dbo.PRTTCH
	JOIN (SELECT COMPANYNUMBER, WkEndDate, EMPLOYEENUMBER, CHECKDATE, CHECKNUMBER,
			PAYSEQ=dense_rank()over (partition by PRTTCH.COMPANYNUMBER, PRTTCH.WkEndDate, 
			PRTTCH.EMPLOYEENUMBER
			order by PRTTCH.COMPANYNUMBER, PRTTCH.WkEndDate, PRTTCH.CHECKDATE, PRTTCH.EMPLOYEENUMBER,
							PRTTCH.CHECKNUMBER)
			FROM CV_CMS_SOURCE.dbo.PRTTCH 
			GROUP BY COMPANYNUMBER, WkEndDate, EMPLOYEENUMBER, CHECKDATE, CHECKNUMBER)
			AS S
			ON S.COMPANYNUMBER=CV_CMS_SOURCE.dbo.PRTTCH.COMPANYNUMBER AND
			S.WkEndDate=CV_CMS_SOURCE.dbo.PRTTCH.WkEndDate AND
			S.EMPLOYEENUMBER=CV_CMS_SOURCE.dbo.PRTTCH.EMPLOYEENUMBER AND
			S.CHECKDATE=CV_CMS_SOURCE.dbo.PRTTCH.CHECKDATE AND
			S.CHECKNUMBER=CV_CMS_SOURCE.dbo.PRTTCH.CHECKNUMBER



--PRTHST
update CV_CMS_SOURCE.dbo.PRTHST set PaySeq=S.PAYSEQ
FROM CV_CMS_SOURCE.dbo.PRTHST
JOIN (SELECT COMPANYNUMBER, WkEndDate, EMPLOYEENUMBER, CHECKDATE, CHECKNUMBER,
			PAYSEQ=dense_rank()over (partition by COMPANYNUMBER, WkEndDate, 
			EMPLOYEENUMBER
			order by COMPANYNUMBER, WkEndDate, CHECKDATE, EMPLOYEENUMBER,
							CHECKNUMBER)
			FROM CV_CMS_SOURCE.dbo.PRTHST 
			GROUP BY COMPANYNUMBER, WkEndDate, EMPLOYEENUMBER, CHECKDATE, CHECKNUMBER)
			AS S
			ON S.COMPANYNUMBER=CV_CMS_SOURCE.dbo.PRTHST.COMPANYNUMBER AND
			S.WkEndDate=CV_CMS_SOURCE.dbo.PRTHST.WkEndDate AND
			S.EMPLOYEENUMBER=CV_CMS_SOURCE.dbo.PRTHST.EMPLOYEENUMBER AND
			S.CHECKDATE=CV_CMS_SOURCE.dbo.PRTHST.CHECKDATE AND
			S.CHECKNUMBER=CV_CMS_SOURCE.dbo.PRTHST.CHECKNUMBER


--PRTMUN
update CV_CMS_SOURCE.dbo.PRTMUN set PaySeq=S.PAYSEQ
FROM CV_CMS_SOURCE.dbo.PRTMUN
JOIN (SELECT COMPANYNUMBER, WkEndDate, EMPLOYEENUMBER, CHECKDATE, CHECKNUMBER,
			PAYSEQ=dense_rank()over (partition by COMPANYNUMBER, WkEndDate, 
			EMPLOYEENUMBER
			order by COMPANYNUMBER, WkEndDate, CHECKDATE, EMPLOYEENUMBER,
							CHECKNUMBER)
			FROM CV_CMS_SOURCE.dbo.PRTMUN 
			GROUP BY COMPANYNUMBER, WkEndDate, EMPLOYEENUMBER, CHECKDATE, CHECKNUMBER)
			AS S
			ON S.COMPANYNUMBER=CV_CMS_SOURCE.dbo.PRTMUN.COMPANYNUMBER AND
			S.WkEndDate=CV_CMS_SOURCE.dbo.PRTMUN.WkEndDate AND
			S.EMPLOYEENUMBER=CV_CMS_SOURCE.dbo.PRTMUN.EMPLOYEENUMBER AND
			isnull(S.CHECKDATE,0)=isnull(CV_CMS_SOURCE.dbo.PRTMUN.CHECKDATE,0) AND
			S.CHECKNUMBER=CV_CMS_SOURCE.dbo.PRTMUN.CHECKNUMBER


--PRTMAJ
update CV_CMS_SOURCE.dbo.PRTMAJ set PaySeq=S.PAYSEQ
FROM CV_CMS_SOURCE.dbo.PRTMAJ
JOIN (SELECT COMPANYNUMBER, WkEndDate, EMPLOYEENUMBER, CHECKDATE, CHECKNUMBER,
			PAYSEQ=dense_rank()over (partition by COMPANYNUMBER, WkEndDate, 
			EMPLOYEENUMBER
			order by COMPANYNUMBER, WkEndDate, CHECKDATE, EMPLOYEENUMBER,
							CHECKNUMBER)
			FROM CV_CMS_SOURCE.dbo.PRTMAJ 
			GROUP BY COMPANYNUMBER, WkEndDate, EMPLOYEENUMBER, CHECKDATE, CHECKNUMBER)
			AS S
			ON S.COMPANYNUMBER=CV_CMS_SOURCE.dbo.PRTMAJ.COMPANYNUMBER AND
			S.WkEndDate=CV_CMS_SOURCE.dbo.PRTMAJ.WkEndDate AND
			S.EMPLOYEENUMBER=CV_CMS_SOURCE.dbo.PRTMAJ.EMPLOYEENUMBER AND
			S.CHECKDATE=CV_CMS_SOURCE.dbo.PRTMAJ.CHECKDATE AND
			S.CHECKNUMBER=CV_CMS_SOURCE.dbo.PRTMAJ.CHECKNUMBER


--HRTMBN
update CV_CMS_SOURCE.dbo.HRTMBN set PaySeq=S.PAYSEQ
FROM CV_CMS_SOURCE.dbo.HRTMBN
JOIN (SELECT COMPANYNUMBER, WkEndDate, EMPLOYEENUMBER, CHECKDATE, CHECKNUMBER,
			PAYSEQ=dense_rank()over (partition by COMPANYNUMBER, WkEndDate, 
			EMPLOYEENUMBER
			order by COMPANYNUMBER, WkEndDate, CHECKDATE, EMPLOYEENUMBER,
							CHECKNUMBER)
			FROM CV_CMS_SOURCE.dbo.HRTMBN 
			GROUP BY COMPANYNUMBER, WkEndDate, EMPLOYEENUMBER, CHECKDATE, CHECKNUMBER)
			AS S
			ON S.COMPANYNUMBER=CV_CMS_SOURCE.dbo.HRTMBN.COMPANYNUMBER AND
			S.WkEndDate=CV_CMS_SOURCE.dbo.HRTMBN.WkEndDate AND
			S.EMPLOYEENUMBER=CV_CMS_SOURCE.dbo.HRTMBN.EMPLOYEENUMBER AND
			S.CHECKDATE=CV_CMS_SOURCE.dbo.HRTMBN.CHECKDATE AND
			S.CHECKNUMBER=CV_CMS_SOURCE.dbo.HRTMBN.CHECKNUMBER


--PRTMED
update CV_CMS_SOURCE.dbo.PRTMED set PaySeq=S.PAYSEQ
FROM CV_CMS_SOURCE.dbo.PRTMED
JOIN (SELECT COMPANYNUMBER, WkEndDate, EMPLOYEENUMBER, CHECKDATE, CHECKNUMBER,
			PAYSEQ=dense_rank()over (partition by COMPANYNUMBER, WkEndDate, 
			EMPLOYEENUMBER
			order by COMPANYNUMBER, WkEndDate, CHECKDATE, EMPLOYEENUMBER,
							CHECKNUMBER)
			FROM CV_CMS_SOURCE.dbo.PRTMED 
			GROUP BY COMPANYNUMBER, WkEndDate, EMPLOYEENUMBER, CHECKDATE, CHECKNUMBER)
			AS S
			ON S.COMPANYNUMBER=CV_CMS_SOURCE.dbo.PRTMED.COMPANYNUMBER AND
			S.WkEndDate=CV_CMS_SOURCE.dbo.PRTMED.WkEndDate AND
			S.EMPLOYEENUMBER=CV_CMS_SOURCE.dbo.PRTMED.EMPLOYEENUMBER AND
			S.CHECKDATE=CV_CMS_SOURCE.dbo.PRTMED.CHECKDATE AND
			S.CHECKNUMBER=CV_CMS_SOURCE.dbo.PRTMED.CHECKNUMBER


--PRTTCE
update CV_CMS_SOURCE.dbo.PRTTCE set PaySeq=S.PAYSEQ
FROM CV_CMS_SOURCE.dbo.PRTTCE
JOIN (SELECT t.COMPANYNUMBER, t.WkEndDate, t.EMPLOYEENUMBER, t.CHECKNUMBER,
			PAYSEQ=min(t.PaySeq)
			FROM CV_CMS_SOURCE.dbo.PRTHST t 
			GROUP BY t.COMPANYNUMBER, t.WkEndDate, t.EMPLOYEENUMBER, t.CHECKNUMBER)
			AS S
			ON S.COMPANYNUMBER=CV_CMS_SOURCE.dbo.PRTTCE.COMPANYNUMBER AND
			S.WkEndDate=CV_CMS_SOURCE.dbo.PRTTCE.WkEndDate AND
			S.EMPLOYEENUMBER=CV_CMS_SOURCE.dbo.PRTTCE.EMPLOYEENUMBER AND
			S.CHECKNUMBER=CV_CMS_SOURCE.dbo.PRTTCE.CHECKNUMBER

--PRPDED
update CV_CMS_SOURCE.dbo.PRPDED set PaySeq=isnull(S.PAYSEQ,1)
FROM CV_CMS_SOURCE.dbo.PRPDED
left JOIN (SELECT t.COMPANYNUMBER, t.WkEndDate, t.EMPLOYEENUMBER, t.CHECKNUMBER,
			PAYSEQ=min(t.PaySeq)
			FROM CV_CMS_SOURCE.dbo.PRTHST t 
			GROUP BY t.COMPANYNUMBER, t.WkEndDate, t.EMPLOYEENUMBER, t.CHECKNUMBER)
			AS S
			ON S.COMPANYNUMBER=CV_CMS_SOURCE.dbo.PRPDED.DCONO AND
			S.WkEndDate=CV_CMS_SOURCE.dbo.PRPDED.WkEndDate AND
			S.EMPLOYEENUMBER=CV_CMS_SOURCE.dbo.PRPDED.DEENO AND
			S.WkEndDate=CV_CMS_SOURCE.dbo.PRPDED.WkEndDate
			


update CV_CMS_SOURCE.dbo.PRTWCH set PaySeq=isnull(S.PAYSEQ,1)
FROM CV_CMS_SOURCE.dbo.PRTWCH
left JOIN (SELECT t.COMPANYNUMBER, t.WkEndDate, t.EMPLOYEENUMBER, t.CHECKNUMBER,
			PAYSEQ=min(t.PaySeq)
			FROM CV_CMS_SOURCE.dbo.PRTHST t 
			GROUP BY t.COMPANYNUMBER, t.WkEndDate, t.EMPLOYEENUMBER, t.CHECKNUMBER)
			AS S
			ON S.COMPANYNUMBER=CV_CMS_SOURCE.dbo.PRTWCH.COMPANYNUMBER AND
			S.WkEndDate=CV_CMS_SOURCE.dbo.PRTWCH.WkEndDate AND
			S.EMPLOYEENUMBER=CV_CMS_SOURCE.dbo.PRTWCH.EMPLOYEENUMBER AND
			S.CHECKNUMBER=CV_CMS_SOURCE.dbo.PRTWCH.CHECKNUMBER
			
			

/************************** End Update Pay Sequences *********************/


/************************** Begin Update Job Numbers *********************/
--Update Job numbers to be used in PRTL
update CV_CMS_SOURCE.dbo.PRTMUN 
set Job=dbo.bfMuliPartFormat(ltrim(rtrim(JOBNUMBER)) + ltrim(rtrim(SUBJOBNUMBER)),@JobFormat)
from CV_CMS_SOURCE.dbo.PRTMUN

update CV_CMS_SOURCE.dbo.PRTTCH 
set Job=dbo.bfMuliPartFormat(ltrim(rtrim(JOBNUMBER)) + ltrim(rtrim(SUBJOBNUMBER)),@JobFormat)
from CV_CMS_SOURCE.dbo.PRTTCH

update CV_CMS_SOURCE.dbo.PRTMUN set Job=null where Job=' '

update CV_CMS_SOURCE.dbo.PRTTCH set Job=null where Job=' '

/************************** End Update Job Numbers *********************/

--Update the WeekEndDate on records where it's different
update CV_CMS_SOURCE.dbo.PRTMUN set WkEndDate=m.MinWkEndDate
from  CV_CMS_SOURCE.dbo.PRTMUN 
	join (select COMPANYNUMBER, CHECKDATE, CHECKNUMBER, EMPLOYEENUMBER, 
				CntWEDates=count(distinct WkEndDate),
				MinWkEndDate=min(WkEndDate)
			from CV_CMS_SOURCE.dbo.PRTMUN
			group by COMPANYNUMBER, CHECKDATE, CHECKNUMBER, EMPLOYEENUMBER
			having  count(distinct WkEndDate)>1)
			as m
			on m.COMPANYNUMBER=CV_CMS_SOURCE.dbo.PRTMUN.COMPANYNUMBER
				and m.CHECKDATE=CV_CMS_SOURCE.dbo.PRTMUN.CHECKDATE
				and m.CHECKNUMBER=CV_CMS_SOURCE.dbo.PRTMUN.CHECKNUMBER
				and m.EMPLOYEENUMBER=CV_CMS_SOURCE.dbo.PRTMUN.EMPLOYEENUMBER
				
/*   The week end dates are different in some of the detail tables versus the PRTHST record
	This updates the details to have consistent PR End Dates which are required to 
	get the right ded/liab with the right earnings and directly impacts subj/elig amts in PRDT */
	
	
update CV_CMS_SOURCE.dbo.PRTTCH  set WkEndDate=m.MinWkEndDate
from  CV_CMS_SOURCE.dbo.PRTTCH 
	join (select COMPANYNUMBER, CHECKDATE, CHECKNUMBER, EMPLOYEENUMBER, 
				CntWEDates=count(distinct WkEndDate),
				MinWkEndDate=min(WkEndDate)
			from CV_CMS_SOURCE.dbo.PRTHST
			group by COMPANYNUMBER, CHECKDATE, CHECKNUMBER, EMPLOYEENUMBER)
			as m
			on m.COMPANYNUMBER=CV_CMS_SOURCE.dbo.PRTTCH.COMPANYNUMBER
				and m.CHECKDATE=CV_CMS_SOURCE.dbo.PRTTCH.CHECKDATE
				and m.CHECKNUMBER=CV_CMS_SOURCE.dbo.PRTTCH.CHECKNUMBER
				and m.EMPLOYEENUMBER=CV_CMS_SOURCE.dbo.PRTTCH.EMPLOYEENUMBER
where m.MinWkEndDate<>WkEndDate

--PRTMUN
update CV_CMS_SOURCE.dbo.PRTMUN  set WkEndDate=m.MinWkEndDate
from  CV_CMS_SOURCE.dbo.PRTMUN 
	join (select COMPANYNUMBER, CHECKDATE, CHECKNUMBER, EMPLOYEENUMBER, 
				CntWEDates=count(distinct WkEndDate),
				MinWkEndDate=min(WkEndDate)
			from CV_CMS_SOURCE.dbo.PRTHST
			group by COMPANYNUMBER, CHECKDATE, CHECKNUMBER, EMPLOYEENUMBER)
			as m
			on m.COMPANYNUMBER=CV_CMS_SOURCE.dbo.PRTMUN.COMPANYNUMBER
				and m.CHECKDATE=CV_CMS_SOURCE.dbo.PRTMUN.CHECKDATE
				and m.CHECKNUMBER=CV_CMS_SOURCE.dbo.PRTMUN.CHECKNUMBER
				and m.EMPLOYEENUMBER=CV_CMS_SOURCE.dbo.PRTMUN.EMPLOYEENUMBER
where m.MinWkEndDate<>WkEndDate

--PRTMED
update CV_CMS_SOURCE.dbo.PRTMED  set WkEndDate=m.MinWkEndDate
from  CV_CMS_SOURCE.dbo.PRTMED 
	join (select COMPANYNUMBER, CHECKDATE, CHECKNUMBER, EMPLOYEENUMBER, 
				CntWEDates=count(distinct WkEndDate),
				MinWkEndDate=min(WkEndDate)
			from CV_CMS_SOURCE.dbo.PRTHST
			group by COMPANYNUMBER, CHECKDATE, CHECKNUMBER, EMPLOYEENUMBER)
			as m
			on m.COMPANYNUMBER=CV_CMS_SOURCE.dbo.PRTMED.COMPANYNUMBER
				and m.CHECKDATE=CV_CMS_SOURCE.dbo.PRTMED.CHECKDATE
				and m.CHECKNUMBER=CV_CMS_SOURCE.dbo.PRTMED.CHECKNUMBER
				and m.EMPLOYEENUMBER=CV_CMS_SOURCE.dbo.PRTMED.EMPLOYEENUMBER
where m.MinWkEndDate<>WkEndDate


--PRTMAJ
update CV_CMS_SOURCE.dbo.PRTMAJ  set WkEndDate=m.MinWkEndDate
from  CV_CMS_SOURCE.dbo.PRTMAJ 
	join (select COMPANYNUMBER, CHECKDATE, CHECKNUMBER, EMPLOYEENUMBER, 
				CntWEDates=count(distinct WkEndDate),
				MinWkEndDate=min(WkEndDate)
			from CV_CMS_SOURCE.dbo.PRTHST
			group by COMPANYNUMBER, CHECKDATE, CHECKNUMBER, EMPLOYEENUMBER)
			as m
			on m.COMPANYNUMBER=CV_CMS_SOURCE.dbo.PRTMAJ.COMPANYNUMBER
				and m.CHECKDATE=CV_CMS_SOURCE.dbo.PRTMAJ.CHECKDATE
				and m.CHECKNUMBER=CV_CMS_SOURCE.dbo.PRTMAJ.CHECKNUMBER
				and m.EMPLOYEENUMBER=CV_CMS_SOURCE.dbo.PRTMAJ.EMPLOYEENUMBER
where m.MinWkEndDate<>WkEndDate

--HRTMBN
update CV_CMS_SOURCE.dbo.HRTMBN  set WkEndDate=m.MinWkEndDate
from  CV_CMS_SOURCE.dbo.HRTMBN 
	join (select COMPANYNUMBER, CHECKDATE, CHECKNUMBER, EMPLOYEENUMBER, 
				CntWEDates=count(distinct WkEndDate),
				MinWkEndDate=min(WkEndDate)
			from CV_CMS_SOURCE.dbo.PRTHST
			group by COMPANYNUMBER, CHECKDATE, CHECKNUMBER, EMPLOYEENUMBER)
			as m
			on m.COMPANYNUMBER=CV_CMS_SOURCE.dbo.HRTMBN.COMPANYNUMBER
				and m.CHECKDATE=CV_CMS_SOURCE.dbo.HRTMBN.CHECKDATE
				and m.CHECKNUMBER=CV_CMS_SOURCE.dbo.HRTMBN.CHECKNUMBER
				and m.EMPLOYEENUMBER=CV_CMS_SOURCE.dbo.HRTMBN.EMPLOYEENUMBER
where m.MinWkEndDate<>WkEndDate

--PRTTCE
update CV_CMS_SOURCE.dbo.PRTTCE  set WkEndDate=m.MinWkEndDate
from  CV_CMS_SOURCE.dbo.PRTTCE 
	join (select COMPANYNUMBER, CHECKNUMBER, EMPLOYEENUMBER, 
				CntWEDates=count(distinct WkEndDate),
				MinWkEndDate=min(WkEndDate)
			from CV_CMS_SOURCE.dbo.PRTHST
			group by COMPANYNUMBER, CHECKNUMBER, EMPLOYEENUMBER)
			as m
			on m.COMPANYNUMBER=CV_CMS_SOURCE.dbo.PRTTCE.COMPANYNUMBER
				and m.CHECKNUMBER=CV_CMS_SOURCE.dbo.PRTTCE.CHECKNUMBER
				and m.EMPLOYEENUMBER=CV_CMS_SOURCE.dbo.PRTTCE.EMPLOYEENUMBER
where m.MinWkEndDate<>WkEndDate
;

/*
updating PaySeq with PaySeq from PRTHST

*/
--PRTTCH
update CV_CMS_SOURCE.dbo.PRTTCH  set PaySeq=m.MinPaySeq
from  CV_CMS_SOURCE.dbo.PRTTCH 
	join (select COMPANYNUMBER, CHECKDATE, CHECKNUMBER, EMPLOYEENUMBER, 
				CntWEDates=count(distinct WkEndDate),
				MinWkEndDate=min(WkEndDate), MinPaySeq=MIN(PaySeq)
			from CV_CMS_SOURCE.dbo.PRTHST
			group by COMPANYNUMBER, CHECKDATE, CHECKNUMBER, EMPLOYEENUMBER)
			as m
			on m.COMPANYNUMBER=CV_CMS_SOURCE.dbo.PRTTCH.COMPANYNUMBER
				and m.CHECKDATE=CV_CMS_SOURCE.dbo.PRTTCH.CHECKDATE
				and m.CHECKNUMBER=CV_CMS_SOURCE.dbo.PRTTCH.CHECKNUMBER
				and m.EMPLOYEENUMBER=CV_CMS_SOURCE.dbo.PRTTCH.EMPLOYEENUMBER
				
--PRTMUN
update CV_CMS_SOURCE.dbo.PRTMUN  set PaySeq=m.MinPaySeq
from  CV_CMS_SOURCE.dbo.PRTMUN 
	join (select COMPANYNUMBER, CHECKDATE, CHECKNUMBER, EMPLOYEENUMBER, 
				CntWEDates=count(distinct WkEndDate),
				MinWkEndDate=min(WkEndDate), MinPaySeq=MIN(PaySeq)
			from CV_CMS_SOURCE.dbo.PRTHST
			group by COMPANYNUMBER, CHECKDATE, CHECKNUMBER, EMPLOYEENUMBER)
			as m
			on m.COMPANYNUMBER=CV_CMS_SOURCE.dbo.PRTMUN.COMPANYNUMBER
				and m.CHECKDATE=CV_CMS_SOURCE.dbo.PRTMUN.CHECKDATE
				and m.CHECKNUMBER=CV_CMS_SOURCE.dbo.PRTMUN.CHECKNUMBER
				and m.EMPLOYEENUMBER=CV_CMS_SOURCE.dbo.PRTMUN.EMPLOYEENUMBER


--PRTMED
update CV_CMS_SOURCE.dbo.PRTMED  set PaySeq=m.MinPaySeq
from  CV_CMS_SOURCE.dbo.PRTMED 
	join (select COMPANYNUMBER, CHECKDATE, CHECKNUMBER, EMPLOYEENUMBER, 
				CntWEDates=count(distinct WkEndDate),
				MinWkEndDate=min(WkEndDate), MinPaySeq=MIN(PaySeq)
			from CV_CMS_SOURCE.dbo.PRTHST
			group by COMPANYNUMBER, CHECKDATE, CHECKNUMBER, EMPLOYEENUMBER)
			as m
			on m.COMPANYNUMBER=CV_CMS_SOURCE.dbo.PRTMED.COMPANYNUMBER
				and m.CHECKDATE=CV_CMS_SOURCE.dbo.PRTMED.CHECKDATE
				and m.CHECKNUMBER=CV_CMS_SOURCE.dbo.PRTMED.CHECKNUMBER
				and m.EMPLOYEENUMBER=CV_CMS_SOURCE.dbo.PRTMED.EMPLOYEENUMBER



--PRTMAJ
update CV_CMS_SOURCE.dbo.PRTMAJ  set PaySeq=m.MinPaySeq
from  CV_CMS_SOURCE.dbo.PRTMAJ 
	join (select COMPANYNUMBER, CHECKDATE, CHECKNUMBER, EMPLOYEENUMBER, 
				CntWEDates=count(distinct WkEndDate),
				MinWkEndDate=min(WkEndDate), MinPaySeq=MIN(PaySeq)
			from CV_CMS_SOURCE.dbo.PRTHST
			group by COMPANYNUMBER, CHECKDATE, CHECKNUMBER, EMPLOYEENUMBER)
			as m
			on m.COMPANYNUMBER=CV_CMS_SOURCE.dbo.PRTMAJ.COMPANYNUMBER
				and m.CHECKDATE=CV_CMS_SOURCE.dbo.PRTMAJ.CHECKDATE
				and m.CHECKNUMBER=CV_CMS_SOURCE.dbo.PRTMAJ.CHECKNUMBER
				and m.EMPLOYEENUMBER=CV_CMS_SOURCE.dbo.PRTMAJ.EMPLOYEENUMBER


--PRTMAJ
update CV_CMS_SOURCE.dbo.PRTMAJ  set PaySeq=m.MinPaySeq
from  CV_CMS_SOURCE.dbo.PRTMAJ 
	left join (select COMPANYNUMBER, CHECKNUMBER, EMPLOYEENUMBER, MIN(CHECKDATE) as checkdate
	, MinPaySeq=MIN(PaySeq)
				
			from CV_CMS_SOURCE.dbo.PRTHST
			group by COMPANYNUMBER, CHECKDATE, CHECKNUMBER, EMPLOYEENUMBER)
			as m
			on m.COMPANYNUMBER=CV_CMS_SOURCE.dbo.PRTMAJ.COMPANYNUMBER
				--and m.CHECKDATE=CV_CMS_SOURCE.dbo.PRTMAJ.CHECKDATE
				and m.CHECKNUMBER=CV_CMS_SOURCE.dbo.PRTMAJ.CHECKNUMBER
				and m.EMPLOYEENUMBER=CV_CMS_SOURCE.dbo.PRTMAJ.EMPLOYEENUMBER


--HRTMBN
update CV_CMS_SOURCE.dbo.HRTMBN  set PaySeq=m.MinPaySeq
from  CV_CMS_SOURCE.dbo.HRTMBN 
	join (select COMPANYNUMBER, CHECKDATE, CHECKNUMBER, EMPLOYEENUMBER, 
				CntWEDates=count(distinct WkEndDate),
				MinWkEndDate=min(WkEndDate), MinPaySeq=MIN(PaySeq)
			from CV_CMS_SOURCE.dbo.PRTHST
			group by COMPANYNUMBER, CHECKDATE, CHECKNUMBER, EMPLOYEENUMBER)
			as m
			on m.COMPANYNUMBER=CV_CMS_SOURCE.dbo.HRTMBN.COMPANYNUMBER
				and m.CHECKDATE=CV_CMS_SOURCE.dbo.HRTMBN.CHECKDATE
				and m.CHECKNUMBER=CV_CMS_SOURCE.dbo.HRTMBN.CHECKNUMBER
				and m.EMPLOYEENUMBER=CV_CMS_SOURCE.dbo.HRTMBN.EMPLOYEENUMBER


--PRTTCE
update CV_CMS_SOURCE.dbo.PRTTCE  set PaySeq=m.MinPaySeq
from  CV_CMS_SOURCE.dbo.PRTTCE 
	join (select COMPANYNUMBER, CHECKNUMBER, EMPLOYEENUMBER, 
				CntWEDates=count(distinct WkEndDate),
				MinWkEndDate=min(WkEndDate), MinPaySeq=MIN(PaySeq)
			from CV_CMS_SOURCE.dbo.PRTHST
			group by COMPANYNUMBER, CHECKNUMBER, EMPLOYEENUMBER)
			as m
			on m.COMPANYNUMBER=CV_CMS_SOURCE.dbo.PRTTCE.COMPANYNUMBER
				and m.CHECKNUMBER=CV_CMS_SOURCE.dbo.PRTTCE.CHECKNUMBER
				and m.EMPLOYEENUMBER=CV_CMS_SOURCE.dbo.PRTTCE.EMPLOYEENUMBER;
				



		



COMMIT TRAN
END TRY

BEGIN CATCH
select @errmsg=isnull(ERROR_PROCEDURE(),'')+' '+convert(varchar(10),isnull(ERROR_LINE(),0))+' '+isnull(ERROR_MESSAGE(),'')
ROLLBACK
END CATCH;


return @@error

GO
