GRANT SELECT ON SCHEMA:: [dbo] TO [AsteaIntegration]
GRANT INSERT ON SCHEMA:: [dbo] TO [AsteaIntegration]
GRANT DELETE ON SCHEMA:: [dbo] TO [AsteaIntegration]
GRANT UPDATE ON SCHEMA:: [dbo] TO [AsteaIntegration]
GRANT EXECUTE ON SCHEMA:: [dbo] TO [AsteaIntegration]
GRANT EXECUTE ON SCHEMA:: [dbo] TO [IntegrationAccount]
GRANT ALTER ON SCHEMA:: [dbo] TO [MCKINSTRY\ERPIntegrationTeam]
GRANT CONTROL ON SCHEMA:: [dbo] TO [MCKINSTRY\ERPIntegrationTeam]
GRANT EXECUTE ON SCHEMA:: [dbo] TO [MCKINSTRY\ERPIntegrationTeam]
GRANT ALTER ON SCHEMA:: [dbo] TO [MCKINSTRY\ERPReportingTeam]
GRANT CONTROL ON SCHEMA:: [dbo] TO [MCKINSTRY\ERPReportingTeam]
GRANT EXECUTE ON SCHEMA:: [dbo] TO [MCKINSTRY\ERPReportingTeam] WITH GRANT OPTION
GRANT EXECUTE ON SCHEMA:: [dbo] TO [public]
GRANT ALTER ON SCHEMA:: [dbo] TO [tracyf] WITH GRANT OPTION
GRANT CONTROL ON SCHEMA:: [dbo] TO [tracyf] WITH GRANT OPTION
GRANT EXECUTE ON SCHEMA:: [dbo] TO [tracyf] WITH GRANT OPTION
GO
