DECLARE @Contract bContract
SET @Contract='10195-'

SELECT * FROM mvwWIPReport WHERE LTRIM(RTRIM(Contract))=@Contract

--SELECT * FROM JCJM WHERE JCCo<100 AND LTRIM(RTRIM(Contract))=@Contract
SELECT * FROM bJCOP WHERE JCCo<100 AND Job IN ( SELECT DISTINCT Job FROM JCJM WHERE LTRIM(RTRIM(Contract))=@Contract )
SELECT * FROM bJCCP WHERE JCCo<100 AND Job IN ( SELECT DISTINCT Job FROM JCJM WHERE LTRIM(RTRIM(Contract))=@Contract )

SELECT * FROM JCOR WHERE JCCo<100 AND LTRIM(RTRIM(Contract))=@Contract
SELECT * FROM JCIP WHERE JCCo<100 AND LTRIM(RTRIM(Contract))=@Contract