USE [Viewpoint]
GO

/****** Object:  Index [mixHQCOTestCo]    Script Date: 11/05/2014 06:53:44 ******/
CREATE NONCLUSTERED INDEX [mixHQCOTestCo] ON [dbo].[bHQCO] 
(
	[udTESTCo] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

USE [Viewpoint]
GO

/****** Object:  Index [mixJCCMPOC]    Script Date: 11/05/2014 06:54:30 ******/
CREATE NONCLUSTERED INDEX [mixJCCMPOC] ON [dbo].[bJCCM] 
(
	[udPOC] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


USE [Viewpoint]
GO

/****** Object:  Index [mixJCCMSalesPerson]    Script Date: 11/05/2014 06:54:48 ******/
CREATE NONCLUSTERED INDEX [mixJCCMSalesPerson] ON [dbo].[bJCCM] 
(
	[udSalesPerson] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

USE [Viewpoint]
GO

/****** Object:  Index [mixPOHDudMCKPoNumber]    Script Date: 11/05/2014 06:55:23 ******/
CREATE NONCLUSTERED INDEX [mixPOHDudMCKPoNumber] ON [dbo].[bPOHD] 
(
	[udMCKPONumber] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

USE [Viewpoint]
GO

/****** Object:  Index [mixxrefJCJobs1]    Script Date: 11/05/2014 06:56:27 ******/
CREATE NONCLUSTERED INDEX [mixxrefJCJobs1] ON [dbo].[budxrefJCJobs] 
(
	[VPCo] ASC,
	[VPJob] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


