SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[DDCT] AS SELECT * FROM vDDCT

GO
GRANT SELECT ON  [dbo].[DDCT] TO [public]
GRANT INSERT ON  [dbo].[DDCT] TO [public]
GRANT DELETE ON  [dbo].[DDCT] TO [public]
GRANT UPDATE ON  [dbo].[DDCT] TO [public]
GO
