/*
-- DDL FOR VIEW ON S1017192 (iSeries)
CREATE VIEW MCK_METLIFE_ROSTER
AS
SELECT
REPEAT('0',9-LENGTH(RTRIM(P.MEENO))) || RTRIM(P.MEENO) AS EMPLOYEENUMBER ,
RTRIM(P.MLN25) AS LASTNAME ,
RTRIM(RTRIM(P.MFN25) || ' ' || RTRIM(P.MM25A) || ' ' || RTRIM(P.MSFX4)) AS FIRSTNAME ,
RTRIM(P.MA25A) AS ADDRESSLINE1 ,
RTRIM(P.MA25B) AS ADDRESSLINE2 ,
RTRIM(P.MCITY) AS CITY ,
RTRIM(P.MST) AS STATE ,
RTRIM(P.MZIP) AS ZIPCODE ,
SUBSTRING(P.MDTBR,5,2) || SUBSTRING(P.MDTBR,7,2) || SUBSTRING(P.MDTBR,1,4) AS BIRTHDATE ,
SUBSTRING(P.MDTBG,5,2) || SUBSTRING(P.MDTBG,7,2) || SUBSTRING(P.MDTBG,1,4) AS HIREDATE ,
CAST
(
 REPEAT
 (
 '0',2-LENGTH(RTRIM(P.MCONO))
 )
 || RTRIM
 (
 P.MCONO
 )
 || '.' || RTRIM
 (
 P.MDVNO
 )
 || '.' || REPEAT
 (
 '0',3-LENGTH(RTRIM(P.MSDDP))
 )
 || RTRIM(P.MSDDP) || '.' || SUBSTRING(D.LGLAN,5,3) AS CHAR(15)
)
AS DEPARTMENTNUMBER
FROM CMSFIL.PRPMST P
INNER JOIN CMSFIL.PRPLBR D ON P.MCONO = D.LCONO
AND P.MDVNO = D.LDVNO
AND P.MSDDP = D.LDPNO
WHERE P.MSTAT='A'
AND P.MUNNO IN ('001','002')
AND P.MCONO IN (1,15,20,30,50,60)
*/

--SELECT * FROM CMS.S1017192.CMSFIL.MCK_METLIFE_ROSTER

--DECLARE @dtwe INT
--SELECT @dtwe=MAX(CHDTWE) FROM CMS.S1017192.CMSFIL.PRPTCH WHERE CHCONO IN (1,15,20,30,50,60)
 
drop FUNCTION mfnBenefitEligibleEmployees

CREATE  FUNCTION mfnBenefitEligibleEmployees(@dtwe DECIMAL(8,0))
RETURNS @resultsTbl TABLE
(	
	EmployeeNumber	[varchar](10) null
,	LastName		[varchar](50) null
,	FirstName		[varchar](50) null
,	AddressLine1	[varchar](50) null
,	AddressLine2	[varchar](50) null
,	City			[varchar](50) null
,	State			[varchar](50) null
,	ZipCode			[varchar](10) null
,	BirthDate		DATETIME null
,	HireDate		DATETIME null
,	Department		[varchar](10) null
)
AS
BEGIN

IF @dtwe IS null
	SELECT @dtwe=MAX(CHDTWE) FROM CMS.S1017192.CMSFIL.PRPTCH WHERE CHCONO IN (1,15,20,30,50,60)


INSERT @resultsTbl
SELECT 
	ber.EMPLOYEENUMBER
,	ber.LASTNAME
,	ber.FIRSTNAME
,	ber.ADDRESSLINE1
,	ber.ADDRESSLINE2
,	ber.CITY
,	ber.STATE
,	ber.ZIPCODE
,	CAST((substring(ber.BIRTHDATE,1,2) + '/' + substring(ber.BIRTHDATE,3,2) + '/' + substring(ber.BIRTHDATE,5,4)) AS DATETIME) AS BIRTHDATE
,	CAST((substring(ber.HIREDATE,1,2) + '/' + substring(ber.HIREDATE,3,2) + '/' + substring(ber.HIREDATE,5,4)) AS DATETIME) AS HIREDATE
,	ber.DEPARTMENTNUMBER
FROM
( 
SELECT
REPLICATE('0',9-LEN(RTRIM(CAST(P.MEENO AS VARCHAR(10))))) + RTRIM(RTRIM(CAST(P.MEENO AS VARCHAR(10)))) AS EMPLOYEENUMBER ,
RTRIM(P.MLN25) AS LASTNAME ,
RTRIM(RTRIM(P.MFN25) + ' ' + RTRIM(P.MM25A) + ' ' + RTRIM(P.MSFX4)) AS FIRSTNAME ,
RTRIM(P.MA25A) AS ADDRESSLINE1 ,
RTRIM(P.MA25B) AS ADDRESSLINE2 ,
RTRIM(P.MCITY) AS CITY ,
RTRIM(P.MST) AS STATE ,
RTRIM(P.MZIP) AS ZIPCODE ,
SUBSTRING(CAST(P.MDTBR AS CHAR(15)),5,2) + SUBSTRING(CAST(P.MDTBR AS CHAR(15)),7,2) + SUBSTRING(CAST(P.MDTBR AS CHAR(15)),1,4) AS BIRTHDATE ,
SUBSTRING(CAST(P.MDTBG AS CHAR(15)),5,2) + SUBSTRING(CAST(P.MDTBG AS CHAR(15)),7,2) + SUBSTRING(CAST(P.MDTBG AS CHAR(15)),1,4) AS HIREDATE ,
CAST
(
	REPLICATE('0',2-LEN(RTRIM(CAST(P.MCONO AS VARCHAR(2)))) )
 +	RTRIM(CAST(P.MCONO AS VARCHAR(2)) )
 --+	'.' + RTRIM(CAST(P.MDVNO AS VARCHAR(2)))
 --+	'.' + REPLICATE('0',3-LEN(RTRIM(CAST(P.MSDDP AS VARCHAR(15)))) )
 --+	RTRIM(CAST(P.MSDDP AS VARCHAR(20)))  
 + '.' + SUBSTRING(CAST(D.LGLAN AS VARCHAR(20)),5,3) AS CHAR(15)
)
AS DEPARTMENTNUMBER,
(
	SELECT 
		SUM(tc.CHRGHR + tc.CHOVHR + tc.CHOTHR) AS TotalHours	
	from 
		CMS.S1017192.CMSFIL.PRPTCH tc 
	WHERE	
		 tc.CHCONO =P.MCONO
	AND  tc.CHDVNO =P.MDVNO
	AND	 tc.CHEENO = P.MEENO
	AND tc.CHDTWE=@dtwe
) AS TotalHours
FROM CMS.S1017192.CMSFIL.PRPMST P
INNER JOIN CMS.S1017192.CMSFIL.PRPLBR D ON P.MCONO = D.LCONO
AND P.MDVNO = D.LDVNO
AND P.MSDDP = D.LDPNO 
WHERE P.MSTAT='A'
AND P.MUNNO IN ('001','002')
AND P.MCONO IN (1,15,20,30,50,60)
) ber
WHERE
	ber.TotalHours >= 30

RETURN 
END
go

SELECT * FROM dbo.mfnBenefitEligibleEmployees(null)


--SELECT TOP 100 * FROM  CMS.S1017192.CMSFIL.PRPMST 
--SELECT TOP 100 * FROM  CMS.S1017192.CMSFIL.PRPTCH


--DECLARE @dtwe INT
--SELECT @dtwe=MAX(CHDTWE) FROM CMS.S1017192.CMSFIL.PRPTCH WHERE CHCONO IN (1,15,20,30,50,60)



--SELECT
--	tc.CHCONO
--,	tc.CHDVNO
--,	tc.CHEENO
--,	p.MNM25
--,	tc.CHDTWE
----,	SUBSTRING(CAST(D.LGLAN AS VARCHAR(20)),5,3)
--,	SUM(tc.CHRGHR + tc.CHOVHR + tc.CHOTHR) AS TotalHours	
--from 
--	CMS.S1017192.CMSFIL.PRPTCH tc LEFT OUTER JOIN
--	CMS.S1017192.CMSFIL.PRPMST p ON
--		tc.CHCONO=p.MCONO
--	AND tc.CHDVNO=p.MDVNO
--	AND tc.CHEENO=p.MEENO /*INNER JOIN 
--	CMS.S1017192.CMSFIL.PRPLBR D ON 
--		p.MCONO = D.LCONO
--	AND p.MDVNO = D.LDVNO
--	AND p.MSDDP = D.LDPNO */
--WHERE	
--	p.MSTAT='A'	
--AND p.MUNNO IN ('001','002')
--AND p.MCONO IN (1,15,20,30,50,60)	
--AND tc.CHDTWE=20140209
--GROUP BY
--	tc.CHCONO
--,	tc.CHDVNO
--,	tc.CHEENO
--,	p.MNM25
--,	tc.CHDTWE	
----,	SUBSTRING(CAST(D.LGLAN AS VARCHAR(20)),5,3)
--HAVING
--	SUM(tc.CHRGHR + tc.CHOVHR + tc.CHOTHR) >=30
--ORDER BY
--	tc.CHDTWE
--,	tc.CHCONO
--,	tc.CHDVNO
--,	tc.CHEENO
