//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace McKinstry.VPIntegration
{
    public partial class JobPhaseCodeInfo
    {
        #region Primitive Properties
    
        public virtual byte JCCo
        {
            get;
            set;
        }
    
        public virtual string Job
        {
            get;
            set;
        }
    
        public virtual string McKJobNo
        {
            get;
            set;
        }
    
        public virtual string JobDescription
        {
            get;
            set;
        }
    
        public virtual byte JobStatus
        {
            get;
            set;
        }
    
        public virtual string JobStatusDescription
        {
            get;
            set;
        }
    
        public virtual Nullable<byte> PhaseGroup
        {
            get;
            set;
        }
    
        public virtual string Phase
        {
            get;
            set;
        }
    
        public virtual string McKPhase
        {
            get;
            set;
        }
    
        public virtual string JobPhaseDescription
        {
            get;
            set;
        }
    
        public virtual string PhaseMasterDescription
        {
            get;
            set;
        }
    
        public virtual string PhaseActive
        {
            get;
            set;
        }
    
        public virtual Nullable<byte> PhaseCostType
        {
            get;
            set;
        }
    
        public virtual string PhaseCostTypeCode
        {
            get;
            set;
        }
    
        public virtual string PhaseCostTypeDescription
        {
            get;
            set;
        }
    
        public virtual string MailAddress
        {
            get;
            set;
        }
    
        public virtual string MailAddress2
        {
            get;
            set;
        }
    
        public virtual string MailCity
        {
            get;
            set;
        }
    
        public virtual string MailState
        {
            get;
            set;
        }
    
        public virtual string MailZip
        {
            get;
            set;
        }
    
        public virtual string JobPhone
        {
            get;
            set;
        }
    
        public virtual Nullable<int> ContactCode
        {
            get;
            set;
        }
    
        public virtual string UpdatedDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> CreatedDate
        {
            get;
            set;
        }
    
        public virtual string PhaseIsInterfacedYN
        {
            get;
            set;
        }
    
        public virtual string SourceStatus
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> InterfaceDate
        {
            get;
            set;
        }

        #endregion
    }
}
