CREATE TABLE [dbo].[bPMHA]
(
[PMHIKeyId] [bigint] NOT NULL,
[AttachmentID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[bPMHA] ADD CONSTRAINT [PK_bPMHA] PRIMARY KEY CLUSTERED  ([PMHIKeyId], [AttachmentID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[bPMHA] WITH NOCHECK ADD CONSTRAINT [FK_bPMHA_bPMHI] FOREIGN KEY ([PMHIKeyId]) REFERENCES [dbo].[bPMHI] ([KeyId])
GO
