CREATE TABLE [dbo].[vRPTM]
(
[ReportID] [int] NOT NULL,
[TemplateName] [varchar] (20) COLLATE Latin1_General_BIN NOT NULL,
[KeyID] [int] NOT NULL IDENTITY(1, 2)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[vRPTM] ADD CONSTRAINT [PK_vRPTM] PRIMARY KEY CLUSTERED  ([KeyID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_vRPTM_ReportID] ON [dbo].[vRPTM] ([ReportID]) ON [PRIMARY]
GO
