CREATE TABLE [dbo].[bPMCO_copy]
(
[PMCo] [dbo].[bCompany] NOT NULL,
[APInUse] [dbo].[bYN] NOT NULL,
[SLInUse] [dbo].[bYN] NOT NULL,
[POInUse] [dbo].[bYN] NOT NULL,
[APCo] [dbo].[bCompany] NULL,
[INInUse] [dbo].[bYN] NOT NULL,
[INCo] [dbo].[bCompany] NULL,
[MSInUse] [dbo].[bYN] NOT NULL,
[MSCo] [dbo].[bCompany] NULL,
[PRInUse] [dbo].[bYN] NOT NULL,
[PRCo] [dbo].[bCompany] NULL,
[EMInUse] [dbo].[bYN] NOT NULL,
[EMCo] [dbo].[bCompany] NULL,
[PhaseGroup] [dbo].[bGroup] NULL,
[SLCostType] [dbo].[bJCCType] NULL,
[MtlCostType] [dbo].[bJCCType] NULL,
[SigPartJob] [dbo].[bYN] NOT NULL,
[SigCharsPO] [smallint] NULL,
[SigCharsMO] [smallint] NULL,
[SigCharsSL] [smallint] NULL,
[SLNo] [char] (1) COLLATE Latin1_General_BIN NOT NULL,
[SLCharsProject] [tinyint] NULL,
[SLCharsVendor] [tinyint] NULL,
[PONo] [char] (1) COLLATE Latin1_General_BIN NOT NULL,
[POCharsProject] [tinyint] NULL,
[POCharsVendor] [tinyint] NULL,
[MONo] [char] (1) COLLATE Latin1_General_BIN NOT NULL,
[MOCharsProject] [tinyint] NULL,
[PhaseDescYN] [dbo].[bYN] NULL,
[VendorGroup] [dbo].[bGroup] NULL,
[OurFirm] [dbo].[bFirm] NULL,
[SLSeqLen] [tinyint] NULL,
[POSeqLen] [tinyint] NULL,
[MOSeqLen] [tinyint] NULL,
[SLCT1Option] [tinyint] NOT NULL,
[SLCostType2] [dbo].[bJCCType] NULL,
[MTCT1Option] [tinyint] NOT NULL,
[POSigPartJob] [dbo].[bYN] NOT NULL,
[MOGroupByLoc] [dbo].[bYN] NOT NULL,
[BeginStatus] [varchar] (6) COLLATE Latin1_General_BIN NULL,
[FinalStatus] [varchar] (6) COLLATE Latin1_General_BIN NULL,
[APVendUpdYN] [dbo].[bYN] NOT NULL,
[DocTrackView] [varchar] (10) COLLATE Latin1_General_BIN NULL,
[RQInUse] [dbo].[bYN] NOT NULL,
[POCreate] [dbo].[bYN] NOT NULL,
[MOCreate] [dbo].[bYN] NOT NULL,
[SLStartSeq] [smallint] NULL,
[POStartSeq] [smallint] NULL,
[MOStartSeq] [smallint] NULL,
[ShowCostType1] [dbo].[bJCCType] NULL,
[ShowCostType2] [dbo].[bJCCType] NULL,
[ShowCostType3] [dbo].[bJCCType] NULL,
[ShowCostType4] [dbo].[bJCCType] NULL,
[ShowCostType5] [dbo].[bJCCType] NULL,
[ShowCostType6] [dbo].[bJCCType] NULL,
[ShowCostType7] [dbo].[bJCCType] NULL,
[ShowCostType8] [dbo].[bJCCType] NULL,
[ShowCostType9] [dbo].[bJCCType] NULL,
[ShowCostType10] [dbo].[bJCCType] NULL,
[FaxServerName] [varchar] (50) COLLATE Latin1_General_BIN NULL,
[DocHistACO] [dbo].[bYN] NOT NULL,
[DocHistDrawing] [dbo].[bYN] NOT NULL,
[DocHistInspect] [dbo].[bYN] NOT NULL,
[DocHistOtherDoc] [dbo].[bYN] NOT NULL,
[DocHistPCO] [dbo].[bYN] NOT NULL,
[DocHistPunchList] [dbo].[bYN] NOT NULL,
[DocHistRFI] [dbo].[bYN] NOT NULL,
[DocHistRFQ] [dbo].[bYN] NOT NULL,
[DocHistSubmittal] [dbo].[bYN] NOT NULL,
[DocHistTestLog] [dbo].[bYN] NOT NULL,
[DocHistTransmittal] [dbo].[bYN] NOT NULL,
[AuditCoParams] [dbo].[bYN] NOT NULL,
[AuditDailyLogs] [dbo].[bYN] NOT NULL,
[AuditPMCA] [dbo].[bYN] NOT NULL,
[AuditPMEC] [dbo].[bYN] NOT NULL,
[AuditPMEH] [dbo].[bYN] NOT NULL,
[AuditPMFM] [dbo].[bYN] NOT NULL,
[AuditPMIM] [dbo].[bYN] NOT NULL,
[AuditPMMF] [dbo].[bYN] NOT NULL,
[AuditPMMM] [dbo].[bYN] NOT NULL,
[AuditPMNR] [dbo].[bYN] NOT NULL,
[AuditPMPA] [dbo].[bYN] NOT NULL,
[AuditPMPC] [dbo].[bYN] NOT NULL,
[AuditPMPF] [dbo].[bYN] NOT NULL,
[AuditPMPL] [dbo].[bYN] NOT NULL,
[AuditPMPM] [dbo].[bYN] NOT NULL,
[AuditPMPN] [dbo].[bYN] NOT NULL,
[AuditPMSL] [dbo].[bYN] NOT NULL,
[AuditPMTH] [dbo].[bYN] NOT NULL,
[Notes] [varchar] (max) COLLATE Latin1_General_BIN NULL,
[UniqueAttchID] [uniqueidentifier] NULL,
[KeyID] [bigint] NOT NULL IDENTITY(1, 1),
[AttachBatchReportsYN] [dbo].[bYN] NOT NULL,
[UseApprSubCo] [dbo].[bYN] NOT NULL,
[MatlPhaseDesc] [char] (1) COLLATE Latin1_General_BIN NOT NULL,
[POAddOrigOpen] [char] (1) COLLATE Latin1_General_BIN NOT NULL,
[POAddChgOpen] [char] (1) COLLATE Latin1_General_BIN NOT NULL,
[MatlCostType2] [dbo].[bJCCType] NULL,
[SLItemCOAutoAdd] [char] (1) COLLATE Latin1_General_BIN NOT NULL,
[SLItemCOManual] [char] (1) COLLATE Latin1_General_BIN NOT NULL,
[AllowPCOToSLSync] [char] (1) COLLATE Latin1_General_BIN NOT NULL,
[DocHistSubCO] [char] (1) COLLATE Latin1_General_BIN NOT NULL,
[RFIStatus] [dbo].[bStatus] NULL,
[DocHistPOCONum] [char] (1) COLLATE Latin1_General_BIN NOT NULL,
[LockDownACOItems] [dbo].[bYN] NOT NULL,
[SubmittalReviewDaysResponsibleFirm] [int] NULL,
[SubmittalReviewDaysApprovingFirm] [int] NULL,
[SubmittalReviewDaysRequestingFirm] [int] NULL,
[DocHistSubmittalRegister] [dbo].[bYN] NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
