CREATE TABLE [dbo].[vDDRelatedForms]
(
[Form] [varchar] (30) COLLATE Latin1_General_BIN NOT NULL,
[Tab] [tinyint] NOT NULL,
[GridKeySeq] [int] NOT NULL,
[ParentFieldSeq] [int] NOT NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[vtDDRelatedFormsd_Audit] ON [dbo].[vDDRelatedForms]
 AFTER DELETE
 NOT FOR REPLICATION AS
 SET NOCOUNT ON 
 -- generated by vspHQCreateAuditTriggers on May 14 2009  9:56AM

 BEGIN TRY 
   INSERT dbo.vDDChangeLog (TableName, KeyString, Action, FieldName, OldValue, NewValue, DateTime, MachineName, CommandText)
   SELECT 'vDDRelatedForms' , '<KeyString ParentForm = "' + REPLACE(CAST(deleted.Form AS VARCHAR(MAX)),'"', '&quot;') + '" Tab = "' + REPLACE(CAST(deleted.Tab AS VARCHAR(MAX)),'"', '&quot;') + '" GridKeySeq = "' + REPLACE(CAST(deleted.GridKeySeq AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 'D' , NULL , NULL , NULL , GETDATE() , HOST_NAME() , 'DELETE FROM vDDRelatedForms WHERE Form = ''' + CAST(deleted.Form AS VARCHAR(MAX)) + '''' + ' AND Tab = ''' + CAST(deleted.Tab AS VARCHAR(MAX)) + '''' + ' AND GridKeySeq = ''' + CAST(deleted.GridKeySeq AS VARCHAR(MAX)) + ''''
	FROM deleted
 END TRY 
 BEGIN CATCH 
   RAISERROR('Error in [dbo].[dbo.vtDDRelatedFormsi_Audit] trigger', 16, 1 ) with log
 END CATCH 
GO
EXEC sp_settriggerorder N'[dbo].[vtDDRelatedFormsd_Audit]', 'last', 'delete', null
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[vtDDRelatedFormsi_Audit] ON [dbo].[vDDRelatedForms]
 AFTER INSERT
 NOT FOR REPLICATION AS
 SET NOCOUNT ON 
 -- generated by vspHQCreateAuditTriggers on May 14 2009  9:56AM

 BEGIN TRY 
   INSERT dbo.vDDChangeLog (TableName, KeyString, Action, FieldName, OldValue, NewValue, DateTime, MachineName, CommandText)
   SELECT 'vDDRelatedForms' , '<KeyString ParentForm = "' + REPLACE(CAST(inserted.Form AS VARCHAR(MAX)),'"', '&quot;') + '" Tab = "' + REPLACE(CAST(inserted.Tab AS VARCHAR(MAX)),'"', '&quot;') + '" GridKeySeq = "' + REPLACE(CAST(inserted.GridKeySeq AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 'A' , NULL , NULL , NULL , GETDATE() , HOST_NAME() , 'INSERT INTO dbo.[vDDRelatedForms] ([Form], [Tab], [GridKeySeq], [ParentFieldSeq]) VALUES (' + ISNULL('''' + REPLACE(CAST(Form AS NVARCHAR(MAX)), '''' , '''''') + '''', 'NULL') + ',' + ISNULL(CAST(Tab AS NVARCHAR(MAX)), 'NULL') +  ',' + ISNULL(CAST(GridKeySeq AS NVARCHAR(MAX)), 'NULL') +  ',' + ISNULL(CAST(ParentFieldSeq AS NVARCHAR(MAX)), 'NULL') + + ')'
	FROM inserted
 END TRY 
 BEGIN CATCH 
   RAISERROR('Error in [dbo].[dbo.vtDDRelatedFormsi_Audit] trigger', 16, 1 ) with log
 END CATCH 
GO
EXEC sp_settriggerorder N'[dbo].[vtDDRelatedFormsi_Audit]', 'last', 'insert', null
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[vtDDRelatedFormsu_Audit] ON [dbo].[vDDRelatedForms]
 AFTER UPDATE 
 NOT FOR REPLICATION AS 
 SET NOCOUNT ON 
 -- generated by vspHQCreateAuditTriggers on May 14 2009  9:56AM

 BEGIN TRY 
 IF UPDATE([Form])
   INSERT dbo.vDDChangeLog (TableName, KeyString, Action, FieldName, OldValue, NewValue, DateTime, MachineName, CommandText)
   SELECT 'vDDRelatedForms' , '<KeyString ParentForm = "' + REPLACE(CAST(inserted.Form AS VARCHAR(MAX)),'"', '&quot;') + '" Tab = "' + REPLACE(CAST(inserted.Tab AS VARCHAR(MAX)),'"', '&quot;') + '" GridKeySeq = "' + REPLACE(CAST(inserted.GridKeySeq AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 'U' , 'Form' ,  CONVERT(VARCHAR(MAX), deleted.[Form]) ,  Convert(VARCHAR(MAX), inserted.[Form]) , GETDATE() , HOST_NAME() , 'UPDATE vDDRelatedForms SET Form = ''' + ISNULL(REPLACE(Convert(VARCHAR(MAX), inserted.[Form]), '''' , ''''''), 'NULL') + ''' WHERE Form = ''' + CAST(inserted.Form AS VARCHAR(MAX)) + '''' + ' AND Tab = ''' + CAST(inserted.Tab AS VARCHAR(MAX)) + '''' + ' AND GridKeySeq = ''' + CAST(inserted.GridKeySeq AS VARCHAR(MAX)) + ''''
		FROM inserted
			INNER JOIN deleted
         ON  inserted.[Form] = deleted.[Form]  AND  inserted.[Tab] = deleted.[Tab]  AND  inserted.[GridKeySeq] = deleted.[GridKeySeq] 
         AND ISNULL(inserted.[Form],'') <> ISNULL(deleted.[Form],'')

 IF UPDATE([Tab])
   INSERT dbo.vDDChangeLog (TableName, KeyString, Action, FieldName, OldValue, NewValue, DateTime, MachineName, CommandText)
   SELECT 'vDDRelatedForms' , '<KeyString ParentForm = "' + REPLACE(CAST(inserted.Form AS VARCHAR(MAX)),'"', '&quot;') + '" Tab = "' + REPLACE(CAST(inserted.Tab AS VARCHAR(MAX)),'"', '&quot;') + '" GridKeySeq = "' + REPLACE(CAST(inserted.GridKeySeq AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 'U' , 'Tab' ,  CONVERT(VARCHAR(MAX), deleted.[Tab]) ,  Convert(VARCHAR(MAX), inserted.[Tab]) , GETDATE() , HOST_NAME() , 'UPDATE vDDRelatedForms SET Tab = ''' + ISNULL(REPLACE(Convert(VARCHAR(MAX), inserted.[Tab]), '''' , ''''''), 'NULL') + ''' WHERE Form = ''' + CAST(inserted.Form AS VARCHAR(MAX)) + '''' + ' AND Tab = ''' + CAST(inserted.Tab AS VARCHAR(MAX)) + '''' + ' AND GridKeySeq = ''' + CAST(inserted.GridKeySeq AS VARCHAR(MAX)) + ''''
		FROM inserted
			INNER JOIN deleted
         ON  inserted.[Form] = deleted.[Form]  AND  inserted.[Tab] = deleted.[Tab]  AND  inserted.[GridKeySeq] = deleted.[GridKeySeq] 
         AND ISNULL(inserted.[Tab],'') <> ISNULL(deleted.[Tab],'')

 IF UPDATE([GridKeySeq])
   INSERT dbo.vDDChangeLog (TableName, KeyString, Action, FieldName, OldValue, NewValue, DateTime, MachineName, CommandText)
   SELECT 'vDDRelatedForms' , '<KeyString ParentForm = "' + REPLACE(CAST(inserted.Form AS VARCHAR(MAX)),'"', '&quot;') + '" Tab = "' + REPLACE(CAST(inserted.Tab AS VARCHAR(MAX)),'"', '&quot;') + '" GridKeySeq = "' + REPLACE(CAST(inserted.GridKeySeq AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 'U' , 'GridKeySeq' ,  CONVERT(VARCHAR(MAX), deleted.[GridKeySeq]) ,  Convert(VARCHAR(MAX), inserted.[GridKeySeq]) , GETDATE() , HOST_NAME() , 'UPDATE vDDRelatedForms SET GridKeySeq = ''' + ISNULL(REPLACE(Convert(VARCHAR(MAX), inserted.[GridKeySeq]), '''' , ''''''), 'NULL') + ''' WHERE Form = ''' + CAST(inserted.Form AS VARCHAR(MAX)) + '''' + ' AND Tab = ''' + CAST(inserted.Tab AS VARCHAR(MAX)) + '''' + ' AND GridKeySeq = ''' + CAST(inserted.GridKeySeq AS VARCHAR(MAX)) + ''''
		FROM inserted
			INNER JOIN deleted
         ON  inserted.[Form] = deleted.[Form]  AND  inserted.[Tab] = deleted.[Tab]  AND  inserted.[GridKeySeq] = deleted.[GridKeySeq] 
         AND ISNULL(inserted.[GridKeySeq],'') <> ISNULL(deleted.[GridKeySeq],'')

 IF UPDATE([ParentFieldSeq])
   INSERT dbo.vDDChangeLog (TableName, KeyString, Action, FieldName, OldValue, NewValue, DateTime, MachineName, CommandText)
   SELECT 'vDDRelatedForms' , '<KeyString ParentForm = "' + REPLACE(CAST(inserted.Form AS VARCHAR(MAX)),'"', '&quot;') + '" Tab = "' + REPLACE(CAST(inserted.Tab AS VARCHAR(MAX)),'"', '&quot;') + '" GridKeySeq = "' + REPLACE(CAST(inserted.GridKeySeq AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 'U' , 'ParentFieldSeq' ,  CONVERT(VARCHAR(MAX), deleted.[ParentFieldSeq]) ,  Convert(VARCHAR(MAX), inserted.[ParentFieldSeq]) , GETDATE() , HOST_NAME() , 'UPDATE vDDRelatedForms SET ParentFieldSeq = ''' + ISNULL(REPLACE(Convert(VARCHAR(MAX), inserted.[ParentFieldSeq]), '''' , ''''''), 'NULL') + ''' WHERE Form = ''' + CAST(inserted.Form AS VARCHAR(MAX)) + '''' + ' AND Tab = ''' + CAST(inserted.Tab AS VARCHAR(MAX)) + '''' + ' AND GridKeySeq = ''' + CAST(inserted.GridKeySeq AS VARCHAR(MAX)) + ''''
		FROM inserted
			INNER JOIN deleted
         ON  inserted.[Form] = deleted.[Form]  AND  inserted.[Tab] = deleted.[Tab]  AND  inserted.[GridKeySeq] = deleted.[GridKeySeq] 
         AND ISNULL(inserted.[ParentFieldSeq],'') <> ISNULL(deleted.[ParentFieldSeq],'')

 END TRY 
 BEGIN CATCH 
   RAISERROR('Error in [dbo].[dbo.vtDDRelatedFormsi_Audit] trigger', 16, 1 ) with log
 END CATCH 
GO
EXEC sp_settriggerorder N'[dbo].[vtDDRelatedFormsu_Audit]', 'last', 'update', null
GO
ALTER TABLE [dbo].[vDDRelatedForms] ADD CONSTRAINT [PK_vDDRelatedForms] PRIMARY KEY CLUSTERED  ([Form], [Tab], [GridKeySeq]) ON [PRIMARY]
GO
