SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE VIEW [dbo].[PRAUBASGSTItems]
AS 
SELECT * FROM dbo.[vPRAUBASGSTItems]


GO
GRANT SELECT ON  [dbo].[PRAUBASGSTItems] TO [public]
GRANT INSERT ON  [dbo].[PRAUBASGSTItems] TO [public]
GRANT DELETE ON  [dbo].[PRAUBASGSTItems] TO [public]
GRANT UPDATE ON  [dbo].[PRAUBASGSTItems] TO [public]
GRANT SELECT ON  [dbo].[PRAUBASGSTItems] TO [Viewpoint]
GRANT INSERT ON  [dbo].[PRAUBASGSTItems] TO [Viewpoint]
GRANT DELETE ON  [dbo].[PRAUBASGSTItems] TO [Viewpoint]
GRANT UPDATE ON  [dbo].[PRAUBASGSTItems] TO [Viewpoint]
GO
