CREATE TABLE [dbo].[boldPREH20131023]
(
[PRCo] [dbo].[bCompany] NOT NULL,
[Employee] [dbo].[bEmployee] NOT NULL,
[LastName] [varchar] (30) COLLATE Latin1_General_BIN NOT NULL,
[FirstName] [varchar] (30) COLLATE Latin1_General_BIN NULL,
[MidName] [varchar] (15) COLLATE Latin1_General_BIN NULL,
[SortName] [dbo].[bSortName] NOT NULL,
[Address] [varchar] (60) COLLATE Latin1_General_BIN NULL,
[City] [varchar] (30) COLLATE Latin1_General_BIN NULL,
[State] [varchar] (4) COLLATE Latin1_General_BIN NULL,
[Zip] [dbo].[bZip] NULL,
[Address2] [varchar] (60) COLLATE Latin1_General_BIN NULL,
[Phone] [dbo].[bPhone] NULL,
[SSN] [char] (11) COLLATE Latin1_General_BIN NOT NULL,
[Race] [char] (2) COLLATE Latin1_General_BIN NOT NULL,
[Sex] [char] (1) COLLATE Latin1_General_BIN NOT NULL,
[BirthDate] [smalldatetime] NULL,
[HireDate] [dbo].[bDate] NULL,
[TermDate] [dbo].[bDate] NULL,
[PRGroup] [dbo].[bGroup] NOT NULL,
[PRDept] [dbo].[bDept] NOT NULL,
[Craft] [dbo].[bCraft] NULL,
[Class] [dbo].[bClass] NULL,
[InsCode] [dbo].[bInsCode] NOT NULL,
[TaxState] [varchar] (4) COLLATE Latin1_General_BIN NULL,
[UnempState] [varchar] (4) COLLATE Latin1_General_BIN NOT NULL,
[InsState] [varchar] (4) COLLATE Latin1_General_BIN NOT NULL,
[LocalCode] [dbo].[bLocalCode] NULL,
[GLCo] [dbo].[bCompany] NULL,
[UseState] [dbo].[bYN] NOT NULL,
[UseIns] [dbo].[bYN] NOT NULL,
[JCCo] [dbo].[bCompany] NULL,
[Job] [dbo].[bJob] NULL,
[Crew] [varchar] (10) COLLATE Latin1_General_BIN NULL,
[LastUpdated] [dbo].[bDate] NULL,
[EarnCode] [dbo].[bEDLCode] NOT NULL,
[HrlyRate] [dbo].[bUnitCost] NOT NULL,
[SalaryAmt] [dbo].[bDollar] NOT NULL,
[OTOpt] [char] (1) COLLATE Latin1_General_BIN NOT NULL,
[OTSched] [tinyint] NULL,
[JCFixedRate] [dbo].[bUnitCost] NOT NULL,
[EMFixedRate] [dbo].[bUnitCost] NOT NULL,
[YTDSUI] [dbo].[bDollar] NOT NULL,
[OccupCat] [varchar] (10) COLLATE Latin1_General_BIN NULL,
[CatStatus] [char] (1) COLLATE Latin1_General_BIN NULL,
[DirDeposit] [char] (1) COLLATE Latin1_General_BIN NOT NULL,
[RoutingId] [varchar] (10) COLLATE Latin1_General_BIN NULL,
[BankAcct] [varchar] (20) COLLATE Latin1_General_BIN NULL,
[AcctType] [char] (1) COLLATE Latin1_General_BIN NULL,
[ActiveYN] [dbo].[bYN] NOT NULL,
[PensionYN] [dbo].[bYN] NOT NULL,
[PostToAll] [dbo].[bYN] NOT NULL,
[CertYN] [dbo].[bYN] NOT NULL,
[ChkSort] [varchar] (10) COLLATE Latin1_General_BIN NULL,
[AuditYN] [dbo].[bYN] NOT NULL,
[Notes] [varchar] (max) COLLATE Latin1_General_BIN NULL,
[UniqueAttchID] [uniqueidentifier] NULL,
[Email] [varchar] (60) COLLATE Latin1_General_BIN NULL,
[DefaultPaySeq] [dbo].[bYN] NOT NULL,
[DDPaySeq] [tinyint] NULL,
[Suffix] [varchar] (4) COLLATE Latin1_General_BIN NULL,
[TradeSeq] [tinyint] NULL,
[CSLimit] [dbo].[bPct] NULL,
[CSGarnGroup] [dbo].[bGroup] NULL,
[CSAllocMethod] [char] (1) COLLATE Latin1_General_BIN NOT NULL,
[Shift] [tinyint] NULL,
[NonResAlienYN] [char] (1) COLLATE Latin1_General_BIN NOT NULL,
[KeyID] [bigint] NOT NULL IDENTITY(1, 1),
[Country] [char] (2) COLLATE Latin1_General_BIN NULL,
[HDAmt] [dbo].[bDollar] NULL,
[F1Amt] [dbo].[bDollar] NULL,
[LCFStock] [dbo].[bDollar] NULL,
[LCPStock] [dbo].[bDollar] NULL,
[NAICS] [varchar] (6) COLLATE Latin1_General_BIN NULL,
[AUEFTYN] [dbo].[bYN] NOT NULL,
[AUAccountNumber] [varchar] (9) COLLATE Latin1_General_BIN NULL,
[AUBSB] [varchar] (6) COLLATE Latin1_General_BIN NULL,
[AUReference] [varchar] (18) COLLATE Latin1_General_BIN NULL,
[EMCo] [dbo].[bCompany] NULL,
[Equipment] [dbo].[bEquip] NULL,
[EMGroup] [dbo].[bGroup] NULL,
[PayMethodDelivery] [char] (1) COLLATE Latin1_General_BIN NULL,
[CPPQPPExempt] [dbo].[bYN] NOT NULL,
[EIExempt] [dbo].[bYN] NOT NULL,
[PPIPExempt] [dbo].[bYN] NOT NULL,
[TimesheetRevGroup] [varchar] (10) COLLATE Latin1_General_BIN NULL,
[UpdatePRAEYN] [dbo].[bYN] NOT NULL,
[WOTaxState] [varchar] (4) COLLATE Latin1_General_BIN NULL,
[WOLocalCode] [dbo].[bLocalCode] NULL,
[UseLocal] [dbo].[bYN] NOT NULL,
[UseUnempState] [dbo].[bYN] NOT NULL,
[UseInsState] [dbo].[bYN] NOT NULL,
[NewHireActStartDate] [dbo].[bDate] NULL,
[NewHireActEndDate] [dbo].[bDate] NULL,
[CellPhone] [dbo].[bPhone] NULL,
[ArrearsActiveYN] [dbo].[bYN] NOT NULL,
[udOrigHireDate] [smalldatetime] NULL,
[udEmpGroup] [varchar] (25) COLLATE Latin1_General_BIN NULL,
[udSource] [varchar] (30) COLLATE Latin1_General_BIN NULL,
[udConv] [varchar] (1) COLLATE Latin1_General_BIN NULL,
[udCGCTable] [varchar] (10) COLLATE Latin1_General_BIN NULL,
[udCGCTableID] [decimal] (12, 0) NULL,
[RecentRehireDate] [dbo].[bDate] NULL,
[RecentSeparationDate] [dbo].[bDate] NULL,
[SeparationRedundancyRetirement] [dbo].[bYN] NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
