CREATE TABLE [dbo].[bEMAG]
(
[EMCo] [dbo].[bCompany] NOT NULL,
[AllocCode] [tinyint] NOT NULL,
[Category] [varchar] (10) COLLATE Latin1_General_BIN NOT NULL
) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [biEMAG] ON [dbo].[bEMAG] ([EMCo], [AllocCode], [Category]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
ALTER TABLE [dbo].[bEMAG] WITH NOCHECK ADD CONSTRAINT [FK_bEMAG_bEMCO_EMCo] FOREIGN KEY ([EMCo]) REFERENCES [dbo].[bEMCO] ([EMCo])
GO
ALTER TABLE [dbo].[bEMAG] WITH NOCHECK ADD CONSTRAINT [FK_bEMAG_bEMAH_AllocCode] FOREIGN KEY ([EMCo], [AllocCode]) REFERENCES [dbo].[bEMAH] ([EMCo], [AllocCode]) ON DELETE CASCADE
GO
ALTER TABLE [dbo].[bEMAG] WITH NOCHECK ADD CONSTRAINT [FK_bEMAG_bEMCM_Category] FOREIGN KEY ([EMCo], [Category]) REFERENCES [dbo].[bEMCM] ([EMCo], [Category])
GO
ALTER TABLE [dbo].[bEMAG] NOCHECK CONSTRAINT [FK_bEMAG_bEMCO_EMCo]
GO
ALTER TABLE [dbo].[bEMAG] NOCHECK CONSTRAINT [FK_bEMAG_bEMAH_AllocCode]
GO
ALTER TABLE [dbo].[bEMAG] NOCHECK CONSTRAINT [FK_bEMAG_bEMCM_Category]
GO
