CREATE TABLE [dbo].[bEMAE]
(
[EMCo] [dbo].[bCompany] NOT NULL,
[AllocCode] [tinyint] NOT NULL,
[Equipment] [dbo].[bEquip] NOT NULL
) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [biEMAE] ON [dbo].[bEMAE] ([EMCo], [AllocCode], [Equipment]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
ALTER TABLE [dbo].[bEMAE] WITH NOCHECK ADD CONSTRAINT [FK_bEMAE_bEMCO_EMCo] FOREIGN KEY ([EMCo]) REFERENCES [dbo].[bEMCO] ([EMCo])
GO
ALTER TABLE [dbo].[bEMAE] WITH NOCHECK ADD CONSTRAINT [FK_bEMAE_bEMAH_AllocCode] FOREIGN KEY ([EMCo], [AllocCode]) REFERENCES [dbo].[bEMAH] ([EMCo], [AllocCode]) ON DELETE CASCADE
GO
ALTER TABLE [dbo].[bEMAE] WITH NOCHECK ADD CONSTRAINT [FK_bEMAE_bEMEM_Equipment] FOREIGN KEY ([EMCo], [Equipment]) REFERENCES [dbo].[bEMEM] ([EMCo], [Equipment]) ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[bEMAE] NOCHECK CONSTRAINT [FK_bEMAE_bEMCO_EMCo]
GO
ALTER TABLE [dbo].[bEMAE] NOCHECK CONSTRAINT [FK_bEMAE_bEMAH_AllocCode]
GO
ALTER TABLE [dbo].[bEMAE] NOCHECK CONSTRAINT [FK_bEMAE_bEMEM_Equipment]
GO
