CREATE TABLE [dbo].[vSMInvoiceDetail]
(
[SMInvoiceDetailID] [bigint] NOT NULL IDENTITY(1, 1),
[SMCo] [dbo].[bCompany] NOT NULL,
[Invoice] [int] NOT NULL,
[InvoiceDetail] [int] NOT NULL,
[IsRemoved] [bit] NOT NULL,
[WorkOrder] [int] NULL,
[Scope] [int] NULL,
[WorkCompleted] [int] NULL,
[Agreement] [varchar] (15) COLLATE Latin1_General_BIN NULL,
[Revision] [int] NULL,
[Service] [int] NULL,
[AgreementBilling] [int] NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- =============================================
-- Author:		Jacob Van Houten
-- Create date: 4/17/13
-- Description:	Insert Validation trigger for vSMInvoiceDetail
-- =============================================
CREATE TRIGGER [dbo].[vtSMInvoiceDetailiu]
   ON [dbo].[vSMInvoiceDetail]
   AFTER INSERT, UPDATE
AS 
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    IF EXISTS
	(
		SELECT 1
		FROM INSERTED
			INNER JOIN dbo.vSMInvoiceDetail ON INSERTED.SMCo = vSMInvoiceDetail.SMCo AND INSERTED.WorkOrder = vSMInvoiceDetail.WorkOrder AND INSERTED.WorkCompleted = vSMInvoiceDetail.WorkCompleted AND INSERTED.SMInvoiceDetailID <> vSMInvoiceDetail.SMInvoiceDetailID
	)
	BEGIN
		ROLLBACK TRAN
		RAISERROR('Work Completed can only exist on one invoice.', 11, -1)
	END
END
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER dbo.vtvSMInvoiceDetail_Audit_Delete ON dbo.vSMInvoiceDetail
 AFTER DELETE
 NOT FOR REPLICATION AS
 SET NOCOUNT ON 
 -- generated by vspAuditCreateAuditTriggers

 BEGIN TRY 

							INSERT dbo.HQMA (
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
								
							SELECT
								'vSMInvoiceDetail' , 
								'<KeyString Invoice = "' + REPLACE(CAST(ISNULL(deleted.[Invoice],'') AS VARCHAR(MAX)),'"', '&quot;') + '" InvoiceDetail = "' + REPLACE(CAST(ISNULL(deleted.[InvoiceDetail],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(deleted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								deleted.SMCo , 
								'D' , 
								'Agreement' , 
								CONVERT(VARCHAR(MAX), deleted.[Agreement]) , 								NULL , 
								GETDATE() , 
								SUSER_SNAME()
							FROM deleted
								JOIN dbo.vAuditFlagCompany AS afc ON deleted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 13
							INSERT dbo.HQMA (
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
								
							SELECT
								'vSMInvoiceDetail' , 
								'<KeyString Invoice = "' + REPLACE(CAST(ISNULL(deleted.[Invoice],'') AS VARCHAR(MAX)),'"', '&quot;') + '" InvoiceDetail = "' + REPLACE(CAST(ISNULL(deleted.[InvoiceDetail],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(deleted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								deleted.SMCo , 
								'D' , 
								'AgreementBilling' , 
								CONVERT(VARCHAR(MAX), deleted.[AgreementBilling]) , 								NULL , 
								GETDATE() , 
								SUSER_SNAME()
							FROM deleted
								JOIN dbo.vAuditFlagCompany AS afc ON deleted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 13
							INSERT dbo.HQMA (
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
								
							SELECT
								'vSMInvoiceDetail' , 
								'<KeyString Invoice = "' + REPLACE(CAST(ISNULL(deleted.[Invoice],'') AS VARCHAR(MAX)),'"', '&quot;') + '" InvoiceDetail = "' + REPLACE(CAST(ISNULL(deleted.[InvoiceDetail],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(deleted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								deleted.SMCo , 
								'D' , 
								'Invoice' , 
								CONVERT(VARCHAR(MAX), deleted.[Invoice]) , 								NULL , 
								GETDATE() , 
								SUSER_SNAME()
							FROM deleted
								JOIN dbo.vAuditFlagCompany AS afc ON deleted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 13
							INSERT dbo.HQMA (
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
								
							SELECT
								'vSMInvoiceDetail' , 
								'<KeyString Invoice = "' + REPLACE(CAST(ISNULL(deleted.[Invoice],'') AS VARCHAR(MAX)),'"', '&quot;') + '" InvoiceDetail = "' + REPLACE(CAST(ISNULL(deleted.[InvoiceDetail],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(deleted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								deleted.SMCo , 
								'D' , 
								'InvoiceDetail' , 
								CONVERT(VARCHAR(MAX), deleted.[InvoiceDetail]) , 								NULL , 
								GETDATE() , 
								SUSER_SNAME()
							FROM deleted
								JOIN dbo.vAuditFlagCompany AS afc ON deleted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 13
							INSERT dbo.HQMA (
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
								
							SELECT
								'vSMInvoiceDetail' , 
								'<KeyString Invoice = "' + REPLACE(CAST(ISNULL(deleted.[Invoice],'') AS VARCHAR(MAX)),'"', '&quot;') + '" InvoiceDetail = "' + REPLACE(CAST(ISNULL(deleted.[InvoiceDetail],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(deleted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								deleted.SMCo , 
								'D' , 
								'IsRemoved' , 
								CONVERT(VARCHAR(MAX), deleted.[IsRemoved]) , 								NULL , 
								GETDATE() , 
								SUSER_SNAME()
							FROM deleted
								JOIN dbo.vAuditFlagCompany AS afc ON deleted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 13
							INSERT dbo.HQMA (
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
								
							SELECT
								'vSMInvoiceDetail' , 
								'<KeyString Invoice = "' + REPLACE(CAST(ISNULL(deleted.[Invoice],'') AS VARCHAR(MAX)),'"', '&quot;') + '" InvoiceDetail = "' + REPLACE(CAST(ISNULL(deleted.[InvoiceDetail],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(deleted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								deleted.SMCo , 
								'D' , 
								'Revision' , 
								CONVERT(VARCHAR(MAX), deleted.[Revision]) , 								NULL , 
								GETDATE() , 
								SUSER_SNAME()
							FROM deleted
								JOIN dbo.vAuditFlagCompany AS afc ON deleted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 13
							INSERT dbo.HQMA (
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
								
							SELECT
								'vSMInvoiceDetail' , 
								'<KeyString Invoice = "' + REPLACE(CAST(ISNULL(deleted.[Invoice],'') AS VARCHAR(MAX)),'"', '&quot;') + '" InvoiceDetail = "' + REPLACE(CAST(ISNULL(deleted.[InvoiceDetail],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(deleted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								deleted.SMCo , 
								'D' , 
								'SMCo' , 
								CONVERT(VARCHAR(MAX), deleted.[SMCo]) , 								NULL , 
								GETDATE() , 
								SUSER_SNAME()
							FROM deleted
								JOIN dbo.vAuditFlagCompany AS afc ON deleted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 13
							INSERT dbo.HQMA (
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
								
							SELECT
								'vSMInvoiceDetail' , 
								'<KeyString Invoice = "' + REPLACE(CAST(ISNULL(deleted.[Invoice],'') AS VARCHAR(MAX)),'"', '&quot;') + '" InvoiceDetail = "' + REPLACE(CAST(ISNULL(deleted.[InvoiceDetail],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(deleted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								deleted.SMCo , 
								'D' , 
								'SMInvoiceDetailID' , 
								CONVERT(VARCHAR(MAX), deleted.[SMInvoiceDetailID]) , 								NULL , 
								GETDATE() , 
								SUSER_SNAME()
							FROM deleted
								JOIN dbo.vAuditFlagCompany AS afc ON deleted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 13
							INSERT dbo.HQMA (
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
								
							SELECT
								'vSMInvoiceDetail' , 
								'<KeyString Invoice = "' + REPLACE(CAST(ISNULL(deleted.[Invoice],'') AS VARCHAR(MAX)),'"', '&quot;') + '" InvoiceDetail = "' + REPLACE(CAST(ISNULL(deleted.[InvoiceDetail],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(deleted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								deleted.SMCo , 
								'D' , 
								'Scope' , 
								CONVERT(VARCHAR(MAX), deleted.[Scope]) , 								NULL , 
								GETDATE() , 
								SUSER_SNAME()
							FROM deleted
								JOIN dbo.vAuditFlagCompany AS afc ON deleted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 13
							INSERT dbo.HQMA (
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
								
							SELECT
								'vSMInvoiceDetail' , 
								'<KeyString Invoice = "' + REPLACE(CAST(ISNULL(deleted.[Invoice],'') AS VARCHAR(MAX)),'"', '&quot;') + '" InvoiceDetail = "' + REPLACE(CAST(ISNULL(deleted.[InvoiceDetail],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(deleted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								deleted.SMCo , 
								'D' , 
								'Service' , 
								CONVERT(VARCHAR(MAX), deleted.[Service]) , 								NULL , 
								GETDATE() , 
								SUSER_SNAME()
							FROM deleted
								JOIN dbo.vAuditFlagCompany AS afc ON deleted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 13
							INSERT dbo.HQMA (
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
								
							SELECT
								'vSMInvoiceDetail' , 
								'<KeyString Invoice = "' + REPLACE(CAST(ISNULL(deleted.[Invoice],'') AS VARCHAR(MAX)),'"', '&quot;') + '" InvoiceDetail = "' + REPLACE(CAST(ISNULL(deleted.[InvoiceDetail],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(deleted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								deleted.SMCo , 
								'D' , 
								'WorkCompleted' , 
								CONVERT(VARCHAR(MAX), deleted.[WorkCompleted]) , 								NULL , 
								GETDATE() , 
								SUSER_SNAME()
							FROM deleted
								JOIN dbo.vAuditFlagCompany AS afc ON deleted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 13
							INSERT dbo.HQMA (
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
								
							SELECT
								'vSMInvoiceDetail' , 
								'<KeyString Invoice = "' + REPLACE(CAST(ISNULL(deleted.[Invoice],'') AS VARCHAR(MAX)),'"', '&quot;') + '" InvoiceDetail = "' + REPLACE(CAST(ISNULL(deleted.[InvoiceDetail],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(deleted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								deleted.SMCo , 
								'D' , 
								'WorkOrder' , 
								CONVERT(VARCHAR(MAX), deleted.[WorkOrder]) , 								NULL , 
								GETDATE() , 
								SUSER_SNAME()
							FROM deleted
								JOIN dbo.vAuditFlagCompany AS afc ON deleted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 13

							
 END TRY 
 BEGIN CATCH 
   DECLARE	@ErrorMessage	NVARCHAR(4000), 
				@ErrorSeverity	INT; 

   SELECT	@ErrorMessage = 'Error '+ ISNULL(ERROR_MESSAGE(),'') +' in [dbo].[dbo.vtvSMInvoiceDetail_Audit_Delete] trigger', 
				@ErrorSeverity = ERROR_SEVERITY(); 

   RAISERROR(@ErrorMessage, @ErrorSeverity, 1 ) 
 END CATCH 
GO
EXEC sp_settriggerorder N'[dbo].[vtvSMInvoiceDetail_Audit_Delete]', 'last', 'delete', null
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER dbo.vtvSMInvoiceDetail_Audit_Insert ON dbo.vSMInvoiceDetail
 AFTER INSERT
 NOT FOR REPLICATION AS
 SET NOCOUNT ON 
 -- generated by vspAuditTriggersCreate

 BEGIN TRY 

-- log additions to the Agreement column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vSMInvoiceDetail' , 
								'<KeyString Invoice = "' + REPLACE(CAST(ISNULL(inserted.[Invoice],'') AS VARCHAR(MAX)),'"', '&quot;') + '" InvoiceDetail = "' + REPLACE(CAST(ISNULL(inserted.[InvoiceDetail],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(inserted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.SMCo, '') , 
								'A' , 
								'Agreement' , 
								NULL , 
								[Agreement] , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								JOIN dbo.vAuditFlagCompany AS afc ON inserted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 13

-- log additions to the AgreementBilling column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vSMInvoiceDetail' , 
								'<KeyString Invoice = "' + REPLACE(CAST(ISNULL(inserted.[Invoice],'') AS VARCHAR(MAX)),'"', '&quot;') + '" InvoiceDetail = "' + REPLACE(CAST(ISNULL(inserted.[InvoiceDetail],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(inserted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.SMCo, '') , 
								'A' , 
								'AgreementBilling' , 
								NULL , 
								[AgreementBilling] , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								JOIN dbo.vAuditFlagCompany AS afc ON inserted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 13

-- log additions to the Invoice column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vSMInvoiceDetail' , 
								'<KeyString Invoice = "' + REPLACE(CAST(ISNULL(inserted.[Invoice],'') AS VARCHAR(MAX)),'"', '&quot;') + '" InvoiceDetail = "' + REPLACE(CAST(ISNULL(inserted.[InvoiceDetail],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(inserted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.SMCo, '') , 
								'A' , 
								'Invoice' , 
								NULL , 
								[Invoice] , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								JOIN dbo.vAuditFlagCompany AS afc ON inserted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 13

-- log additions to the InvoiceDetail column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vSMInvoiceDetail' , 
								'<KeyString Invoice = "' + REPLACE(CAST(ISNULL(inserted.[Invoice],'') AS VARCHAR(MAX)),'"', '&quot;') + '" InvoiceDetail = "' + REPLACE(CAST(ISNULL(inserted.[InvoiceDetail],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(inserted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.SMCo, '') , 
								'A' , 
								'InvoiceDetail' , 
								NULL , 
								[InvoiceDetail] , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								JOIN dbo.vAuditFlagCompany AS afc ON inserted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 13

-- log additions to the IsRemoved column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vSMInvoiceDetail' , 
								'<KeyString Invoice = "' + REPLACE(CAST(ISNULL(inserted.[Invoice],'') AS VARCHAR(MAX)),'"', '&quot;') + '" InvoiceDetail = "' + REPLACE(CAST(ISNULL(inserted.[InvoiceDetail],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(inserted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.SMCo, '') , 
								'A' , 
								'IsRemoved' , 
								NULL , 
								[IsRemoved] , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								JOIN dbo.vAuditFlagCompany AS afc ON inserted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 13

-- log additions to the Revision column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vSMInvoiceDetail' , 
								'<KeyString Invoice = "' + REPLACE(CAST(ISNULL(inserted.[Invoice],'') AS VARCHAR(MAX)),'"', '&quot;') + '" InvoiceDetail = "' + REPLACE(CAST(ISNULL(inserted.[InvoiceDetail],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(inserted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.SMCo, '') , 
								'A' , 
								'Revision' , 
								NULL , 
								[Revision] , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								JOIN dbo.vAuditFlagCompany AS afc ON inserted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 13

-- log additions to the SMCo column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vSMInvoiceDetail' , 
								'<KeyString Invoice = "' + REPLACE(CAST(ISNULL(inserted.[Invoice],'') AS VARCHAR(MAX)),'"', '&quot;') + '" InvoiceDetail = "' + REPLACE(CAST(ISNULL(inserted.[InvoiceDetail],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(inserted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.SMCo, '') , 
								'A' , 
								'SMCo' , 
								NULL , 
								[SMCo] , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								JOIN dbo.vAuditFlagCompany AS afc ON inserted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 13

-- log additions to the SMInvoiceDetailID column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vSMInvoiceDetail' , 
								'<KeyString Invoice = "' + REPLACE(CAST(ISNULL(inserted.[Invoice],'') AS VARCHAR(MAX)),'"', '&quot;') + '" InvoiceDetail = "' + REPLACE(CAST(ISNULL(inserted.[InvoiceDetail],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(inserted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.SMCo, '') , 
								'A' , 
								'SMInvoiceDetailID' , 
								NULL , 
								[SMInvoiceDetailID] , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								JOIN dbo.vAuditFlagCompany AS afc ON inserted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 13

-- log additions to the Scope column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vSMInvoiceDetail' , 
								'<KeyString Invoice = "' + REPLACE(CAST(ISNULL(inserted.[Invoice],'') AS VARCHAR(MAX)),'"', '&quot;') + '" InvoiceDetail = "' + REPLACE(CAST(ISNULL(inserted.[InvoiceDetail],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(inserted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.SMCo, '') , 
								'A' , 
								'Scope' , 
								NULL , 
								[Scope] , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								JOIN dbo.vAuditFlagCompany AS afc ON inserted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 13

-- log additions to the Service column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vSMInvoiceDetail' , 
								'<KeyString Invoice = "' + REPLACE(CAST(ISNULL(inserted.[Invoice],'') AS VARCHAR(MAX)),'"', '&quot;') + '" InvoiceDetail = "' + REPLACE(CAST(ISNULL(inserted.[InvoiceDetail],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(inserted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.SMCo, '') , 
								'A' , 
								'Service' , 
								NULL , 
								[Service] , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								JOIN dbo.vAuditFlagCompany AS afc ON inserted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 13

-- log additions to the WorkCompleted column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vSMInvoiceDetail' , 
								'<KeyString Invoice = "' + REPLACE(CAST(ISNULL(inserted.[Invoice],'') AS VARCHAR(MAX)),'"', '&quot;') + '" InvoiceDetail = "' + REPLACE(CAST(ISNULL(inserted.[InvoiceDetail],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(inserted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.SMCo, '') , 
								'A' , 
								'WorkCompleted' , 
								NULL , 
								[WorkCompleted] , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								JOIN dbo.vAuditFlagCompany AS afc ON inserted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 13

-- log additions to the WorkOrder column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vSMInvoiceDetail' , 
								'<KeyString Invoice = "' + REPLACE(CAST(ISNULL(inserted.[Invoice],'') AS VARCHAR(MAX)),'"', '&quot;') + '" InvoiceDetail = "' + REPLACE(CAST(ISNULL(inserted.[InvoiceDetail],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(inserted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.SMCo, '') , 
								'A' , 
								'WorkOrder' , 
								NULL , 
								[WorkOrder] , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								JOIN dbo.vAuditFlagCompany AS afc ON inserted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 13


 END TRY 
 BEGIN CATCH 
   DECLARE	@ErrorMessage	NVARCHAR(4000), 
				@ErrorSeverity	INT; 

   SELECT	@ErrorMessage = 'Error '+ ISNULL(ERROR_MESSAGE(),'') +' in [dbo].[dbo.vtvSMInvoiceDetail_Audit_Insert] trigger', 
				@ErrorSeverity = ERROR_SEVERITY(); 

   RAISERROR(@ErrorMessage, @ErrorSeverity, 1 ) 
 END CATCH 
GO
EXEC sp_settriggerorder N'[dbo].[vtvSMInvoiceDetail_Audit_Insert]', 'last', 'insert', null
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER dbo.vtvSMInvoiceDetail_Audit_Update ON dbo.vSMInvoiceDetail
 AFTER UPDATE 
 NOT FOR REPLICATION AS 
 SET NOCOUNT ON 
 -- generated by vspAuditTriggersCreate

 BEGIN TRY 

							IF UPDATE([Agreement])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vSMInvoiceDetail' , 								'<KeyString Invoice = "' + REPLACE(CAST(ISNULL(inserted.[Invoice],'') AS VARCHAR(MAX)),'"', '&quot;') + '" InvoiceDetail = "' + REPLACE(CAST(ISNULL(inserted.[InvoiceDetail],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(inserted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.SMCo , 								'C' , 								'Agreement' , 								CONVERT(VARCHAR(MAX), deleted.[Agreement]) , 								CONVERT(VARCHAR(MAX), inserted.[Agreement]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[SMInvoiceDetailID] = deleted.[SMInvoiceDetailID] 
									AND ((inserted.[Agreement] <> deleted.[Agreement]) OR (inserted.[Agreement] IS NULL AND deleted.[Agreement] IS NOT NULL) OR (inserted.[Agreement] IS NOT NULL AND deleted.[Agreement] IS NULL))
								JOIN dbo.vAuditFlagCompany AS afc ON inserted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 13

							END 

							IF UPDATE([AgreementBilling])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vSMInvoiceDetail' , 								'<KeyString Invoice = "' + REPLACE(CAST(ISNULL(inserted.[Invoice],'') AS VARCHAR(MAX)),'"', '&quot;') + '" InvoiceDetail = "' + REPLACE(CAST(ISNULL(inserted.[InvoiceDetail],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(inserted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.SMCo , 								'C' , 								'AgreementBilling' , 								CONVERT(VARCHAR(MAX), deleted.[AgreementBilling]) , 								CONVERT(VARCHAR(MAX), inserted.[AgreementBilling]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[SMInvoiceDetailID] = deleted.[SMInvoiceDetailID] 
									AND ((inserted.[AgreementBilling] <> deleted.[AgreementBilling]) OR (inserted.[AgreementBilling] IS NULL AND deleted.[AgreementBilling] IS NOT NULL) OR (inserted.[AgreementBilling] IS NOT NULL AND deleted.[AgreementBilling] IS NULL))
								JOIN dbo.vAuditFlagCompany AS afc ON inserted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 13

							END 

							IF UPDATE([Invoice])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vSMInvoiceDetail' , 								'<KeyString Invoice = "' + REPLACE(CAST(ISNULL(inserted.[Invoice],'') AS VARCHAR(MAX)),'"', '&quot;') + '" InvoiceDetail = "' + REPLACE(CAST(ISNULL(inserted.[InvoiceDetail],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(inserted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.SMCo , 								'C' , 								'Invoice' , 								CONVERT(VARCHAR(MAX), deleted.[Invoice]) , 								CONVERT(VARCHAR(MAX), inserted.[Invoice]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[SMInvoiceDetailID] = deleted.[SMInvoiceDetailID] 
									AND ((inserted.[Invoice] <> deleted.[Invoice]) OR (inserted.[Invoice] IS NULL AND deleted.[Invoice] IS NOT NULL) OR (inserted.[Invoice] IS NOT NULL AND deleted.[Invoice] IS NULL))
								JOIN dbo.vAuditFlagCompany AS afc ON inserted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 13

							END 

							IF UPDATE([InvoiceDetail])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vSMInvoiceDetail' , 								'<KeyString Invoice = "' + REPLACE(CAST(ISNULL(inserted.[Invoice],'') AS VARCHAR(MAX)),'"', '&quot;') + '" InvoiceDetail = "' + REPLACE(CAST(ISNULL(inserted.[InvoiceDetail],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(inserted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.SMCo , 								'C' , 								'InvoiceDetail' , 								CONVERT(VARCHAR(MAX), deleted.[InvoiceDetail]) , 								CONVERT(VARCHAR(MAX), inserted.[InvoiceDetail]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[SMInvoiceDetailID] = deleted.[SMInvoiceDetailID] 
									AND ((inserted.[InvoiceDetail] <> deleted.[InvoiceDetail]) OR (inserted.[InvoiceDetail] IS NULL AND deleted.[InvoiceDetail] IS NOT NULL) OR (inserted.[InvoiceDetail] IS NOT NULL AND deleted.[InvoiceDetail] IS NULL))
								JOIN dbo.vAuditFlagCompany AS afc ON inserted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 13

							END 

							IF UPDATE([IsRemoved])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vSMInvoiceDetail' , 								'<KeyString Invoice = "' + REPLACE(CAST(ISNULL(inserted.[Invoice],'') AS VARCHAR(MAX)),'"', '&quot;') + '" InvoiceDetail = "' + REPLACE(CAST(ISNULL(inserted.[InvoiceDetail],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(inserted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.SMCo , 								'C' , 								'IsRemoved' , 								CONVERT(VARCHAR(MAX), deleted.[IsRemoved]) , 								CONVERT(VARCHAR(MAX), inserted.[IsRemoved]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[SMInvoiceDetailID] = deleted.[SMInvoiceDetailID] 
									AND ((inserted.[IsRemoved] <> deleted.[IsRemoved]) OR (inserted.[IsRemoved] IS NULL AND deleted.[IsRemoved] IS NOT NULL) OR (inserted.[IsRemoved] IS NOT NULL AND deleted.[IsRemoved] IS NULL))
								JOIN dbo.vAuditFlagCompany AS afc ON inserted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 13

							END 

							IF UPDATE([Revision])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vSMInvoiceDetail' , 								'<KeyString Invoice = "' + REPLACE(CAST(ISNULL(inserted.[Invoice],'') AS VARCHAR(MAX)),'"', '&quot;') + '" InvoiceDetail = "' + REPLACE(CAST(ISNULL(inserted.[InvoiceDetail],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(inserted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.SMCo , 								'C' , 								'Revision' , 								CONVERT(VARCHAR(MAX), deleted.[Revision]) , 								CONVERT(VARCHAR(MAX), inserted.[Revision]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[SMInvoiceDetailID] = deleted.[SMInvoiceDetailID] 
									AND ((inserted.[Revision] <> deleted.[Revision]) OR (inserted.[Revision] IS NULL AND deleted.[Revision] IS NOT NULL) OR (inserted.[Revision] IS NOT NULL AND deleted.[Revision] IS NULL))
								JOIN dbo.vAuditFlagCompany AS afc ON inserted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 13

							END 

							IF UPDATE([SMCo])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vSMInvoiceDetail' , 								'<KeyString Invoice = "' + REPLACE(CAST(ISNULL(inserted.[Invoice],'') AS VARCHAR(MAX)),'"', '&quot;') + '" InvoiceDetail = "' + REPLACE(CAST(ISNULL(inserted.[InvoiceDetail],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(inserted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.SMCo , 								'C' , 								'SMCo' , 								CONVERT(VARCHAR(MAX), deleted.[SMCo]) , 								CONVERT(VARCHAR(MAX), inserted.[SMCo]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[SMInvoiceDetailID] = deleted.[SMInvoiceDetailID] 
									AND ((inserted.[SMCo] <> deleted.[SMCo]) OR (inserted.[SMCo] IS NULL AND deleted.[SMCo] IS NOT NULL) OR (inserted.[SMCo] IS NOT NULL AND deleted.[SMCo] IS NULL))
								JOIN dbo.vAuditFlagCompany AS afc ON inserted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 13

							END 

							IF UPDATE([SMInvoiceDetailID])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vSMInvoiceDetail' , 								'<KeyString Invoice = "' + REPLACE(CAST(ISNULL(inserted.[Invoice],'') AS VARCHAR(MAX)),'"', '&quot;') + '" InvoiceDetail = "' + REPLACE(CAST(ISNULL(inserted.[InvoiceDetail],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(inserted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.SMCo , 								'C' , 								'SMInvoiceDetailID' , 								CONVERT(VARCHAR(MAX), deleted.[SMInvoiceDetailID]) , 								CONVERT(VARCHAR(MAX), inserted.[SMInvoiceDetailID]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[SMInvoiceDetailID] = deleted.[SMInvoiceDetailID] 
									AND ((inserted.[SMInvoiceDetailID] <> deleted.[SMInvoiceDetailID]) OR (inserted.[SMInvoiceDetailID] IS NULL AND deleted.[SMInvoiceDetailID] IS NOT NULL) OR (inserted.[SMInvoiceDetailID] IS NOT NULL AND deleted.[SMInvoiceDetailID] IS NULL))
								JOIN dbo.vAuditFlagCompany AS afc ON inserted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 13

							END 

							IF UPDATE([Scope])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vSMInvoiceDetail' , 								'<KeyString Invoice = "' + REPLACE(CAST(ISNULL(inserted.[Invoice],'') AS VARCHAR(MAX)),'"', '&quot;') + '" InvoiceDetail = "' + REPLACE(CAST(ISNULL(inserted.[InvoiceDetail],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(inserted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.SMCo , 								'C' , 								'Scope' , 								CONVERT(VARCHAR(MAX), deleted.[Scope]) , 								CONVERT(VARCHAR(MAX), inserted.[Scope]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[SMInvoiceDetailID] = deleted.[SMInvoiceDetailID] 
									AND ((inserted.[Scope] <> deleted.[Scope]) OR (inserted.[Scope] IS NULL AND deleted.[Scope] IS NOT NULL) OR (inserted.[Scope] IS NOT NULL AND deleted.[Scope] IS NULL))
								JOIN dbo.vAuditFlagCompany AS afc ON inserted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 13

							END 

							IF UPDATE([Service])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vSMInvoiceDetail' , 								'<KeyString Invoice = "' + REPLACE(CAST(ISNULL(inserted.[Invoice],'') AS VARCHAR(MAX)),'"', '&quot;') + '" InvoiceDetail = "' + REPLACE(CAST(ISNULL(inserted.[InvoiceDetail],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(inserted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.SMCo , 								'C' , 								'Service' , 								CONVERT(VARCHAR(MAX), deleted.[Service]) , 								CONVERT(VARCHAR(MAX), inserted.[Service]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[SMInvoiceDetailID] = deleted.[SMInvoiceDetailID] 
									AND ((inserted.[Service] <> deleted.[Service]) OR (inserted.[Service] IS NULL AND deleted.[Service] IS NOT NULL) OR (inserted.[Service] IS NOT NULL AND deleted.[Service] IS NULL))
								JOIN dbo.vAuditFlagCompany AS afc ON inserted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 13

							END 

							IF UPDATE([WorkCompleted])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vSMInvoiceDetail' , 								'<KeyString Invoice = "' + REPLACE(CAST(ISNULL(inserted.[Invoice],'') AS VARCHAR(MAX)),'"', '&quot;') + '" InvoiceDetail = "' + REPLACE(CAST(ISNULL(inserted.[InvoiceDetail],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(inserted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.SMCo , 								'C' , 								'WorkCompleted' , 								CONVERT(VARCHAR(MAX), deleted.[WorkCompleted]) , 								CONVERT(VARCHAR(MAX), inserted.[WorkCompleted]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[SMInvoiceDetailID] = deleted.[SMInvoiceDetailID] 
									AND ((inserted.[WorkCompleted] <> deleted.[WorkCompleted]) OR (inserted.[WorkCompleted] IS NULL AND deleted.[WorkCompleted] IS NOT NULL) OR (inserted.[WorkCompleted] IS NOT NULL AND deleted.[WorkCompleted] IS NULL))
								JOIN dbo.vAuditFlagCompany AS afc ON inserted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 13

							END 

							IF UPDATE([WorkOrder])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vSMInvoiceDetail' , 								'<KeyString Invoice = "' + REPLACE(CAST(ISNULL(inserted.[Invoice],'') AS VARCHAR(MAX)),'"', '&quot;') + '" InvoiceDetail = "' + REPLACE(CAST(ISNULL(inserted.[InvoiceDetail],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(inserted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.SMCo , 								'C' , 								'WorkOrder' , 								CONVERT(VARCHAR(MAX), deleted.[WorkOrder]) , 								CONVERT(VARCHAR(MAX), inserted.[WorkOrder]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[SMInvoiceDetailID] = deleted.[SMInvoiceDetailID] 
									AND ((inserted.[WorkOrder] <> deleted.[WorkOrder]) OR (inserted.[WorkOrder] IS NULL AND deleted.[WorkOrder] IS NOT NULL) OR (inserted.[WorkOrder] IS NOT NULL AND deleted.[WorkOrder] IS NULL))
								JOIN dbo.vAuditFlagCompany AS afc ON inserted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 13

							END 



 END TRY 
 BEGIN CATCH 
   DECLARE	@ErrorMessage	NVARCHAR(4000), 
				@ErrorSeverity	INT; 

   SELECT	@ErrorMessage = 'Error '+ ISNULL(ERROR_MESSAGE(),'') +' in [dbo].[dbo.vtvSMInvoiceDetail_Audit_Update] trigger', 
				@ErrorSeverity = ERROR_SEVERITY(); 

   RAISERROR(@ErrorMessage, @ErrorSeverity, 1 ) 
 END CATCH 
GO
EXEC sp_settriggerorder N'[dbo].[vtvSMInvoiceDetail_Audit_Update]', 'last', 'update', null
GO
ALTER TABLE [dbo].[vSMInvoiceDetail] WITH NOCHECK ADD CONSTRAINT [CK_vSMInvoiceDetail_Agreement] CHECK (([dbo].[vfEqualsNull]([Agreement])=[dbo].[vfEqualsNull]([Revision]) AND ([Service] IS NULL OR [Agreement] IS NOT NULL) AND [dbo].[vfEqualsNull]([AgreementBilling])=[dbo].[vfEqualsNull]([Agreement])))
GO
ALTER TABLE [dbo].[vSMInvoiceDetail] WITH NOCHECK ADD CONSTRAINT [CK_vSMInvoiceDetail_DetailSource] CHECK (([dbo].[vfEqualsNull]([WorkOrder])<>[dbo].[vfEqualsNull]([Agreement]) AND ([Scope] IS NULL OR [WorkCompleted] IS NULL)))
GO
ALTER TABLE [dbo].[vSMInvoiceDetail] WITH NOCHECK ADD CONSTRAINT [CK_vSMInvoiceDetail_WorkCompleted] CHECK (([WorkCompleted] IS NULL OR [WorkOrder] IS NOT NULL))
GO
ALTER TABLE [dbo].[vSMInvoiceDetail] WITH NOCHECK ADD CONSTRAINT [CK_vSMInvoiceDetail_WorkOrderScope] CHECK (([Scope] IS NULL OR [WorkOrder] IS NOT NULL))
GO
ALTER TABLE [dbo].[vSMInvoiceDetail] ADD CONSTRAINT [PK_vSMInvoiceDetail] PRIMARY KEY CLUSTERED  ([SMInvoiceDetailID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[vSMInvoiceDetail] ADD CONSTRAINT [IX_vSMInvoiceDetail] UNIQUE NONCLUSTERED  ([SMCo], [Invoice], [InvoiceDetail]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_vSMInvoiceDetail_Scope] ON [dbo].[vSMInvoiceDetail] ([SMCo], [WorkOrder], [Scope]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_vSMInvoiceDetail_WorkCompleted] ON [dbo].[vSMInvoiceDetail] ([SMCo], [WorkOrder], [WorkCompleted]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[vSMInvoiceDetail] WITH NOCHECK ADD CONSTRAINT [FK_vSMInvoiceDetail_vSMAgreementBillingSchedule] FOREIGN KEY ([SMCo], [Agreement], [Revision], [Service], [AgreementBilling]) REFERENCES [dbo].[vSMAgreementBillingSchedule] ([SMCo], [Agreement], [Revision], [Service], [Billing])
GO
ALTER TABLE [dbo].[vSMInvoiceDetail] WITH NOCHECK ADD CONSTRAINT [FK_vSMInvoiceDetail_vSMInvoice] FOREIGN KEY ([SMCo], [Invoice]) REFERENCES [dbo].[vSMInvoice] ([SMCo], [Invoice])
GO
ALTER TABLE [dbo].[vSMInvoiceDetail] WITH NOCHECK ADD CONSTRAINT [FK_vSMInvoiceDetail_vSMWorkOrderScope] FOREIGN KEY ([SMCo], [WorkOrder], [Scope]) REFERENCES [dbo].[vSMWorkOrderScope] ([SMCo], [WorkOrder], [Scope])
GO
ALTER TABLE [dbo].[vSMInvoiceDetail] WITH NOCHECK ADD CONSTRAINT [FK_vSMInvoiceDetail_vSMWorkCompleted] FOREIGN KEY ([SMCo], [WorkOrder], [WorkCompleted]) REFERENCES [dbo].[vSMWorkCompleted] ([SMCo], [WorkOrder], [WorkCompleted])
GO
ALTER TABLE [dbo].[vSMInvoiceDetail] NOCHECK CONSTRAINT [FK_vSMInvoiceDetail_vSMAgreementBillingSchedule]
GO
ALTER TABLE [dbo].[vSMInvoiceDetail] NOCHECK CONSTRAINT [FK_vSMInvoiceDetail_vSMInvoice]
GO
ALTER TABLE [dbo].[vSMInvoiceDetail] NOCHECK CONSTRAINT [FK_vSMInvoiceDetail_vSMWorkOrderScope]
GO
ALTER TABLE [dbo].[vSMInvoiceDetail] NOCHECK CONSTRAINT [FK_vSMInvoiceDetail_vSMWorkCompleted]
GO
