CREATE TABLE [dbo].[MckTempCraftClassLoad]
(
[CraftMaster] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[Trade] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[Notes] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[Region] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[Home_Port] [float] NULL,
[RateCode] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[Level] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[CraftClassCode] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[Description] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[EEOClass] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[ShopFlag] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[ShiftNumber1] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[ShiftRate1] [float] NULL,
[ShiftNumber2] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[ShiftRate2] [float] NULL,
[ShiftNumber3] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[ShiftRate3] [float] NULL,
[ShiftNumber4] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[ShiftRate4] [float] NULL,
[ShiftNumber5] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[ShiftRate5] [float] NULL,
[ShiftNumber6] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[ShiftRate6] [float] NULL,
[ShiftNumber7] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[ShiftRate7] [float] NULL,
[ShiftNumber8] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[ShiftRate8] [float] NULL,
[ShiftNumber9] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[ShiftRate9] [float] NULL,
[ShiftNumber10] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[ShiftRate10] [float] NULL,
[ShiftNumber11] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[ShiftRate11] [float] NULL,
[ShiftNumber12] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[ShiftRate12] [float] NULL,
[ShiftNumber13] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[ShiftRate13] [float] NULL,
[ShiftNumber14] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[ShiftRate14] [float] NULL,
[ShiftNumber15] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[ShiftRate15] [float] NULL,
[ShiftNumber16] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[ShiftRate16] [float] NULL,
[ShiftNumber17] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[ShiftRate17] [float] NULL,
[ShiftNumber18] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[ShiftRate18] [float] NULL,
[ShiftNumber19] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[ShiftRate19] [float] NULL,
[ShiftNumber20] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[ShiftRate20] [float] NULL,
[ShiftNumber21] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[ShiftRate21] [float] NULL,
[ShiftNumber22] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[ShiftRate22] [float] NULL,
[ShiftNumber23] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[ShiftRate23] [float] NULL,
[AddOnCode1] [float] NULL,
[AddOnAmt1] [float] NULL,
[AddOnCode2] [float] NULL,
[AddOnAmt2] [float] NULL,
[AddOnCode3] [float] NULL,
[AddOnAmt3] [float] NULL,
[AddOnCode4] [float] NULL,
[AddOnAmt4] [float] NULL,
[AddOnCode5] [float] NULL,
[AddOnAmt5] [float] NULL,
[AddOnCode6] [float] NULL,
[AddOnAmt6] [float] NULL,
[AddOnCode7] [float] NULL,
[AddOnRateReg7] [float] NULL,
[AddOnAmtReg7] [float] NULL,
[AddOnRateOT7] [float] NULL,
[AddOnAmtOT7] [float] NULL,
[AddOnRateDT7] [float] NULL,
[AddOnAmtDT7] [float] NULL,
[DLCode1] [float] NULL,
[DLAmt1] [float] NULL,
[DLCode2] [float] NULL,
[DLAmt2] [float] NULL,
[DLCode3] [float] NULL,
[DLAmt3] [float] NULL,
[DLCode4] [float] NULL,
[DLAmt4] [float] NULL,
[DLCode5] [float] NULL,
[DLAmt5] [float] NULL,
[DLCode6] [float] NULL,
[DLAmt6] [float] NULL,
[DLCode7] [float] NULL,
[DLAmt7] [float] NULL,
[DLCode8] [float] NULL,
[DLAmt8] [float] NULL,
[DLCode9] [float] NULL,
[DLAmt9] [float] NULL,
[DLCode10] [float] NULL,
[DLAmt10] [float] NULL,
[DLCode11] [float] NULL,
[DLAmt11] [float] NULL,
[DLCode12] [float] NULL,
[DLAmt12] [float] NULL,
[DLCode13] [float] NULL,
[DLAmt13] [float] NULL,
[DLCode14] [float] NULL,
[DLAmt14] [float] NULL,
[DLCode15] [float] NULL,
[DLAmt15] [float] NULL,
[DLCode16] [float] NULL,
[DLAmt16] [float] NULL,
[DLCode17] [float] NULL,
[DLAmt17] [float] NULL,
[DLCode18] [float] NULL,
[DLAmt18] [float] NULL,
[DLCode19] [float] NULL,
[DLAmt19] [float] NULL,
[DLCode20] [float] NULL,
[DLAmt20] [float] NULL,
[DLCode21] [float] NULL,
[DLAmt21] [float] NULL,
[DLCode22] [float] NULL,
[DLAmt22] [float] NULL,
[DLCode23] [float] NULL,
[DLAmt23] [float] NULL,
[DLCode24] [float] NULL,
[DLAmt24] [float] NULL,
[DLCode25] [float] NULL,
[DLAmt25] [float] NULL,
[DLCode26] [float] NULL,
[DLRateReg26] [float] NULL,
[DLAmtReg26] [float] NULL,
[DLRateOT26] [float] NULL,
[DLAmtOT26] [float] NULL,
[DLRateDT26] [float] NULL,
[DLAmtDT26] [float] NULL,
[DLCode27] [float] NULL,
[DLAmt27] [float] NULL,
[DLCode28] [float] NULL,
[DLAmt28] [float] NULL,
[DLCode29] [float] NULL,
[DLAmt29] [float] NULL,
[DLCode30] [float] NULL,
[DLAmt30] [float] NULL,
[DLCode31] [float] NULL,
[DLAmt31] [float] NULL,
[DLCode32] [float] NULL,
[DLAmt32] [float] NULL,
[DLCode33] [float] NULL,
[DLAmt33] [float] NULL,
[DLCode34] [float] NULL,
[DLAmt34] [float] NULL,
[DLCode35] [float] NULL,
[DLAmt35] [float] NULL,
[DLCode36] [float] NULL,
[DLAmt36] [float] NULL,
[DLCode37] [float] NULL,
[DLAmt37] [float] NULL,
[DLCode38] [float] NULL,
[DLAmt38] [float] NULL,
[DLCode39] [float] NULL,
[DLAmt39] [float] NULL,
[DLCode40] [float] NULL,
[DLAmt40] [float] NULL,
[DLCode41] [float] NULL,
[DLAmt41] [float] NULL,
[DLCode42] [float] NULL,
[DLAmt42] [float] NULL,
[DLCode43] [float] NULL,
[DLAmt43] [float] NULL,
[DLCode44] [float] NULL,
[DLAmt44] [float] NULL,
[DLCode45] [float] NULL,
[DLAmt45] [float] NULL,
[DLCode46] [float] NULL,
[DLAmt46] [float] NULL,
[DLCode47] [float] NULL,
[DLAmt47] [float] NULL,
[DLCode48] [float] NULL,
[DLAmt48] [float] NULL,
[DLCode49] [float] NULL,
[DLAmt49] [float] NULL,
[DLCode50] [float] NULL,
[DLAmt50] [float] NULL,
[DLCode501] [float] NULL,
[DLAmt501] [float] NULL,
[DLCode51] [float] NULL,
[DLAmt51] [float] NULL,
[DLCode52] [float] NULL,
[DLAmt52] [float] NULL,
[DLCode53] [float] NULL,
[DLAmt53] [float] NULL,
[DLCode54] [float] NULL,
[DLAmt54] [float] NULL,
[DLCode55] [float] NULL,
[DLAmt55] [float] NULL,
[DLCode56] [float] NULL,
[DLAmt56] [float] NULL,
[DLCode57] [float] NULL,
[DLAmt57] [float] NULL,
[DLCode58] [float] NULL,
[DLAmt58] [float] NULL,
[DLCode59] [float] NULL,
[DLAmt59] [float] NULL,
[DLCode60] [float] NULL,
[DLAmt60] [float] NULL,
[DLCode61] [float] NULL,
[DLAmt61] [float] NULL,
[DLCode62] [float] NULL,
[DLAmt62] [float] NULL,
[DLCode63] [float] NULL,
[DLAmt63] [float] NULL,
[DLCode64] [float] NULL,
[DLAmt64] [float] NULL,
[DLCode65] [float] NULL,
[DLAmt65] [float] NULL,
[DLCode66] [float] NULL,
[DLAmt66] [float] NULL,
[DLCode67] [float] NULL,
[DLAmt67] [float] NULL,
[DLCode68] [float] NULL,
[DLAmt68] [float] NULL,
[DLCode69] [float] NULL,
[DLAmt69] [float] NULL,
[DLCode70] [float] NULL,
[DLAmt70] [float] NULL,
[DLCode71] [float] NULL,
[DLAmt71] [float] NULL,
[DLCode72] [float] NULL,
[DLAmt72] [float] NULL,
[DLCode73] [float] NULL,
[DLAmt73] [float] NULL,
[DLCode74] [float] NULL,
[DLAmt74] [float] NULL,
[DLCode75] [float] NULL,
[DLAmt75] [float] NULL,
[DLCode76] [float] NULL,
[DLAmt76] [float] NULL,
[DLCode77] [float] NULL,
[DLAmt77] [float] NULL,
[DLCode78] [float] NULL,
[DLAmt78] [float] NULL,
[DLCode79] [float] NULL,
[DLAmt79] [float] NULL,
[DLCode80] [float] NULL,
[DLAmt80] [float] NULL,
[DLCode81] [float] NULL,
[DLAmt81] [float] NULL,
[DLCode82] [float] NULL,
[DLAmt82] [float] NULL,
[DLCode83] [float] NULL,
[DLAmt83] [float] NULL,
[DLCode84] [float] NULL,
[DLAmt84] [float] NULL,
[DLCode85] [float] NULL,
[DLAmt85] [float] NULL,
[DLCode86] [float] NULL,
[DLAmt86] [float] NULL
) ON [PRIMARY]
GO
