CREATE TABLE [dbo].[budGLDept]
(
[Co] [dbo].[bCompany] NOT NULL,
[GLDept] [varchar] (4) COLLATE Latin1_General_BIN NOT NULL,
[OperatingUnit] [varchar] (10) COLLATE Latin1_General_BIN NULL,
[ResponsiblePerson] [dbo].[bEmployee] NULL,
[UniqueAttchID] [uniqueidentifier] NULL,
[KeyID] [bigint] NOT NULL IDENTITY(1, 1),
[PMCo] [dbo].[bCompany] NULL,
[Type] [varchar] (1) COLLATE Latin1_General_BIN NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER dbo.vtbudGLDept_Audit_Delete ON dbo.budGLDept
 AFTER DELETE
 NOT FOR REPLICATION AS
 SET NOCOUNT ON 
 -- generated by vspHQCreateAuditTriggers on Apr 25 2014  1:56PM

 BEGIN TRY 
DECLARE @HQMAKeys TABLE
	(
		  AuditID		bigint
		, KeyString		varchar(max)
	);
   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)
		OUTPUT inserted.AuditID, inserted.KeyString INTO @HQMAKeys (AuditID, KeyString) 
   SELECT 'budGLDept' , '<KeyString GL Department = "' + REPLACE(CAST(deleted.[GLDept] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , deleted.Co , 'D' , NULL , NULL , NULL , GETDATE() , SUSER_SNAME()
	FROM deleted
 INSERT INTO HQSA ( AuditID, Datatype, Qualifier, Instance, TableName)
				SELECT Keys.AuditID, 'bEmployee', d.Co, CAST(d.ResponsiblePerson AS VARCHAR(30)), 'budGLDept'
				FROM deleted AS d
				INNER JOIN @HQMAKeys AS Keys ON Keys.KeyString = '<KeyString GL Department = "' + REPLACE(CAST(d.[GLDept] AS VARCHAR(MAX)),'"', '&quot;') + '" />'
 INSERT INTO HQSA ( AuditID, Datatype, Qualifier, Instance, TableName)
				SELECT Keys.AuditID, 'bPMCo', d.PMCo, CAST(d.PMCo AS VARCHAR(30)), 'budGLDept'
				FROM deleted AS d
				INNER JOIN @HQMAKeys AS Keys ON Keys.KeyString = '<KeyString GL Department = "' + REPLACE(CAST(d.[GLDept] AS VARCHAR(MAX)),'"', '&quot;') + '" />'

 END TRY 
 BEGIN CATCH 
   DECLARE	@ErrorMessage	NVARCHAR(4000), 
				@ErrorSeverity	INT; 

   SELECT	@ErrorMessage = 'Error '+ ISNULL(ERROR_MESSAGE(),'') +' in [dbo].[dbo.vtbudGLDept_Audit_Delete] trigger', 
				@ErrorSeverity = ERROR_SEVERITY(); 

   RAISERROR(@ErrorMessage, @ErrorSeverity, 1 ) 
 END CATCH 
GO
EXEC sp_settriggerorder N'[dbo].[vtbudGLDept_Audit_Delete]', 'last', 'delete', null
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER dbo.vtbudGLDept_Audit_Insert ON dbo.budGLDept
 AFTER INSERT
 NOT FOR REPLICATION AS
 SET NOCOUNT ON 
 -- generated by vspHQCreateAuditTriggers on Apr 25 2014  1:56PM

 BEGIN TRY 
DECLARE @HQMAKeys TABLE
	(
		  AuditID		bigint
		, KeyString		varchar(max)
	);
   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)
		OUTPUT inserted.AuditID, inserted.KeyString INTO @HQMAKeys (AuditID, KeyString) 
   SELECT 'budGLDept' , '<KeyString GL Department = "' + REPLACE(CAST(inserted.[GLDept] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , ISNULL(inserted.Co, '') , 'A' , NULL , NULL , NULL , GETDATE() , SUSER_SNAME()
	FROM inserted
 INSERT INTO HQSA ( AuditID, Datatype, Qualifier, Instance, TableName)
				SELECT Keys.AuditID, 'bEmployee', i.Co, CAST(i.ResponsiblePerson AS VARCHAR(30)), 'budGLDept'
				FROM inserted AS i
				INNER JOIN @HQMAKeys AS Keys ON Keys.KeyString = '<KeyString GL Department = "' + REPLACE(CAST(i.[GLDept] AS VARCHAR(MAX)),'"', '&quot;') + '" />'
 INSERT INTO HQSA ( AuditID, Datatype, Qualifier, Instance, TableName)
				SELECT Keys.AuditID, 'bPMCo', i.PMCo, CAST(i.PMCo AS VARCHAR(30)), 'budGLDept'
				FROM inserted AS i
				INNER JOIN @HQMAKeys AS Keys ON Keys.KeyString = '<KeyString GL Department = "' + REPLACE(CAST(i.[GLDept] AS VARCHAR(MAX)),'"', '&quot;') + '" />'

 END TRY 
 BEGIN CATCH 
   DECLARE	@ErrorMessage	NVARCHAR(4000), 
				@ErrorSeverity	INT; 

   SELECT	@ErrorMessage = 'Error '+ ISNULL(ERROR_MESSAGE(),'') +' in [dbo].[dbo.vtbudGLDept_Audit_Insert] trigger', 
				@ErrorSeverity = ERROR_SEVERITY(); 

   RAISERROR(@ErrorMessage, @ErrorSeverity, 1 ) 
 END CATCH 
GO
EXEC sp_settriggerorder N'[dbo].[vtbudGLDept_Audit_Insert]', 'last', 'insert', null
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER dbo.vtbudGLDept_Audit_Update ON dbo.budGLDept
 AFTER UPDATE 
 NOT FOR REPLICATION AS 
 SET NOCOUNT ON 
 -- generated by vspHQCreateAuditTriggers on Apr 25 2014  1:56PM

 BEGIN TRY 
DECLARE @HQMAKeys TABLE
	(
		  AuditID		bigint
		, KeyString		varchar(max)
	);
 IF UPDATE([Co])
 BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)
		OUTPUT inserted.AuditID, inserted.KeyString INTO @HQMAKeys (AuditID, KeyString) 
   SELECT 'budGLDept' , '<KeyString GL Department = "' + REPLACE(CAST(inserted.[GLDept] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , inserted.Co , 'C' , '[Co]' ,  CONVERT(VARCHAR(MAX), deleted.[Co]) ,  CONVERT(VARCHAR(MAX), inserted.[Co]) , GETDATE() , SUSER_SNAME()
		FROM inserted
			INNER JOIN deleted
         ON  inserted.[KeyID] = deleted.[KeyID] 
         AND ((inserted.[Co] <> deleted.[Co]) OR (inserted.[Co] IS NULL AND deleted.[Co] IS NOT NULL) OR (inserted.[Co] IS NOT NULL AND deleted.[Co] IS NULL))

 INSERT INTO HQSA ( AuditID, Datatype, Qualifier, Instance, TableName)
				SELECT Keys.AuditID, 'bEmployee', i.Co, CAST(i.ResponsiblePerson AS VARCHAR(30)), 'budGLDept'
				FROM inserted AS i
				INNER JOIN @HQMAKeys AS Keys ON Keys.KeyString = '<KeyString GL Department = "' + REPLACE(CAST(i.[GLDept] AS VARCHAR(MAX)),'"', '&quot;') + '" />'
 INSERT INTO HQSA ( AuditID, Datatype, Qualifier, Instance, TableName)
				SELECT Keys.AuditID, 'bPMCo', i.PMCo, CAST(i.PMCo AS VARCHAR(30)), 'budGLDept'
				FROM inserted AS i
				INNER JOIN @HQMAKeys AS Keys ON Keys.KeyString = '<KeyString GL Department = "' + REPLACE(CAST(i.[GLDept] AS VARCHAR(MAX)),'"', '&quot;') + '" />'

 DELETE FROM @HQMAKeys; 
 END 

 IF UPDATE([GLDept])
 BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)
		OUTPUT inserted.AuditID, inserted.KeyString INTO @HQMAKeys (AuditID, KeyString) 
   SELECT 'budGLDept' , '<KeyString GL Department = "' + REPLACE(CAST(inserted.[GLDept] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , inserted.Co , 'C' , '[GLDept]' ,  CONVERT(VARCHAR(MAX), deleted.[GLDept]) ,  CONVERT(VARCHAR(MAX), inserted.[GLDept]) , GETDATE() , SUSER_SNAME()
		FROM inserted
			INNER JOIN deleted
         ON  inserted.[KeyID] = deleted.[KeyID] 
         AND ((inserted.[GLDept] <> deleted.[GLDept]) OR (inserted.[GLDept] IS NULL AND deleted.[GLDept] IS NOT NULL) OR (inserted.[GLDept] IS NOT NULL AND deleted.[GLDept] IS NULL))

 INSERT INTO HQSA ( AuditID, Datatype, Qualifier, Instance, TableName)
				SELECT Keys.AuditID, 'bEmployee', i.Co, CAST(i.ResponsiblePerson AS VARCHAR(30)), 'budGLDept'
				FROM inserted AS i
				INNER JOIN @HQMAKeys AS Keys ON Keys.KeyString = '<KeyString GL Department = "' + REPLACE(CAST(i.[GLDept] AS VARCHAR(MAX)),'"', '&quot;') + '" />'
 INSERT INTO HQSA ( AuditID, Datatype, Qualifier, Instance, TableName)
				SELECT Keys.AuditID, 'bPMCo', i.PMCo, CAST(i.PMCo AS VARCHAR(30)), 'budGLDept'
				FROM inserted AS i
				INNER JOIN @HQMAKeys AS Keys ON Keys.KeyString = '<KeyString GL Department = "' + REPLACE(CAST(i.[GLDept] AS VARCHAR(MAX)),'"', '&quot;') + '" />'

 DELETE FROM @HQMAKeys; 
 END 

 IF UPDATE([OperatingUnit])
 BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)
		OUTPUT inserted.AuditID, inserted.KeyString INTO @HQMAKeys (AuditID, KeyString) 
   SELECT 'budGLDept' , '<KeyString GL Department = "' + REPLACE(CAST(inserted.[GLDept] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , inserted.Co , 'C' , '[OperatingUnit]' ,  CONVERT(VARCHAR(MAX), deleted.[OperatingUnit]) ,  CONVERT(VARCHAR(MAX), inserted.[OperatingUnit]) , GETDATE() , SUSER_SNAME()
		FROM inserted
			INNER JOIN deleted
         ON  inserted.[KeyID] = deleted.[KeyID] 
         AND ((inserted.[OperatingUnit] <> deleted.[OperatingUnit]) OR (inserted.[OperatingUnit] IS NULL AND deleted.[OperatingUnit] IS NOT NULL) OR (inserted.[OperatingUnit] IS NOT NULL AND deleted.[OperatingUnit] IS NULL))

 INSERT INTO HQSA ( AuditID, Datatype, Qualifier, Instance, TableName)
				SELECT Keys.AuditID, 'bEmployee', i.Co, CAST(i.ResponsiblePerson AS VARCHAR(30)), 'budGLDept'
				FROM inserted AS i
				INNER JOIN @HQMAKeys AS Keys ON Keys.KeyString = '<KeyString GL Department = "' + REPLACE(CAST(i.[GLDept] AS VARCHAR(MAX)),'"', '&quot;') + '" />'
 INSERT INTO HQSA ( AuditID, Datatype, Qualifier, Instance, TableName)
				SELECT Keys.AuditID, 'bPMCo', i.PMCo, CAST(i.PMCo AS VARCHAR(30)), 'budGLDept'
				FROM inserted AS i
				INNER JOIN @HQMAKeys AS Keys ON Keys.KeyString = '<KeyString GL Department = "' + REPLACE(CAST(i.[GLDept] AS VARCHAR(MAX)),'"', '&quot;') + '" />'

 DELETE FROM @HQMAKeys; 
 END 

 IF UPDATE([ResponsiblePerson])
 BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)
		OUTPUT inserted.AuditID, inserted.KeyString INTO @HQMAKeys (AuditID, KeyString) 
   SELECT 'budGLDept' , '<KeyString GL Department = "' + REPLACE(CAST(inserted.[GLDept] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , inserted.Co , 'C' , '[ResponsiblePerson]' ,  CONVERT(VARCHAR(MAX), deleted.[ResponsiblePerson]) ,  CONVERT(VARCHAR(MAX), inserted.[ResponsiblePerson]) , GETDATE() , SUSER_SNAME()
		FROM inserted
			INNER JOIN deleted
         ON  inserted.[KeyID] = deleted.[KeyID] 
         AND ((inserted.[ResponsiblePerson] <> deleted.[ResponsiblePerson]) OR (inserted.[ResponsiblePerson] IS NULL AND deleted.[ResponsiblePerson] IS NOT NULL) OR (inserted.[ResponsiblePerson] IS NOT NULL AND deleted.[ResponsiblePerson] IS NULL))

 INSERT INTO HQSA ( AuditID, Datatype, Qualifier, Instance, TableName)
				SELECT Keys.AuditID, 'bEmployee', i.Co, CAST(i.ResponsiblePerson AS VARCHAR(30)), 'budGLDept'
				FROM inserted AS i
				INNER JOIN @HQMAKeys AS Keys ON Keys.KeyString = '<KeyString GL Department = "' + REPLACE(CAST(i.[GLDept] AS VARCHAR(MAX)),'"', '&quot;') + '" />'
 INSERT INTO HQSA ( AuditID, Datatype, Qualifier, Instance, TableName)
				SELECT Keys.AuditID, 'bPMCo', i.PMCo, CAST(i.PMCo AS VARCHAR(30)), 'budGLDept'
				FROM inserted AS i
				INNER JOIN @HQMAKeys AS Keys ON Keys.KeyString = '<KeyString GL Department = "' + REPLACE(CAST(i.[GLDept] AS VARCHAR(MAX)),'"', '&quot;') + '" />'

 DELETE FROM @HQMAKeys; 
 END 

 IF UPDATE([UniqueAttchID])
 BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)
		OUTPUT inserted.AuditID, inserted.KeyString INTO @HQMAKeys (AuditID, KeyString) 
   SELECT 'budGLDept' , '<KeyString GL Department = "' + REPLACE(CAST(inserted.[GLDept] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , inserted.Co , 'C' , '[UniqueAttchID]' ,  CONVERT(VARCHAR(MAX), deleted.[UniqueAttchID]) ,  CONVERT(VARCHAR(MAX), inserted.[UniqueAttchID]) , GETDATE() , SUSER_SNAME()
		FROM inserted
			INNER JOIN deleted
         ON  inserted.[KeyID] = deleted.[KeyID] 
         AND ((inserted.[UniqueAttchID] <> deleted.[UniqueAttchID]) OR (inserted.[UniqueAttchID] IS NULL AND deleted.[UniqueAttchID] IS NOT NULL) OR (inserted.[UniqueAttchID] IS NOT NULL AND deleted.[UniqueAttchID] IS NULL))

 INSERT INTO HQSA ( AuditID, Datatype, Qualifier, Instance, TableName)
				SELECT Keys.AuditID, 'bEmployee', i.Co, CAST(i.ResponsiblePerson AS VARCHAR(30)), 'budGLDept'
				FROM inserted AS i
				INNER JOIN @HQMAKeys AS Keys ON Keys.KeyString = '<KeyString GL Department = "' + REPLACE(CAST(i.[GLDept] AS VARCHAR(MAX)),'"', '&quot;') + '" />'
 INSERT INTO HQSA ( AuditID, Datatype, Qualifier, Instance, TableName)
				SELECT Keys.AuditID, 'bPMCo', i.PMCo, CAST(i.PMCo AS VARCHAR(30)), 'budGLDept'
				FROM inserted AS i
				INNER JOIN @HQMAKeys AS Keys ON Keys.KeyString = '<KeyString GL Department = "' + REPLACE(CAST(i.[GLDept] AS VARCHAR(MAX)),'"', '&quot;') + '" />'

 DELETE FROM @HQMAKeys; 
 END 

 IF UPDATE([PMCo])
 BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)
		OUTPUT inserted.AuditID, inserted.KeyString INTO @HQMAKeys (AuditID, KeyString) 
   SELECT 'budGLDept' , '<KeyString GL Department = "' + REPLACE(CAST(inserted.[GLDept] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , inserted.Co , 'C' , '[PMCo]' ,  CONVERT(VARCHAR(MAX), deleted.[PMCo]) ,  CONVERT(VARCHAR(MAX), inserted.[PMCo]) , GETDATE() , SUSER_SNAME()
		FROM inserted
			INNER JOIN deleted
         ON  inserted.[KeyID] = deleted.[KeyID] 
         AND ((inserted.[PMCo] <> deleted.[PMCo]) OR (inserted.[PMCo] IS NULL AND deleted.[PMCo] IS NOT NULL) OR (inserted.[PMCo] IS NOT NULL AND deleted.[PMCo] IS NULL))

 INSERT INTO HQSA ( AuditID, Datatype, Qualifier, Instance, TableName)
				SELECT Keys.AuditID, 'bEmployee', i.Co, CAST(i.ResponsiblePerson AS VARCHAR(30)), 'budGLDept'
				FROM inserted AS i
				INNER JOIN @HQMAKeys AS Keys ON Keys.KeyString = '<KeyString GL Department = "' + REPLACE(CAST(i.[GLDept] AS VARCHAR(MAX)),'"', '&quot;') + '" />'
 INSERT INTO HQSA ( AuditID, Datatype, Qualifier, Instance, TableName)
				SELECT Keys.AuditID, 'bPMCo', i.PMCo, CAST(i.PMCo AS VARCHAR(30)), 'budGLDept'
				FROM inserted AS i
				INNER JOIN @HQMAKeys AS Keys ON Keys.KeyString = '<KeyString GL Department = "' + REPLACE(CAST(i.[GLDept] AS VARCHAR(MAX)),'"', '&quot;') + '" />'

 DELETE FROM @HQMAKeys; 
 END 

 IF UPDATE([Type])
 BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)
		OUTPUT inserted.AuditID, inserted.KeyString INTO @HQMAKeys (AuditID, KeyString) 
   SELECT 'budGLDept' , '<KeyString GL Department = "' + REPLACE(CAST(inserted.[GLDept] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , inserted.Co , 'C' , '[Type]' ,  CONVERT(VARCHAR(MAX), deleted.[Type]) ,  CONVERT(VARCHAR(MAX), inserted.[Type]) , GETDATE() , SUSER_SNAME()
		FROM inserted
			INNER JOIN deleted
         ON  inserted.[KeyID] = deleted.[KeyID] 
         AND ((inserted.[Type] <> deleted.[Type]) OR (inserted.[Type] IS NULL AND deleted.[Type] IS NOT NULL) OR (inserted.[Type] IS NOT NULL AND deleted.[Type] IS NULL))

 INSERT INTO HQSA ( AuditID, Datatype, Qualifier, Instance, TableName)
				SELECT Keys.AuditID, 'bEmployee', i.Co, CAST(i.ResponsiblePerson AS VARCHAR(30)), 'budGLDept'
				FROM inserted AS i
				INNER JOIN @HQMAKeys AS Keys ON Keys.KeyString = '<KeyString GL Department = "' + REPLACE(CAST(i.[GLDept] AS VARCHAR(MAX)),'"', '&quot;') + '" />'
 INSERT INTO HQSA ( AuditID, Datatype, Qualifier, Instance, TableName)
				SELECT Keys.AuditID, 'bPMCo', i.PMCo, CAST(i.PMCo AS VARCHAR(30)), 'budGLDept'
				FROM inserted AS i
				INNER JOIN @HQMAKeys AS Keys ON Keys.KeyString = '<KeyString GL Department = "' + REPLACE(CAST(i.[GLDept] AS VARCHAR(MAX)),'"', '&quot;') + '" />'

 DELETE FROM @HQMAKeys; 
 END 

 END TRY 
 BEGIN CATCH 
   DECLARE	@ErrorMessage	NVARCHAR(4000), 
				@ErrorSeverity	INT; 

   SELECT	@ErrorMessage = 'Error '+ ISNULL(ERROR_MESSAGE(),'') +' in [dbo].[dbo.vtbudGLDept_Audit_Update] trigger', 
				@ErrorSeverity = ERROR_SEVERITY(); 

   RAISERROR(@ErrorMessage, @ErrorSeverity, 1 ) 
 END CATCH 
GO
EXEC sp_settriggerorder N'[dbo].[vtbudGLDept_Audit_Update]', 'last', 'update', null
GO
CREATE UNIQUE CLUSTERED INDEX [biudGLDept] ON [dbo].[budGLDept] ([Co], [GLDept]) ON [PRIMARY]
GO
