CREATE TABLE [dbo].[vAPT5018Payment]
(
[KeyID] [bigint] NOT NULL IDENTITY(1, 1),
[APCo] [dbo].[bCompany] NOT NULL,
[PeriodEndDate] [smalldatetime] NOT NULL,
[ContactName] [varchar] (22) COLLATE Latin1_General_BIN NULL,
[ContactAreaCode] [varchar] (3) COLLATE Latin1_General_BIN NULL,
[ContactPhone] [varchar] (8) COLLATE Latin1_General_BIN NULL,
[ContactExtension] [varchar] (5) COLLATE Latin1_General_BIN NULL,
[ContactEmail] [varchar] (60) COLLATE Latin1_General_BIN NULL,
[SubmissionReferenceId] [varchar] (8) COLLATE Latin1_General_BIN NULL,
[TransmitterNo] [varchar] (8) COLLATE Latin1_General_BIN NULL,
[ReportDate] [dbo].[bDate] NULL,
[UniqueAttchID] [uniqueidentifier] NULL,
[Notes] [varchar] (max) COLLATE Latin1_General_BIN NULL,
[PeriodClosed] [char] (1) COLLATE Latin1_General_BIN NOT NULL CONSTRAINT [DF_vAPT5018Payment_PeriodClosed] DEFAULT ('N')
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER dbo.vtvAPT5018Payment_Audit_Delete ON dbo.vAPT5018Payment
 AFTER DELETE
 NOT FOR REPLICATION AS
 SET NOCOUNT ON 
 -- generated by vspAuditCreateAuditTriggers

 BEGIN TRY 

							INSERT dbo.HQMA (
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
								
							SELECT
								'vAPT5018Payment' , 
								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(deleted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(deleted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								deleted.APCo , 
								'D' , 
								'APCo' , 
								CONVERT(VARCHAR(MAX), deleted.[APCo]) , 								NULL , 
								GETDATE() , 
								SUSER_SNAME()
							FROM deleted
								
							INSERT dbo.HQMA (
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
								
							SELECT
								'vAPT5018Payment' , 
								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(deleted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(deleted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								deleted.APCo , 
								'D' , 
								'PeriodEndDate' , 
								CONVERT(VARCHAR(MAX), deleted.[PeriodEndDate]) , 								NULL , 
								GETDATE() , 
								SUSER_SNAME()
							FROM deleted
								

							
 END TRY 
 BEGIN CATCH 
   DECLARE	@ErrorMessage	NVARCHAR(4000), 
				@ErrorSeverity	INT; 

   SELECT	@ErrorMessage = 'Error '+ ISNULL(ERROR_MESSAGE(),'') +' in [dbo].[dbo.vtvAPT5018Payment_Audit_Delete] trigger', 
				@ErrorSeverity = ERROR_SEVERITY(); 

   RAISERROR(@ErrorMessage, @ErrorSeverity, 1 ) 
 END CATCH 
GO
EXEC sp_settriggerorder N'[dbo].[vtvAPT5018Payment_Audit_Delete]', 'last', 'delete', null
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER dbo.vtvAPT5018Payment_Audit_Insert ON dbo.vAPT5018Payment
 AFTER INSERT
 NOT FOR REPLICATION AS
 SET NOCOUNT ON 
 -- generated by vspAuditTriggersCreate

 BEGIN TRY 

-- log additions to the APCo column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vAPT5018Payment' , 
								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(inserted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(inserted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.APCo, '') , 
								'A' , 
								'APCo' , 
								NULL , 
								[APCo] , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								

-- log additions to the ContactAreaCode column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vAPT5018Payment' , 
								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(inserted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(inserted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.APCo, '') , 
								'A' , 
								'ContactAreaCode' , 
								NULL , 
								[ContactAreaCode] , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								

-- log additions to the ContactEmail column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vAPT5018Payment' , 
								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(inserted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(inserted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.APCo, '') , 
								'A' , 
								'ContactEmail' , 
								NULL , 
								[ContactEmail] , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								

-- log additions to the ContactExtension column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vAPT5018Payment' , 
								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(inserted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(inserted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.APCo, '') , 
								'A' , 
								'ContactExtension' , 
								NULL , 
								[ContactExtension] , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								

-- log additions to the ContactName column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vAPT5018Payment' , 
								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(inserted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(inserted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.APCo, '') , 
								'A' , 
								'ContactName' , 
								NULL , 
								[ContactName] , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								

-- log additions to the ContactPhone column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vAPT5018Payment' , 
								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(inserted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(inserted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.APCo, '') , 
								'A' , 
								'ContactPhone' , 
								NULL , 
								[ContactPhone] , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								

-- log additions to the PeriodClosed column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vAPT5018Payment' , 
								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(inserted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(inserted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.APCo, '') , 
								'A' , 
								'PeriodClosed' , 
								NULL , 
								[PeriodClosed] , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								

-- log additions to the PeriodEndDate column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vAPT5018Payment' , 
								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(inserted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(inserted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.APCo, '') , 
								'A' , 
								'PeriodEndDate' , 
								NULL , 
								[PeriodEndDate] , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								

-- log additions to the ReportDate column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vAPT5018Payment' , 
								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(inserted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(inserted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.APCo, '') , 
								'A' , 
								'ReportDate' , 
								NULL , 
								[ReportDate] , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								

-- log additions to the SubmissionReferenceId column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vAPT5018Payment' , 
								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(inserted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(inserted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.APCo, '') , 
								'A' , 
								'SubmissionReferenceId' , 
								NULL , 
								[SubmissionReferenceId] , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								

-- log additions to the TransmitterNo column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vAPT5018Payment' , 
								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(inserted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(inserted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.APCo, '') , 
								'A' , 
								'TransmitterNo' , 
								NULL , 
								[TransmitterNo] , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								


 END TRY 
 BEGIN CATCH 
   DECLARE	@ErrorMessage	NVARCHAR(4000), 
				@ErrorSeverity	INT; 

   SELECT	@ErrorMessage = 'Error '+ ISNULL(ERROR_MESSAGE(),'') +' in [dbo].[dbo.vtvAPT5018Payment_Audit_Insert] trigger', 
				@ErrorSeverity = ERROR_SEVERITY(); 

   RAISERROR(@ErrorMessage, @ErrorSeverity, 1 ) 
 END CATCH 
GO
EXEC sp_settriggerorder N'[dbo].[vtvAPT5018Payment_Audit_Insert]', 'last', 'insert', null
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER dbo.vtvAPT5018Payment_Audit_Update ON dbo.vAPT5018Payment
 AFTER UPDATE 
 NOT FOR REPLICATION AS 
 SET NOCOUNT ON 
 -- generated by vspAuditTriggersCreate

 BEGIN TRY 

							IF UPDATE([APCo])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vAPT5018Payment' , 								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(inserted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(inserted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.APCo , 								'C' , 								'APCo' , 								CONVERT(VARCHAR(MAX), deleted.[APCo]) , 								CONVERT(VARCHAR(MAX), inserted.[APCo]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[KeyID] = deleted.[KeyID] 
									AND ((inserted.[APCo] <> deleted.[APCo]) OR (inserted.[APCo] IS NULL AND deleted.[APCo] IS NOT NULL) OR (inserted.[APCo] IS NOT NULL AND deleted.[APCo] IS NULL))
								

							END 

							IF UPDATE([ContactAreaCode])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vAPT5018Payment' , 								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(inserted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(inserted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.APCo , 								'C' , 								'ContactAreaCode' , 								CONVERT(VARCHAR(MAX), deleted.[ContactAreaCode]) , 								CONVERT(VARCHAR(MAX), inserted.[ContactAreaCode]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[KeyID] = deleted.[KeyID] 
									AND ((inserted.[ContactAreaCode] <> deleted.[ContactAreaCode]) OR (inserted.[ContactAreaCode] IS NULL AND deleted.[ContactAreaCode] IS NOT NULL) OR (inserted.[ContactAreaCode] IS NOT NULL AND deleted.[ContactAreaCode] IS NULL))
								

							END 

							IF UPDATE([ContactEmail])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vAPT5018Payment' , 								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(inserted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(inserted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.APCo , 								'C' , 								'ContactEmail' , 								CONVERT(VARCHAR(MAX), deleted.[ContactEmail]) , 								CONVERT(VARCHAR(MAX), inserted.[ContactEmail]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[KeyID] = deleted.[KeyID] 
									AND ((inserted.[ContactEmail] <> deleted.[ContactEmail]) OR (inserted.[ContactEmail] IS NULL AND deleted.[ContactEmail] IS NOT NULL) OR (inserted.[ContactEmail] IS NOT NULL AND deleted.[ContactEmail] IS NULL))
								

							END 

							IF UPDATE([ContactExtension])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vAPT5018Payment' , 								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(inserted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(inserted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.APCo , 								'C' , 								'ContactExtension' , 								CONVERT(VARCHAR(MAX), deleted.[ContactExtension]) , 								CONVERT(VARCHAR(MAX), inserted.[ContactExtension]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[KeyID] = deleted.[KeyID] 
									AND ((inserted.[ContactExtension] <> deleted.[ContactExtension]) OR (inserted.[ContactExtension] IS NULL AND deleted.[ContactExtension] IS NOT NULL) OR (inserted.[ContactExtension] IS NOT NULL AND deleted.[ContactExtension] IS NULL))
								

							END 

							IF UPDATE([ContactName])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vAPT5018Payment' , 								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(inserted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(inserted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.APCo , 								'C' , 								'ContactName' , 								CONVERT(VARCHAR(MAX), deleted.[ContactName]) , 								CONVERT(VARCHAR(MAX), inserted.[ContactName]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[KeyID] = deleted.[KeyID] 
									AND ((inserted.[ContactName] <> deleted.[ContactName]) OR (inserted.[ContactName] IS NULL AND deleted.[ContactName] IS NOT NULL) OR (inserted.[ContactName] IS NOT NULL AND deleted.[ContactName] IS NULL))
								

							END 

							IF UPDATE([ContactPhone])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vAPT5018Payment' , 								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(inserted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(inserted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.APCo , 								'C' , 								'ContactPhone' , 								CONVERT(VARCHAR(MAX), deleted.[ContactPhone]) , 								CONVERT(VARCHAR(MAX), inserted.[ContactPhone]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[KeyID] = deleted.[KeyID] 
									AND ((inserted.[ContactPhone] <> deleted.[ContactPhone]) OR (inserted.[ContactPhone] IS NULL AND deleted.[ContactPhone] IS NOT NULL) OR (inserted.[ContactPhone] IS NOT NULL AND deleted.[ContactPhone] IS NULL))
								

							END 

							IF UPDATE([PeriodClosed])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vAPT5018Payment' , 								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(inserted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(inserted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.APCo , 								'C' , 								'PeriodClosed' , 								CONVERT(VARCHAR(MAX), deleted.[PeriodClosed]) , 								CONVERT(VARCHAR(MAX), inserted.[PeriodClosed]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[KeyID] = deleted.[KeyID] 
									AND ((inserted.[PeriodClosed] <> deleted.[PeriodClosed]) OR (inserted.[PeriodClosed] IS NULL AND deleted.[PeriodClosed] IS NOT NULL) OR (inserted.[PeriodClosed] IS NOT NULL AND deleted.[PeriodClosed] IS NULL))
								

							END 

							IF UPDATE([PeriodEndDate])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vAPT5018Payment' , 								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(inserted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(inserted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.APCo , 								'C' , 								'PeriodEndDate' , 								CONVERT(VARCHAR(MAX), deleted.[PeriodEndDate]) , 								CONVERT(VARCHAR(MAX), inserted.[PeriodEndDate]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[KeyID] = deleted.[KeyID] 
									AND ((inserted.[PeriodEndDate] <> deleted.[PeriodEndDate]) OR (inserted.[PeriodEndDate] IS NULL AND deleted.[PeriodEndDate] IS NOT NULL) OR (inserted.[PeriodEndDate] IS NOT NULL AND deleted.[PeriodEndDate] IS NULL))
								

							END 

							IF UPDATE([ReportDate])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vAPT5018Payment' , 								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(inserted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(inserted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.APCo , 								'C' , 								'ReportDate' , 								CONVERT(VARCHAR(MAX), deleted.[ReportDate]) , 								CONVERT(VARCHAR(MAX), inserted.[ReportDate]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[KeyID] = deleted.[KeyID] 
									AND ((inserted.[ReportDate] <> deleted.[ReportDate]) OR (inserted.[ReportDate] IS NULL AND deleted.[ReportDate] IS NOT NULL) OR (inserted.[ReportDate] IS NOT NULL AND deleted.[ReportDate] IS NULL))
								

							END 

							IF UPDATE([SubmissionReferenceId])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vAPT5018Payment' , 								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(inserted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(inserted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.APCo , 								'C' , 								'SubmissionReferenceId' , 								CONVERT(VARCHAR(MAX), deleted.[SubmissionReferenceId]) , 								CONVERT(VARCHAR(MAX), inserted.[SubmissionReferenceId]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[KeyID] = deleted.[KeyID] 
									AND ((inserted.[SubmissionReferenceId] <> deleted.[SubmissionReferenceId]) OR (inserted.[SubmissionReferenceId] IS NULL AND deleted.[SubmissionReferenceId] IS NOT NULL) OR (inserted.[SubmissionReferenceId] IS NOT NULL AND deleted.[SubmissionReferenceId] IS NULL))
								

							END 

							IF UPDATE([TransmitterNo])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vAPT5018Payment' , 								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(inserted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(inserted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.APCo , 								'C' , 								'TransmitterNo' , 								CONVERT(VARCHAR(MAX), deleted.[TransmitterNo]) , 								CONVERT(VARCHAR(MAX), inserted.[TransmitterNo]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[KeyID] = deleted.[KeyID] 
									AND ((inserted.[TransmitterNo] <> deleted.[TransmitterNo]) OR (inserted.[TransmitterNo] IS NULL AND deleted.[TransmitterNo] IS NOT NULL) OR (inserted.[TransmitterNo] IS NOT NULL AND deleted.[TransmitterNo] IS NULL))
								

							END 



 END TRY 
 BEGIN CATCH 
   DECLARE	@ErrorMessage	NVARCHAR(4000), 
				@ErrorSeverity	INT; 

   SELECT	@ErrorMessage = 'Error '+ ISNULL(ERROR_MESSAGE(),'') +' in [dbo].[dbo.vtvAPT5018Payment_Audit_Update] trigger', 
				@ErrorSeverity = ERROR_SEVERITY(); 

   RAISERROR(@ErrorMessage, @ErrorSeverity, 1 ) 
 END CATCH 
GO
EXEC sp_settriggerorder N'[dbo].[vtvAPT5018Payment_Audit_Update]', 'last', 'update', null
GO
ALTER TABLE [dbo].[vAPT5018Payment] WITH NOCHECK ADD CONSTRAINT [CK_vAPT5018Payment_PeriodClosed] CHECK (([PeriodClosed]='Y' OR [PeriodClosed]='N'))
GO
ALTER TABLE [dbo].[vAPT5018Payment] WITH NOCHECK ADD CONSTRAINT [CK_vAPT5018Payment_PeriodEndDate] CHECK (([dbo].[vfLastDayOfMonth]([PeriodEndDate])=[PeriodEndDate]))
GO
ALTER TABLE [dbo].[vAPT5018Payment] ADD CONSTRAINT [PK_vAPT5018Payment] PRIMARY KEY CLUSTERED  ([APCo], [PeriodEndDate]) ON [PRIMARY]
GO
