CREATE TABLE [dbo].[vDDTI]
(
[TableName] [varchar] (256) COLLATE Latin1_General_BIN NOT NULL,
[IndexName] [varchar] (256) COLLATE Latin1_General_BIN NOT NULL,
[IndexColumns] [varchar] (256) COLLATE Latin1_General_BIN NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[vtDDTId_Audit] ON [dbo].[vDDTI]
 AFTER DELETE
 NOT FOR REPLICATION AS
 SET NOCOUNT ON 
 -- generated by vspHQCreateAuditTriggers on May 14 2009  9:56AM

 BEGIN TRY 
   INSERT dbo.vDDChangeLog (TableName, KeyString, Action, FieldName, OldValue, NewValue, DateTime, MachineName, CommandText)
   SELECT 'vDDTI' , '<KeyString TableName = "' + REPLACE(CAST(deleted.TableName AS VARCHAR(MAX)),'"', '&quot;') + '" IndexName = "' + REPLACE(CAST(deleted.IndexName AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 'D' , NULL , NULL , NULL , GETDATE() , HOST_NAME() , 'DELETE FROM vDDTI WHERE TableName = ''' + CAST(deleted.TableName AS VARCHAR(MAX)) + '''' + ' AND IndexName = ''' + CAST(deleted.IndexName AS VARCHAR(MAX)) + ''''
	FROM deleted
 END TRY 
 BEGIN CATCH 
   RAISERROR('Error in [dbo].[dbo.vtDDTIi_Audit] trigger', 16, 1 ) with log
 END CATCH 
GO
EXEC sp_settriggerorder N'[dbo].[vtDDTId_Audit]', 'last', 'delete', null
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[vtDDTIi_Audit] ON [dbo].[vDDTI]
 AFTER INSERT
 NOT FOR REPLICATION AS
 SET NOCOUNT ON 
 -- generated by vspHQCreateAuditTriggers on May 14 2009  9:56AM

 BEGIN TRY 
   INSERT dbo.vDDChangeLog (TableName, KeyString, Action, FieldName, OldValue, NewValue, DateTime, MachineName, CommandText)
   SELECT 'vDDTI' , '<KeyString TableName = "' + REPLACE(CAST(inserted.TableName AS VARCHAR(MAX)),'"', '&quot;') + '" IndexName = "' + REPLACE(CAST(inserted.IndexName AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 'A' , NULL , NULL , NULL , GETDATE() , HOST_NAME() , 'INSERT INTO dbo.[vDDTI] ([TableName], [IndexName], [IndexColumns]) VALUES (' + ISNULL('''' + REPLACE(CAST(TableName AS NVARCHAR(MAX)), '''' , '''''') + '''', 'NULL') + ',' + ISNULL('''' + REPLACE(CAST(IndexName AS NVARCHAR(MAX)), '''' , '''''') + '''', 'NULL') + ',' + ISNULL('''' + REPLACE(CAST(IndexColumns AS NVARCHAR(MAX)), '''' , '''''') + '''', 'NULL')  + ')'
	FROM inserted
 END TRY 
 BEGIN CATCH 
   RAISERROR('Error in [dbo].[dbo.vtDDTIi_Audit] trigger', 16, 1 ) with log
 END CATCH 
GO
EXEC sp_settriggerorder N'[dbo].[vtDDTIi_Audit]', 'last', 'insert', null
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[vtDDTIu_Audit] ON [dbo].[vDDTI]
 AFTER UPDATE 
 NOT FOR REPLICATION AS 
 SET NOCOUNT ON 
 -- generated by vspHQCreateAuditTriggers on May 14 2009  9:56AM

 BEGIN TRY 
 IF UPDATE([TableName])
   INSERT dbo.vDDChangeLog (TableName, KeyString, Action, FieldName, OldValue, NewValue, DateTime, MachineName, CommandText)
   SELECT 'vDDTI' , '<KeyString TableName = "' + REPLACE(CAST(inserted.TableName AS VARCHAR(MAX)),'"', '&quot;') + '" IndexName = "' + REPLACE(CAST(inserted.IndexName AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 'U' , 'TableName' ,  CONVERT(VARCHAR(MAX), deleted.[TableName]) ,  Convert(VARCHAR(MAX), inserted.[TableName]) , GETDATE() , HOST_NAME() , 'UPDATE vDDTI SET TableName = ''' + ISNULL(REPLACE(Convert(VARCHAR(MAX), inserted.[TableName]), '''' , ''''''), 'NULL') + ''' WHERE TableName = ''' + CAST(inserted.TableName AS VARCHAR(MAX)) + '''' + ' AND IndexName = ''' + CAST(inserted.IndexName AS VARCHAR(MAX)) + ''''
		FROM inserted
			INNER JOIN deleted
         ON  inserted.[TableName] = deleted.[TableName]  AND  inserted.[IndexName] = deleted.[IndexName] 
         AND ISNULL(inserted.[TableName],'') <> ISNULL(deleted.[TableName],'')

 IF UPDATE([IndexName])
   INSERT dbo.vDDChangeLog (TableName, KeyString, Action, FieldName, OldValue, NewValue, DateTime, MachineName, CommandText)
   SELECT 'vDDTI' , '<KeyString TableName = "' + REPLACE(CAST(inserted.TableName AS VARCHAR(MAX)),'"', '&quot;') + '" IndexName = "' + REPLACE(CAST(inserted.IndexName AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 'U' , 'IndexName' ,  CONVERT(VARCHAR(MAX), deleted.[IndexName]) ,  Convert(VARCHAR(MAX), inserted.[IndexName]) , GETDATE() , HOST_NAME() , 'UPDATE vDDTI SET IndexName = ''' + ISNULL(REPLACE(Convert(VARCHAR(MAX), inserted.[IndexName]), '''' , ''''''), 'NULL') + ''' WHERE TableName = ''' + CAST(inserted.TableName AS VARCHAR(MAX)) + '''' + ' AND IndexName = ''' + CAST(inserted.IndexName AS VARCHAR(MAX)) + ''''
		FROM inserted
			INNER JOIN deleted
         ON  inserted.[TableName] = deleted.[TableName]  AND  inserted.[IndexName] = deleted.[IndexName] 
         AND ISNULL(inserted.[IndexName],'') <> ISNULL(deleted.[IndexName],'')

 IF UPDATE([IndexColumns])
   INSERT dbo.vDDChangeLog (TableName, KeyString, Action, FieldName, OldValue, NewValue, DateTime, MachineName, CommandText)
   SELECT 'vDDTI' , '<KeyString TableName = "' + REPLACE(CAST(inserted.TableName AS VARCHAR(MAX)),'"', '&quot;') + '" IndexName = "' + REPLACE(CAST(inserted.IndexName AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 'U' , 'IndexColumns' ,  CONVERT(VARCHAR(MAX), deleted.[IndexColumns]) ,  Convert(VARCHAR(MAX), inserted.[IndexColumns]) , GETDATE() , HOST_NAME() , 'UPDATE vDDTI SET IndexColumns = ''' + ISNULL(REPLACE(Convert(VARCHAR(MAX), inserted.[IndexColumns]), '''' , ''''''), 'NULL') + ''' WHERE TableName = ''' + CAST(inserted.TableName AS VARCHAR(MAX)) + '''' + ' AND IndexName = ''' + CAST(inserted.IndexName AS VARCHAR(MAX)) + ''''
		FROM inserted
			INNER JOIN deleted
         ON  inserted.[TableName] = deleted.[TableName]  AND  inserted.[IndexName] = deleted.[IndexName] 
         AND ISNULL(inserted.[IndexColumns],'') <> ISNULL(deleted.[IndexColumns],'')

 END TRY 
 BEGIN CATCH 
   RAISERROR('Error in [dbo].[dbo.vtDDTIi_Audit] trigger', 16, 1 ) with log
 END CATCH 
GO
EXEC sp_settriggerorder N'[dbo].[vtDDTIu_Audit]', 'last', 'update', null
GO
CREATE UNIQUE CLUSTERED INDEX [viDDTI] ON [dbo].[vDDTI] ([TableName], [IndexName]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
