CREATE TABLE [dbo].[vAPT5018PaymentDetail]
(
[KeyID] [bigint] NOT NULL IDENTITY(1, 1),
[APCo] [dbo].[bCompany] NOT NULL,
[PeriodEndDate] [smalldatetime] NOT NULL,
[VendorGroup] [dbo].[bGroup] NOT NULL,
[Vendor] [dbo].[bVendor] NOT NULL,
[VendorName] [varchar] (60) COLLATE Latin1_General_BIN NULL,
[Address] [varchar] (30) COLLATE Latin1_General_BIN NULL,
[Address2] [varchar] (30) COLLATE Latin1_General_BIN NULL,
[City] [varchar] (28) COLLATE Latin1_General_BIN NULL,
[State] [varchar] (4) COLLATE Latin1_General_BIN NULL,
[PostalCode] [varchar] (10) COLLATE Latin1_General_BIN NULL,
[Country] [varchar] (3) COLLATE Latin1_General_BIN NULL,
[T5BusTypeCode] [char] (1) COLLATE Latin1_General_BIN NULL CONSTRAINT [DF_vAPT5018PaymentDetail_T5BusTypeCode] DEFAULT ('C'),
[T5BusinessNbr] [varchar] (15) COLLATE Latin1_General_BIN NULL,
[T5PartnerFIN] [varchar] (9) COLLATE Latin1_General_BIN NULL,
[T5FirstName] [varchar] (12) COLLATE Latin1_General_BIN NULL,
[T5MiddleInit] [varchar] (1) COLLATE Latin1_General_BIN NULL,
[T5LastName] [varchar] (20) COLLATE Latin1_General_BIN NULL,
[T5SocInsNbr] [varchar] (9) COLLATE Latin1_General_BIN NULL,
[TotalPaid] [dbo].[bDollar] NULL CONSTRAINT [DF_vAPT5018PaymentDetail_TotalPaid] DEFAULT ((0)),
[ReportTypeCode] [char] (1) COLLATE Latin1_General_BIN NOT NULL CONSTRAINT [DF_vAPT5018PaymentDetail_ReportTypeCode] DEFAULT ('O'),
[UniqueAttchID] [uniqueidentifier] NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER dbo.vtvAPT5018PaymentDetail_Audit_Delete ON dbo.vAPT5018PaymentDetail
 AFTER DELETE
 NOT FOR REPLICATION AS
 SET NOCOUNT ON 
 -- generated by vspAuditCreateAuditTriggers

 BEGIN TRY 

							INSERT dbo.HQMA (
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
								
							SELECT
								'vAPT5018PaymentDetail' , 
								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(deleted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(deleted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(ISNULL(deleted.[Vendor],'') AS VARCHAR(MAX)),'"', '&quot;') + '" VendorGroup = "' + REPLACE(CAST(ISNULL(deleted.[VendorGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								deleted.APCo , 
								'D' , 
								'APCo' , 
								CONVERT(VARCHAR(MAX), deleted.[APCo]) , 								NULL , 
								GETDATE() , 
								SUSER_SNAME()
							FROM deleted
								
							INSERT dbo.HQMA (
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
								
							SELECT
								'vAPT5018PaymentDetail' , 
								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(deleted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(deleted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(ISNULL(deleted.[Vendor],'') AS VARCHAR(MAX)),'"', '&quot;') + '" VendorGroup = "' + REPLACE(CAST(ISNULL(deleted.[VendorGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								deleted.APCo , 
								'D' , 
								'PeriodEndDate' , 
								CONVERT(VARCHAR(MAX), deleted.[PeriodEndDate]) , 								NULL , 
								GETDATE() , 
								SUSER_SNAME()
							FROM deleted
								
							INSERT dbo.HQMA (
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
								
							SELECT
								'vAPT5018PaymentDetail' , 
								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(deleted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(deleted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(ISNULL(deleted.[Vendor],'') AS VARCHAR(MAX)),'"', '&quot;') + '" VendorGroup = "' + REPLACE(CAST(ISNULL(deleted.[VendorGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								deleted.APCo , 
								'D' , 
								'Vendor' , 
								CONVERT(VARCHAR(MAX), deleted.[Vendor]) , 								NULL , 
								GETDATE() , 
								SUSER_SNAME()
							FROM deleted
								
							INSERT dbo.HQMA (
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
								
							SELECT
								'vAPT5018PaymentDetail' , 
								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(deleted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(deleted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(ISNULL(deleted.[Vendor],'') AS VARCHAR(MAX)),'"', '&quot;') + '" VendorGroup = "' + REPLACE(CAST(ISNULL(deleted.[VendorGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								deleted.APCo , 
								'D' , 
								'VendorGroup' , 
								CONVERT(VARCHAR(MAX), deleted.[VendorGroup]) , 								NULL , 
								GETDATE() , 
								SUSER_SNAME()
							FROM deleted
								

							
 END TRY 
 BEGIN CATCH 
   DECLARE	@ErrorMessage	NVARCHAR(4000), 
				@ErrorSeverity	INT; 

   SELECT	@ErrorMessage = 'Error '+ ISNULL(ERROR_MESSAGE(),'') +' in [dbo].[dbo.vtvAPT5018PaymentDetail_Audit_Delete] trigger', 
				@ErrorSeverity = ERROR_SEVERITY(); 

   RAISERROR(@ErrorMessage, @ErrorSeverity, 1 ) 
 END CATCH 
GO
EXEC sp_settriggerorder N'[dbo].[vtvAPT5018PaymentDetail_Audit_Delete]', 'last', 'delete', null
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER dbo.vtvAPT5018PaymentDetail_Audit_Insert ON dbo.vAPT5018PaymentDetail
 AFTER INSERT
 NOT FOR REPLICATION AS
 SET NOCOUNT ON 
 -- generated by vspAuditTriggersCreate

 BEGIN TRY 

-- log additions to the APCo column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vAPT5018PaymentDetail' , 
								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(inserted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(inserted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(ISNULL(inserted.[Vendor],'') AS VARCHAR(MAX)),'"', '&quot;') + '" VendorGroup = "' + REPLACE(CAST(ISNULL(inserted.[VendorGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.APCo, '') , 
								'A' , 
								'APCo' , 
								NULL , 
								[APCo] , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								

-- log additions to the Address column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vAPT5018PaymentDetail' , 
								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(inserted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(inserted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(ISNULL(inserted.[Vendor],'') AS VARCHAR(MAX)),'"', '&quot;') + '" VendorGroup = "' + REPLACE(CAST(ISNULL(inserted.[VendorGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.APCo, '') , 
								'A' , 
								'Address' , 
								NULL , 
								[Address] , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								

-- log additions to the Address2 column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vAPT5018PaymentDetail' , 
								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(inserted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(inserted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(ISNULL(inserted.[Vendor],'') AS VARCHAR(MAX)),'"', '&quot;') + '" VendorGroup = "' + REPLACE(CAST(ISNULL(inserted.[VendorGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.APCo, '') , 
								'A' , 
								'Address2' , 
								NULL , 
								[Address2] , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								

-- log additions to the City column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vAPT5018PaymentDetail' , 
								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(inserted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(inserted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(ISNULL(inserted.[Vendor],'') AS VARCHAR(MAX)),'"', '&quot;') + '" VendorGroup = "' + REPLACE(CAST(ISNULL(inserted.[VendorGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.APCo, '') , 
								'A' , 
								'City' , 
								NULL , 
								[City] , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								

-- log additions to the Country column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vAPT5018PaymentDetail' , 
								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(inserted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(inserted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(ISNULL(inserted.[Vendor],'') AS VARCHAR(MAX)),'"', '&quot;') + '" VendorGroup = "' + REPLACE(CAST(ISNULL(inserted.[VendorGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.APCo, '') , 
								'A' , 
								'Country' , 
								NULL , 
								[Country] , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								

-- log additions to the PeriodEndDate column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vAPT5018PaymentDetail' , 
								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(inserted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(inserted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(ISNULL(inserted.[Vendor],'') AS VARCHAR(MAX)),'"', '&quot;') + '" VendorGroup = "' + REPLACE(CAST(ISNULL(inserted.[VendorGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.APCo, '') , 
								'A' , 
								'PeriodEndDate' , 
								NULL , 
								[PeriodEndDate] , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								

-- log additions to the PostalCode column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vAPT5018PaymentDetail' , 
								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(inserted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(inserted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(ISNULL(inserted.[Vendor],'') AS VARCHAR(MAX)),'"', '&quot;') + '" VendorGroup = "' + REPLACE(CAST(ISNULL(inserted.[VendorGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.APCo, '') , 
								'A' , 
								'PostalCode' , 
								NULL , 
								[PostalCode] , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								

-- log additions to the ReportTypeCode column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vAPT5018PaymentDetail' , 
								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(inserted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(inserted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(ISNULL(inserted.[Vendor],'') AS VARCHAR(MAX)),'"', '&quot;') + '" VendorGroup = "' + REPLACE(CAST(ISNULL(inserted.[VendorGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.APCo, '') , 
								'A' , 
								'ReportTypeCode' , 
								NULL , 
								[ReportTypeCode] , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								

-- log additions to the State column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vAPT5018PaymentDetail' , 
								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(inserted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(inserted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(ISNULL(inserted.[Vendor],'') AS VARCHAR(MAX)),'"', '&quot;') + '" VendorGroup = "' + REPLACE(CAST(ISNULL(inserted.[VendorGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.APCo, '') , 
								'A' , 
								'State' , 
								NULL , 
								[State] , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								

-- log additions to the T5BusTypeCode column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vAPT5018PaymentDetail' , 
								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(inserted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(inserted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(ISNULL(inserted.[Vendor],'') AS VARCHAR(MAX)),'"', '&quot;') + '" VendorGroup = "' + REPLACE(CAST(ISNULL(inserted.[VendorGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.APCo, '') , 
								'A' , 
								'T5BusTypeCode' , 
								NULL , 
								[T5BusTypeCode] , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								

-- log additions to the T5BusinessNbr column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vAPT5018PaymentDetail' , 
								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(inserted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(inserted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(ISNULL(inserted.[Vendor],'') AS VARCHAR(MAX)),'"', '&quot;') + '" VendorGroup = "' + REPLACE(CAST(ISNULL(inserted.[VendorGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.APCo, '') , 
								'A' , 
								'T5BusinessNbr' , 
								NULL , 
								[T5BusinessNbr] , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								

-- log additions to the T5FirstName column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vAPT5018PaymentDetail' , 
								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(inserted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(inserted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(ISNULL(inserted.[Vendor],'') AS VARCHAR(MAX)),'"', '&quot;') + '" VendorGroup = "' + REPLACE(CAST(ISNULL(inserted.[VendorGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.APCo, '') , 
								'A' , 
								'T5FirstName' , 
								NULL , 
								[T5FirstName] , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								

-- log additions to the T5LastName column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vAPT5018PaymentDetail' , 
								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(inserted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(inserted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(ISNULL(inserted.[Vendor],'') AS VARCHAR(MAX)),'"', '&quot;') + '" VendorGroup = "' + REPLACE(CAST(ISNULL(inserted.[VendorGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.APCo, '') , 
								'A' , 
								'T5LastName' , 
								NULL , 
								[T5LastName] , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								

-- log additions to the T5MiddleInit column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vAPT5018PaymentDetail' , 
								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(inserted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(inserted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(ISNULL(inserted.[Vendor],'') AS VARCHAR(MAX)),'"', '&quot;') + '" VendorGroup = "' + REPLACE(CAST(ISNULL(inserted.[VendorGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.APCo, '') , 
								'A' , 
								'T5MiddleInit' , 
								NULL , 
								[T5MiddleInit] , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								

-- log additions to the T5PartnerFIN column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vAPT5018PaymentDetail' , 
								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(inserted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(inserted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(ISNULL(inserted.[Vendor],'') AS VARCHAR(MAX)),'"', '&quot;') + '" VendorGroup = "' + REPLACE(CAST(ISNULL(inserted.[VendorGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.APCo, '') , 
								'A' , 
								'T5PartnerFIN' , 
								NULL , 
								[T5PartnerFIN] , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								

-- log additions to the T5SocInsNbr column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vAPT5018PaymentDetail' , 
								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(inserted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(inserted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(ISNULL(inserted.[Vendor],'') AS VARCHAR(MAX)),'"', '&quot;') + '" VendorGroup = "' + REPLACE(CAST(ISNULL(inserted.[VendorGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.APCo, '') , 
								'A' , 
								'T5SocInsNbr' , 
								NULL , 
								[T5SocInsNbr] , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								

-- log additions to the TotalPaid column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vAPT5018PaymentDetail' , 
								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(inserted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(inserted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(ISNULL(inserted.[Vendor],'') AS VARCHAR(MAX)),'"', '&quot;') + '" VendorGroup = "' + REPLACE(CAST(ISNULL(inserted.[VendorGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.APCo, '') , 
								'A' , 
								'TotalPaid' , 
								NULL , 
								[TotalPaid] , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								

-- log additions to the Vendor column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vAPT5018PaymentDetail' , 
								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(inserted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(inserted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(ISNULL(inserted.[Vendor],'') AS VARCHAR(MAX)),'"', '&quot;') + '" VendorGroup = "' + REPLACE(CAST(ISNULL(inserted.[VendorGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.APCo, '') , 
								'A' , 
								'Vendor' , 
								NULL , 
								[Vendor] , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								

-- log additions to the VendorGroup column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vAPT5018PaymentDetail' , 
								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(inserted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(inserted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(ISNULL(inserted.[Vendor],'') AS VARCHAR(MAX)),'"', '&quot;') + '" VendorGroup = "' + REPLACE(CAST(ISNULL(inserted.[VendorGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.APCo, '') , 
								'A' , 
								'VendorGroup' , 
								NULL , 
								[VendorGroup] , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								

-- log additions to the VendorName column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vAPT5018PaymentDetail' , 
								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(inserted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(inserted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(ISNULL(inserted.[Vendor],'') AS VARCHAR(MAX)),'"', '&quot;') + '" VendorGroup = "' + REPLACE(CAST(ISNULL(inserted.[VendorGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.APCo, '') , 
								'A' , 
								'VendorName' , 
								NULL , 
								[VendorName] , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								


 END TRY 
 BEGIN CATCH 
   DECLARE	@ErrorMessage	NVARCHAR(4000), 
				@ErrorSeverity	INT; 

   SELECT	@ErrorMessage = 'Error '+ ISNULL(ERROR_MESSAGE(),'') +' in [dbo].[dbo.vtvAPT5018PaymentDetail_Audit_Insert] trigger', 
				@ErrorSeverity = ERROR_SEVERITY(); 

   RAISERROR(@ErrorMessage, @ErrorSeverity, 1 ) 
 END CATCH 
GO
EXEC sp_settriggerorder N'[dbo].[vtvAPT5018PaymentDetail_Audit_Insert]', 'last', 'insert', null
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER dbo.vtvAPT5018PaymentDetail_Audit_Update ON dbo.vAPT5018PaymentDetail
 AFTER UPDATE 
 NOT FOR REPLICATION AS 
 SET NOCOUNT ON 
 -- generated by vspAuditTriggersCreate

 BEGIN TRY 

							IF UPDATE([APCo])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vAPT5018PaymentDetail' , 								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(inserted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(inserted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(ISNULL(inserted.[Vendor],'') AS VARCHAR(MAX)),'"', '&quot;') + '" VendorGroup = "' + REPLACE(CAST(ISNULL(inserted.[VendorGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.APCo , 								'C' , 								'APCo' , 								CONVERT(VARCHAR(MAX), deleted.[APCo]) , 								CONVERT(VARCHAR(MAX), inserted.[APCo]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[KeyID] = deleted.[KeyID] 
									AND ((inserted.[APCo] <> deleted.[APCo]) OR (inserted.[APCo] IS NULL AND deleted.[APCo] IS NOT NULL) OR (inserted.[APCo] IS NOT NULL AND deleted.[APCo] IS NULL))
								

							END 

							IF UPDATE([Address])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vAPT5018PaymentDetail' , 								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(inserted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(inserted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(ISNULL(inserted.[Vendor],'') AS VARCHAR(MAX)),'"', '&quot;') + '" VendorGroup = "' + REPLACE(CAST(ISNULL(inserted.[VendorGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.APCo , 								'C' , 								'Address' , 								CONVERT(VARCHAR(MAX), deleted.[Address]) , 								CONVERT(VARCHAR(MAX), inserted.[Address]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[KeyID] = deleted.[KeyID] 
									AND ((inserted.[Address] <> deleted.[Address]) OR (inserted.[Address] IS NULL AND deleted.[Address] IS NOT NULL) OR (inserted.[Address] IS NOT NULL AND deleted.[Address] IS NULL))
								

							END 

							IF UPDATE([Address2])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vAPT5018PaymentDetail' , 								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(inserted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(inserted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(ISNULL(inserted.[Vendor],'') AS VARCHAR(MAX)),'"', '&quot;') + '" VendorGroup = "' + REPLACE(CAST(ISNULL(inserted.[VendorGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.APCo , 								'C' , 								'Address2' , 								CONVERT(VARCHAR(MAX), deleted.[Address2]) , 								CONVERT(VARCHAR(MAX), inserted.[Address2]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[KeyID] = deleted.[KeyID] 
									AND ((inserted.[Address2] <> deleted.[Address2]) OR (inserted.[Address2] IS NULL AND deleted.[Address2] IS NOT NULL) OR (inserted.[Address2] IS NOT NULL AND deleted.[Address2] IS NULL))
								

							END 

							IF UPDATE([City])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vAPT5018PaymentDetail' , 								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(inserted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(inserted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(ISNULL(inserted.[Vendor],'') AS VARCHAR(MAX)),'"', '&quot;') + '" VendorGroup = "' + REPLACE(CAST(ISNULL(inserted.[VendorGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.APCo , 								'C' , 								'City' , 								CONVERT(VARCHAR(MAX), deleted.[City]) , 								CONVERT(VARCHAR(MAX), inserted.[City]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[KeyID] = deleted.[KeyID] 
									AND ((inserted.[City] <> deleted.[City]) OR (inserted.[City] IS NULL AND deleted.[City] IS NOT NULL) OR (inserted.[City] IS NOT NULL AND deleted.[City] IS NULL))
								

							END 

							IF UPDATE([Country])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vAPT5018PaymentDetail' , 								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(inserted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(inserted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(ISNULL(inserted.[Vendor],'') AS VARCHAR(MAX)),'"', '&quot;') + '" VendorGroup = "' + REPLACE(CAST(ISNULL(inserted.[VendorGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.APCo , 								'C' , 								'Country' , 								CONVERT(VARCHAR(MAX), deleted.[Country]) , 								CONVERT(VARCHAR(MAX), inserted.[Country]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[KeyID] = deleted.[KeyID] 
									AND ((inserted.[Country] <> deleted.[Country]) OR (inserted.[Country] IS NULL AND deleted.[Country] IS NOT NULL) OR (inserted.[Country] IS NOT NULL AND deleted.[Country] IS NULL))
								

							END 

							IF UPDATE([PeriodEndDate])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vAPT5018PaymentDetail' , 								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(inserted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(inserted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(ISNULL(inserted.[Vendor],'') AS VARCHAR(MAX)),'"', '&quot;') + '" VendorGroup = "' + REPLACE(CAST(ISNULL(inserted.[VendorGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.APCo , 								'C' , 								'PeriodEndDate' , 								CONVERT(VARCHAR(MAX), deleted.[PeriodEndDate]) , 								CONVERT(VARCHAR(MAX), inserted.[PeriodEndDate]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[KeyID] = deleted.[KeyID] 
									AND ((inserted.[PeriodEndDate] <> deleted.[PeriodEndDate]) OR (inserted.[PeriodEndDate] IS NULL AND deleted.[PeriodEndDate] IS NOT NULL) OR (inserted.[PeriodEndDate] IS NOT NULL AND deleted.[PeriodEndDate] IS NULL))
								

							END 

							IF UPDATE([PostalCode])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vAPT5018PaymentDetail' , 								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(inserted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(inserted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(ISNULL(inserted.[Vendor],'') AS VARCHAR(MAX)),'"', '&quot;') + '" VendorGroup = "' + REPLACE(CAST(ISNULL(inserted.[VendorGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.APCo , 								'C' , 								'PostalCode' , 								CONVERT(VARCHAR(MAX), deleted.[PostalCode]) , 								CONVERT(VARCHAR(MAX), inserted.[PostalCode]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[KeyID] = deleted.[KeyID] 
									AND ((inserted.[PostalCode] <> deleted.[PostalCode]) OR (inserted.[PostalCode] IS NULL AND deleted.[PostalCode] IS NOT NULL) OR (inserted.[PostalCode] IS NOT NULL AND deleted.[PostalCode] IS NULL))
								

							END 

							IF UPDATE([ReportTypeCode])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vAPT5018PaymentDetail' , 								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(inserted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(inserted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(ISNULL(inserted.[Vendor],'') AS VARCHAR(MAX)),'"', '&quot;') + '" VendorGroup = "' + REPLACE(CAST(ISNULL(inserted.[VendorGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.APCo , 								'C' , 								'ReportTypeCode' , 								CONVERT(VARCHAR(MAX), deleted.[ReportTypeCode]) , 								CONVERT(VARCHAR(MAX), inserted.[ReportTypeCode]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[KeyID] = deleted.[KeyID] 
									AND ((inserted.[ReportTypeCode] <> deleted.[ReportTypeCode]) OR (inserted.[ReportTypeCode] IS NULL AND deleted.[ReportTypeCode] IS NOT NULL) OR (inserted.[ReportTypeCode] IS NOT NULL AND deleted.[ReportTypeCode] IS NULL))
								

							END 

							IF UPDATE([State])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vAPT5018PaymentDetail' , 								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(inserted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(inserted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(ISNULL(inserted.[Vendor],'') AS VARCHAR(MAX)),'"', '&quot;') + '" VendorGroup = "' + REPLACE(CAST(ISNULL(inserted.[VendorGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.APCo , 								'C' , 								'State' , 								CONVERT(VARCHAR(MAX), deleted.[State]) , 								CONVERT(VARCHAR(MAX), inserted.[State]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[KeyID] = deleted.[KeyID] 
									AND ((inserted.[State] <> deleted.[State]) OR (inserted.[State] IS NULL AND deleted.[State] IS NOT NULL) OR (inserted.[State] IS NOT NULL AND deleted.[State] IS NULL))
								

							END 

							IF UPDATE([T5BusTypeCode])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vAPT5018PaymentDetail' , 								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(inserted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(inserted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(ISNULL(inserted.[Vendor],'') AS VARCHAR(MAX)),'"', '&quot;') + '" VendorGroup = "' + REPLACE(CAST(ISNULL(inserted.[VendorGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.APCo , 								'C' , 								'T5BusTypeCode' , 								CONVERT(VARCHAR(MAX), deleted.[T5BusTypeCode]) , 								CONVERT(VARCHAR(MAX), inserted.[T5BusTypeCode]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[KeyID] = deleted.[KeyID] 
									AND ((inserted.[T5BusTypeCode] <> deleted.[T5BusTypeCode]) OR (inserted.[T5BusTypeCode] IS NULL AND deleted.[T5BusTypeCode] IS NOT NULL) OR (inserted.[T5BusTypeCode] IS NOT NULL AND deleted.[T5BusTypeCode] IS NULL))
								

							END 

							IF UPDATE([T5BusinessNbr])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vAPT5018PaymentDetail' , 								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(inserted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(inserted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(ISNULL(inserted.[Vendor],'') AS VARCHAR(MAX)),'"', '&quot;') + '" VendorGroup = "' + REPLACE(CAST(ISNULL(inserted.[VendorGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.APCo , 								'C' , 								'T5BusinessNbr' , 								CONVERT(VARCHAR(MAX), deleted.[T5BusinessNbr]) , 								CONVERT(VARCHAR(MAX), inserted.[T5BusinessNbr]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[KeyID] = deleted.[KeyID] 
									AND ((inserted.[T5BusinessNbr] <> deleted.[T5BusinessNbr]) OR (inserted.[T5BusinessNbr] IS NULL AND deleted.[T5BusinessNbr] IS NOT NULL) OR (inserted.[T5BusinessNbr] IS NOT NULL AND deleted.[T5BusinessNbr] IS NULL))
								

							END 

							IF UPDATE([T5FirstName])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vAPT5018PaymentDetail' , 								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(inserted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(inserted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(ISNULL(inserted.[Vendor],'') AS VARCHAR(MAX)),'"', '&quot;') + '" VendorGroup = "' + REPLACE(CAST(ISNULL(inserted.[VendorGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.APCo , 								'C' , 								'T5FirstName' , 								CONVERT(VARCHAR(MAX), deleted.[T5FirstName]) , 								CONVERT(VARCHAR(MAX), inserted.[T5FirstName]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[KeyID] = deleted.[KeyID] 
									AND ((inserted.[T5FirstName] <> deleted.[T5FirstName]) OR (inserted.[T5FirstName] IS NULL AND deleted.[T5FirstName] IS NOT NULL) OR (inserted.[T5FirstName] IS NOT NULL AND deleted.[T5FirstName] IS NULL))
								

							END 

							IF UPDATE([T5LastName])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vAPT5018PaymentDetail' , 								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(inserted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(inserted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(ISNULL(inserted.[Vendor],'') AS VARCHAR(MAX)),'"', '&quot;') + '" VendorGroup = "' + REPLACE(CAST(ISNULL(inserted.[VendorGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.APCo , 								'C' , 								'T5LastName' , 								CONVERT(VARCHAR(MAX), deleted.[T5LastName]) , 								CONVERT(VARCHAR(MAX), inserted.[T5LastName]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[KeyID] = deleted.[KeyID] 
									AND ((inserted.[T5LastName] <> deleted.[T5LastName]) OR (inserted.[T5LastName] IS NULL AND deleted.[T5LastName] IS NOT NULL) OR (inserted.[T5LastName] IS NOT NULL AND deleted.[T5LastName] IS NULL))
								

							END 

							IF UPDATE([T5MiddleInit])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vAPT5018PaymentDetail' , 								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(inserted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(inserted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(ISNULL(inserted.[Vendor],'') AS VARCHAR(MAX)),'"', '&quot;') + '" VendorGroup = "' + REPLACE(CAST(ISNULL(inserted.[VendorGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.APCo , 								'C' , 								'T5MiddleInit' , 								CONVERT(VARCHAR(MAX), deleted.[T5MiddleInit]) , 								CONVERT(VARCHAR(MAX), inserted.[T5MiddleInit]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[KeyID] = deleted.[KeyID] 
									AND ((inserted.[T5MiddleInit] <> deleted.[T5MiddleInit]) OR (inserted.[T5MiddleInit] IS NULL AND deleted.[T5MiddleInit] IS NOT NULL) OR (inserted.[T5MiddleInit] IS NOT NULL AND deleted.[T5MiddleInit] IS NULL))
								

							END 

							IF UPDATE([T5PartnerFIN])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vAPT5018PaymentDetail' , 								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(inserted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(inserted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(ISNULL(inserted.[Vendor],'') AS VARCHAR(MAX)),'"', '&quot;') + '" VendorGroup = "' + REPLACE(CAST(ISNULL(inserted.[VendorGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.APCo , 								'C' , 								'T5PartnerFIN' , 								CONVERT(VARCHAR(MAX), deleted.[T5PartnerFIN]) , 								CONVERT(VARCHAR(MAX), inserted.[T5PartnerFIN]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[KeyID] = deleted.[KeyID] 
									AND ((inserted.[T5PartnerFIN] <> deleted.[T5PartnerFIN]) OR (inserted.[T5PartnerFIN] IS NULL AND deleted.[T5PartnerFIN] IS NOT NULL) OR (inserted.[T5PartnerFIN] IS NOT NULL AND deleted.[T5PartnerFIN] IS NULL))
								

							END 

							IF UPDATE([T5SocInsNbr])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vAPT5018PaymentDetail' , 								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(inserted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(inserted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(ISNULL(inserted.[Vendor],'') AS VARCHAR(MAX)),'"', '&quot;') + '" VendorGroup = "' + REPLACE(CAST(ISNULL(inserted.[VendorGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.APCo , 								'C' , 								'T5SocInsNbr' , 								CONVERT(VARCHAR(MAX), deleted.[T5SocInsNbr]) , 								CONVERT(VARCHAR(MAX), inserted.[T5SocInsNbr]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[KeyID] = deleted.[KeyID] 
									AND ((inserted.[T5SocInsNbr] <> deleted.[T5SocInsNbr]) OR (inserted.[T5SocInsNbr] IS NULL AND deleted.[T5SocInsNbr] IS NOT NULL) OR (inserted.[T5SocInsNbr] IS NOT NULL AND deleted.[T5SocInsNbr] IS NULL))
								

							END 

							IF UPDATE([TotalPaid])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vAPT5018PaymentDetail' , 								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(inserted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(inserted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(ISNULL(inserted.[Vendor],'') AS VARCHAR(MAX)),'"', '&quot;') + '" VendorGroup = "' + REPLACE(CAST(ISNULL(inserted.[VendorGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.APCo , 								'C' , 								'TotalPaid' , 								CONVERT(VARCHAR(MAX), deleted.[TotalPaid]) , 								CONVERT(VARCHAR(MAX), inserted.[TotalPaid]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[KeyID] = deleted.[KeyID] 
									AND ((inserted.[TotalPaid] <> deleted.[TotalPaid]) OR (inserted.[TotalPaid] IS NULL AND deleted.[TotalPaid] IS NOT NULL) OR (inserted.[TotalPaid] IS NOT NULL AND deleted.[TotalPaid] IS NULL))
								

							END 

							IF UPDATE([Vendor])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vAPT5018PaymentDetail' , 								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(inserted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(inserted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(ISNULL(inserted.[Vendor],'') AS VARCHAR(MAX)),'"', '&quot;') + '" VendorGroup = "' + REPLACE(CAST(ISNULL(inserted.[VendorGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.APCo , 								'C' , 								'Vendor' , 								CONVERT(VARCHAR(MAX), deleted.[Vendor]) , 								CONVERT(VARCHAR(MAX), inserted.[Vendor]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[KeyID] = deleted.[KeyID] 
									AND ((inserted.[Vendor] <> deleted.[Vendor]) OR (inserted.[Vendor] IS NULL AND deleted.[Vendor] IS NOT NULL) OR (inserted.[Vendor] IS NOT NULL AND deleted.[Vendor] IS NULL))
								

							END 

							IF UPDATE([VendorGroup])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vAPT5018PaymentDetail' , 								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(inserted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(inserted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(ISNULL(inserted.[Vendor],'') AS VARCHAR(MAX)),'"', '&quot;') + '" VendorGroup = "' + REPLACE(CAST(ISNULL(inserted.[VendorGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.APCo , 								'C' , 								'VendorGroup' , 								CONVERT(VARCHAR(MAX), deleted.[VendorGroup]) , 								CONVERT(VARCHAR(MAX), inserted.[VendorGroup]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[KeyID] = deleted.[KeyID] 
									AND ((inserted.[VendorGroup] <> deleted.[VendorGroup]) OR (inserted.[VendorGroup] IS NULL AND deleted.[VendorGroup] IS NOT NULL) OR (inserted.[VendorGroup] IS NOT NULL AND deleted.[VendorGroup] IS NULL))
								

							END 

							IF UPDATE([VendorName])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vAPT5018PaymentDetail' , 								'<KeyString APCo = "' + REPLACE(CAST(ISNULL(inserted.[APCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" PeriodEndDate = "' + REPLACE(CAST(ISNULL(inserted.[PeriodEndDate],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(ISNULL(inserted.[Vendor],'') AS VARCHAR(MAX)),'"', '&quot;') + '" VendorGroup = "' + REPLACE(CAST(ISNULL(inserted.[VendorGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.APCo , 								'C' , 								'VendorName' , 								CONVERT(VARCHAR(MAX), deleted.[VendorName]) , 								CONVERT(VARCHAR(MAX), inserted.[VendorName]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[KeyID] = deleted.[KeyID] 
									AND ((inserted.[VendorName] <> deleted.[VendorName]) OR (inserted.[VendorName] IS NULL AND deleted.[VendorName] IS NOT NULL) OR (inserted.[VendorName] IS NOT NULL AND deleted.[VendorName] IS NULL))
								

							END 



 END TRY 
 BEGIN CATCH 
   DECLARE	@ErrorMessage	NVARCHAR(4000), 
				@ErrorSeverity	INT; 

   SELECT	@ErrorMessage = 'Error '+ ISNULL(ERROR_MESSAGE(),'') +' in [dbo].[dbo.vtvAPT5018PaymentDetail_Audit_Update] trigger', 
				@ErrorSeverity = ERROR_SEVERITY(); 

   RAISERROR(@ErrorMessage, @ErrorSeverity, 1 ) 
 END CATCH 
GO
EXEC sp_settriggerorder N'[dbo].[vtvAPT5018PaymentDetail_Audit_Update]', 'last', 'update', null
GO
ALTER TABLE [dbo].[vAPT5018PaymentDetail] WITH NOCHECK ADD CONSTRAINT [CK_vAPT5018PaymentDetail_ReportTypeCode] CHECK (([ReportTypeCode]='O' OR [ReportTypeCode]='A' OR [ReportTypeCode]='C'))
GO
ALTER TABLE [dbo].[vAPT5018PaymentDetail] WITH NOCHECK ADD CONSTRAINT [CK_vAPT5018PaymentDetail_T5BusTypeCode] CHECK (([T5BusTypeCode]='I' OR [T5BusTypeCode]='C' OR [T5BusTypeCode]='P'))
GO
ALTER TABLE [dbo].[vAPT5018PaymentDetail] ADD CONSTRAINT [PK_vAPT5018PaymentDetail] PRIMARY KEY CLUSTERED  ([APCo], [PeriodEndDate], [VendorGroup], [Vendor]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[vAPT5018PaymentDetail] WITH NOCHECK ADD CONSTRAINT [FK_vAPT5018PaymentDetail_vAPT5018Payment] FOREIGN KEY ([APCo], [PeriodEndDate]) REFERENCES [dbo].[vAPT5018Payment] ([APCo], [PeriodEndDate]) ON DELETE CASCADE
GO
ALTER TABLE [dbo].[vAPT5018PaymentDetail] NOCHECK CONSTRAINT [FK_vAPT5018PaymentDetail_vAPT5018Payment]
GO
