CREATE TABLE [dbo].[bCMAC061413]
(
[CMCo] [dbo].[bCompany] NOT NULL,
[CMAcct] [dbo].[bCMAcct] NOT NULL,
[Description] [dbo].[bDesc] NULL,
[GLCo] [dbo].[bCompany] NOT NULL,
[GLAcct] [dbo].[bGLAcct] NOT NULL,
[BankAcct] [varchar] (30) COLLATE Latin1_General_BIN NULL,
[ImmedDest] [varchar] (10) COLLATE Latin1_General_BIN NULL,
[ImmedOrig] [varchar] (10) COLLATE Latin1_General_BIN NULL,
[CompanyId] [varchar] (10) COLLATE Latin1_General_BIN NULL,
[BankName] [varchar] (30) COLLATE Latin1_General_BIN NULL,
[DFI] [varchar] (10) COLLATE Latin1_General_BIN NULL,
[RoutingId] [varchar] (10) COLLATE Latin1_General_BIN NULL,
[ServiceClass] [varchar] (3) COLLATE Latin1_General_BIN NULL,
[AcctType] [char] (1) COLLATE Latin1_General_BIN NULL,
[Notes] [varchar] (max) COLLATE Latin1_General_BIN NULL,
[BatchHeader] [varchar] (94) COLLATE Latin1_General_BIN NULL,
[AssignBank] [varchar] (23) COLLATE Latin1_General_BIN NULL,
[UniqueAttchID] [uniqueidentifier] NULL,
[KeyID] [bigint] NOT NULL IDENTITY(1, 1),
[AUAccountName] [varchar] (26) COLLATE Latin1_General_BIN NULL,
[AUBSB] [varchar] (6) COLLATE Latin1_General_BIN NULL,
[AUBankShortName] [varchar] (3) COLLATE Latin1_General_BIN NULL,
[AUCustomerNumber] [varchar] (6) COLLATE Latin1_General_BIN NULL,
[AUReference] [varchar] (12) COLLATE Latin1_General_BIN NULL,
[AUContraRequiredYN] [dbo].[bYN] NOT NULL,
[CADestDataCentre] [varchar] (5) COLLATE Latin1_General_BIN NULL,
[CACurrencyCode] [varchar] (3) COLLATE Latin1_General_BIN NULL,
[CAOriginatorId] [varchar] (10) COLLATE Latin1_General_BIN NULL,
[CACMRoutingNbr] [varchar] (9) COLLATE Latin1_General_BIN NULL,
[Discretionary] [varchar] (20) COLLATE Latin1_General_BIN NULL,
[CAShortName] [varchar] (15) COLLATE Latin1_General_BIN NULL,
[CALongName] [varchar] (30) COLLATE Latin1_General_BIN NULL,
[CAEFTFormat] [varchar] (10) COLLATE Latin1_General_BIN NOT NULL,
[CARBCFileDescriptor] [varchar] (50) COLLATE Latin1_General_BIN NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
