CREATE TABLE [dbo].[oldEMEM20131105]
(
[EMCo] [dbo].[bCompany] NOT NULL,
[Equipment] [dbo].[bEquip] NOT NULL,
[Location] [varchar] (10) COLLATE Latin1_General_BIN NULL,
[Type] [char] (1) COLLATE Latin1_General_BIN NOT NULL,
[Department] [dbo].[bDept] NULL,
[Category] [dbo].[bCat] NULL,
[Manufacturer] [varchar] (20) COLLATE Latin1_General_BIN NULL,
[Model] [varchar] (20) COLLATE Latin1_General_BIN NULL,
[ModelYr] [char] (6) COLLATE Latin1_General_BIN NULL,
[VINNumber] [varchar] (40) COLLATE Latin1_General_BIN NULL,
[Description] [dbo].[bItemDesc] NULL,
[Status] [char] (1) COLLATE Latin1_General_BIN NOT NULL,
[OdoReading] [dbo].[bHrs] NOT NULL,
[OdoDate] [dbo].[bDate] NULL,
[ReplacedOdoReading] [dbo].[bHrs] NOT NULL,
[ReplacedOdoDate] [dbo].[bDate] NULL,
[HourReading] [dbo].[bHrs] NOT NULL,
[HourDate] [dbo].[bDate] NULL,
[ReplacedHourReading] [dbo].[bHrs] NOT NULL,
[ReplacedHourDate] [dbo].[bDate] NULL,
[MatlGroup] [dbo].[bGroup] NULL,
[FuelMatlCode] [dbo].[bMatl] NULL,
[FuelCapacity] [dbo].[bHrs] NOT NULL,
[FuelCapUM] [dbo].[bUM] NULL,
[FuelUsed] [dbo].[bUnits] NOT NULL,
[EMGroup] [dbo].[bGroup] NULL,
[FuelCostCode] [varchar] (10) COLLATE Latin1_General_BIN NULL,
[FuelCostType] [tinyint] NULL,
[LastFuelDate] [dbo].[bDate] NULL,
[AttachToEquip] [dbo].[bEquip] NULL,
[AttachPostRevenue] [dbo].[bYN] NULL,
[JCCo] [dbo].[bCompany] NULL,
[Job] [dbo].[bJob] NULL,
[PhaseGrp] [dbo].[bGroup] NULL,
[UsageCostType] [dbo].[bJCCType] NULL,
[WeightUM] [dbo].[bUM] NULL,
[WeightCapacity] [dbo].[bHrs] NOT NULL,
[VolumeUM] [dbo].[bUM] NULL,
[VolumeCapacity] [dbo].[bHrs] NOT NULL,
[Capitalized] [dbo].[bYN] NULL,
[LicensePlateNo] [varchar] (10) COLLATE Latin1_General_BIN NULL,
[LicensePlateState] [varchar] (4) COLLATE Latin1_General_BIN NULL,
[LicensePlateExpDate] [dbo].[bDate] NULL,
[IRPFleet] [varchar] (10) COLLATE Latin1_General_BIN NULL,
[CompOfEquip] [dbo].[bEquip] NULL,
[ComponentTypeCode] [varchar] (10) COLLATE Latin1_General_BIN NULL,
[CompUpdateHrs] [dbo].[bYN] NULL,
[CompUpdateMiles] [dbo].[bYN] NULL,
[CompUpdateFuel] [dbo].[bYN] NULL,
[PostCostToComp] [dbo].[bYN] NULL,
[PRCo] [dbo].[bCompany] NULL,
[Operator] [dbo].[bEmployee] NULL,
[Shop] [varchar] (20) COLLATE Latin1_General_BIN NULL,
[GrossVehicleWeight] [dbo].[bHrs] NOT NULL,
[TareWeight] [dbo].[bUnits] NOT NULL,
[Height] [varchar] (20) COLLATE Latin1_General_BIN NULL,
[Wheelbase] [varchar] (20) COLLATE Latin1_General_BIN NULL,
[NoAxles] [tinyint] NOT NULL,
[Width] [varchar] (20) COLLATE Latin1_General_BIN NULL,
[OverallLength] [varchar] (20) COLLATE Latin1_General_BIN NULL,
[HorsePower] [varchar] (20) COLLATE Latin1_General_BIN NULL,
[TireSize] [varchar] (20) COLLATE Latin1_General_BIN NULL,
[OwnershipStatus] [varchar] (20) COLLATE Latin1_General_BIN NULL,
[InServiceDate] [dbo].[bDate] NULL,
[ExpLife] [smallint] NOT NULL,
[ReplCost] [dbo].[bDollar] NOT NULL,
[CurrentAppraisal] [dbo].[bDollar] NOT NULL,
[SoldDate] [dbo].[bDate] NULL,
[SalePrice] [dbo].[bDollar] NOT NULL,
[PurchasedFrom] [varchar] (30) COLLATE Latin1_General_BIN NULL,
[PurchasePrice] [dbo].[bDollar] NOT NULL,
[PurchDate] [dbo].[bDate] NULL,
[APCo] [dbo].[bCompany] NULL,
[VendorGroup] [dbo].[bGroup] NULL,
[LeasedFrom] [dbo].[bVendor] NULL,
[LeaseStartDate] [dbo].[bDate] NULL,
[LeaseEndDate] [dbo].[bDate] NULL,
[LeasePayment] [dbo].[bDollar] NOT NULL,
[LeaseResidualValue] [dbo].[bDollar] NOT NULL,
[ARCo] [dbo].[bCompany] NULL,
[CustGroup] [dbo].[bGroup] NULL,
[Customer] [dbo].[bCustomer] NULL,
[CustEquipNo] [varchar] (20) COLLATE Latin1_General_BIN NULL,
[MSTruckType] [varchar] (10) COLLATE Latin1_General_BIN NULL,
[RevenueCode] [dbo].[bRevCode] NULL,
[Notes] [varchar] (max) COLLATE Latin1_General_BIN NULL,
[MechanicNotes] [varchar] (max) COLLATE Latin1_General_BIN NULL,
[JobDate] [dbo].[bDate] NULL,
[FuelType] [char] (1) COLLATE Latin1_General_BIN NOT NULL,
[UpdateYN] [dbo].[bYN] NOT NULL,
[ShopGroup] [dbo].[bGroup] NOT NULL,
[IFTAState] [varchar] (4) COLLATE Latin1_General_BIN NULL,
[UniqueAttchID] [uniqueidentifier] NULL,
[LastUsedDate] [dbo].[bDate] NULL,
[KeyID] [bigint] NOT NULL IDENTITY(1, 1),
[ChangeInProgress] [dbo].[bYN] NULL,
[LastUsedEquipmentCode] [dbo].[bEquip] NULL,
[LastEquipmentChangeDate] [dbo].[bDate] NULL,
[LastEquipmentChangeUser] [dbo].[bVPUserName] NULL,
[EquipmentCodeChanges] [int] NULL,
[OriginalEquipmentCode] [dbo].[bEquip] NULL,
[ExpLifeTimeFrame] [char] (1) COLLATE Latin1_General_BIN NOT NULL,
[udSource] [varchar] (305) COLLATE Latin1_General_BIN NULL,
[udConv] [varchar] (1) COLLATE Latin1_General_BIN NULL,
[udCGCTable] [varchar] (10) COLLATE Latin1_General_BIN NULL,
[udCGCTableID] [decimal] (12, 0) NULL,
[udMckEQNum] [varchar] (30) COLLATE Latin1_General_BIN NULL,
[udSeaDOTNum] [varchar] (30) COLLATE Latin1_General_BIN NULL,
[udOffRdDate] [smalldatetime] NULL,
[udOnRdDate] [smalldatetime] NULL,
[udEmissionTest] [dbo].[bDesc] NULL,
[udFuelCard] [dbo].[bDesc] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
