CREATE TABLE [dbo].[cgcPayrollBatchForVPImport]
(
[Co] [tinyint] NULL,
[Mth] [smalldatetime] NULL,
[BatchId] [int] NULL,
[BatchSequence] [int] NULL,
[BatchTransType] [char] (1) COLLATE Latin1_General_BIN NULL,
[Employee] [int] NULL,
[PRGroup] [tinyint] NULL,
[PREndDate] [smalldatetime] NULL,
[PaySeq] [tinyint] NULL,
[PostSeq] [smallint] NULL,
[Type] [char] (1) COLLATE Latin1_General_BIN NULL,
[DayNum] [smallint] NULL,
[PostDate] [smalldatetime] NULL,
[JCCo] [tinyint] NULL,
[Job] [varchar] (10) COLLATE Latin1_General_BIN NULL,
[PhaseGroup] [tinyint] NULL,
[Phase] [varchar] (20) COLLATE Latin1_General_BIN NULL,
[GLCo] [tinyint] NULL,
[EMCo] [tinyint] NULL,
[WO] [varchar] (10) COLLATE Latin1_General_BIN NULL,
[WOItem] [smallint] NULL,
[Equipment] [varchar] (10) COLLATE Latin1_General_BIN NULL,
[EMGroup] [tinyint] NULL,
[EquipPhase] [varchar] (20) COLLATE Latin1_General_BIN NULL,
[CostCode] [varchar] (10) COLLATE Latin1_General_BIN NULL,
[CompType] [varchar] (10) COLLATE Latin1_General_BIN NULL,
[Component] [varchar] (10) COLLATE Latin1_General_BIN NULL,
[SMCo] [tinyint] NULL,
[SMWorkOrder] [int] NULL,
[SMScope] [int] NULL,
[SMPayType] [varchar] (10) COLLATE Latin1_General_BIN NULL,
[RevCode] [varchar] (10) COLLATE Latin1_General_BIN NULL,
[SMCostType] [smallint] NULL,
[SMJCCostType] [tinyint] NULL,
[EquipCType] [tinyint] NULL,
[UsageUnits] [numeric] (10, 2) NULL,
[TaxState] [varchar] (4) COLLATE Latin1_General_BIN NULL,
[LocalCode] [varchar] (10) COLLATE Latin1_General_BIN NULL,
[UnempState] [varchar] (4) COLLATE Latin1_General_BIN NULL,
[InsState] [varchar] (4) COLLATE Latin1_General_BIN NULL,
[InsCode] [varchar] (10) COLLATE Latin1_General_BIN NULL,
[PRDept] [varchar] (10) COLLATE Latin1_General_BIN NULL,
[Crew] [varchar] (10) COLLATE Latin1_General_BIN NULL,
[Cert] [char] (1) COLLATE Latin1_General_BIN NULL,
[Craft] [varchar] (10) COLLATE Latin1_General_BIN NULL,
[Class] [varchar] (10) COLLATE Latin1_General_BIN NULL,
[EarnCode] [smallint] NULL,
[Shift] [tinyint] NULL,
[Hours] [numeric] (10, 2) NULL,
[Rate] [numeric] (16, 5) NULL,
[Amt] [numeric] (12, 2) NULL,
[Memo] [varchar] (500) COLLATE Latin1_General_BIN NULL,
[udAdrea] [varchar] (5) COLLATE Latin1_General_BIN NULL
) ON [PRIMARY]
GO
