CREATE TABLE [dbo].[bEMAT]
(
[EMCo] [dbo].[bCompany] NOT NULL,
[AllocCode] [tinyint] NOT NULL,
[CostType] [dbo].[bEMCType] NOT NULL,
[EMGroup] [dbo].[bGroup] NOT NULL
) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [biEMAT] ON [dbo].[bEMAT] ([EMCo], [AllocCode], [CostType], [EMGroup]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
ALTER TABLE [dbo].[bEMAT] WITH NOCHECK ADD CONSTRAINT [FK_bEMAT_bEMCO_EMCo] FOREIGN KEY ([EMCo]) REFERENCES [dbo].[bEMCO] ([EMCo])
GO
ALTER TABLE [dbo].[bEMAT] WITH NOCHECK ADD CONSTRAINT [FK_bEMAT_bEMAH_AllocCode] FOREIGN KEY ([EMCo], [AllocCode]) REFERENCES [dbo].[bEMAH] ([EMCo], [AllocCode]) ON DELETE CASCADE
GO
ALTER TABLE [dbo].[bEMAT] WITH NOCHECK ADD CONSTRAINT [FK_bEMAT_bHQGP_EMGroup] FOREIGN KEY ([EMGroup]) REFERENCES [dbo].[bHQGP] ([Grp])
GO
ALTER TABLE [dbo].[bEMAT] WITH NOCHECK ADD CONSTRAINT [FK_bEMAT_bEMCT_CostType] FOREIGN KEY ([EMGroup], [CostType]) REFERENCES [dbo].[bEMCT] ([EMGroup], [CostType])
GO
ALTER TABLE [dbo].[bEMAT] NOCHECK CONSTRAINT [FK_bEMAT_bEMCO_EMCo]
GO
ALTER TABLE [dbo].[bEMAT] NOCHECK CONSTRAINT [FK_bEMAT_bEMAH_AllocCode]
GO
ALTER TABLE [dbo].[bEMAT] NOCHECK CONSTRAINT [FK_bEMAT_bHQGP_EMGroup]
GO
ALTER TABLE [dbo].[bEMAT] NOCHECK CONSTRAINT [FK_bEMAT_bEMCT_CostType]
GO
