CREATE TABLE [dbo].[MckTempHRnetData]
(
[HR_EmployeeNum] [float] NULL,
[HR_EmployeeName] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[HR_Status] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[HR_Company] [float] NULL,
[HR_LastName] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[HR_FirstName] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[HR_MiddleNames] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[HR_Suffix] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[HR_Address1] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[HR_Address2] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[HR_City] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[HR_State] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[HR_ZipCode] [float] NULL,
[HR_AreaCode] [float] NULL,
[HR_PhoneNumber] [float] NULL,
[HR_EEO_Ethnicity_Code] [float] NULL,
[HR_Gender] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[HR_BirthDate] [float] NULL,
[HR_OriginalHireDate] [float] NULL,
[HR_BeginDate] [float] NULL,
[HR_PayGroup] [float] NULL,
[HR_Department] [float] NULL,
[HR_Class] [float] NULL,
[HR_EmployeeType] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[HR_Default_TaxState] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[HR_Default_UnempState] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[HR_Default_InsState] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[HR_Default_LocalCode] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[HR_Default_StdInsCode] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[HR_RegularRate] [float] NULL,
[HR_SalariedAnnualAmt] [float] NULL,
[HR_OvertimeRate] [float] NULL,
[HR_Status1] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[HR_TermDate] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[HR_JobTitle] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[EEOJOBCATEGORIES] [float] NULL
) ON [PRIMARY]
GO
