CREATE TABLE [dbo].[bEMAD]
(
[EMCo] [dbo].[bCompany] NOT NULL,
[AllocCode] [tinyint] NOT NULL,
[Department] [dbo].[bDept] NOT NULL
) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [biEMAD] ON [dbo].[bEMAD] ([EMCo], [AllocCode], [Department]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
ALTER TABLE [dbo].[bEMAD] WITH NOCHECK ADD CONSTRAINT [FK_bEMAD_bEMCO_EMCo] FOREIGN KEY ([EMCo]) REFERENCES [dbo].[bEMCO] ([EMCo])
GO
ALTER TABLE [dbo].[bEMAD] WITH NOCHECK ADD CONSTRAINT [FK_bEMAD_bEMAH_AllocCode] FOREIGN KEY ([EMCo], [AllocCode]) REFERENCES [dbo].[bEMAH] ([EMCo], [AllocCode]) ON DELETE CASCADE
GO
ALTER TABLE [dbo].[bEMAD] WITH NOCHECK ADD CONSTRAINT [FK_bEMAD_bEMDM_Department] FOREIGN KEY ([EMCo], [Department]) REFERENCES [dbo].[bEMDM] ([EMCo], [Department])
GO
ALTER TABLE [dbo].[bEMAD] NOCHECK CONSTRAINT [FK_bEMAD_bEMCO_EMCo]
GO
ALTER TABLE [dbo].[bEMAD] NOCHECK CONSTRAINT [FK_bEMAD_bEMAH_AllocCode]
GO
ALTER TABLE [dbo].[bEMAD] NOCHECK CONSTRAINT [FK_bEMAD_bEMDM_Department]
GO
