CREATE TABLE [dbo].[boldPOHB20131111]
(
[Co] [dbo].[bCompany] NOT NULL,
[Mth] [dbo].[bMonth] NOT NULL,
[BatchId] [dbo].[bBatchID] NOT NULL,
[BatchSeq] [int] NOT NULL,
[BatchTransType] [char] (1) COLLATE Latin1_General_BIN NOT NULL,
[PO] [varchar] (30) COLLATE Latin1_General_BIN NOT NULL,
[VendorGroup] [dbo].[bGroup] NOT NULL,
[Vendor] [dbo].[bVendor] NULL,
[Description] [dbo].[bItemDesc] NULL,
[OrderDate] [dbo].[bDate] NULL,
[OrderedBy] [varchar] (10) COLLATE Latin1_General_BIN NULL,
[ExpDate] [dbo].[bDate] NULL,
[Status] [tinyint] NOT NULL,
[JCCo] [dbo].[bCompany] NULL,
[Job] [dbo].[bJob] NULL,
[INCo] [dbo].[bCompany] NULL,
[Loc] [dbo].[bLoc] NULL,
[ShipLoc] [dbo].[bShipLoc] NULL,
[Address] [varchar] (60) COLLATE Latin1_General_BIN NULL,
[City] [varchar] (30) COLLATE Latin1_General_BIN NULL,
[State] [varchar] (4) COLLATE Latin1_General_BIN NULL,
[Zip] [dbo].[bZip] NULL,
[ShipIns] [varchar] (60) COLLATE Latin1_General_BIN NULL,
[HoldCode] [dbo].[bHoldCode] NULL,
[PayTerms] [dbo].[bPayTerms] NULL,
[CompGroup] [varchar] (10) COLLATE Latin1_General_BIN NULL,
[Notes] [varchar] (max) COLLATE Latin1_General_BIN NULL,
[OldVendorGroup] [dbo].[bGroup] NULL,
[OldVendor] [dbo].[bVendor] NULL,
[OldDesc] [dbo].[bItemDesc] NULL,
[OldOrderDate] [dbo].[bDate] NULL,
[OldOrderedBy] [varchar] (10) COLLATE Latin1_General_BIN NULL,
[OldExpDate] [dbo].[bDate] NULL,
[OldStatus] [tinyint] NULL,
[OldJCCo] [dbo].[bCompany] NULL,
[OldJob] [dbo].[bJob] NULL,
[OldINCo] [dbo].[bCompany] NULL,
[OldLoc] [dbo].[bLoc] NULL,
[OldShipLoc] [varchar] (10) COLLATE Latin1_General_BIN NULL,
[OldAddress] [varchar] (60) COLLATE Latin1_General_BIN NULL,
[OldCity] [varchar] (30) COLLATE Latin1_General_BIN NULL,
[OldState] [varchar] (4) COLLATE Latin1_General_BIN NULL,
[OldZip] [dbo].[bZip] NULL,
[OldShipIns] [varchar] (60) COLLATE Latin1_General_BIN NULL,
[OldHoldCode] [dbo].[bHoldCode] NULL,
[OldPayTerms] [dbo].[bPayTerms] NULL,
[OldCompGroup] [varchar] (10) COLLATE Latin1_General_BIN NULL,
[UniqueAttchID] [uniqueidentifier] NULL,
[Attention] [dbo].[bDesc] NULL,
[OldAttention] [dbo].[bDesc] NULL,
[PayAddressSeq] [tinyint] NULL,
[OldPayAddressSeq] [tinyint] NULL,
[POAddressSeq] [tinyint] NULL,
[OldPOAddressSeq] [tinyint] NULL,
[Address2] [varchar] (60) COLLATE Latin1_General_BIN NULL,
[OldAddress2] [varchar] (60) COLLATE Latin1_General_BIN NULL,
[KeyID] [bigint] NOT NULL IDENTITY(1, 1),
[Country] [char] (2) COLLATE Latin1_General_BIN NULL,
[OldCountry] [char] (2) COLLATE Latin1_General_BIN NULL,
[udOrderedBy] [int] NULL,
[udPRCo] [dbo].[bCompany] NULL,
[udMCKPONumber] [varchar] (30) COLLATE Latin1_General_BIN NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
