CREATE TABLE [dbo].[boldPOHD20131111]
(
[POCo] [dbo].[bCompany] NOT NULL,
[PO] [varchar] (30) COLLATE Latin1_General_BIN NOT NULL,
[VendorGroup] [dbo].[bGroup] NOT NULL,
[Vendor] [dbo].[bVendor] NOT NULL,
[Description] [dbo].[bItemDesc] NULL,
[OrderDate] [dbo].[bDate] NULL,
[OrderedBy] [varchar] (10) COLLATE Latin1_General_BIN NULL,
[ExpDate] [dbo].[bDate] NULL,
[Status] [tinyint] NOT NULL,
[JCCo] [dbo].[bCompany] NULL,
[Job] [dbo].[bJob] NULL,
[INCo] [dbo].[bCompany] NULL,
[Loc] [dbo].[bLoc] NULL,
[ShipLoc] [dbo].[bShipLoc] NULL,
[Address] [varchar] (60) COLLATE Latin1_General_BIN NULL,
[City] [varchar] (30) COLLATE Latin1_General_BIN NULL,
[State] [varchar] (4) COLLATE Latin1_General_BIN NULL,
[Zip] [dbo].[bZip] NULL,
[ShipIns] [varchar] (60) COLLATE Latin1_General_BIN NULL,
[HoldCode] [dbo].[bHoldCode] NULL,
[PayTerms] [dbo].[bPayTerms] NULL,
[CompGroup] [varchar] (10) COLLATE Latin1_General_BIN NULL,
[MthClosed] [dbo].[bMonth] NULL,
[InUseMth] [dbo].[bMonth] NULL,
[InUseBatchId] [dbo].[bBatchID] NULL,
[Approved] [dbo].[bYN] NULL,
[ApprovedBy] [dbo].[bVPUserName] NULL,
[Purge] [dbo].[bYN] NOT NULL,
[Notes] [varchar] (max) COLLATE Latin1_General_BIN NULL,
[AddedMth] [dbo].[bMonth] NULL,
[AddedBatchID] [dbo].[bBatchID] NULL,
[UniqueAttchID] [uniqueidentifier] NULL,
[Attention] [dbo].[bDesc] NULL,
[PayAddressSeq] [tinyint] NULL,
[POAddressSeq] [tinyint] NULL,
[Address2] [varchar] (60) COLLATE Latin1_General_BIN NULL,
[KeyID] [bigint] NOT NULL IDENTITY(1, 1),
[Country] [char] (2) COLLATE Latin1_General_BIN NULL,
[POCloseBatchID] [dbo].[bBatchID] NULL,
[udSource] [varchar] (30) COLLATE Latin1_General_BIN NULL,
[udConv] [varchar] (1) COLLATE Latin1_General_BIN NULL,
[udCGCTable] [varchar] (10) COLLATE Latin1_General_BIN NULL,
[udCGCTableID] [decimal] (12, 0) NULL,
[udOrderedBy] [int] NULL,
[udPRCo] [dbo].[bCompany] NULL,
[DocType] [dbo].[bDocType] NOT NULL,
[udMCKPONumber] [varchar] (30) COLLATE Latin1_General_BIN NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
