CREATE TABLE [dbo].[bJBAL]
(
[Co] [dbo].[bCompany] NOT NULL,
[Mth] [dbo].[bMonth] NOT NULL,
[BatchId] [dbo].[bBatchID] NOT NULL,
[BatchSeq] [int] NOT NULL,
[Item] [dbo].[bContractItem] NULL,
[ARLine] [smallint] NULL,
[BatchTransType] [char] (1) COLLATE Latin1_General_BIN NOT NULL,
[GLCo] [dbo].[bCompany] NULL,
[GLAcct] [dbo].[bGLAcct] NOT NULL,
[Description] [dbo].[bDesc] NULL,
[TaxGroup] [dbo].[bGroup] NULL,
[TaxCode] [dbo].[bTaxCode] NULL,
[UM] [dbo].[bUM] NOT NULL,
[Amount] [dbo].[bDollar] NOT NULL,
[Units] [dbo].[bUnits] NOT NULL,
[TaxBasis] [dbo].[bDollar] NOT NULL,
[TaxAmount] [dbo].[bDollar] NOT NULL,
[RetgPct] [dbo].[bPct] NOT NULL,
[Retainage] [dbo].[bDollar] NOT NULL,
[RetgRel] [dbo].[bDollar] NOT NULL,
[Notes] [varchar] (max) COLLATE Latin1_General_BIN NULL,
[oldLineType] [char] (1) COLLATE Latin1_General_BIN NULL,
[oldDescription] [dbo].[bDesc] NULL,
[oldAmount] [dbo].[bDollar] NULL,
[oldUnits] [dbo].[bUnits] NULL,
[oldTaxCode] [dbo].[bTaxCode] NULL,
[oldTaxBasis] [dbo].[bDollar] NULL,
[oldTaxAmount] [dbo].[bDollar] NULL,
[oldRetgPct] [dbo].[bPct] NULL,
[oldRetainage] [dbo].[bDollar] NULL,
[oldRetgRel] [dbo].[bDollar] NULL,
[Discount] [dbo].[bDollar] NOT NULL CONSTRAINT [DF_bJBAL_Discount] DEFAULT ((0)),
[oldDiscount] [dbo].[bDollar] NULL,
[oldNotes] [varchar] (max) COLLATE Latin1_General_BIN NULL,
[RetgTax] [dbo].[bDollar] NULL,
[oldRetgTax] [dbo].[bDollar] NULL,
[RetgTaxRel] [dbo].[bDollar] NULL,
[oldRetgTaxRel] [dbo].[bDollar] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [biJBAL] ON [dbo].[bJBAL] ([Co], [Mth], [BatchId], [BatchSeq], [Item], [ARLine]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
