CREATE TABLE [dbo].[bPROS]
(
[PRCo] [dbo].[bCompany] NOT NULL,
[OTSched] [tinyint] NOT NULL,
[Shift] [tinyint] NOT NULL,
[Lvl1MonHrs] [dbo].[bHrs] NOT NULL,
[Lvl1MonEarnCode] [dbo].[bEDLCode] NULL,
[Lvl1TuesHrs] [dbo].[bHrs] NOT NULL,
[Lvl1TuesEarnCode] [dbo].[bEDLCode] NULL,
[Lvl1WedHrs] [dbo].[bHrs] NOT NULL,
[Lvl1WedEarnCode] [dbo].[bEDLCode] NULL,
[Lvl1ThursHrs] [dbo].[bHrs] NOT NULL,
[Lvl1ThursEarnCode] [dbo].[bEDLCode] NULL,
[Lvl1FriHrs] [dbo].[bHrs] NOT NULL,
[Lvl1FriEarnCode] [dbo].[bEDLCode] NULL,
[Lvl1SatHrs] [dbo].[bHrs] NOT NULL,
[Lvl1SatEarnCode] [dbo].[bEDLCode] NULL,
[Lvl1SunHrs] [dbo].[bHrs] NOT NULL,
[Lvl1SunEarnCode] [dbo].[bEDLCode] NULL,
[Lvl1HolHrs] [dbo].[bHrs] NOT NULL,
[Lvl1HolEarnCode] [dbo].[bEDLCode] NULL,
[Lvl2MonHrs] [dbo].[bHrs] NOT NULL,
[Lvl2MonEarnCode] [dbo].[bEDLCode] NULL,
[Lvl2TuesHrs] [dbo].[bHrs] NOT NULL,
[Lvl2TuesEarnCode] [dbo].[bEDLCode] NULL,
[Lvl2WedHrs] [dbo].[bHrs] NOT NULL,
[Lvl2WedEarnCode] [dbo].[bEDLCode] NULL,
[Lvl2ThursHrs] [dbo].[bHrs] NOT NULL,
[Lvl2ThursEarnCode] [dbo].[bEDLCode] NULL,
[Lvl2FriHrs] [dbo].[bHrs] NOT NULL,
[Lvl2FriEarnCode] [dbo].[bEDLCode] NULL,
[Lvl2SatHrs] [dbo].[bHrs] NOT NULL,
[Lvl2SatEarnCode] [dbo].[bEDLCode] NULL,
[Lvl2SunHrs] [dbo].[bHrs] NOT NULL,
[Lvl2SunEarnCode] [dbo].[bEDLCode] NULL,
[Lvl2HolHrs] [dbo].[bHrs] NOT NULL,
[Lvl2HolEarnCode] [dbo].[bEDLCode] NULL,
[Lvl3MonHrs] [dbo].[bHrs] NOT NULL,
[Lvl3MonEarnCode] [dbo].[bEDLCode] NULL,
[Lvl3TuesHrs] [dbo].[bHrs] NOT NULL,
[Lvl3TuesEarnCode] [dbo].[bEDLCode] NULL,
[Lvl3WedHrs] [dbo].[bHrs] NOT NULL,
[Lvl3WedEarnCode] [dbo].[bEDLCode] NULL,
[Lvl3ThursHrs] [dbo].[bHrs] NOT NULL,
[Lvl3ThursEarnCode] [dbo].[bEDLCode] NULL,
[Lvl3FriHrs] [dbo].[bHrs] NOT NULL,
[Lvl3FriEarnCode] [dbo].[bEDLCode] NULL,
[Lvl3SatHrs] [dbo].[bHrs] NOT NULL,
[Lvl3SatEarnCode] [dbo].[bEDLCode] NULL,
[Lvl3SunHrs] [dbo].[bHrs] NOT NULL,
[Lvl3SunEarnCode] [dbo].[bEDLCode] NULL,
[Lvl3HolHrs] [dbo].[bHrs] NOT NULL,
[Lvl3HolEarnCode] [dbo].[bEDLCode] NULL,
[Notes] [varchar] (max) COLLATE Latin1_General_BIN NULL,
[UniqueAttchID] [uniqueidentifier] NULL,
[KeyID] [bigint] NOT NULL IDENTITY(1, 1)
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [biKeyID] ON [dbo].[bPROS] ([KeyID]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [biPROS] ON [dbo].[bPROS] ([PRCo], [OTSched], [Shift]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
