CREATE TABLE [dbo].[bPMHF]
(
[PMHIKeyId] [bigint] NOT NULL,
[FileName] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[FileData] [image] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[bPMHF] ADD CONSTRAINT [PK_bPMHF_1] PRIMARY KEY CLUSTERED  ([PMHIKeyId]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
ALTER TABLE [dbo].[bPMHF] WITH NOCHECK ADD CONSTRAINT [FK_bPMHF_bPMHI] FOREIGN KEY ([PMHIKeyId]) REFERENCES [dbo].[bPMHI] ([KeyId])
GO
ALTER TABLE [dbo].[bPMHF] NOCHECK CONSTRAINT [FK_bPMHF_bPMHI]
GO
