CREATE TABLE [dbo].[mckTEMPPhaseLoad]
(
[Phase] [nvarchar] (50) COLLATE Latin1_General_BIN NOT NULL,
[Description] [nvarchar] (max) COLLATE Latin1_General_BIN NULL,
[CT1] [char] (30) COLLATE Latin1_General_BIN NULL,
[CT2] [char] (30) COLLATE Latin1_General_BIN NULL,
[CT3] [char] (30) COLLATE Latin1_General_BIN NULL,
[CT4] [char] (30) COLLATE Latin1_General_BIN NULL,
[CT5] [char] (30) COLLATE Latin1_General_BIN NULL,
[T1] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[T2] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[T3] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[T4] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[T5] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[T6] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[T7] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[T8] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[T9] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[T10] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[T11] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[T12] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[T13] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[T14] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[T15] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[T16] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[T17] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[T18] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[T19] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[T20] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[T21] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[T22] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[T23] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[T24] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[T25] [varchar] (255) COLLATE Latin1_General_BIN NULL,
[RollupPhase] [varchar] (255) COLLATE Latin1_General_BIN NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
