SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO



CREATE proc [dbo].[cvsp_CMS_PR_RebuildIndexes] (@fromco smallint, @toco smallint, 
	@errmsg varchar(1000) output, @rowcount bigint output) 
as

/**
=========================================================================
Copyright © 2009 Viewpoint Construction Software (VCS)
The TSQL code in this procedure may not be reproduced, copied, modified,
or executed without written consent from VCS.
=========================================================================
	Title:		Rebuild PR Indexes
  	Created:	9.2.09
	Created by: JRE        
	Revisions:	1. None
**/



set @errmsg=''
set @rowcount=0

ALTER INDEX ALL ON bPRDB REBUILD WITH (FILLFACTOR = 85, SORT_IN_TEMPDB = ON,STATISTICS_NORECOMPUTE = ON);
ALTER INDEX ALL ON bPRIA REBUILD WITH (FILLFACTOR = 85, SORT_IN_TEMPDB = ON,STATISTICS_NORECOMPUTE = ON);
ALTER INDEX ALL ON bPRPC REBUILD WITH (FILLFACTOR = 85, SORT_IN_TEMPDB = ON,STATISTICS_NORECOMPUTE = ON);
ALTER INDEX ALL ON bPRPH REBUILD WITH (FILLFACTOR = 85, SORT_IN_TEMPDB = ON,STATISTICS_NORECOMPUTE = ON);
ALTER INDEX ALL ON bPRPS REBUILD WITH (FILLFACTOR = 85, SORT_IN_TEMPDB = ON,STATISTICS_NORECOMPUTE = ON);
ALTER INDEX ALL ON bPRSQ REBUILD WITH (FILLFACTOR = 85, SORT_IN_TEMPDB = ON,STATISTICS_NORECOMPUTE = ON);
ALTER INDEX ALL ON bPRAE REBUILD WITH (FILLFACTOR = 85, SORT_IN_TEMPDB = ON,STATISTICS_NORECOMPUTE = ON);
ALTER INDEX ALL ON bPRTH REBUILD WITH (FILLFACTOR = 85, SORT_IN_TEMPDB = ON,STATISTICS_NORECOMPUTE = ON);
ALTER INDEX ALL ON bPRAF REBUILD WITH (FILLFACTOR = 85, SORT_IN_TEMPDB = ON,STATISTICS_NORECOMPUTE = ON);
ALTER INDEX ALL ON bPRCC REBUILD WITH (FILLFACTOR = 85, SORT_IN_TEMPDB = ON,STATISTICS_NORECOMPUTE = ON);
ALTER INDEX ALL ON bPRDE REBUILD WITH (FILLFACTOR = 85, SORT_IN_TEMPDB = ON,STATISTICS_NORECOMPUTE = ON);
ALTER INDEX ALL ON bPRDG REBUILD WITH (FILLFACTOR = 85, SORT_IN_TEMPDB = ON,STATISTICS_NORECOMPUTE = ON);
ALTER INDEX ALL ON bPRDL REBUILD WITH (FILLFACTOR = 85, SORT_IN_TEMPDB = ON,STATISTICS_NORECOMPUTE = ON);
ALTER INDEX ALL ON bPRDT REBUILD WITH (FILLFACTOR = 85, SORT_IN_TEMPDB = ON,STATISTICS_NORECOMPUTE = ON);
ALTER INDEX ALL ON bPREA REBUILD WITH (FILLFACTOR = 85, SORT_IN_TEMPDB = ON,STATISTICS_NORECOMPUTE = ON);
ALTER INDEX ALL ON bPREC REBUILD WITH (FILLFACTOR = 85, SORT_IN_TEMPDB = ON,STATISTICS_NORECOMPUTE = ON);
ALTER INDEX ALL ON bPRED REBUILD WITH (FILLFACTOR = 85, SORT_IN_TEMPDB = ON,STATISTICS_NORECOMPUTE = ON);
ALTER INDEX ALL ON bPREH REBUILD WITH (FILLFACTOR = 85, SORT_IN_TEMPDB = ON,STATISTICS_NORECOMPUTE = ON);
--ALTER INDEX ALL ON bPRRM REBUILD WITH (FILLFACTOR = 85, SORT_IN_TEMPDB = ON,STATISTICS_NORECOMPUTE = ON);
--ALTER INDEX ALL ON bPREL REBUILD WITH (FILLFACTOR = 85, SORT_IN_TEMPDB = ON,STATISTICS_NORECOMPUTE = ON);
--ALTER INDEX ALL ON bJCCD REBUILD WITH (FILLFACTOR = 85, SORT_IN_TEMPDB = ON,STATISTICS_NORECOMPUTE = ON);
--ALTER INDEX ALL ON bPRTB REBUILD WITH (FILLFACTOR = 85, SORT_IN_TEMPDB = ON,STATISTICS_NORECOMPUTE = ON);
--ALTER INDEX ALL ON bPRLH REBUILD WITH (FILLFACTOR = 85, SORT_IN_TEMPDB = ON,STATISTICS_NORECOMPUTE = ON);
ALTER INDEX ALL ON CV_CMS_SOURCE.dbo.DedLiabByEmp REBUILD WITH (FILLFACTOR = 85, SORT_IN_TEMPDB = ON,STATISTICS_NORECOMPUTE = ON);
ALTER INDEX ALL ON CV_CMS_SOURCE.dbo.PRTMUN REBUILD WITH (FILLFACTOR = 85, SORT_IN_TEMPDB = ON,STATISTICS_NORECOMPUTE = ON);
ALTER INDEX ALL ON CV_CMS_SOURCE.dbo.PRTTCH REBUILD WITH (FILLFACTOR = 85, SORT_IN_TEMPDB = ON,STATISTICS_NORECOMPUTE = ON);
ALTER INDEX ALL ON CV_CMS_SOURCE.dbo.PRTHST REBUILD WITH (FILLFACTOR = 85, SORT_IN_TEMPDB = ON,STATISTICS_NORECOMPUTE = ON);
ALTER INDEX ALL ON CV_CMS_SOURCE.dbo.PRTMAJ REBUILD WITH (FILLFACTOR = 85, SORT_IN_TEMPDB = ON,STATISTICS_NORECOMPUTE = ON);
ALTER INDEX ALL ON CV_CMS_SOURCE.dbo.PRTMED REBUILD WITH (FILLFACTOR = 85, SORT_IN_TEMPDB = ON,STATISTICS_NORECOMPUTE = ON);
ALTER INDEX ALL ON CV_CMS_SOURCE.dbo.PRTOTH REBUILD WITH (FILLFACTOR = 85, SORT_IN_TEMPDB = ON,STATISTICS_NORECOMPUTE = ON);
ALTER INDEX ALL ON CV_CMS_SOURCE.dbo.PRTTCE REBUILD WITH (FILLFACTOR = 85, SORT_IN_TEMPDB = ON,STATISTICS_NORECOMPUTE = ON);
ALTER INDEX ALL ON CV_CMS_SOURCE.dbo.PRTTXT REBUILD WITH (FILLFACTOR = 85, SORT_IN_TEMPDB = ON,STATISTICS_NORECOMPUTE = ON);
ALTER INDEX ALL ON dbo.budxrefPRDedLiab REBUILD WITH (FILLFACTOR = 85, SORT_IN_TEMPDB = ON,STATISTICS_NORECOMPUTE = ON);




return @@error

GO
