SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO



create procedure  [dbo].[cvsp_CMS_AP_RebuildIndexes] (@fromco smallint, @toco smallint, 
	@errmsg varchar(1000) output, @rowcount bigint output) 
as



/**
=========================================================================
Copyright © 2009 Viewpoint Construction Software (VCS)
The TSQL code in this procedure may not be reproduced, copied, modified,
or executed without written consent from VCS.
=========================================================================
	Title:		Rebuild JC Indexes
	Created:	
	Created by:	JRE 
	Revisions:	1. none


**/


ALTER INDEX ALL ON bAPTH REBUILD WITH (FILLFACTOR = 85, SORT_IN_TEMPDB = ON,STATISTICS_NORECOMPUTE = ON);
ALTER INDEX ALL ON bAPTL REBUILD WITH (FILLFACTOR = 85, SORT_IN_TEMPDB = ON,STATISTICS_NORECOMPUTE = ON);
ALTER INDEX ALL ON bAPTD REBUILD WITH (FILLFACTOR = 85, SORT_IN_TEMPDB = ON,STATISTICS_NORECOMPUTE = ON);
ALTER INDEX ALL ON bSLHD REBUILD WITH (FILLFACTOR = 85, SORT_IN_TEMPDB = ON,STATISTICS_NORECOMPUTE = ON);
ALTER INDEX ALL ON bSLIT REBUILD WITH (FILLFACTOR = 85, SORT_IN_TEMPDB = ON,STATISTICS_NORECOMPUTE = ON);
ALTER INDEX ALL ON bSLCD REBUILD WITH (FILLFACTOR = 85, SORT_IN_TEMPDB = ON,STATISTICS_NORECOMPUTE = ON);
ALTER INDEX ALL ON bPOHD REBUILD WITH (FILLFACTOR = 85, SORT_IN_TEMPDB = ON,STATISTICS_NORECOMPUTE = ON);
ALTER INDEX ALL ON bPOIT REBUILD WITH (FILLFACTOR = 85, SORT_IN_TEMPDB = ON,STATISTICS_NORECOMPUTE = ON);
ALTER INDEX ALL ON bPOCD REBUILD WITH (FILLFACTOR = 85, SORT_IN_TEMPDB = ON,STATISTICS_NORECOMPUTE = ON);

GO
