IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'MCKINSTRY\ERPProcessTeam')
CREATE LOGIN [MCKINSTRY\ERPProcessTeam] FROM WINDOWS
GO
CREATE USER [MCKINSTRY\ERPProcessTeam] FOR LOGIN [MCKINSTRY\ERPProcessTeam]
GO
