IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'MCKINSTRY\mahendarb')
CREATE LOGIN [MCKINSTRY\mahendarb] FROM WINDOWS
GO
CREATE USER [MCKINSTRY\mahendarb] FOR LOGIN [MCKINSTRY\mahendarb] WITH DEFAULT_SCHEMA=[MCKINSTRY\mahendarb]
GO
REVOKE CONNECT TO [MCKINSTRY\mahendarb]
