IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'MCKINSTRY\ERPReportingTeam')
CREATE LOGIN [MCKINSTRY\ERPReportingTeam] FROM WINDOWS
GO
CREATE USER [MCKINSTRY\ERPReportingTeam] FOR LOGIN [MCKINSTRY\ERPReportingTeam]
GO
GRANT CREATE PROCEDURE TO [MCKINSTRY\ERPReportingTeam]
GRANT EXECUTE TO [MCKINSTRY\ERPReportingTeam] WITH GRANT OPTION
