IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'MCKINSTRY\ERPIntegrationTeam')
CREATE LOGIN [MCKINSTRY\ERPIntegrationTeam] FROM WINDOWS
GO
CREATE USER [MCKINSTRY\ERPIntegrationTeam] FOR LOGIN [MCKINSTRY\ERPIntegrationTeam]
GO
GRANT CREATE FUNCTION TO [MCKINSTRY\ERPIntegrationTeam]
GRANT CREATE PROCEDURE TO [MCKINSTRY\ERPIntegrationTeam]
GRANT CREATE VIEW TO [MCKINSTRY\ERPIntegrationTeam]
GRANT EXECUTE TO [MCKINSTRY\ERPIntegrationTeam] WITH GRANT OPTION
GRANT REFERENCES TO [MCKINSTRY\ERPIntegrationTeam]
GRANT SELECT TO [MCKINSTRY\ERPIntegrationTeam]
