USE Viewpoint
go

SELECT udMCKPONumber, COUNT(*) FROM POHD WHERE POCo<100 AND udMCKPONumber IS NOT NULL GROUP BY udMCKPONumber HAVING COUNT(*) > 1

SELECT * FROM JCCM WHERE JCCo < 100 AND udPOC IS NULL  
