USE [MCK_INTEGRATION]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[RLBProcessNotes](
	[RLBProcessNotesID] [int] IDENTITY(1,1) NOT NULL,
	[ProcessNotes] [nvarchar](512) NOT NULL,
	[Created] [datetime] NULL,
 CONSTRAINT [PK_RLBProcessNotes] PRIMARY KEY CLUSTERED 
(
	[RLBProcessNotesID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[RLBProcessNotes] ADD  CONSTRAINT [DF_RLBProcessNotes_Created]  DEFAULT (getdate()) FOR [Created]
GO


