SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE view [dbo].[HQDXPREH] as select a.* From bHQDXPREH a
GO
GRANT SELECT ON  [dbo].[HQDXPREH] TO [public]
GRANT INSERT ON  [dbo].[HQDXPREH] TO [public]
GRANT DELETE ON  [dbo].[HQDXPREH] TO [public]
GRANT UPDATE ON  [dbo].[HQDXPREH] TO [public]
GO
