CREATE TABLE [dbo].[vDDFIRestore]
(
[Form] [varchar] (30) COLLATE Latin1_General_BIN NOT NULL,
[Seq] [smallint] NOT NULL,
[ViewName] [varchar] (30) COLLATE Latin1_General_BIN NULL,
[ColumnName] [varchar] (500) COLLATE Latin1_General_BIN NULL,
[Description] [varchar] (60) COLLATE Latin1_General_BIN NULL,
[Datatype] [varchar] (30) COLLATE Latin1_General_BIN NULL,
[InputType] [tinyint] NULL,
[InputMask] [varchar] (30) COLLATE Latin1_General_BIN NULL,
[InputLength] [smallint] NULL,
[Prec] [tinyint] NULL,
[ActiveLookup] [char] (1) COLLATE Latin1_General_BIN NULL,
[LookupParams] [varchar] (256) COLLATE Latin1_General_BIN NULL,
[LookupLoadSeq] [tinyint] NULL,
[SetupForm] [varchar] (30) COLLATE Latin1_General_BIN NULL,
[SetupParams] [varchar] (256) COLLATE Latin1_General_BIN NULL,
[StatusText] [varchar] (256) COLLATE Latin1_General_BIN NULL,
[Tab] [tinyint] NULL,
[Req] [char] (1) COLLATE Latin1_General_BIN NOT NULL,
[ValProc] [varchar] (60) COLLATE Latin1_General_BIN NULL,
[ValParams] [varchar] (256) COLLATE Latin1_General_BIN NULL,
[ValLevel] [tinyint] NOT NULL,
[UpdateGroup] [tinyint] NULL,
[ControlType] [tinyint] NOT NULL,
[FieldType] [tinyint] NOT NULL,
[HelpKeyword] [varchar] (60) COLLATE Latin1_General_BIN NULL,
[DescriptionColumn] [varchar] (256) COLLATE Latin1_General_BIN NULL,
[GridCol] [smallint] NULL,
[AutoSeqType] [tinyint] NOT NULL,
[MinValue] [varchar] (20) COLLATE Latin1_General_BIN NULL,
[MaxValue] [varchar] (20) COLLATE Latin1_General_BIN NULL,
[ValExpression] [varchar] (256) COLLATE Latin1_General_BIN NULL,
[ValExpError] [varchar] (256) COLLATE Latin1_General_BIN NULL,
[ComboType] [varchar] (20) COLLATE Latin1_General_BIN NULL,
[ShowGrid] [char] (1) COLLATE Latin1_General_BIN NOT NULL,
[ShowForm] [char] (1) COLLATE Latin1_General_BIN NOT NULL,
[GridColHeading] [varchar] (30) COLLATE Latin1_General_BIN NULL,
[V5xForm] [varchar] (30) COLLATE Latin1_General_BIN NULL,
[V5xSeq] [smallint] NULL,
[HeaderLinkSeq] [smallint] NULL,
[Computed] [char] (1) COLLATE Latin1_General_BIN NOT NULL,
[ShowDesc] [tinyint] NULL,
[ColWidth] [smallint] NULL,
[DescriptionColWidth] [smallint] NULL,
[IsFormFilter] [char] (1) COLLATE Latin1_General_BIN NOT NULL,
[LabelTextID] [int] NULL,
[ColumnTextID] [int] NULL,
[ShowInQueryFilter] [char] (1) COLLATE Latin1_General_BIN NOT NULL,
[ShowInQueryResultSet] [char] (1) COLLATE Latin1_General_BIN NOT NULL,
[QueryColumnName] [varchar] (30) COLLATE Latin1_General_BIN NULL,
[OldHelpID] [int] NULL,
[ExcludeFromRecordCopy] [char] (1) COLLATE Latin1_General_BIN NOT NULL
) ON [PRIMARY]
GO
