CREATE TABLE [dbo].[budMSA]
(
[Seq] [int] NOT NULL,
[Title] [dbo].[bDesc] NULL,
[Vendor] [dbo].[bVendor] NOT NULL,
[VendorGroup] [dbo].[bGroup] NOT NULL,
[UniqueAttchID] [uniqueidentifier] NULL,
[KeyID] [bigint] NOT NULL IDENTITY(1, 1),
[Employment] [dbo].[bYN] NOT NULL CONSTRAINT [DF_udMSA_Employment] DEFAULT ('N'),
[Insurance] [varchar] (30) COLLATE Latin1_General_BIN NULL,
[SpecTandC] [dbo].[bYN] NOT NULL CONSTRAINT [DF_udMSA_SpecTandC] DEFAULT ('N'),
[StateTandC] [dbo].[bYN] NOT NULL CONSTRAINT [DF_udMSA_StateTandC] DEFAULT ('N'),
[ExecDate] [dbo].[bDate] NULL,
[OrigDate] [dbo].[bDate] NULL,
[BalancingYN] [dbo].[bYN] NOT NULL CONSTRAINT [DF_udMSA_BalancingYN] DEFAULT ('N'),
[ConsultingYN] [dbo].[bYN] NOT NULL CONSTRAINT [DF_udMSA_ConsultingYN] DEFAULT ('N'),
[ControlsYN] [dbo].[bYN] NOT NULL CONSTRAINT [DF_udMSA_ControlsYN] DEFAULT ('N'),
[DesignYN] [dbo].[bYN] NOT NULL CONSTRAINT [DF_udMSA_DesignYN] DEFAULT ('N'),
[FacilityServicesYN] [dbo].[bYN] NOT NULL CONSTRAINT [DF_udMSA_FacilityServicesYN] DEFAULT ('N'),
[ProfessionalYN] [dbo].[bYN] NOT NULL CONSTRAINT [DF_udMSA_ProfessionalYN] DEFAULT ('N'),
[NegotiatedModYN] [dbo].[bYN] NOT NULL CONSTRAINT [DF_udMSA_NegotiatedModYN] DEFAULT ('N'),
[LightingYN] [dbo].[bYN] NOT NULL CONSTRAINT [DF_udMSA_LightingYN] DEFAULT ('N'),
[RoofingYN] [dbo].[bYN] NOT NULL CONSTRAINT [DF_udMSA_RoofingYN] DEFAULT ('N'),
[SafetyYN] [dbo].[bYN] NOT NULL CONSTRAINT [DF_udMSA_SafetyYN] DEFAULT ('N'),
[EEOYN] [dbo].[bYN] NOT NULL CONSTRAINT [DF_udMSA_EEOYN] DEFAULT ('N'),
[InvoicingYN] [dbo].[bYN] NOT NULL CONSTRAINT [DF_udMSA_InvoicingYN] DEFAULT ('N'),
[GenTerms] [varchar] (30) COLLATE Latin1_General_BIN NULL,
[CommissioningYN] [dbo].[bYN] NOT NULL CONSTRAINT [DF_udMSA_CommissioningYN] DEFAULT ('N'),
[ProServSoftYN] [dbo].[bYN] NOT NULL CONSTRAINT [DF_udMSA_ProServSoftYN] DEFAULT ('N'),
[SupportMaintSoftYN] [dbo].[bYN] NOT NULL CONSTRAINT [DF_udMSA_SupportMaintSoftYN] DEFAULT ('N'),
[LicenseSoftYN] [dbo].[bYN] NOT NULL CONSTRAINT [DF_udMSA_LicenseSoftYN] DEFAULT ('N'),
[HostingSoftYN] [dbo].[bYN] NOT NULL CONSTRAINT [DF_udMSA_HostingSoftYN] DEFAULT ('N'),
[PayPerf-Bond] [dbo].[bYN] NOT NULL CONSTRAINT [DF_udMSA_PayPerf-Bond] DEFAULT ('N'),
[CostPlusYN] [dbo].[bYN] NOT NULL CONSTRAINT [DF_udMSA_CostPlusYN] DEFAULT ('N'),
[FederalYN] [dbo].[bYN] NOT NULL CONSTRAINT [DF_udMSA_FederalYN] DEFAULT ('N'),
[AddendumYN] [dbo].[bYN] NOT NULL CONSTRAINT [DF_udMSA_AddendumYN] DEFAULT ('N')
) ON [PRIMARY]
CREATE UNIQUE CLUSTERED INDEX [biudMSA] ON [dbo].[budMSA] ([VendorGroup], [Vendor], [Seq]) ON [PRIMARY]

GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER dbo.vtbudMSA_Audit_Delete ON dbo.budMSA
 AFTER DELETE
 NOT FOR REPLICATION AS
 SET NOCOUNT ON 
 -- generated by vspHQCreateAuditTriggers on Oct 19 2013  2:51PM

 BEGIN TRY 

   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(deleted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(deleted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(deleted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'D' , NULL , NULL , NULL , GETDATE() , SUSER_SNAME()
	FROM deleted

 END TRY 
 BEGIN CATCH 
   DECLARE	@ErrorMessage	NVARCHAR(4000), 
				@ErrorSeverity	INT; 

   SELECT	@ErrorMessage = 'Error '+ ISNULL(ERROR_MESSAGE(),'') +' in [dbo].[dbo.vtbudMSA_Audit_Delete] trigger', 
				@ErrorSeverity = ERROR_SEVERITY(); 

   RAISERROR(@ErrorMessage, @ErrorSeverity, 1 ) 
 END CATCH 
GO
EXEC sp_settriggerorder N'[dbo].[vtbudMSA_Audit_Delete]', 'last', 'delete', null
GO

SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER dbo.vtbudMSA_Audit_Insert ON dbo.budMSA
 AFTER INSERT
 NOT FOR REPLICATION AS
 SET NOCOUNT ON 
 -- generated by vspHQCreateAuditTriggers on Oct 19 2013  2:51PM

 BEGIN TRY 

   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'A' , NULL , NULL , NULL , GETDATE() , SUSER_SNAME()
	FROM inserted

 END TRY 
 BEGIN CATCH 
   DECLARE	@ErrorMessage	NVARCHAR(4000), 
				@ErrorSeverity	INT; 

   SELECT	@ErrorMessage = 'Error '+ ISNULL(ERROR_MESSAGE(),'') +' in [dbo].[dbo.vtbudMSA_Audit_Insert] trigger', 
				@ErrorSeverity = ERROR_SEVERITY(); 

   RAISERROR(@ErrorMessage, @ErrorSeverity, 1 ) 
 END CATCH 
GO
EXEC sp_settriggerorder N'[dbo].[vtbudMSA_Audit_Insert]', 'last', 'insert', null
GO

SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER dbo.vtbudMSA_Audit_Update ON dbo.budMSA
 AFTER UPDATE 
 NOT FOR REPLICATION AS 
 SET NOCOUNT ON 
 -- generated by vspHQCreateAuditTriggers on Oct 19 2013  2:51PM

 BEGIN TRY 

 IF UPDATE([Seq])
 BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[Seq]' ,  CONVERT(VARCHAR(MAX), deleted.[Seq]) ,  CONVERT(VARCHAR(MAX), inserted.[Seq]) , GETDATE() , SUSER_SNAME()
		FROM inserted
			INNER JOIN deleted
         ON  inserted.[KeyID] = deleted.[KeyID] 
         AND ((inserted.[Seq] <> deleted.[Seq]) OR (inserted.[Seq] IS NULL AND deleted.[Seq] IS NOT NULL) OR (inserted.[Seq] IS NOT NULL AND deleted.[Seq] IS NULL))



 END 

 IF UPDATE([Title])
 BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[Title]' ,  CONVERT(VARCHAR(MAX), deleted.[Title]) ,  CONVERT(VARCHAR(MAX), inserted.[Title]) , GETDATE() , SUSER_SNAME()
		FROM inserted
			INNER JOIN deleted
         ON  inserted.[KeyID] = deleted.[KeyID] 
         AND ((inserted.[Title] <> deleted.[Title]) OR (inserted.[Title] IS NULL AND deleted.[Title] IS NOT NULL) OR (inserted.[Title] IS NOT NULL AND deleted.[Title] IS NULL))



 END 

 IF UPDATE([Vendor])
 BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[Vendor]' ,  CONVERT(VARCHAR(MAX), deleted.[Vendor]) ,  CONVERT(VARCHAR(MAX), inserted.[Vendor]) , GETDATE() , SUSER_SNAME()
		FROM inserted
			INNER JOIN deleted
         ON  inserted.[KeyID] = deleted.[KeyID] 
         AND ((inserted.[Vendor] <> deleted.[Vendor]) OR (inserted.[Vendor] IS NULL AND deleted.[Vendor] IS NOT NULL) OR (inserted.[Vendor] IS NOT NULL AND deleted.[Vendor] IS NULL))



 END 

 IF UPDATE([VendorGroup])
 BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[VendorGroup]' ,  CONVERT(VARCHAR(MAX), deleted.[VendorGroup]) ,  CONVERT(VARCHAR(MAX), inserted.[VendorGroup]) , GETDATE() , SUSER_SNAME()
		FROM inserted
			INNER JOIN deleted
         ON  inserted.[KeyID] = deleted.[KeyID] 
         AND ((inserted.[VendorGroup] <> deleted.[VendorGroup]) OR (inserted.[VendorGroup] IS NULL AND deleted.[VendorGroup] IS NOT NULL) OR (inserted.[VendorGroup] IS NOT NULL AND deleted.[VendorGroup] IS NULL))



 END 

 IF UPDATE([UniqueAttchID])
 BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[UniqueAttchID]' ,  CONVERT(VARCHAR(MAX), deleted.[UniqueAttchID]) ,  CONVERT(VARCHAR(MAX), inserted.[UniqueAttchID]) , GETDATE() , SUSER_SNAME()
		FROM inserted
			INNER JOIN deleted
         ON  inserted.[KeyID] = deleted.[KeyID] 
         AND ((inserted.[UniqueAttchID] <> deleted.[UniqueAttchID]) OR (inserted.[UniqueAttchID] IS NULL AND deleted.[UniqueAttchID] IS NOT NULL) OR (inserted.[UniqueAttchID] IS NOT NULL AND deleted.[UniqueAttchID] IS NULL))



 END 

 IF UPDATE([Employment])
 BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[Employment]' ,  CONVERT(VARCHAR(MAX), deleted.[Employment]) ,  CONVERT(VARCHAR(MAX), inserted.[Employment]) , GETDATE() , SUSER_SNAME()
		FROM inserted
			INNER JOIN deleted
         ON  inserted.[KeyID] = deleted.[KeyID] 
         AND ((inserted.[Employment] <> deleted.[Employment]) OR (inserted.[Employment] IS NULL AND deleted.[Employment] IS NOT NULL) OR (inserted.[Employment] IS NOT NULL AND deleted.[Employment] IS NULL))



 END 

 IF UPDATE([Insurance])
 BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[Insurance]' ,  CONVERT(VARCHAR(MAX), deleted.[Insurance]) ,  CONVERT(VARCHAR(MAX), inserted.[Insurance]) , GETDATE() , SUSER_SNAME()
		FROM inserted
			INNER JOIN deleted
         ON  inserted.[KeyID] = deleted.[KeyID] 
         AND ((inserted.[Insurance] <> deleted.[Insurance]) OR (inserted.[Insurance] IS NULL AND deleted.[Insurance] IS NOT NULL) OR (inserted.[Insurance] IS NOT NULL AND deleted.[Insurance] IS NULL))



 END 

 IF UPDATE([SpecTandC])
 BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[SpecTandC]' ,  CONVERT(VARCHAR(MAX), deleted.[SpecTandC]) ,  CONVERT(VARCHAR(MAX), inserted.[SpecTandC]) , GETDATE() , SUSER_SNAME()
		FROM inserted
			INNER JOIN deleted
         ON  inserted.[KeyID] = deleted.[KeyID] 
         AND ((inserted.[SpecTandC] <> deleted.[SpecTandC]) OR (inserted.[SpecTandC] IS NULL AND deleted.[SpecTandC] IS NOT NULL) OR (inserted.[SpecTandC] IS NOT NULL AND deleted.[SpecTandC] IS NULL))



 END 

 IF UPDATE([StateTandC])
 BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[StateTandC]' ,  CONVERT(VARCHAR(MAX), deleted.[StateTandC]) ,  CONVERT(VARCHAR(MAX), inserted.[StateTandC]) , GETDATE() , SUSER_SNAME()
		FROM inserted
			INNER JOIN deleted
         ON  inserted.[KeyID] = deleted.[KeyID] 
         AND ((inserted.[StateTandC] <> deleted.[StateTandC]) OR (inserted.[StateTandC] IS NULL AND deleted.[StateTandC] IS NOT NULL) OR (inserted.[StateTandC] IS NOT NULL AND deleted.[StateTandC] IS NULL))



 END 

 IF UPDATE([ExecDate])
 BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[ExecDate]' ,  CONVERT(VARCHAR(MAX), deleted.[ExecDate]) ,  CONVERT(VARCHAR(MAX), inserted.[ExecDate]) , GETDATE() , SUSER_SNAME()
		FROM inserted
			INNER JOIN deleted
         ON  inserted.[KeyID] = deleted.[KeyID] 
         AND ((inserted.[ExecDate] <> deleted.[ExecDate]) OR (inserted.[ExecDate] IS NULL AND deleted.[ExecDate] IS NOT NULL) OR (inserted.[ExecDate] IS NOT NULL AND deleted.[ExecDate] IS NULL))



 END 

 IF UPDATE([OrigDate])
 BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[OrigDate]' ,  CONVERT(VARCHAR(MAX), deleted.[OrigDate]) ,  CONVERT(VARCHAR(MAX), inserted.[OrigDate]) , GETDATE() , SUSER_SNAME()
		FROM inserted
			INNER JOIN deleted
         ON  inserted.[KeyID] = deleted.[KeyID] 
         AND ((inserted.[OrigDate] <> deleted.[OrigDate]) OR (inserted.[OrigDate] IS NULL AND deleted.[OrigDate] IS NOT NULL) OR (inserted.[OrigDate] IS NOT NULL AND deleted.[OrigDate] IS NULL))



 END 

 IF UPDATE([BalancingYN])
 BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[BalancingYN]' ,  CONVERT(VARCHAR(MAX), deleted.[BalancingYN]) ,  CONVERT(VARCHAR(MAX), inserted.[BalancingYN]) , GETDATE() , SUSER_SNAME()
		FROM inserted
			INNER JOIN deleted
         ON  inserted.[KeyID] = deleted.[KeyID] 
         AND ((inserted.[BalancingYN] <> deleted.[BalancingYN]) OR (inserted.[BalancingYN] IS NULL AND deleted.[BalancingYN] IS NOT NULL) OR (inserted.[BalancingYN] IS NOT NULL AND deleted.[BalancingYN] IS NULL))



 END 

 IF UPDATE([ConsultingYN])
 BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[ConsultingYN]' ,  CONVERT(VARCHAR(MAX), deleted.[ConsultingYN]) ,  CONVERT(VARCHAR(MAX), inserted.[ConsultingYN]) , GETDATE() , SUSER_SNAME()
		FROM inserted
			INNER JOIN deleted
         ON  inserted.[KeyID] = deleted.[KeyID] 
         AND ((inserted.[ConsultingYN] <> deleted.[ConsultingYN]) OR (inserted.[ConsultingYN] IS NULL AND deleted.[ConsultingYN] IS NOT NULL) OR (inserted.[ConsultingYN] IS NOT NULL AND deleted.[ConsultingYN] IS NULL))



 END 

 IF UPDATE([ControlsYN])
 BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[ControlsYN]' ,  CONVERT(VARCHAR(MAX), deleted.[ControlsYN]) ,  CONVERT(VARCHAR(MAX), inserted.[ControlsYN]) , GETDATE() , SUSER_SNAME()
		FROM inserted
			INNER JOIN deleted
         ON  inserted.[KeyID] = deleted.[KeyID] 
         AND ((inserted.[ControlsYN] <> deleted.[ControlsYN]) OR (inserted.[ControlsYN] IS NULL AND deleted.[ControlsYN] IS NOT NULL) OR (inserted.[ControlsYN] IS NOT NULL AND deleted.[ControlsYN] IS NULL))



 END 

 IF UPDATE([DesignYN])
 BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[DesignYN]' ,  CONVERT(VARCHAR(MAX), deleted.[DesignYN]) ,  CONVERT(VARCHAR(MAX), inserted.[DesignYN]) , GETDATE() , SUSER_SNAME()
		FROM inserted
			INNER JOIN deleted
         ON  inserted.[KeyID] = deleted.[KeyID] 
         AND ((inserted.[DesignYN] <> deleted.[DesignYN]) OR (inserted.[DesignYN] IS NULL AND deleted.[DesignYN] IS NOT NULL) OR (inserted.[DesignYN] IS NOT NULL AND deleted.[DesignYN] IS NULL))



 END 

 IF UPDATE([FacilityServicesYN])
 BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[FacilityServicesYN]' ,  CONVERT(VARCHAR(MAX), deleted.[FacilityServicesYN]) ,  CONVERT(VARCHAR(MAX), inserted.[FacilityServicesYN]) , GETDATE() , SUSER_SNAME()
		FROM inserted
			INNER JOIN deleted
         ON  inserted.[KeyID] = deleted.[KeyID] 
         AND ((inserted.[FacilityServicesYN] <> deleted.[FacilityServicesYN]) OR (inserted.[FacilityServicesYN] IS NULL AND deleted.[FacilityServicesYN] IS NOT NULL) OR (inserted.[FacilityServicesYN] IS NOT NULL AND deleted.[FacilityServicesYN] IS NULL))



 END 

 IF UPDATE([ProfessionalYN])
 BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[ProfessionalYN]' ,  CONVERT(VARCHAR(MAX), deleted.[ProfessionalYN]) ,  CONVERT(VARCHAR(MAX), inserted.[ProfessionalYN]) , GETDATE() , SUSER_SNAME()
		FROM inserted
			INNER JOIN deleted
         ON  inserted.[KeyID] = deleted.[KeyID] 
         AND ((inserted.[ProfessionalYN] <> deleted.[ProfessionalYN]) OR (inserted.[ProfessionalYN] IS NULL AND deleted.[ProfessionalYN] IS NOT NULL) OR (inserted.[ProfessionalYN] IS NOT NULL AND deleted.[ProfessionalYN] IS NULL))



 END 

 IF UPDATE([NegotiatedModYN])
 BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[NegotiatedModYN]' ,  CONVERT(VARCHAR(MAX), deleted.[NegotiatedModYN]) ,  CONVERT(VARCHAR(MAX), inserted.[NegotiatedModYN]) , GETDATE() , SUSER_SNAME()
		FROM inserted
			INNER JOIN deleted
         ON  inserted.[KeyID] = deleted.[KeyID] 
         AND ((inserted.[NegotiatedModYN] <> deleted.[NegotiatedModYN]) OR (inserted.[NegotiatedModYN] IS NULL AND deleted.[NegotiatedModYN] IS NOT NULL) OR (inserted.[NegotiatedModYN] IS NOT NULL AND deleted.[NegotiatedModYN] IS NULL))



 END 

 IF UPDATE([LightingYN])
 BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[LightingYN]' ,  CONVERT(VARCHAR(MAX), deleted.[LightingYN]) ,  CONVERT(VARCHAR(MAX), inserted.[LightingYN]) , GETDATE() , SUSER_SNAME()
		FROM inserted
			INNER JOIN deleted
         ON  inserted.[KeyID] = deleted.[KeyID] 
         AND ((inserted.[LightingYN] <> deleted.[LightingYN]) OR (inserted.[LightingYN] IS NULL AND deleted.[LightingYN] IS NOT NULL) OR (inserted.[LightingYN] IS NOT NULL AND deleted.[LightingYN] IS NULL))



 END 

 IF UPDATE([RoofingYN])
 BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[RoofingYN]' ,  CONVERT(VARCHAR(MAX), deleted.[RoofingYN]) ,  CONVERT(VARCHAR(MAX), inserted.[RoofingYN]) , GETDATE() , SUSER_SNAME()
		FROM inserted
			INNER JOIN deleted
         ON  inserted.[KeyID] = deleted.[KeyID] 
         AND ((inserted.[RoofingYN] <> deleted.[RoofingYN]) OR (inserted.[RoofingYN] IS NULL AND deleted.[RoofingYN] IS NOT NULL) OR (inserted.[RoofingYN] IS NOT NULL AND deleted.[RoofingYN] IS NULL))



 END 

 IF UPDATE([SafetyYN])
 BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[SafetyYN]' ,  CONVERT(VARCHAR(MAX), deleted.[SafetyYN]) ,  CONVERT(VARCHAR(MAX), inserted.[SafetyYN]) , GETDATE() , SUSER_SNAME()
		FROM inserted
			INNER JOIN deleted
         ON  inserted.[KeyID] = deleted.[KeyID] 
         AND ((inserted.[SafetyYN] <> deleted.[SafetyYN]) OR (inserted.[SafetyYN] IS NULL AND deleted.[SafetyYN] IS NOT NULL) OR (inserted.[SafetyYN] IS NOT NULL AND deleted.[SafetyYN] IS NULL))



 END 

 IF UPDATE([EEOYN])
 BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[EEOYN]' ,  CONVERT(VARCHAR(MAX), deleted.[EEOYN]) ,  CONVERT(VARCHAR(MAX), inserted.[EEOYN]) , GETDATE() , SUSER_SNAME()
		FROM inserted
			INNER JOIN deleted
         ON  inserted.[KeyID] = deleted.[KeyID] 
         AND ((inserted.[EEOYN] <> deleted.[EEOYN]) OR (inserted.[EEOYN] IS NULL AND deleted.[EEOYN] IS NOT NULL) OR (inserted.[EEOYN] IS NOT NULL AND deleted.[EEOYN] IS NULL))



 END 

 IF UPDATE([InvoicingYN])
 BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[InvoicingYN]' ,  CONVERT(VARCHAR(MAX), deleted.[InvoicingYN]) ,  CONVERT(VARCHAR(MAX), inserted.[InvoicingYN]) , GETDATE() , SUSER_SNAME()
		FROM inserted
			INNER JOIN deleted
         ON  inserted.[KeyID] = deleted.[KeyID] 
         AND ((inserted.[InvoicingYN] <> deleted.[InvoicingYN]) OR (inserted.[InvoicingYN] IS NULL AND deleted.[InvoicingYN] IS NOT NULL) OR (inserted.[InvoicingYN] IS NOT NULL AND deleted.[InvoicingYN] IS NULL))



 END 

 IF UPDATE([GenTerms])
 BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[GenTerms]' ,  CONVERT(VARCHAR(MAX), deleted.[GenTerms]) ,  CONVERT(VARCHAR(MAX), inserted.[GenTerms]) , GETDATE() , SUSER_SNAME()
		FROM inserted
			INNER JOIN deleted
         ON  inserted.[KeyID] = deleted.[KeyID] 
         AND ((inserted.[GenTerms] <> deleted.[GenTerms]) OR (inserted.[GenTerms] IS NULL AND deleted.[GenTerms] IS NOT NULL) OR (inserted.[GenTerms] IS NOT NULL AND deleted.[GenTerms] IS NULL))



 END 

 IF UPDATE([CommissioningYN])
 BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[CommissioningYN]' ,  CONVERT(VARCHAR(MAX), deleted.[CommissioningYN]) ,  CONVERT(VARCHAR(MAX), inserted.[CommissioningYN]) , GETDATE() , SUSER_SNAME()
		FROM inserted
			INNER JOIN deleted
         ON  inserted.[KeyID] = deleted.[KeyID] 
         AND ((inserted.[CommissioningYN] <> deleted.[CommissioningYN]) OR (inserted.[CommissioningYN] IS NULL AND deleted.[CommissioningYN] IS NOT NULL) OR (inserted.[CommissioningYN] IS NOT NULL AND deleted.[CommissioningYN] IS NULL))



 END 

 IF UPDATE([ProServSoftYN])
 BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[ProServSoftYN]' ,  CONVERT(VARCHAR(MAX), deleted.[ProServSoftYN]) ,  CONVERT(VARCHAR(MAX), inserted.[ProServSoftYN]) , GETDATE() , SUSER_SNAME()
		FROM inserted
			INNER JOIN deleted
         ON  inserted.[KeyID] = deleted.[KeyID] 
         AND ((inserted.[ProServSoftYN] <> deleted.[ProServSoftYN]) OR (inserted.[ProServSoftYN] IS NULL AND deleted.[ProServSoftYN] IS NOT NULL) OR (inserted.[ProServSoftYN] IS NOT NULL AND deleted.[ProServSoftYN] IS NULL))



 END 

 IF UPDATE([SupportMaintSoftYN])
 BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[SupportMaintSoftYN]' ,  CONVERT(VARCHAR(MAX), deleted.[SupportMaintSoftYN]) ,  CONVERT(VARCHAR(MAX), inserted.[SupportMaintSoftYN]) , GETDATE() , SUSER_SNAME()
		FROM inserted
			INNER JOIN deleted
         ON  inserted.[KeyID] = deleted.[KeyID] 
         AND ((inserted.[SupportMaintSoftYN] <> deleted.[SupportMaintSoftYN]) OR (inserted.[SupportMaintSoftYN] IS NULL AND deleted.[SupportMaintSoftYN] IS NOT NULL) OR (inserted.[SupportMaintSoftYN] IS NOT NULL AND deleted.[SupportMaintSoftYN] IS NULL))



 END 

 IF UPDATE([LicenseSoftYN])
 BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[LicenseSoftYN]' ,  CONVERT(VARCHAR(MAX), deleted.[LicenseSoftYN]) ,  CONVERT(VARCHAR(MAX), inserted.[LicenseSoftYN]) , GETDATE() , SUSER_SNAME()
		FROM inserted
			INNER JOIN deleted
         ON  inserted.[KeyID] = deleted.[KeyID] 
         AND ((inserted.[LicenseSoftYN] <> deleted.[LicenseSoftYN]) OR (inserted.[LicenseSoftYN] IS NULL AND deleted.[LicenseSoftYN] IS NOT NULL) OR (inserted.[LicenseSoftYN] IS NOT NULL AND deleted.[LicenseSoftYN] IS NULL))



 END 

 IF UPDATE([HostingSoftYN])
 BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[HostingSoftYN]' ,  CONVERT(VARCHAR(MAX), deleted.[HostingSoftYN]) ,  CONVERT(VARCHAR(MAX), inserted.[HostingSoftYN]) , GETDATE() , SUSER_SNAME()
		FROM inserted
			INNER JOIN deleted
         ON  inserted.[KeyID] = deleted.[KeyID] 
         AND ((inserted.[HostingSoftYN] <> deleted.[HostingSoftYN]) OR (inserted.[HostingSoftYN] IS NULL AND deleted.[HostingSoftYN] IS NOT NULL) OR (inserted.[HostingSoftYN] IS NOT NULL AND deleted.[HostingSoftYN] IS NULL))



 END 

 IF UPDATE([PayPerf-Bond])
 BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[PayPerf-Bond]' ,  CONVERT(VARCHAR(MAX), deleted.[PayPerf-Bond]) ,  CONVERT(VARCHAR(MAX), inserted.[PayPerf-Bond]) , GETDATE() , SUSER_SNAME()
		FROM inserted
			INNER JOIN deleted
         ON  inserted.[KeyID] = deleted.[KeyID] 
         AND ((inserted.[PayPerf-Bond] <> deleted.[PayPerf-Bond]) OR (inserted.[PayPerf-Bond] IS NULL AND deleted.[PayPerf-Bond] IS NOT NULL) OR (inserted.[PayPerf-Bond] IS NOT NULL AND deleted.[PayPerf-Bond] IS NULL))



 END 

 IF UPDATE([CostPlusYN])
 BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[CostPlusYN]' ,  CONVERT(VARCHAR(MAX), deleted.[CostPlusYN]) ,  CONVERT(VARCHAR(MAX), inserted.[CostPlusYN]) , GETDATE() , SUSER_SNAME()
		FROM inserted
			INNER JOIN deleted
         ON  inserted.[KeyID] = deleted.[KeyID] 
         AND ((inserted.[CostPlusYN] <> deleted.[CostPlusYN]) OR (inserted.[CostPlusYN] IS NULL AND deleted.[CostPlusYN] IS NOT NULL) OR (inserted.[CostPlusYN] IS NOT NULL AND deleted.[CostPlusYN] IS NULL))



 END 

 IF UPDATE([FederalYN])
 BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[FederalYN]' ,  CONVERT(VARCHAR(MAX), deleted.[FederalYN]) ,  CONVERT(VARCHAR(MAX), inserted.[FederalYN]) , GETDATE() , SUSER_SNAME()
		FROM inserted
			INNER JOIN deleted
         ON  inserted.[KeyID] = deleted.[KeyID] 
         AND ((inserted.[FederalYN] <> deleted.[FederalYN]) OR (inserted.[FederalYN] IS NULL AND deleted.[FederalYN] IS NOT NULL) OR (inserted.[FederalYN] IS NOT NULL AND deleted.[FederalYN] IS NULL))



 END 

 IF UPDATE([AddendumYN])
 BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[AddendumYN]' ,  CONVERT(VARCHAR(MAX), deleted.[AddendumYN]) ,  CONVERT(VARCHAR(MAX), inserted.[AddendumYN]) , GETDATE() , SUSER_SNAME()
		FROM inserted
			INNER JOIN deleted
         ON  inserted.[KeyID] = deleted.[KeyID] 
         AND ((inserted.[AddendumYN] <> deleted.[AddendumYN]) OR (inserted.[AddendumYN] IS NULL AND deleted.[AddendumYN] IS NOT NULL) OR (inserted.[AddendumYN] IS NOT NULL AND deleted.[AddendumYN] IS NULL))



 END 

 END TRY 
 BEGIN CATCH 
   DECLARE	@ErrorMessage	NVARCHAR(4000), 
				@ErrorSeverity	INT; 

   SELECT	@ErrorMessage = 'Error '+ ISNULL(ERROR_MESSAGE(),'') +' in [dbo].[dbo.vtbudMSA_Audit_Update] trigger', 
				@ErrorSeverity = ERROR_SEVERITY(); 

   RAISERROR(@ErrorMessage, @ErrorSeverity, 1 ) 
 END CATCH 
GO
EXEC sp_settriggerorder N'[dbo].[vtbudMSA_Audit_Update]', 'last', 'update', null
GO


SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
--CREATE TRIGGER dbo.vtbudMSA_Audit_Delete ON dbo.budMSA
-- AFTER DELETE
-- NOT FOR REPLICATION AS
-- SET NOCOUNT ON 
-- -- generated by vspHQCreateAuditTriggers on Oct 14 2013  4:59PM

-- BEGIN TRY 

--   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

--   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(deleted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(deleted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(deleted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'D' , NULL , NULL , NULL , GETDATE() , SUSER_SNAME()
--	FROM deleted

-- END TRY 
-- BEGIN CATCH 
--   DECLARE	@ErrorMessage	NVARCHAR(4000), 
--				@ErrorSeverity	INT; 

--   SELECT	@ErrorMessage = 'Error '+ ISNULL(ERROR_MESSAGE(),'') +' in [dbo].[dbo.vtbudMSA_Audit_Delete] trigger', 
--				@ErrorSeverity = ERROR_SEVERITY(); 

--   RAISERROR(@ErrorMessage, @ErrorSeverity, 1 ) 
-- END CATCH 
--GO
--EXEC sp_settriggerorder N'[dbo].[vtbudMSA_Audit_Delete]', 'last', 'delete', null
--GO

--EXEC sp_settriggerorder N'[dbo].[vtbudMSA_Audit_Delete]', 'last', 'delete', null
--GO

--EXEC sp_settriggerorder N'[dbo].[vtbudMSA_Audit_Delete]', 'last', 'delete', null
--GO

--SET QUOTED_IDENTIFIER ON
--GO
--SET ANSI_NULLS ON
--GO
--CREATE TRIGGER dbo.vtbudMSA_Audit_Insert ON dbo.budMSA
-- AFTER INSERT
-- NOT FOR REPLICATION AS
-- SET NOCOUNT ON 
-- -- generated by vspHQCreateAuditTriggers on Oct 14 2013  4:59PM

-- BEGIN TRY 

--   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

--   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'A' , NULL , NULL , NULL , GETDATE() , SUSER_SNAME()
--	FROM inserted

-- END TRY 
-- BEGIN CATCH 
--   DECLARE	@ErrorMessage	NVARCHAR(4000), 
--				@ErrorSeverity	INT; 

--   SELECT	@ErrorMessage = 'Error '+ ISNULL(ERROR_MESSAGE(),'') +' in [dbo].[dbo.vtbudMSA_Audit_Insert] trigger', 
--				@ErrorSeverity = ERROR_SEVERITY(); 

--   RAISERROR(@ErrorMessage, @ErrorSeverity, 1 ) 
-- END CATCH 
--GO
--EXEC sp_settriggerorder N'[dbo].[vtbudMSA_Audit_Insert]', 'last', 'insert', null
--GO

--EXEC sp_settriggerorder N'[dbo].[vtbudMSA_Audit_Insert]', 'last', 'insert', null
--GO

--EXEC sp_settriggerorder N'[dbo].[vtbudMSA_Audit_Insert]', 'last', 'insert', null
--GO

--SET QUOTED_IDENTIFIER ON
--GO
--SET ANSI_NULLS ON
--GO
--CREATE TRIGGER dbo.vtbudMSA_Audit_Update ON dbo.budMSA
-- AFTER UPDATE 
-- NOT FOR REPLICATION AS 
-- SET NOCOUNT ON 
-- -- generated by vspHQCreateAuditTriggers on Oct 14 2013  4:59PM

-- BEGIN TRY 

-- IF UPDATE([Seq])
-- BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

--   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[Seq]' ,  CONVERT(VARCHAR(MAX), deleted.[Seq]) ,  CONVERT(VARCHAR(MAX), inserted.[Seq]) , GETDATE() , SUSER_SNAME()
--		FROM inserted
--			INNER JOIN deleted
--         ON  inserted.[KeyID] = deleted.[KeyID] 
--         AND ((inserted.[Seq] <> deleted.[Seq]) OR (inserted.[Seq] IS NULL AND deleted.[Seq] IS NOT NULL) OR (inserted.[Seq] IS NOT NULL AND deleted.[Seq] IS NULL))



-- END 

-- IF UPDATE([Title])
-- BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

--   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[Title]' ,  CONVERT(VARCHAR(MAX), deleted.[Title]) ,  CONVERT(VARCHAR(MAX), inserted.[Title]) , GETDATE() , SUSER_SNAME()
--		FROM inserted
--			INNER JOIN deleted
--         ON  inserted.[KeyID] = deleted.[KeyID] 
--         AND ((inserted.[Title] <> deleted.[Title]) OR (inserted.[Title] IS NULL AND deleted.[Title] IS NOT NULL) OR (inserted.[Title] IS NOT NULL AND deleted.[Title] IS NULL))



-- END 

-- IF UPDATE([Vendor])
-- BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

--   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[Vendor]' ,  CONVERT(VARCHAR(MAX), deleted.[Vendor]) ,  CONVERT(VARCHAR(MAX), inserted.[Vendor]) , GETDATE() , SUSER_SNAME()
--		FROM inserted
--			INNER JOIN deleted
--         ON  inserted.[KeyID] = deleted.[KeyID] 
--         AND ((inserted.[Vendor] <> deleted.[Vendor]) OR (inserted.[Vendor] IS NULL AND deleted.[Vendor] IS NOT NULL) OR (inserted.[Vendor] IS NOT NULL AND deleted.[Vendor] IS NULL))



-- END 

-- IF UPDATE([VendorGroup])
-- BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

--   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[VendorGroup]' ,  CONVERT(VARCHAR(MAX), deleted.[VendorGroup]) ,  CONVERT(VARCHAR(MAX), inserted.[VendorGroup]) , GETDATE() , SUSER_SNAME()
--		FROM inserted
--			INNER JOIN deleted
--         ON  inserted.[KeyID] = deleted.[KeyID] 
--         AND ((inserted.[VendorGroup] <> deleted.[VendorGroup]) OR (inserted.[VendorGroup] IS NULL AND deleted.[VendorGroup] IS NOT NULL) OR (inserted.[VendorGroup] IS NOT NULL AND deleted.[VendorGroup] IS NULL))



-- END 

-- IF UPDATE([UniqueAttchID])
-- BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

--   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[UniqueAttchID]' ,  CONVERT(VARCHAR(MAX), deleted.[UniqueAttchID]) ,  CONVERT(VARCHAR(MAX), inserted.[UniqueAttchID]) , GETDATE() , SUSER_SNAME()
--		FROM inserted
--			INNER JOIN deleted
--         ON  inserted.[KeyID] = deleted.[KeyID] 
--         AND ((inserted.[UniqueAttchID] <> deleted.[UniqueAttchID]) OR (inserted.[UniqueAttchID] IS NULL AND deleted.[UniqueAttchID] IS NOT NULL) OR (inserted.[UniqueAttchID] IS NOT NULL AND deleted.[UniqueAttchID] IS NULL))



-- END 

-- IF UPDATE([Employment])
-- BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

--   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[Employment]' ,  CONVERT(VARCHAR(MAX), deleted.[Employment]) ,  CONVERT(VARCHAR(MAX), inserted.[Employment]) , GETDATE() , SUSER_SNAME()
--		FROM inserted
--			INNER JOIN deleted
--         ON  inserted.[KeyID] = deleted.[KeyID] 
--         AND ((inserted.[Employment] <> deleted.[Employment]) OR (inserted.[Employment] IS NULL AND deleted.[Employment] IS NOT NULL) OR (inserted.[Employment] IS NOT NULL AND deleted.[Employment] IS NULL))



-- END 

-- IF UPDATE([Insurance])
-- BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

--   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[Insurance]' ,  CONVERT(VARCHAR(MAX), deleted.[Insurance]) ,  CONVERT(VARCHAR(MAX), inserted.[Insurance]) , GETDATE() , SUSER_SNAME()
--		FROM inserted
--			INNER JOIN deleted
--         ON  inserted.[KeyID] = deleted.[KeyID] 
--         AND ((inserted.[Insurance] <> deleted.[Insurance]) OR (inserted.[Insurance] IS NULL AND deleted.[Insurance] IS NOT NULL) OR (inserted.[Insurance] IS NOT NULL AND deleted.[Insurance] IS NULL))



-- END 

-- IF UPDATE([InvAndPymt])
-- BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

--   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[InvAndPymt]' ,  CONVERT(VARCHAR(MAX), deleted.[InvAndPymt]) ,  CONVERT(VARCHAR(MAX), inserted.[InvAndPymt]) , GETDATE() , SUSER_SNAME()
--		FROM inserted
--			INNER JOIN deleted
--         ON  inserted.[KeyID] = deleted.[KeyID] 
--         AND ((inserted.[InvAndPymt] <> deleted.[InvAndPymt]) OR (inserted.[InvAndPymt] IS NULL AND deleted.[InvAndPymt] IS NOT NULL) OR (inserted.[InvAndPymt] IS NOT NULL AND deleted.[InvAndPymt] IS NULL))



-- END 

-- IF UPDATE([SpecTandC])
-- BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

--   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[SpecTandC]' ,  CONVERT(VARCHAR(MAX), deleted.[SpecTandC]) ,  CONVERT(VARCHAR(MAX), inserted.[SpecTandC]) , GETDATE() , SUSER_SNAME()
--		FROM inserted
--			INNER JOIN deleted
--         ON  inserted.[KeyID] = deleted.[KeyID] 
--         AND ((inserted.[SpecTandC] <> deleted.[SpecTandC]) OR (inserted.[SpecTandC] IS NULL AND deleted.[SpecTandC] IS NOT NULL) OR (inserted.[SpecTandC] IS NOT NULL AND deleted.[SpecTandC] IS NULL))



-- END 

-- IF UPDATE([StateTandC])
-- BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

--   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[StateTandC]' ,  CONVERT(VARCHAR(MAX), deleted.[StateTandC]) ,  CONVERT(VARCHAR(MAX), inserted.[StateTandC]) , GETDATE() , SUSER_SNAME()
--		FROM inserted
--			INNER JOIN deleted
--         ON  inserted.[KeyID] = deleted.[KeyID] 
--         AND ((inserted.[StateTandC] <> deleted.[StateTandC]) OR (inserted.[StateTandC] IS NULL AND deleted.[StateTandC] IS NOT NULL) OR (inserted.[StateTandC] IS NOT NULL AND deleted.[StateTandC] IS NULL))



-- END 

-- IF UPDATE([ExecDate])
-- BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

--   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[ExecDate]' ,  CONVERT(VARCHAR(MAX), deleted.[ExecDate]) ,  CONVERT(VARCHAR(MAX), inserted.[ExecDate]) , GETDATE() , SUSER_SNAME()
--		FROM inserted
--			INNER JOIN deleted
--         ON  inserted.[KeyID] = deleted.[KeyID] 
--         AND ((inserted.[ExecDate] <> deleted.[ExecDate]) OR (inserted.[ExecDate] IS NULL AND deleted.[ExecDate] IS NOT NULL) OR (inserted.[ExecDate] IS NOT NULL AND deleted.[ExecDate] IS NULL))



-- END 

-- IF UPDATE([OrigDate])
-- BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

--   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[OrigDate]' ,  CONVERT(VARCHAR(MAX), deleted.[OrigDate]) ,  CONVERT(VARCHAR(MAX), inserted.[OrigDate]) , GETDATE() , SUSER_SNAME()
--		FROM inserted
--			INNER JOIN deleted
--         ON  inserted.[KeyID] = deleted.[KeyID] 
--         AND ((inserted.[OrigDate] <> deleted.[OrigDate]) OR (inserted.[OrigDate] IS NULL AND deleted.[OrigDate] IS NOT NULL) OR (inserted.[OrigDate] IS NOT NULL AND deleted.[OrigDate] IS NULL))



-- END 

-- IF UPDATE([GenTC])
-- BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

--   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[GenTC]' ,  CONVERT(VARCHAR(MAX), deleted.[GenTC]) ,  CONVERT(VARCHAR(MAX), inserted.[GenTC]) , GETDATE() , SUSER_SNAME()
--		FROM inserted
--			INNER JOIN deleted
--         ON  inserted.[KeyID] = deleted.[KeyID] 
--         AND ((inserted.[GenTC] <> deleted.[GenTC]) OR (inserted.[GenTC] IS NULL AND deleted.[GenTC] IS NOT NULL) OR (inserted.[GenTC] IS NOT NULL AND deleted.[GenTC] IS NULL))



-- END 

-- IF UPDATE([BalancingYN])
-- BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

--   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[BalancingYN]' ,  CONVERT(VARCHAR(MAX), deleted.[BalancingYN]) ,  CONVERT(VARCHAR(MAX), inserted.[BalancingYN]) , GETDATE() , SUSER_SNAME()
--		FROM inserted
--			INNER JOIN deleted
--         ON  inserted.[KeyID] = deleted.[KeyID] 
--         AND ((inserted.[BalancingYN] <> deleted.[BalancingYN]) OR (inserted.[BalancingYN] IS NULL AND deleted.[BalancingYN] IS NOT NULL) OR (inserted.[BalancingYN] IS NOT NULL AND deleted.[BalancingYN] IS NULL))



-- END 

-- IF UPDATE([ConsultingYN])
-- BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

--   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[ConsultingYN]' ,  CONVERT(VARCHAR(MAX), deleted.[ConsultingYN]) ,  CONVERT(VARCHAR(MAX), inserted.[ConsultingYN]) , GETDATE() , SUSER_SNAME()
--		FROM inserted
--			INNER JOIN deleted
--         ON  inserted.[KeyID] = deleted.[KeyID] 
--         AND ((inserted.[ConsultingYN] <> deleted.[ConsultingYN]) OR (inserted.[ConsultingYN] IS NULL AND deleted.[ConsultingYN] IS NOT NULL) OR (inserted.[ConsultingYN] IS NOT NULL AND deleted.[ConsultingYN] IS NULL))



-- END 

-- IF UPDATE([ControlsYN])
-- BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

--   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[ControlsYN]' ,  CONVERT(VARCHAR(MAX), deleted.[ControlsYN]) ,  CONVERT(VARCHAR(MAX), inserted.[ControlsYN]) , GETDATE() , SUSER_SNAME()
--		FROM inserted
--			INNER JOIN deleted
--         ON  inserted.[KeyID] = deleted.[KeyID] 
--         AND ((inserted.[ControlsYN] <> deleted.[ControlsYN]) OR (inserted.[ControlsYN] IS NULL AND deleted.[ControlsYN] IS NOT NULL) OR (inserted.[ControlsYN] IS NOT NULL AND deleted.[ControlsYN] IS NULL))



-- END 

-- IF UPDATE([CostPlusYN])
-- BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

--   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[CostPlusYN]' ,  CONVERT(VARCHAR(MAX), deleted.[CostPlusYN]) ,  CONVERT(VARCHAR(MAX), inserted.[CostPlusYN]) , GETDATE() , SUSER_SNAME()
--		FROM inserted
--			INNER JOIN deleted
--         ON  inserted.[KeyID] = deleted.[KeyID] 
--         AND ((inserted.[CostPlusYN] <> deleted.[CostPlusYN]) OR (inserted.[CostPlusYN] IS NULL AND deleted.[CostPlusYN] IS NOT NULL) OR (inserted.[CostPlusYN] IS NOT NULL AND deleted.[CostPlusYN] IS NULL))



-- END 

-- IF UPDATE([DesignYN])
-- BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

--   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[DesignYN]' ,  CONVERT(VARCHAR(MAX), deleted.[DesignYN]) ,  CONVERT(VARCHAR(MAX), inserted.[DesignYN]) , GETDATE() , SUSER_SNAME()
--		FROM inserted
--			INNER JOIN deleted
--         ON  inserted.[KeyID] = deleted.[KeyID] 
--         AND ((inserted.[DesignYN] <> deleted.[DesignYN]) OR (inserted.[DesignYN] IS NULL AND deleted.[DesignYN] IS NOT NULL) OR (inserted.[DesignYN] IS NOT NULL AND deleted.[DesignYN] IS NULL))



-- END 

-- IF UPDATE([DrawingYN])
-- BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

--   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[DrawingYN]' ,  CONVERT(VARCHAR(MAX), deleted.[DrawingYN]) ,  CONVERT(VARCHAR(MAX), inserted.[DrawingYN]) , GETDATE() , SUSER_SNAME()
--		FROM inserted
--			INNER JOIN deleted
--         ON  inserted.[KeyID] = deleted.[KeyID] 
--         AND ((inserted.[DrawingYN] <> deleted.[DrawingYN]) OR (inserted.[DrawingYN] IS NULL AND deleted.[DrawingYN] IS NOT NULL) OR (inserted.[DrawingYN] IS NOT NULL AND deleted.[DrawingYN] IS NULL))



-- END 

-- IF UPDATE([EqualOppYN])
-- BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

--   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[EqualOppYN]' ,  CONVERT(VARCHAR(MAX), deleted.[EqualOppYN]) ,  CONVERT(VARCHAR(MAX), inserted.[EqualOppYN]) , GETDATE() , SUSER_SNAME()
--		FROM inserted
--			INNER JOIN deleted
--         ON  inserted.[KeyID] = deleted.[KeyID] 
--         AND ((inserted.[EqualOppYN] <> deleted.[EqualOppYN]) OR (inserted.[EqualOppYN] IS NULL AND deleted.[EqualOppYN] IS NOT NULL) OR (inserted.[EqualOppYN] IS NOT NULL AND deleted.[EqualOppYN] IS NULL))



-- END 

-- IF UPDATE([FacilityServicesYN])
-- BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

--   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[FacilityServicesYN]' ,  CONVERT(VARCHAR(MAX), deleted.[FacilityServicesYN]) ,  CONVERT(VARCHAR(MAX), inserted.[FacilityServicesYN]) , GETDATE() , SUSER_SNAME()
--		FROM inserted
--			INNER JOIN deleted
--         ON  inserted.[KeyID] = deleted.[KeyID] 
--         AND ((inserted.[FacilityServicesYN] <> deleted.[FacilityServicesYN]) OR (inserted.[FacilityServicesYN] IS NULL AND deleted.[FacilityServicesYN] IS NOT NULL) OR (inserted.[FacilityServicesYN] IS NOT NULL AND deleted.[FacilityServicesYN] IS NULL))



-- END 

-- IF UPDATE([FederalYN])
-- BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

--   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[FederalYN]' ,  CONVERT(VARCHAR(MAX), deleted.[FederalYN]) ,  CONVERT(VARCHAR(MAX), inserted.[FederalYN]) , GETDATE() , SUSER_SNAME()
--		FROM inserted
--			INNER JOIN deleted
--         ON  inserted.[KeyID] = deleted.[KeyID] 
--         AND ((inserted.[FederalYN] <> deleted.[FederalYN]) OR (inserted.[FederalYN] IS NULL AND deleted.[FederalYN] IS NOT NULL) OR (inserted.[FederalYN] IS NOT NULL AND deleted.[FederalYN] IS NULL))



-- END 

-- IF UPDATE([PScheduleYN])
-- BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

--   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[PScheduleYN]' ,  CONVERT(VARCHAR(MAX), deleted.[PScheduleYN]) ,  CONVERT(VARCHAR(MAX), inserted.[PScheduleYN]) , GETDATE() , SUSER_SNAME()
--		FROM inserted
--			INNER JOIN deleted
--         ON  inserted.[KeyID] = deleted.[KeyID] 
--         AND ((inserted.[PScheduleYN] <> deleted.[PScheduleYN]) OR (inserted.[PScheduleYN] IS NULL AND deleted.[PScheduleYN] IS NOT NULL) OR (inserted.[PScheduleYN] IS NOT NULL AND deleted.[PScheduleYN] IS NULL))



-- END 

-- IF UPDATE([PerformanceBondYN])
-- BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

--   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[PerformanceBondYN]' ,  CONVERT(VARCHAR(MAX), deleted.[PerformanceBondYN]) ,  CONVERT(VARCHAR(MAX), inserted.[PerformanceBondYN]) , GETDATE() , SUSER_SNAME()
--		FROM inserted
--			INNER JOIN deleted
--         ON  inserted.[KeyID] = deleted.[KeyID] 
--         AND ((inserted.[PerformanceBondYN] <> deleted.[PerformanceBondYN]) OR (inserted.[PerformanceBondYN] IS NULL AND deleted.[PerformanceBondYN] IS NOT NULL) OR (inserted.[PerformanceBondYN] IS NOT NULL AND deleted.[PerformanceBondYN] IS NULL))



-- END 

-- IF UPDATE([ProServSoftYN])
-- BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

--   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[ProServSoftYN]' ,  CONVERT(VARCHAR(MAX), deleted.[ProServSoftYN]) ,  CONVERT(VARCHAR(MAX), inserted.[ProServSoftYN]) , GETDATE() , SUSER_SNAME()
--		FROM inserted
--			INNER JOIN deleted
--         ON  inserted.[KeyID] = deleted.[KeyID] 
--         AND ((inserted.[ProServSoftYN] <> deleted.[ProServSoftYN]) OR (inserted.[ProServSoftYN] IS NULL AND deleted.[ProServSoftYN] IS NOT NULL) OR (inserted.[ProServSoftYN] IS NOT NULL AND deleted.[ProServSoftYN] IS NULL))



-- END 

-- IF UPDATE([ProfessionalYN])
-- BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

--   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[ProfessionalYN]' ,  CONVERT(VARCHAR(MAX), deleted.[ProfessionalYN]) ,  CONVERT(VARCHAR(MAX), inserted.[ProfessionalYN]) , GETDATE() , SUSER_SNAME()
--		FROM inserted
--			INNER JOIN deleted
--         ON  inserted.[KeyID] = deleted.[KeyID] 
--         AND ((inserted.[ProfessionalYN] <> deleted.[ProfessionalYN]) OR (inserted.[ProfessionalYN] IS NULL AND deleted.[ProfessionalYN] IS NOT NULL) OR (inserted.[ProfessionalYN] IS NOT NULL AND deleted.[ProfessionalYN] IS NULL))



-- END 

-- IF UPDATE([SafetyYN])
-- BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

--   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[SafetyYN]' ,  CONVERT(VARCHAR(MAX), deleted.[SafetyYN]) ,  CONVERT(VARCHAR(MAX), inserted.[SafetyYN]) , GETDATE() , SUSER_SNAME()
--		FROM inserted
--			INNER JOIN deleted
--         ON  inserted.[KeyID] = deleted.[KeyID] 
--         AND ((inserted.[SafetyYN] <> deleted.[SafetyYN]) OR (inserted.[SafetyYN] IS NULL AND deleted.[SafetyYN] IS NOT NULL) OR (inserted.[SafetyYN] IS NOT NULL AND deleted.[SafetyYN] IS NULL))



-- END 

-- IF UPDATE([ScheduleValYN])
-- BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

--   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[ScheduleValYN]' ,  CONVERT(VARCHAR(MAX), deleted.[ScheduleValYN]) ,  CONVERT(VARCHAR(MAX), inserted.[ScheduleValYN]) , GETDATE() , SUSER_SNAME()
--		FROM inserted
--			INNER JOIN deleted
--         ON  inserted.[KeyID] = deleted.[KeyID] 
--         AND ((inserted.[ScheduleValYN] <> deleted.[ScheduleValYN]) OR (inserted.[ScheduleValYN] IS NULL AND deleted.[ScheduleValYN] IS NOT NULL) OR (inserted.[ScheduleValYN] IS NOT NULL AND deleted.[ScheduleValYN] IS NULL))



-- END 

-- IF UPDATE([HostingYN])
-- BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

--   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[HostingYN]' ,  CONVERT(VARCHAR(MAX), deleted.[HostingYN]) ,  CONVERT(VARCHAR(MAX), inserted.[HostingYN]) , GETDATE() , SUSER_SNAME()
--		FROM inserted
--			INNER JOIN deleted
--         ON  inserted.[KeyID] = deleted.[KeyID] 
--         AND ((inserted.[HostingYN] <> deleted.[HostingYN]) OR (inserted.[HostingYN] IS NULL AND deleted.[HostingYN] IS NOT NULL) OR (inserted.[HostingYN] IS NOT NULL AND deleted.[HostingYN] IS NULL))



-- END 

-- IF UPDATE([LicenseSoftYN])
-- BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

--   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[LicenseSoftYN]' ,  CONVERT(VARCHAR(MAX), deleted.[LicenseSoftYN]) ,  CONVERT(VARCHAR(MAX), inserted.[LicenseSoftYN]) , GETDATE() , SUSER_SNAME()
--		FROM inserted
--			INNER JOIN deleted
--         ON  inserted.[KeyID] = deleted.[KeyID] 
--         AND ((inserted.[LicenseSoftYN] <> deleted.[LicenseSoftYN]) OR (inserted.[LicenseSoftYN] IS NULL AND deleted.[LicenseSoftYN] IS NOT NULL) OR (inserted.[LicenseSoftYN] IS NOT NULL AND deleted.[LicenseSoftYN] IS NULL))



-- END 

-- IF UPDATE([NegotiatedModYN])
-- BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

--   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[NegotiatedModYN]' ,  CONVERT(VARCHAR(MAX), deleted.[NegotiatedModYN]) ,  CONVERT(VARCHAR(MAX), inserted.[NegotiatedModYN]) , GETDATE() , SUSER_SNAME()
--		FROM inserted
--			INNER JOIN deleted
--         ON  inserted.[KeyID] = deleted.[KeyID] 
--         AND ((inserted.[NegotiatedModYN] <> deleted.[NegotiatedModYN]) OR (inserted.[NegotiatedModYN] IS NULL AND deleted.[NegotiatedModYN] IS NOT NULL) OR (inserted.[NegotiatedModYN] IS NOT NULL AND deleted.[NegotiatedModYN] IS NULL))



-- END 

-- IF UPDATE([SupportSoftYN])
-- BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

--   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[SupportSoftYN]' ,  CONVERT(VARCHAR(MAX), deleted.[SupportSoftYN]) ,  CONVERT(VARCHAR(MAX), inserted.[SupportSoftYN]) , GETDATE() , SUSER_SNAME()
--		FROM inserted
--			INNER JOIN deleted
--         ON  inserted.[KeyID] = deleted.[KeyID] 
--         AND ((inserted.[SupportSoftYN] <> deleted.[SupportSoftYN]) OR (inserted.[SupportSoftYN] IS NULL AND deleted.[SupportSoftYN] IS NOT NULL) OR (inserted.[SupportSoftYN] IS NOT NULL AND deleted.[SupportSoftYN] IS NULL))



-- END 

-- IF UPDATE([WorkOrderYN])
-- BEGIN   INSERT dbo.HQMA (TableName, KeyString, Co, RecType, FieldName, OldValue, NewValue, DateTime, UserName)

--   SELECT 'budMSA' , '<KeyString VendorGroup = "' + REPLACE(CAST(inserted.[VendorGroup] AS VARCHAR(MAX)),'"', '&quot;') + '" Vendor = "' + REPLACE(CAST(inserted.[Vendor] AS VARCHAR(MAX)),'"', '&quot;') + '" Sequence = "' + REPLACE(CAST(inserted.[Seq] AS VARCHAR(MAX)),'"', '&quot;') + '" />' , '' , 'C' , '[WorkOrderYN]' ,  CONVERT(VARCHAR(MAX), deleted.[WorkOrderYN]) ,  CONVERT(VARCHAR(MAX), inserted.[WorkOrderYN]) , GETDATE() , SUSER_SNAME()
--		FROM inserted
--			INNER JOIN deleted
--         ON  inserted.[KeyID] = deleted.[KeyID] 
--         AND ((inserted.[WorkOrderYN] <> deleted.[WorkOrderYN]) OR (inserted.[WorkOrderYN] IS NULL AND deleted.[WorkOrderYN] IS NOT NULL) OR (inserted.[WorkOrderYN] IS NOT NULL AND deleted.[WorkOrderYN] IS NULL))



-- END 

-- END TRY 
-- BEGIN CATCH 
--   DECLARE	@ErrorMessage	NVARCHAR(4000), 
--				@ErrorSeverity	INT; 

--   SELECT	@ErrorMessage = 'Error '+ ISNULL(ERROR_MESSAGE(),'') +' in [dbo].[dbo.vtbudMSA_Audit_Update] trigger', 
--				@ErrorSeverity = ERROR_SEVERITY(); 

--   RAISERROR(@ErrorMessage, @ErrorSeverity, 1 ) 
-- END CATCH 
--GO
--EXEC sp_settriggerorder N'[dbo].[vtbudMSA_Audit_Update]', 'last', 'update', null
--GO

--EXEC sp_settriggerorder N'[dbo].[vtbudMSA_Audit_Update]', 'last', 'update', null
--GO

--EXEC sp_settriggerorder N'[dbo].[vtbudMSA_Audit_Update]', 'last', 'update', null
--GO
