CREATE TABLE [dbo].[vSMWorkOrderPOHD]
(
[SMWorkOrderPOHDID] [bigint] NOT NULL IDENTITY(1, 1),
[POCo] [dbo].[bCompany] NOT NULL,
[PO] [varchar] (30) COLLATE Latin1_General_BIN NULL,
[SMCo] [dbo].[bCompany] NOT NULL,
[WorkOrder] [int] NOT NULL
) ON [PRIMARY]
ALTER TABLE [dbo].[vSMWorkOrderPOHD] ADD
CONSTRAINT [FK_vSMWorkOrderPOHD_bPOHD] FOREIGN KEY ([POCo], [PO]) REFERENCES [dbo].[bPOHD] ([POCo], [PO]) ON DELETE CASCADE
GO
ALTER TABLE [dbo].[vSMWorkOrderPOHD] ADD CONSTRAINT [PK_vSMWorkOrderPOHD] PRIMARY KEY CLUSTERED  ([SMWorkOrderPOHDID]) ON [PRIMARY]
GO

ALTER TABLE [dbo].[vSMWorkOrderPOHD] WITH NOCHECK ADD CONSTRAINT [FK_vSMWorkOrderPOHD_vSMWorkOrder] FOREIGN KEY ([WorkOrder], [SMCo]) REFERENCES [dbo].[vSMWorkOrder] ([WorkOrder], [SMCo]) ON DELETE CASCADE
GO
