CREATE TABLE [dbo].[vSLClaimItem]
(
[KeyID] [bigint] NOT NULL IDENTITY(1, 1),
[SLCo] [dbo].[bCompany] NOT NULL,
[SL] [varchar] (30) COLLATE Latin1_General_BIN NOT NULL,
[ClaimNo] [int] NOT NULL,
[SLItem] [dbo].[bItem] NOT NULL,
[ClaimToDateUnits] [dbo].[bUnits] NOT NULL CONSTRAINT [DF_vSLClaimItem_ClaimToDateUnits] DEFAULT ((0)),
[ClaimToDateAmt] [dbo].[bDollar] NOT NULL CONSTRAINT [DF_vSLClaimItem_ClaimToDateAmt] DEFAULT ((0)),
[ClaimUnits] [dbo].[bUnits] NOT NULL CONSTRAINT [DF_vSLClaimItem_UnitsClaimed] DEFAULT ((0)),
[ClaimAmount] [dbo].[bDollar] NOT NULL CONSTRAINT [DF_vSLClaimItem_AmtClaimed] DEFAULT ((0)),
[ApproveUnits] [dbo].[bUnits] NOT NULL CONSTRAINT [DF_vSLClaimItem_UnitsApproved] DEFAULT ((0)),
[ApproveAmount] [dbo].[bDollar] NOT NULL CONSTRAINT [DF_vSLClaimItem_AmtApproved] DEFAULT ((0)),
[ApproveRetPct] [dbo].[bPct] NOT NULL CONSTRAINT [DF_vSLClaimItem_ApproveRetPct] DEFAULT ((0)),
[ApproveRetention] [dbo].[bDollar] NOT NULL CONSTRAINT [DF_vSLClaimItem_RetApproved] DEFAULT ((0)),
[TaxAmount] [dbo].[bDollar] NOT NULL CONSTRAINT [DF_vSLClaimItem_TaxAmount] DEFAULT ((0)),
[Notes] [varchar] (max) COLLATE Latin1_General_BIN NULL,
[UniqueAttchID] [uniqueidentifier] NULL,
[Description] [dbo].[bDesc] NULL,
[UM] [dbo].[bUM] NOT NULL,
[CurUnitCost] [dbo].[bUnitCost] NOT NULL CONSTRAINT [DF_vSLClaimItem_CurUnitCost] DEFAULT ((0)),
[CurUnits] [dbo].[bUnits] NOT NULL CONSTRAINT [DF_vSLClaimItem_CurUnits] DEFAULT ((0)),
[CurCost] [dbo].[bDollar] NOT NULL CONSTRAINT [DF_vSLClaimItem_CurCost] DEFAULT ((0)),
[TaxGroup] [dbo].[bGroup] NULL,
[TaxCode] [dbo].[bTaxCode] NULL,
[TaxType] [tinyint] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
ALTER TABLE [dbo].[vSLClaimItem] ADD 
CONSTRAINT [PK_vSLClaimItem] PRIMARY KEY CLUSTERED  ([SLCo], [SL], [ClaimNo], [SLItem]) ON [PRIMARY]
CREATE UNIQUE NONCLUSTERED INDEX [IX_vSLClaimItem_KeyID] ON [dbo].[vSLClaimItem] ([KeyID]) ON [PRIMARY]

CREATE NONCLUSTERED INDEX [IX_vSLClaimItem_SL] ON [dbo].[vSLClaimItem] ([SLCo], [SL]) ON [PRIMARY]

CREATE NONCLUSTERED INDEX [IX_vSLClaimItem_ClaimNo] ON [dbo].[vSLClaimItem] ([SLCo], [SL], [ClaimNo]) ON [PRIMARY]

CREATE NONCLUSTERED INDEX [IX_vSLClaimItem_SLItem] ON [dbo].[vSLClaimItem] ([SLCo], [SL], [SLItem]) ON [PRIMARY]



ALTER TABLE [dbo].[vSLClaimItem] WITH NOCHECK ADD
CONSTRAINT [FK_vSLClaimItem_vSLClaimHeader] FOREIGN KEY ([SLCo], [SL], [ClaimNo]) REFERENCES [dbo].[vSLClaimHeader] ([SLCo], [SL], [ClaimNo])
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER dbo.vtvSLClaimItem_Audit_Delete ON dbo.vSLClaimItem
 AFTER DELETE
 NOT FOR REPLICATION AS
 SET NOCOUNT ON 
 -- generated by vspAuditCreateAuditTriggers

 BEGIN TRY 

							INSERT dbo.HQMA (
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
								
							SELECT
								'vSLClaimItem' , 
								'<KeyString ClaimNo = "' + REPLACE(CAST(ISNULL(deleted.[ClaimNo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SL = "' + REPLACE(CAST(ISNULL(deleted.[SL],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLCo = "' + REPLACE(CAST(ISNULL(deleted.[SLCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLItem = "' + REPLACE(CAST(ISNULL(deleted.[SLItem],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								deleted.SLCo , 
								'D' , 
								'ClaimNo' , 
								CONVERT(VARCHAR(MAX), deleted.[ClaimNo]) , 								NULL , 
								GETDATE() , 
								SUSER_SNAME()
							FROM deleted
								
							INSERT dbo.HQMA (
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
								
							SELECT
								'vSLClaimItem' , 
								'<KeyString ClaimNo = "' + REPLACE(CAST(ISNULL(deleted.[ClaimNo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SL = "' + REPLACE(CAST(ISNULL(deleted.[SL],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLCo = "' + REPLACE(CAST(ISNULL(deleted.[SLCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLItem = "' + REPLACE(CAST(ISNULL(deleted.[SLItem],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								deleted.SLCo , 
								'D' , 
								'SL' , 
								CONVERT(VARCHAR(MAX), deleted.[SL]) , 								NULL , 
								GETDATE() , 
								SUSER_SNAME()
							FROM deleted
								
							INSERT dbo.HQMA (
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
								
							SELECT
								'vSLClaimItem' , 
								'<KeyString ClaimNo = "' + REPLACE(CAST(ISNULL(deleted.[ClaimNo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SL = "' + REPLACE(CAST(ISNULL(deleted.[SL],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLCo = "' + REPLACE(CAST(ISNULL(deleted.[SLCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLItem = "' + REPLACE(CAST(ISNULL(deleted.[SLItem],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								deleted.SLCo , 
								'D' , 
								'SLCo' , 
								CONVERT(VARCHAR(MAX), deleted.[SLCo]) , 								NULL , 
								GETDATE() , 
								SUSER_SNAME()
							FROM deleted
								
							INSERT dbo.HQMA (
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
								
							SELECT
								'vSLClaimItem' , 
								'<KeyString ClaimNo = "' + REPLACE(CAST(ISNULL(deleted.[ClaimNo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SL = "' + REPLACE(CAST(ISNULL(deleted.[SL],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLCo = "' + REPLACE(CAST(ISNULL(deleted.[SLCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLItem = "' + REPLACE(CAST(ISNULL(deleted.[SLItem],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								deleted.SLCo , 
								'D' , 
								'SLItem' , 
								CONVERT(VARCHAR(MAX), deleted.[SLItem]) , 								NULL , 
								GETDATE() , 
								SUSER_SNAME()
							FROM deleted
								

							
 END TRY 
 BEGIN CATCH 
   DECLARE	@ErrorMessage	NVARCHAR(4000), 
				@ErrorSeverity	INT; 

   SELECT	@ErrorMessage = 'Error '+ ISNULL(ERROR_MESSAGE(),'') +' in [dbo].[dbo.vtvSLClaimItem_Audit_Delete] trigger', 
				@ErrorSeverity = ERROR_SEVERITY(); 

   RAISERROR(@ErrorMessage, @ErrorSeverity, 1 ) 
 END CATCH 
GO
EXEC sp_settriggerorder N'[dbo].[vtvSLClaimItem_Audit_Delete]', 'last', 'delete', null
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER dbo.vtvSLClaimItem_Audit_Insert ON dbo.vSLClaimItem
 AFTER INSERT
 NOT FOR REPLICATION AS
 SET NOCOUNT ON 
 -- generated by vspAuditTriggersCreate

 BEGIN TRY 

-- log additions to the ApproveAmount column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vSLClaimItem' , 
								'<KeyString ClaimNo = "' + REPLACE(CAST(ISNULL(inserted.[ClaimNo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SL = "' + REPLACE(CAST(ISNULL(inserted.[SL],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLCo = "' + REPLACE(CAST(ISNULL(inserted.[SLCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLItem = "' + REPLACE(CAST(ISNULL(inserted.[SLItem],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.SLCo, '') , 
								'A' , 
								'ApproveAmount' , 
								NULL , 
								ApproveAmount , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								

-- log additions to the ApproveRetPct column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vSLClaimItem' , 
								'<KeyString ClaimNo = "' + REPLACE(CAST(ISNULL(inserted.[ClaimNo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SL = "' + REPLACE(CAST(ISNULL(inserted.[SL],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLCo = "' + REPLACE(CAST(ISNULL(inserted.[SLCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLItem = "' + REPLACE(CAST(ISNULL(inserted.[SLItem],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.SLCo, '') , 
								'A' , 
								'ApproveRetPct' , 
								NULL , 
								ApproveRetPct , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								

-- log additions to the ApproveRetention column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vSLClaimItem' , 
								'<KeyString ClaimNo = "' + REPLACE(CAST(ISNULL(inserted.[ClaimNo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SL = "' + REPLACE(CAST(ISNULL(inserted.[SL],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLCo = "' + REPLACE(CAST(ISNULL(inserted.[SLCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLItem = "' + REPLACE(CAST(ISNULL(inserted.[SLItem],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.SLCo, '') , 
								'A' , 
								'ApproveRetention' , 
								NULL , 
								ApproveRetention , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								

-- log additions to the ApproveUnits column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vSLClaimItem' , 
								'<KeyString ClaimNo = "' + REPLACE(CAST(ISNULL(inserted.[ClaimNo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SL = "' + REPLACE(CAST(ISNULL(inserted.[SL],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLCo = "' + REPLACE(CAST(ISNULL(inserted.[SLCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLItem = "' + REPLACE(CAST(ISNULL(inserted.[SLItem],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.SLCo, '') , 
								'A' , 
								'ApproveUnits' , 
								NULL , 
								ApproveUnits , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								

-- log additions to the ClaimAmount column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vSLClaimItem' , 
								'<KeyString ClaimNo = "' + REPLACE(CAST(ISNULL(inserted.[ClaimNo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SL = "' + REPLACE(CAST(ISNULL(inserted.[SL],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLCo = "' + REPLACE(CAST(ISNULL(inserted.[SLCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLItem = "' + REPLACE(CAST(ISNULL(inserted.[SLItem],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.SLCo, '') , 
								'A' , 
								'ClaimAmount' , 
								NULL , 
								ClaimAmount , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								

-- log additions to the ClaimNo column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vSLClaimItem' , 
								'<KeyString ClaimNo = "' + REPLACE(CAST(ISNULL(inserted.[ClaimNo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SL = "' + REPLACE(CAST(ISNULL(inserted.[SL],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLCo = "' + REPLACE(CAST(ISNULL(inserted.[SLCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLItem = "' + REPLACE(CAST(ISNULL(inserted.[SLItem],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.SLCo, '') , 
								'A' , 
								'ClaimNo' , 
								NULL , 
								ClaimNo , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								

-- log additions to the ClaimToDateAmt column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vSLClaimItem' , 
								'<KeyString ClaimNo = "' + REPLACE(CAST(ISNULL(inserted.[ClaimNo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SL = "' + REPLACE(CAST(ISNULL(inserted.[SL],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLCo = "' + REPLACE(CAST(ISNULL(inserted.[SLCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLItem = "' + REPLACE(CAST(ISNULL(inserted.[SLItem],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.SLCo, '') , 
								'A' , 
								'ClaimToDateAmt' , 
								NULL , 
								ClaimToDateAmt , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								

-- log additions to the ClaimToDateUnits column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vSLClaimItem' , 
								'<KeyString ClaimNo = "' + REPLACE(CAST(ISNULL(inserted.[ClaimNo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SL = "' + REPLACE(CAST(ISNULL(inserted.[SL],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLCo = "' + REPLACE(CAST(ISNULL(inserted.[SLCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLItem = "' + REPLACE(CAST(ISNULL(inserted.[SLItem],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.SLCo, '') , 
								'A' , 
								'ClaimToDateUnits' , 
								NULL , 
								ClaimToDateUnits , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								

-- log additions to the ClaimUnits column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vSLClaimItem' , 
								'<KeyString ClaimNo = "' + REPLACE(CAST(ISNULL(inserted.[ClaimNo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SL = "' + REPLACE(CAST(ISNULL(inserted.[SL],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLCo = "' + REPLACE(CAST(ISNULL(inserted.[SLCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLItem = "' + REPLACE(CAST(ISNULL(inserted.[SLItem],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.SLCo, '') , 
								'A' , 
								'ClaimUnits' , 
								NULL , 
								ClaimUnits , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								

-- log additions to the CurCost column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vSLClaimItem' , 
								'<KeyString ClaimNo = "' + REPLACE(CAST(ISNULL(inserted.[ClaimNo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SL = "' + REPLACE(CAST(ISNULL(inserted.[SL],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLCo = "' + REPLACE(CAST(ISNULL(inserted.[SLCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLItem = "' + REPLACE(CAST(ISNULL(inserted.[SLItem],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.SLCo, '') , 
								'A' , 
								'CurCost' , 
								NULL , 
								CurCost , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								

-- log additions to the CurUnitCost column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vSLClaimItem' , 
								'<KeyString ClaimNo = "' + REPLACE(CAST(ISNULL(inserted.[ClaimNo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SL = "' + REPLACE(CAST(ISNULL(inserted.[SL],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLCo = "' + REPLACE(CAST(ISNULL(inserted.[SLCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLItem = "' + REPLACE(CAST(ISNULL(inserted.[SLItem],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.SLCo, '') , 
								'A' , 
								'CurUnitCost' , 
								NULL , 
								CurUnitCost , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								

-- log additions to the CurUnits column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vSLClaimItem' , 
								'<KeyString ClaimNo = "' + REPLACE(CAST(ISNULL(inserted.[ClaimNo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SL = "' + REPLACE(CAST(ISNULL(inserted.[SL],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLCo = "' + REPLACE(CAST(ISNULL(inserted.[SLCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLItem = "' + REPLACE(CAST(ISNULL(inserted.[SLItem],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.SLCo, '') , 
								'A' , 
								'CurUnits' , 
								NULL , 
								CurUnits , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								

-- log additions to the Description column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vSLClaimItem' , 
								'<KeyString ClaimNo = "' + REPLACE(CAST(ISNULL(inserted.[ClaimNo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SL = "' + REPLACE(CAST(ISNULL(inserted.[SL],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLCo = "' + REPLACE(CAST(ISNULL(inserted.[SLCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLItem = "' + REPLACE(CAST(ISNULL(inserted.[SLItem],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.SLCo, '') , 
								'A' , 
								'Description' , 
								NULL , 
								Description , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								

-- log additions to the SL column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vSLClaimItem' , 
								'<KeyString ClaimNo = "' + REPLACE(CAST(ISNULL(inserted.[ClaimNo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SL = "' + REPLACE(CAST(ISNULL(inserted.[SL],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLCo = "' + REPLACE(CAST(ISNULL(inserted.[SLCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLItem = "' + REPLACE(CAST(ISNULL(inserted.[SLItem],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.SLCo, '') , 
								'A' , 
								'SL' , 
								NULL , 
								SL , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								

-- log additions to the SLCo column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vSLClaimItem' , 
								'<KeyString ClaimNo = "' + REPLACE(CAST(ISNULL(inserted.[ClaimNo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SL = "' + REPLACE(CAST(ISNULL(inserted.[SL],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLCo = "' + REPLACE(CAST(ISNULL(inserted.[SLCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLItem = "' + REPLACE(CAST(ISNULL(inserted.[SLItem],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.SLCo, '') , 
								'A' , 
								'SLCo' , 
								NULL , 
								SLCo , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								

-- log additions to the SLItem column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vSLClaimItem' , 
								'<KeyString ClaimNo = "' + REPLACE(CAST(ISNULL(inserted.[ClaimNo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SL = "' + REPLACE(CAST(ISNULL(inserted.[SL],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLCo = "' + REPLACE(CAST(ISNULL(inserted.[SLCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLItem = "' + REPLACE(CAST(ISNULL(inserted.[SLItem],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.SLCo, '') , 
								'A' , 
								'SLItem' , 
								NULL , 
								SLItem , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								

-- log additions to the TaxAmount column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vSLClaimItem' , 
								'<KeyString ClaimNo = "' + REPLACE(CAST(ISNULL(inserted.[ClaimNo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SL = "' + REPLACE(CAST(ISNULL(inserted.[SL],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLCo = "' + REPLACE(CAST(ISNULL(inserted.[SLCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLItem = "' + REPLACE(CAST(ISNULL(inserted.[SLItem],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.SLCo, '') , 
								'A' , 
								'TaxAmount' , 
								NULL , 
								TaxAmount , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								

-- log additions to the TaxCode column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vSLClaimItem' , 
								'<KeyString ClaimNo = "' + REPLACE(CAST(ISNULL(inserted.[ClaimNo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SL = "' + REPLACE(CAST(ISNULL(inserted.[SL],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLCo = "' + REPLACE(CAST(ISNULL(inserted.[SLCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLItem = "' + REPLACE(CAST(ISNULL(inserted.[SLItem],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.SLCo, '') , 
								'A' , 
								'TaxCode' , 
								NULL , 
								TaxCode , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								

-- log additions to the TaxGroup column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vSLClaimItem' , 
								'<KeyString ClaimNo = "' + REPLACE(CAST(ISNULL(inserted.[ClaimNo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SL = "' + REPLACE(CAST(ISNULL(inserted.[SL],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLCo = "' + REPLACE(CAST(ISNULL(inserted.[SLCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLItem = "' + REPLACE(CAST(ISNULL(inserted.[SLItem],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.SLCo, '') , 
								'A' , 
								'TaxGroup' , 
								NULL , 
								TaxGroup , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								

-- log additions to the TaxType column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vSLClaimItem' , 
								'<KeyString ClaimNo = "' + REPLACE(CAST(ISNULL(inserted.[ClaimNo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SL = "' + REPLACE(CAST(ISNULL(inserted.[SL],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLCo = "' + REPLACE(CAST(ISNULL(inserted.[SLCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLItem = "' + REPLACE(CAST(ISNULL(inserted.[SLItem],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.SLCo, '') , 
								'A' , 
								'TaxType' , 
								NULL , 
								TaxType , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								

-- log additions to the UM column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vSLClaimItem' , 
								'<KeyString ClaimNo = "' + REPLACE(CAST(ISNULL(inserted.[ClaimNo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SL = "' + REPLACE(CAST(ISNULL(inserted.[SL],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLCo = "' + REPLACE(CAST(ISNULL(inserted.[SLCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLItem = "' + REPLACE(CAST(ISNULL(inserted.[SLItem],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.SLCo, '') , 
								'A' , 
								'UM' , 
								NULL , 
								UM , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								


 END TRY 
 BEGIN CATCH 
   DECLARE	@ErrorMessage	NVARCHAR(4000), 
				@ErrorSeverity	INT; 

   SELECT	@ErrorMessage = 'Error '+ ISNULL(ERROR_MESSAGE(),'') +' in [dbo].[dbo.vtvSLClaimItem_Audit_Insert] trigger', 
				@ErrorSeverity = ERROR_SEVERITY(); 

   RAISERROR(@ErrorMessage, @ErrorSeverity, 1 ) 
 END CATCH 
GO
EXEC sp_settriggerorder N'[dbo].[vtvSLClaimItem_Audit_Insert]', 'last', 'insert', null
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER dbo.vtvSLClaimItem_Audit_Update ON dbo.vSLClaimItem
 AFTER UPDATE 
 NOT FOR REPLICATION AS 
 SET NOCOUNT ON 
 -- generated by vspAuditTriggersCreate

 BEGIN TRY 

							IF UPDATE([ApproveAmount])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vSLClaimItem' , 								'<KeyString ClaimNo = "' + REPLACE(CAST(ISNULL(inserted.[ClaimNo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SL = "' + REPLACE(CAST(ISNULL(inserted.[SL],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLCo = "' + REPLACE(CAST(ISNULL(inserted.[SLCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLItem = "' + REPLACE(CAST(ISNULL(inserted.[SLItem],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.SLCo , 								'C' , 								'ApproveAmount' , 								CONVERT(VARCHAR(MAX), deleted.[ApproveAmount]) , 								CONVERT(VARCHAR(MAX), inserted.[ApproveAmount]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[KeyID] = deleted.[KeyID] 
									AND ((inserted.[ApproveAmount] <> deleted.[ApproveAmount]) OR (inserted.[ApproveAmount] IS NULL AND deleted.[ApproveAmount] IS NOT NULL) OR (inserted.[ApproveAmount] IS NOT NULL AND deleted.[ApproveAmount] IS NULL))
								

							END 

							IF UPDATE([ApproveRetPct])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vSLClaimItem' , 								'<KeyString ClaimNo = "' + REPLACE(CAST(ISNULL(inserted.[ClaimNo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SL = "' + REPLACE(CAST(ISNULL(inserted.[SL],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLCo = "' + REPLACE(CAST(ISNULL(inserted.[SLCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLItem = "' + REPLACE(CAST(ISNULL(inserted.[SLItem],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.SLCo , 								'C' , 								'ApproveRetPct' , 								CONVERT(VARCHAR(MAX), deleted.[ApproveRetPct]) , 								CONVERT(VARCHAR(MAX), inserted.[ApproveRetPct]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[KeyID] = deleted.[KeyID] 
									AND ((inserted.[ApproveRetPct] <> deleted.[ApproveRetPct]) OR (inserted.[ApproveRetPct] IS NULL AND deleted.[ApproveRetPct] IS NOT NULL) OR (inserted.[ApproveRetPct] IS NOT NULL AND deleted.[ApproveRetPct] IS NULL))
								

							END 

							IF UPDATE([ApproveRetention])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vSLClaimItem' , 								'<KeyString ClaimNo = "' + REPLACE(CAST(ISNULL(inserted.[ClaimNo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SL = "' + REPLACE(CAST(ISNULL(inserted.[SL],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLCo = "' + REPLACE(CAST(ISNULL(inserted.[SLCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLItem = "' + REPLACE(CAST(ISNULL(inserted.[SLItem],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.SLCo , 								'C' , 								'ApproveRetention' , 								CONVERT(VARCHAR(MAX), deleted.[ApproveRetention]) , 								CONVERT(VARCHAR(MAX), inserted.[ApproveRetention]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[KeyID] = deleted.[KeyID] 
									AND ((inserted.[ApproveRetention] <> deleted.[ApproveRetention]) OR (inserted.[ApproveRetention] IS NULL AND deleted.[ApproveRetention] IS NOT NULL) OR (inserted.[ApproveRetention] IS NOT NULL AND deleted.[ApproveRetention] IS NULL))
								

							END 

							IF UPDATE([ApproveUnits])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vSLClaimItem' , 								'<KeyString ClaimNo = "' + REPLACE(CAST(ISNULL(inserted.[ClaimNo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SL = "' + REPLACE(CAST(ISNULL(inserted.[SL],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLCo = "' + REPLACE(CAST(ISNULL(inserted.[SLCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLItem = "' + REPLACE(CAST(ISNULL(inserted.[SLItem],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.SLCo , 								'C' , 								'ApproveUnits' , 								CONVERT(VARCHAR(MAX), deleted.[ApproveUnits]) , 								CONVERT(VARCHAR(MAX), inserted.[ApproveUnits]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[KeyID] = deleted.[KeyID] 
									AND ((inserted.[ApproveUnits] <> deleted.[ApproveUnits]) OR (inserted.[ApproveUnits] IS NULL AND deleted.[ApproveUnits] IS NOT NULL) OR (inserted.[ApproveUnits] IS NOT NULL AND deleted.[ApproveUnits] IS NULL))
								

							END 

							IF UPDATE([ClaimAmount])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vSLClaimItem' , 								'<KeyString ClaimNo = "' + REPLACE(CAST(ISNULL(inserted.[ClaimNo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SL = "' + REPLACE(CAST(ISNULL(inserted.[SL],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLCo = "' + REPLACE(CAST(ISNULL(inserted.[SLCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLItem = "' + REPLACE(CAST(ISNULL(inserted.[SLItem],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.SLCo , 								'C' , 								'ClaimAmount' , 								CONVERT(VARCHAR(MAX), deleted.[ClaimAmount]) , 								CONVERT(VARCHAR(MAX), inserted.[ClaimAmount]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[KeyID] = deleted.[KeyID] 
									AND ((inserted.[ClaimAmount] <> deleted.[ClaimAmount]) OR (inserted.[ClaimAmount] IS NULL AND deleted.[ClaimAmount] IS NOT NULL) OR (inserted.[ClaimAmount] IS NOT NULL AND deleted.[ClaimAmount] IS NULL))
								

							END 

							IF UPDATE([ClaimNo])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vSLClaimItem' , 								'<KeyString ClaimNo = "' + REPLACE(CAST(ISNULL(inserted.[ClaimNo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SL = "' + REPLACE(CAST(ISNULL(inserted.[SL],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLCo = "' + REPLACE(CAST(ISNULL(inserted.[SLCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLItem = "' + REPLACE(CAST(ISNULL(inserted.[SLItem],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.SLCo , 								'C' , 								'ClaimNo' , 								CONVERT(VARCHAR(MAX), deleted.[ClaimNo]) , 								CONVERT(VARCHAR(MAX), inserted.[ClaimNo]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[KeyID] = deleted.[KeyID] 
									AND ((inserted.[ClaimNo] <> deleted.[ClaimNo]) OR (inserted.[ClaimNo] IS NULL AND deleted.[ClaimNo] IS NOT NULL) OR (inserted.[ClaimNo] IS NOT NULL AND deleted.[ClaimNo] IS NULL))
								

							END 

							IF UPDATE([ClaimToDateAmt])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vSLClaimItem' , 								'<KeyString ClaimNo = "' + REPLACE(CAST(ISNULL(inserted.[ClaimNo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SL = "' + REPLACE(CAST(ISNULL(inserted.[SL],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLCo = "' + REPLACE(CAST(ISNULL(inserted.[SLCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLItem = "' + REPLACE(CAST(ISNULL(inserted.[SLItem],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.SLCo , 								'C' , 								'ClaimToDateAmt' , 								CONVERT(VARCHAR(MAX), deleted.[ClaimToDateAmt]) , 								CONVERT(VARCHAR(MAX), inserted.[ClaimToDateAmt]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[KeyID] = deleted.[KeyID] 
									AND ((inserted.[ClaimToDateAmt] <> deleted.[ClaimToDateAmt]) OR (inserted.[ClaimToDateAmt] IS NULL AND deleted.[ClaimToDateAmt] IS NOT NULL) OR (inserted.[ClaimToDateAmt] IS NOT NULL AND deleted.[ClaimToDateAmt] IS NULL))
								

							END 

							IF UPDATE([ClaimToDateUnits])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vSLClaimItem' , 								'<KeyString ClaimNo = "' + REPLACE(CAST(ISNULL(inserted.[ClaimNo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SL = "' + REPLACE(CAST(ISNULL(inserted.[SL],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLCo = "' + REPLACE(CAST(ISNULL(inserted.[SLCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLItem = "' + REPLACE(CAST(ISNULL(inserted.[SLItem],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.SLCo , 								'C' , 								'ClaimToDateUnits' , 								CONVERT(VARCHAR(MAX), deleted.[ClaimToDateUnits]) , 								CONVERT(VARCHAR(MAX), inserted.[ClaimToDateUnits]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[KeyID] = deleted.[KeyID] 
									AND ((inserted.[ClaimToDateUnits] <> deleted.[ClaimToDateUnits]) OR (inserted.[ClaimToDateUnits] IS NULL AND deleted.[ClaimToDateUnits] IS NOT NULL) OR (inserted.[ClaimToDateUnits] IS NOT NULL AND deleted.[ClaimToDateUnits] IS NULL))
								

							END 

							IF UPDATE([ClaimUnits])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vSLClaimItem' , 								'<KeyString ClaimNo = "' + REPLACE(CAST(ISNULL(inserted.[ClaimNo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SL = "' + REPLACE(CAST(ISNULL(inserted.[SL],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLCo = "' + REPLACE(CAST(ISNULL(inserted.[SLCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLItem = "' + REPLACE(CAST(ISNULL(inserted.[SLItem],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.SLCo , 								'C' , 								'ClaimUnits' , 								CONVERT(VARCHAR(MAX), deleted.[ClaimUnits]) , 								CONVERT(VARCHAR(MAX), inserted.[ClaimUnits]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[KeyID] = deleted.[KeyID] 
									AND ((inserted.[ClaimUnits] <> deleted.[ClaimUnits]) OR (inserted.[ClaimUnits] IS NULL AND deleted.[ClaimUnits] IS NOT NULL) OR (inserted.[ClaimUnits] IS NOT NULL AND deleted.[ClaimUnits] IS NULL))
								

							END 

							IF UPDATE([CurCost])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vSLClaimItem' , 								'<KeyString ClaimNo = "' + REPLACE(CAST(ISNULL(inserted.[ClaimNo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SL = "' + REPLACE(CAST(ISNULL(inserted.[SL],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLCo = "' + REPLACE(CAST(ISNULL(inserted.[SLCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLItem = "' + REPLACE(CAST(ISNULL(inserted.[SLItem],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.SLCo , 								'C' , 								'CurCost' , 								CONVERT(VARCHAR(MAX), deleted.[CurCost]) , 								CONVERT(VARCHAR(MAX), inserted.[CurCost]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[KeyID] = deleted.[KeyID] 
									AND ((inserted.[CurCost] <> deleted.[CurCost]) OR (inserted.[CurCost] IS NULL AND deleted.[CurCost] IS NOT NULL) OR (inserted.[CurCost] IS NOT NULL AND deleted.[CurCost] IS NULL))
								

							END 

							IF UPDATE([CurUnitCost])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vSLClaimItem' , 								'<KeyString ClaimNo = "' + REPLACE(CAST(ISNULL(inserted.[ClaimNo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SL = "' + REPLACE(CAST(ISNULL(inserted.[SL],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLCo = "' + REPLACE(CAST(ISNULL(inserted.[SLCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLItem = "' + REPLACE(CAST(ISNULL(inserted.[SLItem],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.SLCo , 								'C' , 								'CurUnitCost' , 								CONVERT(VARCHAR(MAX), deleted.[CurUnitCost]) , 								CONVERT(VARCHAR(MAX), inserted.[CurUnitCost]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[KeyID] = deleted.[KeyID] 
									AND ((inserted.[CurUnitCost] <> deleted.[CurUnitCost]) OR (inserted.[CurUnitCost] IS NULL AND deleted.[CurUnitCost] IS NOT NULL) OR (inserted.[CurUnitCost] IS NOT NULL AND deleted.[CurUnitCost] IS NULL))
								

							END 

							IF UPDATE([CurUnits])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vSLClaimItem' , 								'<KeyString ClaimNo = "' + REPLACE(CAST(ISNULL(inserted.[ClaimNo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SL = "' + REPLACE(CAST(ISNULL(inserted.[SL],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLCo = "' + REPLACE(CAST(ISNULL(inserted.[SLCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLItem = "' + REPLACE(CAST(ISNULL(inserted.[SLItem],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.SLCo , 								'C' , 								'CurUnits' , 								CONVERT(VARCHAR(MAX), deleted.[CurUnits]) , 								CONVERT(VARCHAR(MAX), inserted.[CurUnits]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[KeyID] = deleted.[KeyID] 
									AND ((inserted.[CurUnits] <> deleted.[CurUnits]) OR (inserted.[CurUnits] IS NULL AND deleted.[CurUnits] IS NOT NULL) OR (inserted.[CurUnits] IS NOT NULL AND deleted.[CurUnits] IS NULL))
								

							END 

							IF UPDATE([Description])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vSLClaimItem' , 								'<KeyString ClaimNo = "' + REPLACE(CAST(ISNULL(inserted.[ClaimNo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SL = "' + REPLACE(CAST(ISNULL(inserted.[SL],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLCo = "' + REPLACE(CAST(ISNULL(inserted.[SLCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLItem = "' + REPLACE(CAST(ISNULL(inserted.[SLItem],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.SLCo , 								'C' , 								'Description' , 								CONVERT(VARCHAR(MAX), deleted.[Description]) , 								CONVERT(VARCHAR(MAX), inserted.[Description]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[KeyID] = deleted.[KeyID] 
									AND ((inserted.[Description] <> deleted.[Description]) OR (inserted.[Description] IS NULL AND deleted.[Description] IS NOT NULL) OR (inserted.[Description] IS NOT NULL AND deleted.[Description] IS NULL))
								

							END 

							IF UPDATE([SL])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vSLClaimItem' , 								'<KeyString ClaimNo = "' + REPLACE(CAST(ISNULL(inserted.[ClaimNo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SL = "' + REPLACE(CAST(ISNULL(inserted.[SL],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLCo = "' + REPLACE(CAST(ISNULL(inserted.[SLCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLItem = "' + REPLACE(CAST(ISNULL(inserted.[SLItem],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.SLCo , 								'C' , 								'SL' , 								CONVERT(VARCHAR(MAX), deleted.[SL]) , 								CONVERT(VARCHAR(MAX), inserted.[SL]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[KeyID] = deleted.[KeyID] 
									AND ((inserted.[SL] <> deleted.[SL]) OR (inserted.[SL] IS NULL AND deleted.[SL] IS NOT NULL) OR (inserted.[SL] IS NOT NULL AND deleted.[SL] IS NULL))
								

							END 

							IF UPDATE([SLCo])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vSLClaimItem' , 								'<KeyString ClaimNo = "' + REPLACE(CAST(ISNULL(inserted.[ClaimNo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SL = "' + REPLACE(CAST(ISNULL(inserted.[SL],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLCo = "' + REPLACE(CAST(ISNULL(inserted.[SLCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLItem = "' + REPLACE(CAST(ISNULL(inserted.[SLItem],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.SLCo , 								'C' , 								'SLCo' , 								CONVERT(VARCHAR(MAX), deleted.[SLCo]) , 								CONVERT(VARCHAR(MAX), inserted.[SLCo]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[KeyID] = deleted.[KeyID] 
									AND ((inserted.[SLCo] <> deleted.[SLCo]) OR (inserted.[SLCo] IS NULL AND deleted.[SLCo] IS NOT NULL) OR (inserted.[SLCo] IS NOT NULL AND deleted.[SLCo] IS NULL))
								

							END 

							IF UPDATE([SLItem])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vSLClaimItem' , 								'<KeyString ClaimNo = "' + REPLACE(CAST(ISNULL(inserted.[ClaimNo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SL = "' + REPLACE(CAST(ISNULL(inserted.[SL],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLCo = "' + REPLACE(CAST(ISNULL(inserted.[SLCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLItem = "' + REPLACE(CAST(ISNULL(inserted.[SLItem],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.SLCo , 								'C' , 								'SLItem' , 								CONVERT(VARCHAR(MAX), deleted.[SLItem]) , 								CONVERT(VARCHAR(MAX), inserted.[SLItem]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[KeyID] = deleted.[KeyID] 
									AND ((inserted.[SLItem] <> deleted.[SLItem]) OR (inserted.[SLItem] IS NULL AND deleted.[SLItem] IS NOT NULL) OR (inserted.[SLItem] IS NOT NULL AND deleted.[SLItem] IS NULL))
								

							END 

							IF UPDATE([TaxAmount])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vSLClaimItem' , 								'<KeyString ClaimNo = "' + REPLACE(CAST(ISNULL(inserted.[ClaimNo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SL = "' + REPLACE(CAST(ISNULL(inserted.[SL],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLCo = "' + REPLACE(CAST(ISNULL(inserted.[SLCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLItem = "' + REPLACE(CAST(ISNULL(inserted.[SLItem],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.SLCo , 								'C' , 								'TaxAmount' , 								CONVERT(VARCHAR(MAX), deleted.[TaxAmount]) , 								CONVERT(VARCHAR(MAX), inserted.[TaxAmount]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[KeyID] = deleted.[KeyID] 
									AND ((inserted.[TaxAmount] <> deleted.[TaxAmount]) OR (inserted.[TaxAmount] IS NULL AND deleted.[TaxAmount] IS NOT NULL) OR (inserted.[TaxAmount] IS NOT NULL AND deleted.[TaxAmount] IS NULL))
								

							END 

							IF UPDATE([TaxCode])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vSLClaimItem' , 								'<KeyString ClaimNo = "' + REPLACE(CAST(ISNULL(inserted.[ClaimNo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SL = "' + REPLACE(CAST(ISNULL(inserted.[SL],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLCo = "' + REPLACE(CAST(ISNULL(inserted.[SLCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLItem = "' + REPLACE(CAST(ISNULL(inserted.[SLItem],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.SLCo , 								'C' , 								'TaxCode' , 								CONVERT(VARCHAR(MAX), deleted.[TaxCode]) , 								CONVERT(VARCHAR(MAX), inserted.[TaxCode]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[KeyID] = deleted.[KeyID] 
									AND ((inserted.[TaxCode] <> deleted.[TaxCode]) OR (inserted.[TaxCode] IS NULL AND deleted.[TaxCode] IS NOT NULL) OR (inserted.[TaxCode] IS NOT NULL AND deleted.[TaxCode] IS NULL))
								

							END 

							IF UPDATE([TaxGroup])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vSLClaimItem' , 								'<KeyString ClaimNo = "' + REPLACE(CAST(ISNULL(inserted.[ClaimNo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SL = "' + REPLACE(CAST(ISNULL(inserted.[SL],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLCo = "' + REPLACE(CAST(ISNULL(inserted.[SLCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLItem = "' + REPLACE(CAST(ISNULL(inserted.[SLItem],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.SLCo , 								'C' , 								'TaxGroup' , 								CONVERT(VARCHAR(MAX), deleted.[TaxGroup]) , 								CONVERT(VARCHAR(MAX), inserted.[TaxGroup]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[KeyID] = deleted.[KeyID] 
									AND ((inserted.[TaxGroup] <> deleted.[TaxGroup]) OR (inserted.[TaxGroup] IS NULL AND deleted.[TaxGroup] IS NOT NULL) OR (inserted.[TaxGroup] IS NOT NULL AND deleted.[TaxGroup] IS NULL))
								

							END 

							IF UPDATE([TaxType])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vSLClaimItem' , 								'<KeyString ClaimNo = "' + REPLACE(CAST(ISNULL(inserted.[ClaimNo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SL = "' + REPLACE(CAST(ISNULL(inserted.[SL],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLCo = "' + REPLACE(CAST(ISNULL(inserted.[SLCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLItem = "' + REPLACE(CAST(ISNULL(inserted.[SLItem],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.SLCo , 								'C' , 								'TaxType' , 								CONVERT(VARCHAR(MAX), deleted.[TaxType]) , 								CONVERT(VARCHAR(MAX), inserted.[TaxType]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[KeyID] = deleted.[KeyID] 
									AND ((inserted.[TaxType] <> deleted.[TaxType]) OR (inserted.[TaxType] IS NULL AND deleted.[TaxType] IS NOT NULL) OR (inserted.[TaxType] IS NOT NULL AND deleted.[TaxType] IS NULL))
								

							END 

							IF UPDATE([UM])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vSLClaimItem' , 								'<KeyString ClaimNo = "' + REPLACE(CAST(ISNULL(inserted.[ClaimNo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SL = "' + REPLACE(CAST(ISNULL(inserted.[SL],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLCo = "' + REPLACE(CAST(ISNULL(inserted.[SLCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SLItem = "' + REPLACE(CAST(ISNULL(inserted.[SLItem],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.SLCo , 								'C' , 								'UM' , 								CONVERT(VARCHAR(MAX), deleted.[UM]) , 								CONVERT(VARCHAR(MAX), inserted.[UM]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[KeyID] = deleted.[KeyID] 
									AND ((inserted.[UM] <> deleted.[UM]) OR (inserted.[UM] IS NULL AND deleted.[UM] IS NOT NULL) OR (inserted.[UM] IS NOT NULL AND deleted.[UM] IS NULL))
								

							END 



 END TRY 
 BEGIN CATCH 
   DECLARE	@ErrorMessage	NVARCHAR(4000), 
				@ErrorSeverity	INT; 

   SELECT	@ErrorMessage = 'Error '+ ISNULL(ERROR_MESSAGE(),'') +' in [dbo].[dbo.vtvSLClaimItem_Audit_Update] trigger', 
				@ErrorSeverity = ERROR_SEVERITY(); 

   RAISERROR(@ErrorMessage, @ErrorSeverity, 1 ) 
 END CATCH 
GO
EXEC sp_settriggerorder N'[dbo].[vtvSLClaimItem_Audit_Update]', 'last', 'update', null
GO
