//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewPointExcelAddIn.Dev {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CraftInfo", Namespace="http://schemas.datacontract.org/2004/07/McKinstry.ViewPoint.Data", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class CraftInfo : ViewPointExcelAddIn.Dev.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CraftField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EEOClassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long KeyIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal NewCapLimitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal OldCapLimitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte PRCoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SuperWeeklyMinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> UniqueAttchIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WghtAvgOTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string udShopYNField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Class {
            get {
                return this.ClassField;
            }
            set {
                if ((object.ReferenceEquals(this.ClassField, value) != true)) {
                    this.ClassField = value;
                    this.RaisePropertyChanged("Class");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Craft {
            get {
                return this.CraftField;
            }
            set {
                if ((object.ReferenceEquals(this.CraftField, value) != true)) {
                    this.CraftField = value;
                    this.RaisePropertyChanged("Craft");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EEOClass {
            get {
                return this.EEOClassField;
            }
            set {
                if ((object.ReferenceEquals(this.EEOClassField, value) != true)) {
                    this.EEOClassField = value;
                    this.RaisePropertyChanged("EEOClass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long KeyID {
            get {
                return this.KeyIDField;
            }
            set {
                if ((this.KeyIDField.Equals(value) != true)) {
                    this.KeyIDField = value;
                    this.RaisePropertyChanged("KeyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal NewCapLimit {
            get {
                return this.NewCapLimitField;
            }
            set {
                if ((this.NewCapLimitField.Equals(value) != true)) {
                    this.NewCapLimitField = value;
                    this.RaisePropertyChanged("NewCapLimit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Notes {
            get {
                return this.NotesField;
            }
            set {
                if ((object.ReferenceEquals(this.NotesField, value) != true)) {
                    this.NotesField = value;
                    this.RaisePropertyChanged("Notes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OldCapLimit {
            get {
                return this.OldCapLimitField;
            }
            set {
                if ((this.OldCapLimitField.Equals(value) != true)) {
                    this.OldCapLimitField = value;
                    this.RaisePropertyChanged("OldCapLimit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte PRCo {
            get {
                return this.PRCoField;
            }
            set {
                if ((this.PRCoField.Equals(value) != true)) {
                    this.PRCoField = value;
                    this.RaisePropertyChanged("PRCo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SuperWeeklyMin {
            get {
                return this.SuperWeeklyMinField;
            }
            set {
                if ((this.SuperWeeklyMinField.Equals(value) != true)) {
                    this.SuperWeeklyMinField = value;
                    this.RaisePropertyChanged("SuperWeeklyMin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> UniqueAttchID {
            get {
                return this.UniqueAttchIDField;
            }
            set {
                if ((this.UniqueAttchIDField.Equals(value) != true)) {
                    this.UniqueAttchIDField = value;
                    this.RaisePropertyChanged("UniqueAttchID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WghtAvgOT {
            get {
                return this.WghtAvgOTField;
            }
            set {
                if ((object.ReferenceEquals(this.WghtAvgOTField, value) != true)) {
                    this.WghtAvgOTField = value;
                    this.RaisePropertyChanged("WghtAvgOT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string udShopYN {
            get {
                return this.udShopYNField;
            }
            set {
                if ((object.ReferenceEquals(this.udShopYNField, value) != true)) {
                    this.udShopYNField = value;
                    this.RaisePropertyChanged("udShopYN");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StructuralObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ViewPointExcelAddIn.Dev.ComplexObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ViewPointExcelAddIn.Dev.MasterEarning))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ViewPointExcelAddIn.Dev.MasterDeduction))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ViewPointExcelAddIn.Dev.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ViewPointExcelAddIn.Dev.Deduction))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ViewPointExcelAddIn.Dev.Earning))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ViewPointExcelAddIn.Dev.ShiftRate))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ViewPointExcelAddIn.Dev.MasterCraft))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ViewPointExcelAddIn.Dev.CraftInfo))]
    public partial class StructuralObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ComplexObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ViewPointExcelAddIn.Dev.MasterEarning))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ViewPointExcelAddIn.Dev.MasterDeduction))]
    public partial class ComplexObject : ViewPointExcelAddIn.Dev.StructuralObject {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MasterEarning", Namespace="http://schemas.datacontract.org/2004/07/McKinstry.ViewPoint.Data", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class MasterEarning : ViewPointExcelAddIn.Dev.ComplexObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short EarnCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal FactorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MethodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte PRCoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short EarnCode {
            get {
                return this.EarnCodeField;
            }
            set {
                if ((this.EarnCodeField.Equals(value) != true)) {
                    this.EarnCodeField = value;
                    this.RaisePropertyChanged("EarnCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Factor {
            get {
                return this.FactorField;
            }
            set {
                if ((this.FactorField.Equals(value) != true)) {
                    this.FactorField = value;
                    this.RaisePropertyChanged("Factor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Method {
            get {
                return this.MethodField;
            }
            set {
                if ((object.ReferenceEquals(this.MethodField, value) != true)) {
                    this.MethodField = value;
                    this.RaisePropertyChanged("Method");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte PRCo {
            get {
                return this.PRCoField;
            }
            set {
                if ((this.PRCoField.Equals(value) != true)) {
                    this.PRCoField = value;
                    this.RaisePropertyChanged("PRCo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MasterDeduction", Namespace="http://schemas.datacontract.org/2004/07/McKinstry.ViewPoint.Data", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class MasterDeduction : ViewPointExcelAddIn.Dev.ComplexObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short DLCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DLTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MethodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte PRCoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short DLCode {
            get {
                return this.DLCodeField;
            }
            set {
                if ((this.DLCodeField.Equals(value) != true)) {
                    this.DLCodeField = value;
                    this.RaisePropertyChanged("DLCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DLType {
            get {
                return this.DLTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.DLTypeField, value) != true)) {
                    this.DLTypeField = value;
                    this.RaisePropertyChanged("DLType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Method {
            get {
                return this.MethodField;
            }
            set {
                if ((object.ReferenceEquals(this.MethodField, value) != true)) {
                    this.MethodField = value;
                    this.RaisePropertyChanged("Method");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte PRCo {
            get {
                return this.PRCoField;
            }
            set {
                if ((this.PRCoField.Equals(value) != true)) {
                    this.PRCoField = value;
                    this.RaisePropertyChanged("PRCo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ViewPointExcelAddIn.Dev.Deduction))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ViewPointExcelAddIn.Dev.Earning))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ViewPointExcelAddIn.Dev.ShiftRate))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ViewPointExcelAddIn.Dev.MasterCraft))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ViewPointExcelAddIn.Dev.CraftInfo))]
    public partial class EntityObject : ViewPointExcelAddIn.Dev.StructuralObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ViewPointExcelAddIn.Dev.EntityKey EntityKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ViewPointExcelAddIn.Dev.EntityKey EntityKey {
            get {
                return this.EntityKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyField, value) != true)) {
                    this.EntityKeyField = value;
                    this.RaisePropertyChanged("EntityKey");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Deduction", Namespace="http://schemas.datacontract.org/2004/07/McKinstry.ViewPoint.Data", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Deduction : ViewPointExcelAddIn.Dev.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CraftField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short DLCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal FactorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long KeyIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal NewRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal OldRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte PRCoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> UniqueAttchIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Class {
            get {
                return this.ClassField;
            }
            set {
                if ((object.ReferenceEquals(this.ClassField, value) != true)) {
                    this.ClassField = value;
                    this.RaisePropertyChanged("Class");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Craft {
            get {
                return this.CraftField;
            }
            set {
                if ((object.ReferenceEquals(this.CraftField, value) != true)) {
                    this.CraftField = value;
                    this.RaisePropertyChanged("Craft");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short DLCode {
            get {
                return this.DLCodeField;
            }
            set {
                if ((this.DLCodeField.Equals(value) != true)) {
                    this.DLCodeField = value;
                    this.RaisePropertyChanged("DLCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Factor {
            get {
                return this.FactorField;
            }
            set {
                if ((this.FactorField.Equals(value) != true)) {
                    this.FactorField = value;
                    this.RaisePropertyChanged("Factor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long KeyID {
            get {
                return this.KeyIDField;
            }
            set {
                if ((this.KeyIDField.Equals(value) != true)) {
                    this.KeyIDField = value;
                    this.RaisePropertyChanged("KeyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal NewRate {
            get {
                return this.NewRateField;
            }
            set {
                if ((this.NewRateField.Equals(value) != true)) {
                    this.NewRateField = value;
                    this.RaisePropertyChanged("NewRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OldRate {
            get {
                return this.OldRateField;
            }
            set {
                if ((this.OldRateField.Equals(value) != true)) {
                    this.OldRateField = value;
                    this.RaisePropertyChanged("OldRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte PRCo {
            get {
                return this.PRCoField;
            }
            set {
                if ((this.PRCoField.Equals(value) != true)) {
                    this.PRCoField = value;
                    this.RaisePropertyChanged("PRCo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> UniqueAttchID {
            get {
                return this.UniqueAttchIDField;
            }
            set {
                if ((this.UniqueAttchIDField.Equals(value) != true)) {
                    this.UniqueAttchIDField = value;
                    this.RaisePropertyChanged("UniqueAttchID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Earning", Namespace="http://schemas.datacontract.org/2004/07/McKinstry.ViewPoint.Data", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Earning : ViewPointExcelAddIn.Dev.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CraftField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short EarnCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal FactorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long KeyIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal NewRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal OldRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte PRCoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> UniqueAttchIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Class {
            get {
                return this.ClassField;
            }
            set {
                if ((object.ReferenceEquals(this.ClassField, value) != true)) {
                    this.ClassField = value;
                    this.RaisePropertyChanged("Class");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Craft {
            get {
                return this.CraftField;
            }
            set {
                if ((object.ReferenceEquals(this.CraftField, value) != true)) {
                    this.CraftField = value;
                    this.RaisePropertyChanged("Craft");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short EarnCode {
            get {
                return this.EarnCodeField;
            }
            set {
                if ((this.EarnCodeField.Equals(value) != true)) {
                    this.EarnCodeField = value;
                    this.RaisePropertyChanged("EarnCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Factor {
            get {
                return this.FactorField;
            }
            set {
                if ((this.FactorField.Equals(value) != true)) {
                    this.FactorField = value;
                    this.RaisePropertyChanged("Factor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long KeyID {
            get {
                return this.KeyIDField;
            }
            set {
                if ((this.KeyIDField.Equals(value) != true)) {
                    this.KeyIDField = value;
                    this.RaisePropertyChanged("KeyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal NewRate {
            get {
                return this.NewRateField;
            }
            set {
                if ((this.NewRateField.Equals(value) != true)) {
                    this.NewRateField = value;
                    this.RaisePropertyChanged("NewRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OldRate {
            get {
                return this.OldRateField;
            }
            set {
                if ((this.OldRateField.Equals(value) != true)) {
                    this.OldRateField = value;
                    this.RaisePropertyChanged("OldRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte PRCo {
            get {
                return this.PRCoField;
            }
            set {
                if ((this.PRCoField.Equals(value) != true)) {
                    this.PRCoField = value;
                    this.RaisePropertyChanged("PRCo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> UniqueAttchID {
            get {
                return this.UniqueAttchIDField;
            }
            set {
                if ((this.UniqueAttchIDField.Equals(value) != true)) {
                    this.UniqueAttchIDField = value;
                    this.RaisePropertyChanged("UniqueAttchID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShiftRate", Namespace="http://schemas.datacontract.org/2004/07/McKinstry.ViewPoint.Data", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class ShiftRate : ViewPointExcelAddIn.Dev.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CraftField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long KeyIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal NewRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal OldRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte PRCoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte ShiftField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> UniqueAttchIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Class {
            get {
                return this.ClassField;
            }
            set {
                if ((object.ReferenceEquals(this.ClassField, value) != true)) {
                    this.ClassField = value;
                    this.RaisePropertyChanged("Class");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Craft {
            get {
                return this.CraftField;
            }
            set {
                if ((object.ReferenceEquals(this.CraftField, value) != true)) {
                    this.CraftField = value;
                    this.RaisePropertyChanged("Craft");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long KeyID {
            get {
                return this.KeyIDField;
            }
            set {
                if ((this.KeyIDField.Equals(value) != true)) {
                    this.KeyIDField = value;
                    this.RaisePropertyChanged("KeyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal NewRate {
            get {
                return this.NewRateField;
            }
            set {
                if ((this.NewRateField.Equals(value) != true)) {
                    this.NewRateField = value;
                    this.RaisePropertyChanged("NewRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OldRate {
            get {
                return this.OldRateField;
            }
            set {
                if ((this.OldRateField.Equals(value) != true)) {
                    this.OldRateField = value;
                    this.RaisePropertyChanged("OldRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte PRCo {
            get {
                return this.PRCoField;
            }
            set {
                if ((this.PRCoField.Equals(value) != true)) {
                    this.PRCoField = value;
                    this.RaisePropertyChanged("PRCo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte Shift {
            get {
                return this.ShiftField;
            }
            set {
                if ((this.ShiftField.Equals(value) != true)) {
                    this.ShiftField = value;
                    this.RaisePropertyChanged("Shift");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> UniqueAttchID {
            get {
                return this.UniqueAttchIDField;
            }
            set {
                if ((this.UniqueAttchIDField.Equals(value) != true)) {
                    this.UniqueAttchIDField = value;
                    this.RaisePropertyChanged("UniqueAttchID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MasterCraft", Namespace="http://schemas.datacontract.org/2004/07/McKinstry.ViewPoint.Data", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class MasterCraft : ViewPointExcelAddIn.Dev.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CraftField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte PRCoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<byte> VendorGroupField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Craft {
            get {
                return this.CraftField;
            }
            set {
                if ((object.ReferenceEquals(this.CraftField, value) != true)) {
                    this.CraftField = value;
                    this.RaisePropertyChanged("Craft");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte PRCo {
            get {
                return this.PRCoField;
            }
            set {
                if ((this.PRCoField.Equals(value) != true)) {
                    this.PRCoField = value;
                    this.RaisePropertyChanged("PRCo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> VendorGroup {
            get {
                return this.VendorGroupField;
            }
            set {
                if ((this.VendorGroupField.Equals(value) != true)) {
                    this.VendorGroupField = value;
                    this.RaisePropertyChanged("VendorGroup");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKey", Namespace="http://schemas.datacontract.org/2004/07/System.Data", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class EntityKey : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntityContainerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ViewPointExcelAddIn.Dev.EntityKeyMember> EntityKeyValuesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntitySetNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntityContainerName {
            get {
                return this.EntityContainerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityContainerNameField, value) != true)) {
                    this.EntityContainerNameField = value;
                    this.RaisePropertyChanged("EntityContainerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ViewPointExcelAddIn.Dev.EntityKeyMember> EntityKeyValues {
            get {
                return this.EntityKeyValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyValuesField, value) != true)) {
                    this.EntityKeyValuesField = value;
                    this.RaisePropertyChanged("EntityKeyValues");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntitySetName {
            get {
                return this.EntitySetNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntitySetNameField, value) != true)) {
                    this.EntitySetNameField = value;
                    this.RaisePropertyChanged("EntitySetName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKeyMember", Namespace="http://schemas.datacontract.org/2004/07/System.Data")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ViewPointExcelAddIn.Dev.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ViewPointExcelAddIn.Dev.StructuralObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ViewPointExcelAddIn.Dev.ComplexObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<ViewPointExcelAddIn.Dev.CraftInfo>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ViewPointExcelAddIn.Dev.CraftInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<ViewPointExcelAddIn.Dev.Deduction>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ViewPointExcelAddIn.Dev.Deduction))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<ViewPointExcelAddIn.Dev.Earning>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ViewPointExcelAddIn.Dev.Earning))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<ViewPointExcelAddIn.Dev.ShiftRate>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ViewPointExcelAddIn.Dev.ShiftRate))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<ViewPointExcelAddIn.Dev.MasterEarning>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ViewPointExcelAddIn.Dev.MasterEarning))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<ViewPointExcelAddIn.Dev.MasterDeduction>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ViewPointExcelAddIn.Dev.MasterDeduction))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<ViewPointExcelAddIn.Dev.MasterCraft>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ViewPointExcelAddIn.Dev.MasterCraft))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ViewPointExcelAddIn.Dev.EntityKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<ViewPointExcelAddIn.Dev.EntityKeyMember>))]
    public partial class EntityKeyMember : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Dev.IUnionClassService")]
    public interface IUnionClassService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnionClassService/AddUpdateCraftClass", ReplyAction="http://tempuri.org/IUnionClassService/AddUpdateCraftClassResponse")]
        void AddUpdateCraftClass(System.Collections.Generic.List<ViewPointExcelAddIn.Dev.CraftInfo> craftclasses);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnionClassService/AddUpdateDeductions", ReplyAction="http://tempuri.org/IUnionClassService/AddUpdateDeductionsResponse")]
        void AddUpdateDeductions(System.Collections.Generic.List<ViewPointExcelAddIn.Dev.Deduction> deduction);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnionClassService/AddUpdateEarnings", ReplyAction="http://tempuri.org/IUnionClassService/AddUpdateEarningsResponse")]
        void AddUpdateEarnings(System.Collections.Generic.List<ViewPointExcelAddIn.Dev.Earning> earnings);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnionClassService/AddUpdateShiftRate", ReplyAction="http://tempuri.org/IUnionClassService/AddUpdateShiftRateResponse")]
        void AddUpdateShiftRate(System.Collections.Generic.List<ViewPointExcelAddIn.Dev.ShiftRate> shiftrates);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnionClassService/GetMasterEarnings", ReplyAction="http://tempuri.org/IUnionClassService/GetMasterEarningsResponse")]
        System.Collections.Generic.List<ViewPointExcelAddIn.Dev.MasterEarning> GetMasterEarnings();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnionClassService/GetMasterDeductions", ReplyAction="http://tempuri.org/IUnionClassService/GetMasterDeductionsResponse")]
        System.Collections.Generic.List<ViewPointExcelAddIn.Dev.MasterDeduction> GetMasterDeductions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnionClassService/GetMasterCrafts", ReplyAction="http://tempuri.org/IUnionClassService/GetMasterCraftsResponse")]
        System.Collections.Generic.List<ViewPointExcelAddIn.Dev.MasterCraft> GetMasterCrafts();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUnionClassServiceChannel : ViewPointExcelAddIn.Dev.IUnionClassService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UnionClassServiceClient : System.ServiceModel.ClientBase<ViewPointExcelAddIn.Dev.IUnionClassService>, ViewPointExcelAddIn.Dev.IUnionClassService {
        
        public UnionClassServiceClient() {
        }
        
        public UnionClassServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UnionClassServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UnionClassServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UnionClassServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddUpdateCraftClass(System.Collections.Generic.List<ViewPointExcelAddIn.Dev.CraftInfo> craftclasses) {
            base.Channel.AddUpdateCraftClass(craftclasses);
        }
        
        public void AddUpdateDeductions(System.Collections.Generic.List<ViewPointExcelAddIn.Dev.Deduction> deduction) {
            base.Channel.AddUpdateDeductions(deduction);
        }
        
        public void AddUpdateEarnings(System.Collections.Generic.List<ViewPointExcelAddIn.Dev.Earning> earnings) {
            base.Channel.AddUpdateEarnings(earnings);
        }
        
        public void AddUpdateShiftRate(System.Collections.Generic.List<ViewPointExcelAddIn.Dev.ShiftRate> shiftrates) {
            base.Channel.AddUpdateShiftRate(shiftrates);
        }
        
        public System.Collections.Generic.List<ViewPointExcelAddIn.Dev.MasterEarning> GetMasterEarnings() {
            return base.Channel.GetMasterEarnings();
        }
        
        public System.Collections.Generic.List<ViewPointExcelAddIn.Dev.MasterDeduction> GetMasterDeductions() {
            return base.Channel.GetMasterDeductions();
        }
        
        public System.Collections.Generic.List<ViewPointExcelAddIn.Dev.MasterCraft> GetMasterCrafts() {
            return base.Channel.GetMasterCrafts();
        }
    }
}
