<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="asp" %>
<%@ Page Language="C#" EnableEventValidation="false" AutoEventWireup="false" Codebehind="SignInMobile.aspx.cs" Culture="en-US" MasterPageFile="../Master Pages/Mobile.master" Inherits="ViewpointXRef.UI.SignInMobile" %>
<%@ Register Tagprefix="Selectors" Namespace="ViewpointXRef" Assembly="ViewpointXRef" %>

<%@ Register Tagprefix="ViewpointXRef" TagName="ThemeButtonMobile" Src="../Shared/ThemeButtonMobile.ascx" %>

<%@ Register Tagprefix="BaseClasses" Namespace="BaseClasses.Web.UI.WebControls" Assembly="BaseClasses" %><asp:Content id="Content" ContentPlaceHolderID="PageContent" runat="server">
    <a id="StartOfPageContent"></a>
          <table cellpadding="0" cellspacing="0" border="0" width="100%"><tr><td><table class="mobileHeader" cellpadding="0" cellspacing="0" border="0" width="100%"><tr><td class="mobileHeaderLeft"><ViewpointXRef:ThemeButtonMobile runat="server" id="MenuButton" button-causesvalidation="False" button-commandname="Redirect" button-text="&lt;%# GetResourceValue(&quot;Btn:Menu&quot;, &quot;ViewpointXRef&quot;) %>" button-tooltip="&lt;%# GetResourceValue(&quot;Btn:Menu&quot;, &quot;ViewpointXRef&quot;) %>" postback="False"></ViewpointXRef:ThemeButtonMobile></td><td class="mobileHeaderTitle"><asp:Literal runat="server" id="DialogTitle" Text="&lt;%# GetResourceValue(&quot;Txt:SignIn&quot;, &quot;ViewpointXRef&quot;) %>">	</asp:Literal></td><td class="mobileHeaderRight"><asp:ImageButton runat="server" id="OKButton" button-tooltip="&lt;%# GetResourceValue(&quot;Btn:OK&quot;, &quot;ViewpointXRef&quot;) %>" causesvalidation="True" commandname="Login" imageurl="../Images/MobileButtonOK.png">		
	</asp:ImageButton></td></tr></table>
</td></tr><tr><td><%= SystemUtils.GenerateEnterKeyCaptureBeginTag(FindControlRecursively("OKButton")) %><asp:panel id="SignInCollapsibleRegion" runat="server"><table cellpadding="0" cellspacing="0" border="0" width="100%"><tr><td class="mobileBody"><table cellpadding="1" cellspacing="1" border="0" width="100%" class="mobileBody"><tr><td colspan="2" style="height: 5px;" class="mobileBodyText"></td></tr><tr><td class="mobileBodyText" colspan="2"><asp:Label runat="server" id="LoginMessage">	</asp:Label></td></tr><tr><td colspan="2" style="height: 5px;" class="mobileBodyText"></td></tr><tr><td colspan="2" class="mobileFieldLabelOnTop"><asp:Label runat="server" id="UserNameLabel" Text="&lt;%# GetResourceValue(&quot;Txt:UserName&quot;, &quot;ViewpointXRef&quot;) %>">	</asp:Label></td></tr><tr><td class="mobileFieldValueOnBottom" colspan="2"><asp:TextBox runat="server" id="UserName" columns="20" commandname="TextBoxUserName_Command" cssclass="mobileFieldInput">	</asp:TextBox>
	<asp:RequiredFieldValidator runat="server" id="UserNameRequiredFieldValidator" ControlToValidate="UserName" ErrorMessage="&lt;%# GetResourceValue(&quot;Val:ValueIsRequired&quot;, &quot;ViewpointXRef&quot;).Replace(&quot;{FieldName}&quot;, &quot;UserName&quot;) %>" display="None" enabled="True">	</asp:RequiredFieldValidator></td></tr><tr><td colspan="2" style="height: 5px;" class="mobileBodyText"></td></tr><tr><td colspan="2" class="mobileFieldLabelOnTop"><asp:Label runat="server" id="PasswordLabel" Text="&lt;%# GetResourceValue(&quot;Txt:Password&quot;, &quot;ViewpointXRef&quot;) %>">	</asp:Label></td></tr><tr><td class="mobileFieldValueOnBottom" colspan="2"><asp:TextBox runat="server" id="Password" columns="20" commandname="TextBoxPassword_Command" cssclass="mobileFieldInput" textmode="Password">	</asp:TextBox>
	<asp:RequiredFieldValidator runat="server" id="PasswordRequiredFieldValidator" ControlToValidate="Password" ErrorMessage="&lt;%# GetResourceValue(&quot;Val:ValueIsRequired&quot;, &quot;ViewpointXRef&quot;).Replace(&quot;{FieldName}&quot;, &quot;Password&quot;) %>" display="None" enabled="True">	</asp:RequiredFieldValidator></td></tr><tr><td colspan="2" style="height: 15px;" class="mobileBodyText"></td></tr><tr><td colspan="2">
<span class="mobileFontAdjust80">
<asp:LinkButton runat="server" id="EmailLinkButton" causesvalidation="False" commandname="ForgotUser" consumers="page" cssclass="mobileLink" text="&lt;%# GetResourceValue(&quot;Txt:ForgotPassword&quot;, &quot;ViewpointXRef&quot;) %>">		
	</asp:LinkButton>
</span>
</td></tr><tr><td colspan="2"><br /></td></tr><tr><td class="mobileFieldLabelOnLeft"><asp:CheckBox runat="server" id="AutomaticallySignIn" commandname="CheckBoxAutoLogin_Command" cssclass="mobileCheckbox" postback="True">	</asp:CheckBox></td><td class="mobileFieldLabelOnRight"><asp:Label runat="server" id="AutomaticallySignInLabel" Text="&lt;%# GetResourceValue(&quot;Txt:AutoLogin&quot;, &quot;ViewpointXRef&quot;) %>">	</asp:Label></td></tr><tr><td class="mobileFieldLabelOnLeft"><asp:CheckBox runat="server" id="RememberUserName" commandname="CheckBoxUN_Command" cssclass="mobileCheckbox" postback="True">	</asp:CheckBox></td><td class="mobileFieldLabelOnRight"><asp:Label runat="server" id="RememberUserNameLabel" Text="&lt;%# GetResourceValue(&quot;Txt:RememberUN&quot;, &quot;ViewpointXRef&quot;) %>">	</asp:Label></td></tr><tr><td class="mobileFieldLabelOnLeft"><asp:CheckBox runat="server" id="RememberPassword" commandname="CheckBoxPass_Command" cssclass="mobileCheckbox" postback="True">	</asp:CheckBox></td><td class="mobileFieldLabelOnRight"><asp:Label runat="server" id="RememberPasswordLabel" Text="&lt;%# GetResourceValue(&quot;Txt:RememberPassword&quot;, &quot;ViewpointXRef&quot;) %>">	</asp:Label></td></tr><tr><td colspan="2" style="height: 5px;" class="mobileBodyText"></td></tr><tr><td style="height: 5px;" class="mobileBodyText"></td><td class="mobileBodyText"><asp:Label runat="server" id="PasswordMessage">	</asp:Label></td></tr></table>
</td></tr></table></asp:panel>
<%= SystemUtils.GenerateEnterKeyCaptureEndTag(FindControlRecursively("OKButton")) %></td></tr></table><div id="detailPopup" class="detailRolloverPopup" onmouseout="detailRolloverPopupClose();" onmouseover="clearTimeout(gPopupTimer);"></div>          
        <asp:ValidationSummary id="ValidationSummary1" ShowMessageBox="true" ShowSummary="false" runat="server"></asp:ValidationSummary>
    </asp:Content>
          