CREATE TABLE [dbo].[vDDCB]
(
[ComboType] [varchar] (20) COLLATE Latin1_General_BIN NOT NULL,
[Description] [varchar] (30) COLLATE Latin1_General_BIN NULL
) ON [PRIMARY]
CREATE UNIQUE CLUSTERED INDEX [viDDCB] ON [dbo].[vDDCB] ([ComboType]) WITH (FILLFACTOR=90) ON [PRIMARY]

GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO




CREATE   trigger [dbo].[vtDDCBd] on [dbo].[vDDCB] for DELETE
/************************************
* Created: MJ 1/11/05
* Modified: 
*
* Delete trigger on vDDCB (DD ComboTypes)
*
* Rejects deletion if any of the following conditions exist:
*	ComboItems (DDCI) Exist
*	Exists in a DDFI entry
*
* Adds DD Audit entry
*
************************************/
as



declare @errmsg varchar(255)
  
if @@rowcount = 0 return
set nocount on

-- check ComboTypes
if exists(select top 1 1 from deleted d join dbo.vDDCI i (nolock) on d.ComboType = i.ComboType)
	begin
  	select @errmsg = 'ComboType Items exist (vDDCI)'
  	goto error
  	end
  
-- check Form Inputs 
if exists (select top 1 1 from deleted d join dbo.vDDFI i (nolock) on d.ComboType = i.ComboType)
  	begin
  	select @errmsg = 'In use on Form Inputs (vDDFI)'
  	goto error
  	end
  	
-- DD Audit 
insert dbo.vDDDA (TableName, Action, KeyString, FieldName,
	OldValue, NewValue, RevDate, UserName, HostName)
select 'vDDCB', 'D', 'ComboType: ' + rtrim(ComboType), null,
	null, null, getdate(), SUSER_SNAME(), host_name()
from deleted
  
return
  
error:
	select @errmsg = isnull(@errmsg,'') + ' - cannot delete ComboType!'
    RAISERROR(@errmsg, 11, -1);
    rollback transaction
  
  
  
  
 







GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[vtDDCBd_Audit] ON [dbo].[vDDCB]
 AFTER DELETE
 NOT FOR REPLICATION AS
 SET NOCOUNT ON 
 -- generated by vspHQCreateAuditTriggers on May 14 2009  9:56AM

 BEGIN TRY 
   INSERT dbo.vDDChangeLog (TableName, KeyString, Action, FieldName, OldValue, NewValue, DateTime, MachineName, CommandText)
   SELECT 'vDDCB' , '<KeyString ComboBoxType = "' + REPLACE(CAST(deleted.ComboType AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 'D' , NULL , NULL , NULL , GETDATE() , HOST_NAME() , 'DELETE FROM vDDCB WHERE ComboType = ''' + CAST(deleted.ComboType AS VARCHAR(MAX)) + ''''
	FROM deleted
 END TRY 
 BEGIN CATCH 
   RAISERROR('Error in [dbo].[dbo.vtDDCBi_Audit] trigger', 16, 1 ) with log
 END CATCH 
GO
EXEC sp_settriggerorder N'[dbo].[vtDDCBd_Audit]', 'last', 'delete', null
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO






CREATE    trigger [dbo].[vtDDCBi] on [dbo].[vDDCB] for INSERT
/*****************************
* Created: MJ 1/11/05
* Modified:
*
* Insert trigger on vDDCB (DD ComboTypes)
*
* Rejects insert if the following conditions exist:
*	
* Adds DD Audit entry
*
*************************************/

as


declare @errmsg varchar(255), @numrows int
  
select @numrows = @@rowcount
if @numrows = 0 return

set nocount on

  
-- DD Audit  
insert vDDDA (TableName, Action, KeyString, FieldName, OldValue, 
  	NewValue, RevDate, UserName, HostName)
select 'vDDCB', 'I', 'ComboType: ' + rtrim(ComboType), null, null,
	null, getdate(), SUSER_SNAME(), host_name()
from inserted 
  	 	 	 
return

error:
	select @errmsg = isnull(@errmsg,'') + ' - cannot insert Combination Header!'
  	RAISERROR(@errmsg, 11, -1);
  	rollback transaction
  
    







GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[vtDDCBi_Audit] ON [dbo].[vDDCB]
 AFTER INSERT
 NOT FOR REPLICATION AS
 SET NOCOUNT ON 
 -- generated by vspHQCreateAuditTriggers on May 14 2009  9:56AM

 BEGIN TRY 
   INSERT dbo.vDDChangeLog (TableName, KeyString, Action, FieldName, OldValue, NewValue, DateTime, MachineName, CommandText)
   SELECT 'vDDCB' , '<KeyString ComboBoxType = "' + REPLACE(CAST(inserted.ComboType AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 'A' , NULL , NULL , NULL , GETDATE() , HOST_NAME() , 'INSERT INTO dbo.[vDDCB] ([ComboType], [Description]) VALUES (' + ISNULL('''' + REPLACE(CAST(ComboType AS NVARCHAR(MAX)), '''' , '''''') + '''', 'NULL') + ',' + ISNULL('''' + REPLACE(CAST(Description AS NVARCHAR(MAX)), '''' , '''''') + '''', 'NULL')  + ')'
	FROM inserted
 END TRY 
 BEGIN CATCH 
   RAISERROR('Error in [dbo].[dbo.vtDDCBi_Audit] trigger', 16, 1 ) with log
 END CATCH 
GO
EXEC sp_settriggerorder N'[dbo].[vtDDCBi_Audit]', 'last', 'insert', null
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO



CREATE trigger [dbo].[vtDDCBu] on [dbo].[vDDCB] for UPDATE
/************************************
* Created: MJ 1/11/04
* Modified: 
*
* Update trigger on vDDCB (DD ComboTypes)
*
* Rejects update if any of the following conditions exist:
*	Change ComboType name
*
* Adds DD Audit entries for changed values
*
************************************/

as


declare @errmsg varchar(255), @numrows int, @validcnt int 
  
select @numrows = @@rowcount
if @numrows = 0 return
set nocount on
  
-- check for key changes 
select @validcnt = count(*) from inserted i join deleted d on i.ComboType = d.ComboType
if @validcnt <> @numrows
	begin
  	select @errmsg = 'Cannot change ComboType'
  	goto error
  	end
  	
-- DD Audit
if update(Description)
	insert dbo.vDDDA(TableName, Action, KeyString, FieldName,
		OldValue, NewValue, RevDate, UserName, HostName)
	select  'vDDCB', 'U', 'ComboType: ' + rtrim(i.ComboType), 'Description',
		d.Description, i.Description, getdate(), SUSER_SNAME(), host_name()
  	from inserted i
  	join deleted d on i.ComboType = d.ComboType 
  	where isnull(i.Description,'') <> isnull(d.Description,'')

return
  
error:
	select @errmsg = isnull(@errmsg,'') + ' - cannot update ComboType!'
    RAISERROR(@errmsg, 11, -1);
    rollback transaction
  
  
  
  
 





GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[vtDDCBu_Audit] ON [dbo].[vDDCB]
 AFTER UPDATE 
 NOT FOR REPLICATION AS 
 SET NOCOUNT ON 
 -- generated by vspHQCreateAuditTriggers on May 14 2009  9:56AM

 BEGIN TRY 
 IF UPDATE([ComboType])
   INSERT dbo.vDDChangeLog (TableName, KeyString, Action, FieldName, OldValue, NewValue, DateTime, MachineName, CommandText)
   SELECT 'vDDCB' , '<KeyString ComboBoxType = "' + REPLACE(CAST(inserted.ComboType AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 'U' , 'ComboType' ,  CONVERT(VARCHAR(MAX), deleted.[ComboType]) ,  Convert(VARCHAR(MAX), inserted.[ComboType]) , GETDATE() , HOST_NAME() , 'UPDATE vDDCB SET ComboType = ''' + ISNULL(REPLACE(Convert(VARCHAR(MAX), inserted.[ComboType]), '''' , ''''''), 'NULL') + ''' WHERE ComboType = ''' + CAST(inserted.ComboType AS VARCHAR(MAX)) + ''''
		FROM inserted
			INNER JOIN deleted
         ON  inserted.[ComboType] = deleted.[ComboType] 
         AND ISNULL(inserted.[ComboType],'') <> ISNULL(deleted.[ComboType],'')

 IF UPDATE([Description])
   INSERT dbo.vDDChangeLog (TableName, KeyString, Action, FieldName, OldValue, NewValue, DateTime, MachineName, CommandText)
   SELECT 'vDDCB' , '<KeyString ComboBoxType = "' + REPLACE(CAST(inserted.ComboType AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 'U' , 'Description' ,  CONVERT(VARCHAR(MAX), deleted.[Description]) ,  Convert(VARCHAR(MAX), inserted.[Description]) , GETDATE() , HOST_NAME() , 'UPDATE vDDCB SET Description = ''' + ISNULL(REPLACE(Convert(VARCHAR(MAX), inserted.[Description]), '''' , ''''''), 'NULL') + ''' WHERE ComboType = ''' + CAST(inserted.ComboType AS VARCHAR(MAX)) + ''''
		FROM inserted
			INNER JOIN deleted
         ON  inserted.[ComboType] = deleted.[ComboType] 
         AND ISNULL(inserted.[Description],'') <> ISNULL(deleted.[Description],'')

 END TRY 
 BEGIN CATCH 
   RAISERROR('Error in [dbo].[dbo.vtDDCBi_Audit] trigger', 16, 1 ) with log
 END CATCH 
GO
EXEC sp_settriggerorder N'[dbo].[vtDDCBu_Audit]', 'last', 'update', null
GO
