CREATE TABLE [dbo].[TempCraftClassLoad]
(
[CraftMaster] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[Trade] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[Notes] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[Region] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[Home_Port] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[RateCode] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[Level] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[CraftClassCode] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[Description] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[EEOClass] [nvarchar] (255) COLLATE Latin1_General_BIN NULL,
[Shift1BaseRate] [float] NULL,
[Shift2BaseRate] [float] NULL,
[Shift3BaseRate] [float] NULL,
[AddOn1Code] [float] NULL,
[AddOn1Amt] [float] NULL,
[AddOn2Code] [float] NULL,
[AddOn2Amt] [float] NULL,
[Ded_LiabCode1] [float] NULL,
[Ded_LiabAmt1] [float] NULL,
[Ded_LiabCode2] [float] NULL,
[Ded_LiabAmt2] [float] NULL,
[Ded_LiabCode3] [float] NULL,
[Ded_LiabAmt3] [float] NULL,
[Ded_LiabCode4] [float] NULL,
[Ded_LiabAmt4] [float] NULL,
[Ded_LiabCode5] [float] NULL,
[Ded_LiabAmt5] [float] NULL,
[Ded_LiabCode6] [float] NULL,
[Ded_LiabAmt6] [float] NULL,
[Ded_LiabCode7] [float] NULL,
[Ded_LiabAmt7] [float] NULL,
[Ded_LiabCode8] [float] NULL,
[Ded_LiabAmt8] [float] NULL,
[Ded_LiabCode9] [float] NULL,
[Ded_LiabAmt9] [float] NULL,
[Ded_LiabCode10] [float] NULL,
[Ded_LiabAmt10] [float] NULL,
[Ded_LiabCode11] [float] NULL,
[Ded_LiabAmt11] [float] NULL
) ON [PRIMARY]
GO
