CREATE TABLE [dbo].[bPMHA]
(
[PMHIKeyId] [bigint] NOT NULL,
[AttachmentID] [int] NOT NULL
) ON [PRIMARY]
ALTER TABLE [dbo].[bPMHA] ADD 
CONSTRAINT [PK_bPMHA] PRIMARY KEY CLUSTERED  ([PMHIKeyId], [AttachmentID]) WITH (FILLFACTOR=90) ON [PRIMARY]
ALTER TABLE [dbo].[bPMHA] WITH NOCHECK ADD
CONSTRAINT [FK_bPMHA_bPMHI] FOREIGN KEY ([PMHIKeyId]) REFERENCES [dbo].[bPMHI] ([KeyId])
GO
