CREATE TABLE [dbo].[vSMDepartmentOverrides]
(
[SMDepartmentOverridesID] [bigint] NOT NULL IDENTITY(1, 1),
[SMCo] [dbo].[bCompany] NOT NULL,
[Department] [dbo].[bDept] NOT NULL,
[Seq] [tinyint] NOT NULL,
[LineType] [tinyint] NOT NULL,
[CallType] [varchar] (10) COLLATE Latin1_General_BIN NULL,
[CostType] [smallint] NULL,
[GLCo] [dbo].[bCompany] NOT NULL,
[CostGLAcct] [dbo].[bGLAcct] NOT NULL,
[RevenueGLAcct] [dbo].[bGLAcct] NOT NULL,
[CostWIPGLAcct] [dbo].[bGLAcct] NOT NULL,
[RevenueWIPGLAcct] [dbo].[bGLAcct] NOT NULL,
[UniqueAttchID] [uniqueidentifier] NULL
) ON [PRIMARY]
ALTER TABLE [dbo].[vSMDepartmentOverrides] WITH NOCHECK ADD
CONSTRAINT [FK_vSMDepartmentOverrides_bGLAC_CostGLAcct] FOREIGN KEY ([GLCo], [CostGLAcct]) REFERENCES [dbo].[bGLAC] ([GLCo], [GLAcct])
ALTER TABLE [dbo].[vSMDepartmentOverrides] WITH NOCHECK ADD
CONSTRAINT [FK_vSMDepartmentOverrides_bGLAC_CostWIPGLAcct] FOREIGN KEY ([GLCo], [CostWIPGLAcct]) REFERENCES [dbo].[bGLAC] ([GLCo], [GLAcct])
ALTER TABLE [dbo].[vSMDepartmentOverrides] WITH NOCHECK ADD
CONSTRAINT [FK_vSMDepartmentOverrides_bGLAC_RevenueGLAcct] FOREIGN KEY ([GLCo], [RevenueGLAcct]) REFERENCES [dbo].[bGLAC] ([GLCo], [GLAcct])
ALTER TABLE [dbo].[vSMDepartmentOverrides] WITH NOCHECK ADD
CONSTRAINT [FK_vSMDepartmentOverrides_bGLAC_RevenueWIPGLAcct] FOREIGN KEY ([GLCo], [RevenueWIPGLAcct]) REFERENCES [dbo].[bGLAC] ([GLCo], [GLAcct])
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER dbo.vtvSMDepartmentOverrides_Audit_Delete ON dbo.vSMDepartmentOverrides
 AFTER DELETE
 NOT FOR REPLICATION AS
 SET NOCOUNT ON 
 -- generated by vspAuditCreateAuditTriggers

 BEGIN TRY 
DECLARE @HQMAKeys TABLE
	(
		  AuditID		bigint
		, KeyString		varchar(max)
	);
							INSERT dbo.HQMA (
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
										OUTPUT inserted.AuditID, inserted.KeyString INTO @HQMAKeys (AuditID, KeyString) 
							SELECT
								'vSMDepartmentOverrides' , 
								'<KeyString Department = "' + REPLACE(CAST(ISNULL(deleted.[Department],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(deleted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Seq = "' + REPLACE(CAST(ISNULL(deleted.[Seq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								deleted.SMCo , 
								'D' , 
								'CallType' , 
								CONVERT(VARCHAR(MAX), deleted.[CallType]) , 								NULL , 
								GETDATE() , 
								SUSER_SNAME()
							FROM deleted
								JOIN dbo.vAuditFlagCompany AS afc ON deleted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 8
							INSERT dbo.HQMA (
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
										OUTPUT inserted.AuditID, inserted.KeyString INTO @HQMAKeys (AuditID, KeyString) 
							SELECT
								'vSMDepartmentOverrides' , 
								'<KeyString Department = "' + REPLACE(CAST(ISNULL(deleted.[Department],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(deleted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Seq = "' + REPLACE(CAST(ISNULL(deleted.[Seq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								deleted.SMCo , 
								'D' , 
								'CostGLAcct' , 
								CONVERT(VARCHAR(MAX), deleted.[CostGLAcct]) , 								NULL , 
								GETDATE() , 
								SUSER_SNAME()
							FROM deleted
								JOIN dbo.vAuditFlagCompany AS afc ON deleted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 8
							INSERT dbo.HQMA (
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
										OUTPUT inserted.AuditID, inserted.KeyString INTO @HQMAKeys (AuditID, KeyString) 
							SELECT
								'vSMDepartmentOverrides' , 
								'<KeyString Department = "' + REPLACE(CAST(ISNULL(deleted.[Department],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(deleted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Seq = "' + REPLACE(CAST(ISNULL(deleted.[Seq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								deleted.SMCo , 
								'D' , 
								'CostType' , 
								CONVERT(VARCHAR(MAX), deleted.[CostType]) , 								NULL , 
								GETDATE() , 
								SUSER_SNAME()
							FROM deleted
								JOIN dbo.vAuditFlagCompany AS afc ON deleted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 8
							INSERT dbo.HQMA (
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
										OUTPUT inserted.AuditID, inserted.KeyString INTO @HQMAKeys (AuditID, KeyString) 
							SELECT
								'vSMDepartmentOverrides' , 
								'<KeyString Department = "' + REPLACE(CAST(ISNULL(deleted.[Department],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(deleted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Seq = "' + REPLACE(CAST(ISNULL(deleted.[Seq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								deleted.SMCo , 
								'D' , 
								'CostWIPGLAcct' , 
								CONVERT(VARCHAR(MAX), deleted.[CostWIPGLAcct]) , 								NULL , 
								GETDATE() , 
								SUSER_SNAME()
							FROM deleted
								JOIN dbo.vAuditFlagCompany AS afc ON deleted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 8
							INSERT dbo.HQMA (
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
										OUTPUT inserted.AuditID, inserted.KeyString INTO @HQMAKeys (AuditID, KeyString) 
							SELECT
								'vSMDepartmentOverrides' , 
								'<KeyString Department = "' + REPLACE(CAST(ISNULL(deleted.[Department],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(deleted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Seq = "' + REPLACE(CAST(ISNULL(deleted.[Seq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								deleted.SMCo , 
								'D' , 
								'Department' , 
								CONVERT(VARCHAR(MAX), deleted.[Department]) , 								NULL , 
								GETDATE() , 
								SUSER_SNAME()
							FROM deleted
								JOIN dbo.vAuditFlagCompany AS afc ON deleted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 8
							INSERT dbo.HQMA (
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
										OUTPUT inserted.AuditID, inserted.KeyString INTO @HQMAKeys (AuditID, KeyString) 
							SELECT
								'vSMDepartmentOverrides' , 
								'<KeyString Department = "' + REPLACE(CAST(ISNULL(deleted.[Department],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(deleted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Seq = "' + REPLACE(CAST(ISNULL(deleted.[Seq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								deleted.SMCo , 
								'D' , 
								'GLCo' , 
								CONVERT(VARCHAR(MAX), deleted.[GLCo]) , 								NULL , 
								GETDATE() , 
								SUSER_SNAME()
							FROM deleted
								JOIN dbo.vAuditFlagCompany AS afc ON deleted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 8
							INSERT dbo.HQMA (
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
										OUTPUT inserted.AuditID, inserted.KeyString INTO @HQMAKeys (AuditID, KeyString) 
							SELECT
								'vSMDepartmentOverrides' , 
								'<KeyString Department = "' + REPLACE(CAST(ISNULL(deleted.[Department],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(deleted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Seq = "' + REPLACE(CAST(ISNULL(deleted.[Seq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								deleted.SMCo , 
								'D' , 
								'LineType' , 
								CONVERT(VARCHAR(MAX), deleted.[LineType]) , 								NULL , 
								GETDATE() , 
								SUSER_SNAME()
							FROM deleted
								JOIN dbo.vAuditFlagCompany AS afc ON deleted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 8
							INSERT dbo.HQMA (
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
										OUTPUT inserted.AuditID, inserted.KeyString INTO @HQMAKeys (AuditID, KeyString) 
							SELECT
								'vSMDepartmentOverrides' , 
								'<KeyString Department = "' + REPLACE(CAST(ISNULL(deleted.[Department],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(deleted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Seq = "' + REPLACE(CAST(ISNULL(deleted.[Seq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								deleted.SMCo , 
								'D' , 
								'RevenueGLAcct' , 
								CONVERT(VARCHAR(MAX), deleted.[RevenueGLAcct]) , 								NULL , 
								GETDATE() , 
								SUSER_SNAME()
							FROM deleted
								JOIN dbo.vAuditFlagCompany AS afc ON deleted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 8
							INSERT dbo.HQMA (
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
										OUTPUT inserted.AuditID, inserted.KeyString INTO @HQMAKeys (AuditID, KeyString) 
							SELECT
								'vSMDepartmentOverrides' , 
								'<KeyString Department = "' + REPLACE(CAST(ISNULL(deleted.[Department],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(deleted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Seq = "' + REPLACE(CAST(ISNULL(deleted.[Seq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								deleted.SMCo , 
								'D' , 
								'RevenueWIPGLAcct' , 
								CONVERT(VARCHAR(MAX), deleted.[RevenueWIPGLAcct]) , 								NULL , 
								GETDATE() , 
								SUSER_SNAME()
							FROM deleted
								JOIN dbo.vAuditFlagCompany AS afc ON deleted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 8
							INSERT dbo.HQMA (
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
										OUTPUT inserted.AuditID, inserted.KeyString INTO @HQMAKeys (AuditID, KeyString) 
							SELECT
								'vSMDepartmentOverrides' , 
								'<KeyString Department = "' + REPLACE(CAST(ISNULL(deleted.[Department],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(deleted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Seq = "' + REPLACE(CAST(ISNULL(deleted.[Seq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								deleted.SMCo , 
								'D' , 
								'SMCo' , 
								CONVERT(VARCHAR(MAX), deleted.[SMCo]) , 								NULL , 
								GETDATE() , 
								SUSER_SNAME()
							FROM deleted
								JOIN dbo.vAuditFlagCompany AS afc ON deleted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 8
							INSERT dbo.HQMA (
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
										OUTPUT inserted.AuditID, inserted.KeyString INTO @HQMAKeys (AuditID, KeyString) 
							SELECT
								'vSMDepartmentOverrides' , 
								'<KeyString Department = "' + REPLACE(CAST(ISNULL(deleted.[Department],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(deleted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Seq = "' + REPLACE(CAST(ISNULL(deleted.[Seq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								deleted.SMCo , 
								'D' , 
								'SMDepartmentOverridesID' , 
								CONVERT(VARCHAR(MAX), deleted.[SMDepartmentOverridesID]) , 								NULL , 
								GETDATE() , 
								SUSER_SNAME()
							FROM deleted
								JOIN dbo.vAuditFlagCompany AS afc ON deleted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 8
							INSERT dbo.HQMA (
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
										OUTPUT inserted.AuditID, inserted.KeyString INTO @HQMAKeys (AuditID, KeyString) 
							SELECT
								'vSMDepartmentOverrides' , 
								'<KeyString Department = "' + REPLACE(CAST(ISNULL(deleted.[Department],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(deleted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Seq = "' + REPLACE(CAST(ISNULL(deleted.[Seq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								deleted.SMCo , 
								'D' , 
								'Seq' , 
								CONVERT(VARCHAR(MAX), deleted.[Seq]) , 								NULL , 
								GETDATE() , 
								SUSER_SNAME()
							FROM deleted
								JOIN dbo.vAuditFlagCompany AS afc ON deleted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 8
							INSERT dbo.HQMA (
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
										OUTPUT inserted.AuditID, inserted.KeyString INTO @HQMAKeys (AuditID, KeyString) 
							SELECT
								'vSMDepartmentOverrides' , 
								'<KeyString Department = "' + REPLACE(CAST(ISNULL(deleted.[Department],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(deleted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Seq = "' + REPLACE(CAST(ISNULL(deleted.[Seq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								deleted.SMCo , 
								'D' , 
								'UniqueAttchID' , 
								CONVERT(VARCHAR(MAX), deleted.[UniqueAttchID]) , 								NULL , 
								GETDATE() , 
								SUSER_SNAME()
							FROM deleted
								JOIN dbo.vAuditFlagCompany AS afc ON deleted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 8

							 INSERT INTO HQSA ( AuditID, Datatype, Qualifier, Instance, TableName)
				SELECT DISTINCT Keys.AuditID, 'bSMCo', d.SMCo, CAST(d.SMCo AS VARCHAR(30)), 'vSMDepartmentOverrides'
				FROM deleted AS d
				INNER JOIN @HQMAKeys AS Keys ON Keys.KeyString = '<KeyString Department = "' + REPLACE(CAST(ISNULL(d.[Department],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(d.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Seq = "' + REPLACE(CAST(ISNULL(d.[Seq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />'

 END TRY 
 BEGIN CATCH 
   DECLARE	@ErrorMessage	NVARCHAR(4000), 
				@ErrorSeverity	INT; 

   SELECT	@ErrorMessage = 'Error '+ ISNULL(ERROR_MESSAGE(),'') +' in [dbo].[dbo.vtvSMDepartmentOverrides_Audit_Delete] trigger', 
				@ErrorSeverity = ERROR_SEVERITY(); 

   RAISERROR(@ErrorMessage, @ErrorSeverity, 1 ) 
 END CATCH 
GO
EXEC sp_settriggerorder N'[dbo].[vtvSMDepartmentOverrides_Audit_Delete]', 'last', 'delete', null
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER dbo.vtvSMDepartmentOverrides_Audit_Insert ON dbo.vSMDepartmentOverrides
 AFTER INSERT
 NOT FOR REPLICATION AS
 SET NOCOUNT ON 
 -- generated by vspAuditTriggersCreate

 BEGIN TRY 
DECLARE @HQMAKeys TABLE
	(
		  AuditID		bigint
		, KeyString		varchar(max)
	);
-- log additions to the CallType column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
									OUTPUT inserted.AuditID, inserted.KeyString INTO @HQMAKeys (AuditID, KeyString) 
							SELECT 
								'vSMDepartmentOverrides' , 
								'<KeyString Department = "' + REPLACE(CAST(ISNULL(inserted.[Department],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(inserted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Seq = "' + REPLACE(CAST(ISNULL(inserted.[Seq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.SMCo, '') , 
								'A' , 
								'CallType' , 
								NULL , 
								CallType , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								JOIN dbo.vAuditFlagCompany AS afc ON inserted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 8

-- log additions to the CostGLAcct column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
									OUTPUT inserted.AuditID, inserted.KeyString INTO @HQMAKeys (AuditID, KeyString) 
							SELECT 
								'vSMDepartmentOverrides' , 
								'<KeyString Department = "' + REPLACE(CAST(ISNULL(inserted.[Department],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(inserted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Seq = "' + REPLACE(CAST(ISNULL(inserted.[Seq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.SMCo, '') , 
								'A' , 
								'CostGLAcct' , 
								NULL , 
								CostGLAcct , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								JOIN dbo.vAuditFlagCompany AS afc ON inserted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 8

-- log additions to the CostType column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
									OUTPUT inserted.AuditID, inserted.KeyString INTO @HQMAKeys (AuditID, KeyString) 
							SELECT 
								'vSMDepartmentOverrides' , 
								'<KeyString Department = "' + REPLACE(CAST(ISNULL(inserted.[Department],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(inserted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Seq = "' + REPLACE(CAST(ISNULL(inserted.[Seq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.SMCo, '') , 
								'A' , 
								'CostType' , 
								NULL , 
								CostType , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								JOIN dbo.vAuditFlagCompany AS afc ON inserted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 8

-- log additions to the CostWIPGLAcct column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
									OUTPUT inserted.AuditID, inserted.KeyString INTO @HQMAKeys (AuditID, KeyString) 
							SELECT 
								'vSMDepartmentOverrides' , 
								'<KeyString Department = "' + REPLACE(CAST(ISNULL(inserted.[Department],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(inserted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Seq = "' + REPLACE(CAST(ISNULL(inserted.[Seq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.SMCo, '') , 
								'A' , 
								'CostWIPGLAcct' , 
								NULL , 
								CostWIPGLAcct , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								JOIN dbo.vAuditFlagCompany AS afc ON inserted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 8

-- log additions to the Department column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
									OUTPUT inserted.AuditID, inserted.KeyString INTO @HQMAKeys (AuditID, KeyString) 
							SELECT 
								'vSMDepartmentOverrides' , 
								'<KeyString Department = "' + REPLACE(CAST(ISNULL(inserted.[Department],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(inserted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Seq = "' + REPLACE(CAST(ISNULL(inserted.[Seq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.SMCo, '') , 
								'A' , 
								'Department' , 
								NULL , 
								Department , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								JOIN dbo.vAuditFlagCompany AS afc ON inserted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 8

-- log additions to the GLCo column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
									OUTPUT inserted.AuditID, inserted.KeyString INTO @HQMAKeys (AuditID, KeyString) 
							SELECT 
								'vSMDepartmentOverrides' , 
								'<KeyString Department = "' + REPLACE(CAST(ISNULL(inserted.[Department],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(inserted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Seq = "' + REPLACE(CAST(ISNULL(inserted.[Seq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.SMCo, '') , 
								'A' , 
								'GLCo' , 
								NULL , 
								GLCo , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								JOIN dbo.vAuditFlagCompany AS afc ON inserted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 8

-- log additions to the LineType column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
									OUTPUT inserted.AuditID, inserted.KeyString INTO @HQMAKeys (AuditID, KeyString) 
							SELECT 
								'vSMDepartmentOverrides' , 
								'<KeyString Department = "' + REPLACE(CAST(ISNULL(inserted.[Department],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(inserted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Seq = "' + REPLACE(CAST(ISNULL(inserted.[Seq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.SMCo, '') , 
								'A' , 
								'LineType' , 
								NULL , 
								LineType , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								JOIN dbo.vAuditFlagCompany AS afc ON inserted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 8

-- log additions to the RevenueGLAcct column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
									OUTPUT inserted.AuditID, inserted.KeyString INTO @HQMAKeys (AuditID, KeyString) 
							SELECT 
								'vSMDepartmentOverrides' , 
								'<KeyString Department = "' + REPLACE(CAST(ISNULL(inserted.[Department],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(inserted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Seq = "' + REPLACE(CAST(ISNULL(inserted.[Seq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.SMCo, '') , 
								'A' , 
								'RevenueGLAcct' , 
								NULL , 
								RevenueGLAcct , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								JOIN dbo.vAuditFlagCompany AS afc ON inserted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 8

-- log additions to the RevenueWIPGLAcct column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
									OUTPUT inserted.AuditID, inserted.KeyString INTO @HQMAKeys (AuditID, KeyString) 
							SELECT 
								'vSMDepartmentOverrides' , 
								'<KeyString Department = "' + REPLACE(CAST(ISNULL(inserted.[Department],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(inserted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Seq = "' + REPLACE(CAST(ISNULL(inserted.[Seq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.SMCo, '') , 
								'A' , 
								'RevenueWIPGLAcct' , 
								NULL , 
								RevenueWIPGLAcct , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								JOIN dbo.vAuditFlagCompany AS afc ON inserted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 8

-- log additions to the SMCo column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
									OUTPUT inserted.AuditID, inserted.KeyString INTO @HQMAKeys (AuditID, KeyString) 
							SELECT 
								'vSMDepartmentOverrides' , 
								'<KeyString Department = "' + REPLACE(CAST(ISNULL(inserted.[Department],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(inserted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Seq = "' + REPLACE(CAST(ISNULL(inserted.[Seq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.SMCo, '') , 
								'A' , 
								'SMCo' , 
								NULL , 
								SMCo , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								JOIN dbo.vAuditFlagCompany AS afc ON inserted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 8

-- log additions to the SMDepartmentOverridesID column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
									OUTPUT inserted.AuditID, inserted.KeyString INTO @HQMAKeys (AuditID, KeyString) 
							SELECT 
								'vSMDepartmentOverrides' , 
								'<KeyString Department = "' + REPLACE(CAST(ISNULL(inserted.[Department],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(inserted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Seq = "' + REPLACE(CAST(ISNULL(inserted.[Seq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.SMCo, '') , 
								'A' , 
								'SMDepartmentOverridesID' , 
								NULL , 
								SMDepartmentOverridesID , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								JOIN dbo.vAuditFlagCompany AS afc ON inserted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 8

-- log additions to the Seq column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
									OUTPUT inserted.AuditID, inserted.KeyString INTO @HQMAKeys (AuditID, KeyString) 
							SELECT 
								'vSMDepartmentOverrides' , 
								'<KeyString Department = "' + REPLACE(CAST(ISNULL(inserted.[Department],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(inserted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Seq = "' + REPLACE(CAST(ISNULL(inserted.[Seq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.SMCo, '') , 
								'A' , 
								'Seq' , 
								NULL , 
								Seq , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								JOIN dbo.vAuditFlagCompany AS afc ON inserted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 8

-- log additions to the UniqueAttchID column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
									OUTPUT inserted.AuditID, inserted.KeyString INTO @HQMAKeys (AuditID, KeyString) 
							SELECT 
								'vSMDepartmentOverrides' , 
								'<KeyString Department = "' + REPLACE(CAST(ISNULL(inserted.[Department],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(inserted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Seq = "' + REPLACE(CAST(ISNULL(inserted.[Seq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.SMCo, '') , 
								'A' , 
								'UniqueAttchID' , 
								NULL , 
								UniqueAttchID , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								JOIN dbo.vAuditFlagCompany AS afc ON inserted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 8

 INSERT INTO HQSA ( AuditID, Datatype, Qualifier, Instance, TableName)
				SELECT DISTINCT Keys.AuditID, 'bSMCo', i.SMCo, CAST(i.SMCo AS VARCHAR(30)), 'vSMDepartmentOverrides'
				FROM inserted AS i
				INNER JOIN @HQMAKeys AS Keys ON Keys.KeyString = '<KeyString Department = "' + REPLACE(CAST(ISNULL(i.[Department],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(i.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Seq = "' + REPLACE(CAST(ISNULL(i.[Seq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />'

 END TRY 
 BEGIN CATCH 
   DECLARE	@ErrorMessage	NVARCHAR(4000), 
				@ErrorSeverity	INT; 

   SELECT	@ErrorMessage = 'Error '+ ISNULL(ERROR_MESSAGE(),'') +' in [dbo].[dbo.vtvSMDepartmentOverrides_Audit_Insert] trigger', 
				@ErrorSeverity = ERROR_SEVERITY(); 

   RAISERROR(@ErrorMessage, @ErrorSeverity, 1 ) 
 END CATCH 
GO
EXEC sp_settriggerorder N'[dbo].[vtvSMDepartmentOverrides_Audit_Insert]', 'last', 'insert', null
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER dbo.vtvSMDepartmentOverrides_Audit_Update ON dbo.vSMDepartmentOverrides
 AFTER UPDATE 
 NOT FOR REPLICATION AS 
 SET NOCOUNT ON 
 -- generated by vspAuditTriggersCreate

 BEGIN TRY 
DECLARE @HQMAKeys TABLE
	(
		  AuditID		bigint
		, KeyString		varchar(max)
	);
							IF UPDATE([CallType])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
										OUTPUT inserted.AuditID, inserted.KeyString INTO @HQMAKeys (AuditID, KeyString) 
								SELECT 							'vSMDepartmentOverrides' , 								'<KeyString Department = "' + REPLACE(CAST(ISNULL(inserted.[Department],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(inserted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Seq = "' + REPLACE(CAST(ISNULL(inserted.[Seq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.SMCo , 								'C' , 								'CallType' , 								CONVERT(VARCHAR(MAX), deleted.[CallType]) , 								CONVERT(VARCHAR(MAX), inserted.[CallType]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[SMDepartmentOverridesID] = deleted.[SMDepartmentOverridesID] 
									AND ((inserted.[CallType] <> deleted.[CallType]) OR (inserted.[CallType] IS NULL AND deleted.[CallType] IS NOT NULL) OR (inserted.[CallType] IS NOT NULL AND deleted.[CallType] IS NULL))
								JOIN dbo.vAuditFlagCompany AS afc ON inserted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 8

							END 

							IF UPDATE([CostGLAcct])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
										OUTPUT inserted.AuditID, inserted.KeyString INTO @HQMAKeys (AuditID, KeyString) 
								SELECT 							'vSMDepartmentOverrides' , 								'<KeyString Department = "' + REPLACE(CAST(ISNULL(inserted.[Department],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(inserted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Seq = "' + REPLACE(CAST(ISNULL(inserted.[Seq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.SMCo , 								'C' , 								'CostGLAcct' , 								CONVERT(VARCHAR(MAX), deleted.[CostGLAcct]) , 								CONVERT(VARCHAR(MAX), inserted.[CostGLAcct]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[SMDepartmentOverridesID] = deleted.[SMDepartmentOverridesID] 
									AND ((inserted.[CostGLAcct] <> deleted.[CostGLAcct]) OR (inserted.[CostGLAcct] IS NULL AND deleted.[CostGLAcct] IS NOT NULL) OR (inserted.[CostGLAcct] IS NOT NULL AND deleted.[CostGLAcct] IS NULL))
								JOIN dbo.vAuditFlagCompany AS afc ON inserted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 8

							END 

							IF UPDATE([CostType])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
										OUTPUT inserted.AuditID, inserted.KeyString INTO @HQMAKeys (AuditID, KeyString) 
								SELECT 							'vSMDepartmentOverrides' , 								'<KeyString Department = "' + REPLACE(CAST(ISNULL(inserted.[Department],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(inserted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Seq = "' + REPLACE(CAST(ISNULL(inserted.[Seq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.SMCo , 								'C' , 								'CostType' , 								CONVERT(VARCHAR(MAX), deleted.[CostType]) , 								CONVERT(VARCHAR(MAX), inserted.[CostType]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[SMDepartmentOverridesID] = deleted.[SMDepartmentOverridesID] 
									AND ((inserted.[CostType] <> deleted.[CostType]) OR (inserted.[CostType] IS NULL AND deleted.[CostType] IS NOT NULL) OR (inserted.[CostType] IS NOT NULL AND deleted.[CostType] IS NULL))
								JOIN dbo.vAuditFlagCompany AS afc ON inserted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 8

							END 

							IF UPDATE([CostWIPGLAcct])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
										OUTPUT inserted.AuditID, inserted.KeyString INTO @HQMAKeys (AuditID, KeyString) 
								SELECT 							'vSMDepartmentOverrides' , 								'<KeyString Department = "' + REPLACE(CAST(ISNULL(inserted.[Department],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(inserted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Seq = "' + REPLACE(CAST(ISNULL(inserted.[Seq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.SMCo , 								'C' , 								'CostWIPGLAcct' , 								CONVERT(VARCHAR(MAX), deleted.[CostWIPGLAcct]) , 								CONVERT(VARCHAR(MAX), inserted.[CostWIPGLAcct]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[SMDepartmentOverridesID] = deleted.[SMDepartmentOverridesID] 
									AND ((inserted.[CostWIPGLAcct] <> deleted.[CostWIPGLAcct]) OR (inserted.[CostWIPGLAcct] IS NULL AND deleted.[CostWIPGLAcct] IS NOT NULL) OR (inserted.[CostWIPGLAcct] IS NOT NULL AND deleted.[CostWIPGLAcct] IS NULL))
								JOIN dbo.vAuditFlagCompany AS afc ON inserted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 8

							END 

							IF UPDATE([Department])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
										OUTPUT inserted.AuditID, inserted.KeyString INTO @HQMAKeys (AuditID, KeyString) 
								SELECT 							'vSMDepartmentOverrides' , 								'<KeyString Department = "' + REPLACE(CAST(ISNULL(inserted.[Department],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(inserted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Seq = "' + REPLACE(CAST(ISNULL(inserted.[Seq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.SMCo , 								'C' , 								'Department' , 								CONVERT(VARCHAR(MAX), deleted.[Department]) , 								CONVERT(VARCHAR(MAX), inserted.[Department]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[SMDepartmentOverridesID] = deleted.[SMDepartmentOverridesID] 
									AND ((inserted.[Department] <> deleted.[Department]) OR (inserted.[Department] IS NULL AND deleted.[Department] IS NOT NULL) OR (inserted.[Department] IS NOT NULL AND deleted.[Department] IS NULL))
								JOIN dbo.vAuditFlagCompany AS afc ON inserted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 8

							END 

							IF UPDATE([GLCo])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
										OUTPUT inserted.AuditID, inserted.KeyString INTO @HQMAKeys (AuditID, KeyString) 
								SELECT 							'vSMDepartmentOverrides' , 								'<KeyString Department = "' + REPLACE(CAST(ISNULL(inserted.[Department],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(inserted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Seq = "' + REPLACE(CAST(ISNULL(inserted.[Seq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.SMCo , 								'C' , 								'GLCo' , 								CONVERT(VARCHAR(MAX), deleted.[GLCo]) , 								CONVERT(VARCHAR(MAX), inserted.[GLCo]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[SMDepartmentOverridesID] = deleted.[SMDepartmentOverridesID] 
									AND ((inserted.[GLCo] <> deleted.[GLCo]) OR (inserted.[GLCo] IS NULL AND deleted.[GLCo] IS NOT NULL) OR (inserted.[GLCo] IS NOT NULL AND deleted.[GLCo] IS NULL))
								JOIN dbo.vAuditFlagCompany AS afc ON inserted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 8

							END 

							IF UPDATE([LineType])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
										OUTPUT inserted.AuditID, inserted.KeyString INTO @HQMAKeys (AuditID, KeyString) 
								SELECT 							'vSMDepartmentOverrides' , 								'<KeyString Department = "' + REPLACE(CAST(ISNULL(inserted.[Department],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(inserted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Seq = "' + REPLACE(CAST(ISNULL(inserted.[Seq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.SMCo , 								'C' , 								'LineType' , 								CONVERT(VARCHAR(MAX), deleted.[LineType]) , 								CONVERT(VARCHAR(MAX), inserted.[LineType]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[SMDepartmentOverridesID] = deleted.[SMDepartmentOverridesID] 
									AND ((inserted.[LineType] <> deleted.[LineType]) OR (inserted.[LineType] IS NULL AND deleted.[LineType] IS NOT NULL) OR (inserted.[LineType] IS NOT NULL AND deleted.[LineType] IS NULL))
								JOIN dbo.vAuditFlagCompany AS afc ON inserted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 8

							END 

							IF UPDATE([RevenueGLAcct])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
										OUTPUT inserted.AuditID, inserted.KeyString INTO @HQMAKeys (AuditID, KeyString) 
								SELECT 							'vSMDepartmentOverrides' , 								'<KeyString Department = "' + REPLACE(CAST(ISNULL(inserted.[Department],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(inserted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Seq = "' + REPLACE(CAST(ISNULL(inserted.[Seq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.SMCo , 								'C' , 								'RevenueGLAcct' , 								CONVERT(VARCHAR(MAX), deleted.[RevenueGLAcct]) , 								CONVERT(VARCHAR(MAX), inserted.[RevenueGLAcct]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[SMDepartmentOverridesID] = deleted.[SMDepartmentOverridesID] 
									AND ((inserted.[RevenueGLAcct] <> deleted.[RevenueGLAcct]) OR (inserted.[RevenueGLAcct] IS NULL AND deleted.[RevenueGLAcct] IS NOT NULL) OR (inserted.[RevenueGLAcct] IS NOT NULL AND deleted.[RevenueGLAcct] IS NULL))
								JOIN dbo.vAuditFlagCompany AS afc ON inserted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 8

							END 

							IF UPDATE([RevenueWIPGLAcct])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
										OUTPUT inserted.AuditID, inserted.KeyString INTO @HQMAKeys (AuditID, KeyString) 
								SELECT 							'vSMDepartmentOverrides' , 								'<KeyString Department = "' + REPLACE(CAST(ISNULL(inserted.[Department],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(inserted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Seq = "' + REPLACE(CAST(ISNULL(inserted.[Seq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.SMCo , 								'C' , 								'RevenueWIPGLAcct' , 								CONVERT(VARCHAR(MAX), deleted.[RevenueWIPGLAcct]) , 								CONVERT(VARCHAR(MAX), inserted.[RevenueWIPGLAcct]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[SMDepartmentOverridesID] = deleted.[SMDepartmentOverridesID] 
									AND ((inserted.[RevenueWIPGLAcct] <> deleted.[RevenueWIPGLAcct]) OR (inserted.[RevenueWIPGLAcct] IS NULL AND deleted.[RevenueWIPGLAcct] IS NOT NULL) OR (inserted.[RevenueWIPGLAcct] IS NOT NULL AND deleted.[RevenueWIPGLAcct] IS NULL))
								JOIN dbo.vAuditFlagCompany AS afc ON inserted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 8

							END 

							IF UPDATE([SMCo])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
										OUTPUT inserted.AuditID, inserted.KeyString INTO @HQMAKeys (AuditID, KeyString) 
								SELECT 							'vSMDepartmentOverrides' , 								'<KeyString Department = "' + REPLACE(CAST(ISNULL(inserted.[Department],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(inserted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Seq = "' + REPLACE(CAST(ISNULL(inserted.[Seq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.SMCo , 								'C' , 								'SMCo' , 								CONVERT(VARCHAR(MAX), deleted.[SMCo]) , 								CONVERT(VARCHAR(MAX), inserted.[SMCo]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[SMDepartmentOverridesID] = deleted.[SMDepartmentOverridesID] 
									AND ((inserted.[SMCo] <> deleted.[SMCo]) OR (inserted.[SMCo] IS NULL AND deleted.[SMCo] IS NOT NULL) OR (inserted.[SMCo] IS NOT NULL AND deleted.[SMCo] IS NULL))
								JOIN dbo.vAuditFlagCompany AS afc ON inserted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 8

							END 

							IF UPDATE([SMDepartmentOverridesID])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
										OUTPUT inserted.AuditID, inserted.KeyString INTO @HQMAKeys (AuditID, KeyString) 
								SELECT 							'vSMDepartmentOverrides' , 								'<KeyString Department = "' + REPLACE(CAST(ISNULL(inserted.[Department],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(inserted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Seq = "' + REPLACE(CAST(ISNULL(inserted.[Seq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.SMCo , 								'C' , 								'SMDepartmentOverridesID' , 								CONVERT(VARCHAR(MAX), deleted.[SMDepartmentOverridesID]) , 								CONVERT(VARCHAR(MAX), inserted.[SMDepartmentOverridesID]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[SMDepartmentOverridesID] = deleted.[SMDepartmentOverridesID] 
									AND ((inserted.[SMDepartmentOverridesID] <> deleted.[SMDepartmentOverridesID]) OR (inserted.[SMDepartmentOverridesID] IS NULL AND deleted.[SMDepartmentOverridesID] IS NOT NULL) OR (inserted.[SMDepartmentOverridesID] IS NOT NULL AND deleted.[SMDepartmentOverridesID] IS NULL))
								JOIN dbo.vAuditFlagCompany AS afc ON inserted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 8

							END 

							IF UPDATE([Seq])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
										OUTPUT inserted.AuditID, inserted.KeyString INTO @HQMAKeys (AuditID, KeyString) 
								SELECT 							'vSMDepartmentOverrides' , 								'<KeyString Department = "' + REPLACE(CAST(ISNULL(inserted.[Department],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(inserted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Seq = "' + REPLACE(CAST(ISNULL(inserted.[Seq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.SMCo , 								'C' , 								'Seq' , 								CONVERT(VARCHAR(MAX), deleted.[Seq]) , 								CONVERT(VARCHAR(MAX), inserted.[Seq]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[SMDepartmentOverridesID] = deleted.[SMDepartmentOverridesID] 
									AND ((inserted.[Seq] <> deleted.[Seq]) OR (inserted.[Seq] IS NULL AND deleted.[Seq] IS NOT NULL) OR (inserted.[Seq] IS NOT NULL AND deleted.[Seq] IS NULL))
								JOIN dbo.vAuditFlagCompany AS afc ON inserted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 8

							END 

							IF UPDATE([UniqueAttchID])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
										OUTPUT inserted.AuditID, inserted.KeyString INTO @HQMAKeys (AuditID, KeyString) 
								SELECT 							'vSMDepartmentOverrides' , 								'<KeyString Department = "' + REPLACE(CAST(ISNULL(inserted.[Department],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(inserted.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Seq = "' + REPLACE(CAST(ISNULL(inserted.[Seq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.SMCo , 								'C' , 								'UniqueAttchID' , 								CONVERT(VARCHAR(MAX), deleted.[UniqueAttchID]) , 								CONVERT(VARCHAR(MAX), inserted.[UniqueAttchID]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[SMDepartmentOverridesID] = deleted.[SMDepartmentOverridesID] 
									AND ((inserted.[UniqueAttchID] <> deleted.[UniqueAttchID]) OR (inserted.[UniqueAttchID] IS NULL AND deleted.[UniqueAttchID] IS NOT NULL) OR (inserted.[UniqueAttchID] IS NOT NULL AND deleted.[UniqueAttchID] IS NULL))
								JOIN dbo.vAuditFlagCompany AS afc ON inserted.SMCo = afc.AuditCo 
							WHERE afc.AuditFlagID = 8

							END 

 INSERT INTO HQSA ( AuditID, Datatype, Qualifier, Instance, TableName)
				SELECT DISTINCT Keys.AuditID, 'bSMCo', i.SMCo, CAST(i.SMCo AS VARCHAR(30)), 'vSMDepartmentOverrides'
				FROM inserted AS i
				INNER JOIN @HQMAKeys AS Keys ON Keys.KeyString = '<KeyString Department = "' + REPLACE(CAST(ISNULL(i.[Department],'') AS VARCHAR(MAX)),'"', '&quot;') + '" SMCo = "' + REPLACE(CAST(ISNULL(i.[SMCo],'') AS VARCHAR(MAX)),'"', '&quot;') + '" Seq = "' + REPLACE(CAST(ISNULL(i.[Seq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />'


 END TRY 
 BEGIN CATCH 
   DECLARE	@ErrorMessage	NVARCHAR(4000), 
				@ErrorSeverity	INT; 

   SELECT	@ErrorMessage = 'Error '+ ISNULL(ERROR_MESSAGE(),'') +' in [dbo].[dbo.vtvSMDepartmentOverrides_Audit_Update] trigger', 
				@ErrorSeverity = ERROR_SEVERITY(); 

   RAISERROR(@ErrorMessage, @ErrorSeverity, 1 ) 
 END CATCH 
GO
EXEC sp_settriggerorder N'[dbo].[vtvSMDepartmentOverrides_Audit_Update]', 'last', 'update', null
GO
ALTER TABLE [dbo].[vSMDepartmentOverrides] ADD CONSTRAINT [PK_vSMDepartmentOverrides] PRIMARY KEY CLUSTERED  ([SMDepartmentOverridesID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[vSMDepartmentOverrides] ADD CONSTRAINT [IX_vSMDepartmentOverrides_SMCo_Department_LineType_CallType_CostType] UNIQUE NONCLUSTERED  ([SMCo], [Department], [LineType], [CallType], [CostType]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[vSMDepartmentOverrides] ADD CONSTRAINT [IX_vSMDepartmentOverrides_SMCo_Department_Seq] UNIQUE NONCLUSTERED  ([SMCo], [Department], [Seq]) ON [PRIMARY]
GO

ALTER TABLE [dbo].[vSMDepartmentOverrides] WITH NOCHECK ADD CONSTRAINT [FK_vSMDepartmentOverrides_vSMDepartment_SMCo_Department] FOREIGN KEY ([SMCo], [Department]) REFERENCES [dbo].[vSMDepartment] ([SMCo], [Department])
GO
