CREATE TABLE [dbo].[vRPTM]
(
[ReportID] [int] NOT NULL,
[TemplateName] [varchar] (20) COLLATE Latin1_General_BIN NOT NULL,
[KeyID] [int] NOT NULL IDENTITY(1, 2)
) ON [PRIMARY]
ALTER TABLE [dbo].[vRPTM] ADD 
CONSTRAINT [PK_vRPTM] PRIMARY KEY CLUSTERED  ([KeyID]) WITH (FILLFACTOR=100) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [IX_vRPTM_ReportID] ON [dbo].[vRPTM] ([ReportID]) WITH (FILLFACTOR=80) ON [PRIMARY]

GO
