CREATE TABLE [dbo].[bHQAI]
(
[AttachmentID] [int] NOT NULL,
[IndexSeq] [int] NOT NULL,
[IndexName] [varchar] (50) COLLATE Latin1_General_BIN NULL,
[APCo] [dbo].[bCompany] NULL,
[APVendorGroup] [dbo].[bGroup] NULL,
[APVendor] [dbo].[bVendor] NULL,
[APReference] [dbo].[bAPReference] NULL,
[APCheckNumber] [dbo].[bCMRef] NULL,
[ARCo] [dbo].[bCompany] NULL,
[ARCustomer] [dbo].[bCustomer] NULL,
[ARInvoice] [varchar] (10) COLLATE Latin1_General_BIN NULL,
[JCCo] [dbo].[bCompany] NULL,
[JCJob] [dbo].[bJob] NULL,
[JCPhaseGroup] [dbo].[bGroup] NULL,
[JCPhase] [dbo].[bPhase] NULL,
[JCCostType] [dbo].[bJCCType] NULL,
[JCContract] [dbo].[bContract] NULL,
[JCContractItem] [dbo].[bContractItem] NULL,
[POCo] [dbo].[bCompany] NULL,
[POPurchaseOrder] [varchar] (30) COLLATE Latin1_General_BIN NULL,
[POItem] [dbo].[bItem] NULL,
[EMCo] [dbo].[bCompany] NULL,
[EMEquipment] [dbo].[bEquip] NULL,
[EMCostCode] [dbo].[bCostCode] NULL,
[EMCostType] [dbo].[bEMCType] NULL,
[PRCo] [dbo].[bCompany] NULL,
[PREmployee] [dbo].[bEmployee] NULL,
[HRCo] [dbo].[bCompany] NULL,
[HRReference] [dbo].[bHRRef] NULL,
[MIMaterialGroup] [dbo].[bGroup] NULL,
[MIMaterial] [dbo].[bMatl] NULL,
[MIMonth] [dbo].[bMonth] NULL,
[MITransaction] [dbo].[bTrans] NULL,
[INCo] [dbo].[bCompany] NULL,
[INLoc] [dbo].[bLoc] NULL,
[MSCo] [dbo].[bCompany] NULL,
[MSTicket] [dbo].[bTic] NULL,
[SLCo] [dbo].[bCompany] NULL,
[SLSubcontract] [varchar] (30) COLLATE Latin1_General_BIN NULL,
[SLSubcontractItem] [dbo].[bItem] NULL,
[Notes] [varchar] (max) COLLATE Latin1_General_BIN NULL,
[UniqueAttchID] [uniqueidentifier] NULL,
[CustomYN] [dbo].[bYN] NOT NULL CONSTRAINT [DF_bHQAI_CustomYN] DEFAULT ('N'),
[UserCustom1] [varchar] (50) COLLATE Latin1_General_BIN NULL,
[UserCustom2] [varchar] (50) COLLATE Latin1_General_BIN NULL,
[UserCustom3] [varchar] (50) COLLATE Latin1_General_BIN NULL,
[UserCustom4] [varchar] (50) COLLATE Latin1_General_BIN NULL,
[UserCustom5] [varchar] (50) COLLATE Latin1_General_BIN NULL,
[PMIssue] [dbo].[bIssue] NULL,
[PMFirmNumber] [dbo].[bFirm] NULL,
[PMFirmType] [varchar] (10) COLLATE Latin1_General_BIN NULL,
[PMFirmContact] [dbo].[bEmployee] NULL,
[PMSubmSrcFirm] [dbo].[bFirm] NULL,
[PMSubmSrcContact] [dbo].[bEmployee] NULL,
[ARCustGroup] [dbo].[bGroup] NULL,
[EMGroup] [dbo].[bGroup] NULL,
[PMACO] [dbo].[bACO] NULL,
[PMACOItem] [dbo].[bACOItem] NULL,
[PMPCO] [dbo].[bPCO] NULL,
[PMPCOItem] [dbo].[bPCOItem] NULL,
[PMPCOType] [dbo].[bDocType] NULL,
[PMDocType] [dbo].[bDocType] NULL,
[PMSubmittal] [dbo].[bDocument] NULL,
[PMTransmittal] [dbo].[bDocument] NULL,
[PMRFQ] [dbo].[bDocument] NULL,
[PMRFI] [dbo].[bDocument] NULL,
[PMDocument] [dbo].[bDocument] NULL,
[PMInspectionCode] [dbo].[bDocument] NULL,
[PMTestCode] [dbo].[bDocument] NULL,
[PMDrawing] [dbo].[bDocument] NULL,
[PMMeeting] [int] NULL,
[PMPunchList] [dbo].[bDocument] NULL,
[PMLogDate] [dbo].[bDate] NULL,
[PMDailyLog] [smallint] NULL,
[GLCo] [dbo].[bCompany] NULL,
[GLAcct] [dbo].[bGLAcct] NULL,
[PMRev] [tinyint] NULL,
[PMSMPItem] [int] NULL,
[RQCo] [dbo].[bCompany] NULL,
[RQID] [dbo].[bRQ] NULL,
[RQLine] [dbo].[bItem] NULL,
[RQQuote] [int] NULL,
[RQQuoteLine] [int] NULL,
[PRGroup] [dbo].[bGroup] NULL,
[PREndDate] [dbo].[bDate] NULL,
[MO] [dbo].[bMO] NULL,
[MOItem] [dbo].[bItem] NULL,
[CMDeposit] [dbo].[bCMRef] NULL,
[EmailSubject] [varchar] (1500) COLLATE Latin1_General_BIN NULL,
[IsEmailIndex] [bit] NULL,
[EmailReceivedDate] [datetime] NULL,
[EmailSentDate] [datetime] NULL,
[EmailFromAddress] [varchar] (200) COLLATE Latin1_General_BIN NULL,
[EmailToAddresses] [varchar] (2000) COLLATE Latin1_General_BIN NULL,
[EmailCCAddresses] [varchar] (2000) COLLATE Latin1_General_BIN NULL,
[PCBidPackage] [varchar] (20) COLLATE Latin1_General_BIN NULL,
[PCPhaseGroup] [dbo].[bGroup] NULL,
[PCPhase] [dbo].[bPhase] NULL,
[PCPotentialProject] [varchar] (20) COLLATE Latin1_General_BIN NULL,
[PCScopeCode] [varchar] (10) COLLATE Latin1_General_BIN NULL,
[PCContactSeq] [tinyint] NULL,
[SMCo] [dbo].[bCompany] NULL,
[SMWorkOrder] [int] NULL,
[SMScope] [int] NULL,
[SMWorkScope] [varchar] (20) COLLATE Latin1_General_BIN NULL,
[SMCustGroup] [dbo].[bGroup] NULL,
[SMCustomer] [bigint] NULL,
[SMServiceSite] [varchar] (20) COLLATE Latin1_General_BIN NULL,
[SMServiceItem] [varchar] (20) COLLATE Latin1_General_BIN NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
ALTER TABLE [dbo].[bHQAI] ADD 
CONSTRAINT [PK_bHQAI] PRIMARY KEY CLUSTERED  ([AttachmentID], [IndexSeq]) WITH (FILLFACTOR=80) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE TRIGGER [dbo].[btHQAIi] ON [dbo].[bHQAI]
    INSTEAD OF INSERT
   /************************************************************************
 * CREATED:	08/21/01 RM   
 * MODIFIED: AR 03/23/2010 - Issue 134951 -- performance issues, removing loop,
					writing to batch insert and handle mutliple attachment IDs
			 FDT 10/20/2011 - B-06396 -- added eight SM columns
 *
 * Purpose:	Need to ensure unique records here and update index seq
   			because we cannot have an index on them.
 
 * returns throws error on failure and rolls back transaction
 *
 *************************************************************************/
 AS
    SET NOCOUNT ON ;
    
    BEGIN TRY	;

		-- we need to limit the list of attachments so we don't get carteasian products
		WITH    cteDist (AttachmentID)
				AS (
						SELECT DISTINCT AttachmentID
						FROM inserted	
					),
				-- lets get the last seq used by each attach
				cteMaxSeq ( AttachmentID, MaxIndexSeq )
				  AS ( SELECT   bh.AttachmentID,
								MAX(bh.IndexSeq)
					   FROM     dbo.bHQAI AS bh
								JOIN cteDist dist ON dist.AttachmentID = bh.AttachmentID
					   GROUP BY bh.AttachmentID
					 ),
				-- generate new ordered numbers for each seq
				cteNewSeq ( [AttachmentID], [IndexSeq], [IndexName], [APCo], [APVendorGroup], [APVendor], [APReference], [APCheckNumber], [ARCo], [ARCustomer], [ARInvoice], [JCCo], [JCJob], [JCPhaseGroup], [JCPhase], [JCCostType], [JCContract], [JCContractItem], [POCo], [POPurchaseOrder], [POItem], [EMCo], [EMEquipment], [EMCostCode], [EMCostType], [PRCo], [PREmployee], [HRCo], [HRReference], [MIMaterialGroup], [MIMaterial], [MIMonth], [MITransaction], [INCo], [INLoc], [MSCo], [MSTicket], [SLCo], [SLSubcontract], [SLSubcontractItem], [Notes], [UniqueAttchID], [CustomYN], [UserCustom1], [UserCustom2], [UserCustom3], [UserCustom4], [UserCustom5], [PMIssue], [PMFirmNumber], [PMFirmType], [PMFirmContact], [PMSubmSrcFirm], [PMSubmSrcContact], [ARCustGroup], [EMGroup], [PMACO], [PMACOItem], [PMPCO], [PMPCOItem], [PMPCOType], [PMDocType], [PMSubmittal], [PMTransmittal], [PMRFQ], [PMRFI], [PMDocument], [PMInspectionCode], [PMTestCode], [PMDrawing], [PMMeeting], [PMPunchList], [PMLogDate], [PMDailyLog], [GLCo], [GLAcct], [PMRev], [PMSMPItem], [RQCo], [RQID], [RQLine], [RQQuote], [RQQuoteLine], [PRGroup], [PREndDate], [MO], [MOItem], [CMDeposit], [EmailSubject], [EmailReceivedDate], [EmailSentDate], [EmailFromAddress], [EmailToAddresses], [EmailCCAddresses], [IsEmailIndex],[PCBidPackage],[PCContactSeq],[PCPhaseGroup],[PCPhase],[PCPotentialProject],[PCScopeCode],[SMCo],[SMWorkOrder],[SMScope],[SMWorkScope],[SMCustGroup],[SMCustomer],[SMServiceSite],[SMServiceItem],NewIndexSeq )
				  AS ( SELECT   [AttachmentID],
								[IndexSeq],
								[IndexName],
								[APCo],
								[APVendorGroup],
								[APVendor],
								[APReference],
								[APCheckNumber],
								[ARCo],
								[ARCustomer],
								[ARInvoice],
								[JCCo],
								[JCJob],
								[JCPhaseGroup],
								[JCPhase],
								[JCCostType],
								[JCContract],
								[JCContractItem],
								[POCo],
								[POPurchaseOrder],
								[POItem],
								[EMCo],
								[EMEquipment],
								[EMCostCode],
								[EMCostType],
								[PRCo],
								[PREmployee],
								[HRCo],
								[HRReference],
								[MIMaterialGroup],
								[MIMaterial],
								[MIMonth],
								[MITransaction],
								[INCo],
								[INLoc],
								[MSCo],
								[MSTicket],
								[SLCo],
								[SLSubcontract],
								[SLSubcontractItem],
								[Notes],
								[UniqueAttchID],
								[CustomYN],
								[UserCustom1],
								[UserCustom2],
								[UserCustom3],
								[UserCustom4],
								[UserCustom5],
								[PMIssue],
								[PMFirmNumber],
								[PMFirmType],
								[PMFirmContact],
								[PMSubmSrcFirm],
								[PMSubmSrcContact],
								[ARCustGroup],
								[EMGroup],
								[PMACO],
								[PMACOItem],
								[PMPCO],
								[PMPCOItem],
								[PMPCOType],
								[PMDocType],
								[PMSubmittal],
								[PMTransmittal],
								[PMRFQ],
								[PMRFI],
								[PMDocument],
								[PMInspectionCode],
								[PMTestCode],
								[PMDrawing],
								[PMMeeting],
								[PMPunchList],
								[PMLogDate],
								[PMDailyLog],
								[GLCo],
								[GLAcct],
								[PMRev],
								[PMSMPItem],
								[RQCo],
								[RQID],
								[RQLine],
								[RQQuote],
								[RQQuoteLine],
								[PRGroup],
								[PREndDate],
								[MO],
								[MOItem],
								[CMDeposit],
								[EmailSubject],
								[EmailReceivedDate],
								[EmailSentDate],
								[EmailFromAddress],
								[EmailToAddresses],
								[EmailCCAddresses],
								[IsEmailIndex],
								[PCBidPackage],
								[PCContactSeq],								
								[PCPhaseGroup],
								[PCPhase],
								[PCPotentialProject],
								[PCScopeCode],
								[SMCo],
								[SMWorkOrder],
								[SMScope],
								[SMWorkScope],
								[SMCustGroup],
								[SMCustomer],
								[SMServiceSite],
								[SMServiceItem],
								-- row number all the nulls so I have an incrementing order
								RowNum = ROW_NUMBER() OVER ( PARTITION BY AttachmentID ORDER BY AttachmentID )
					   FROM     inserted
					 )
	                 

			-- one big insert to all the rows at once.	
			INSERT  INTO dbo.bHQAI
						( [AttachmentID],
						  [IndexSeq],
						  [IndexName],
						  [APCo],
						  [APVendorGroup],
						  [APVendor],
						  [APReference],
						  [APCheckNumber],
						  [ARCo],
						  [ARCustomer],
						  [ARInvoice],
						  [JCCo],
						  [JCJob],
						  [JCPhaseGroup],
						  [JCPhase],
						  [JCCostType],
						  [JCContract],
						  [JCContractItem],
						  [POCo],
						  [POPurchaseOrder],
						  [POItem],
						  [EMCo],
						  [EMEquipment],
						  [EMCostCode],
						  [EMCostType],
						  [PRCo],
						  [PREmployee],
						  [HRCo],
						  [HRReference],
						  [MIMaterialGroup],
						  [MIMaterial],
						  [MIMonth],
						  [MITransaction],
						  [INCo],
						  [INLoc],
						  [MSCo],
						  [MSTicket],
						  [SLCo],
						  [SLSubcontract],
						  [SLSubcontractItem],
						  [Notes],
						  [UniqueAttchID],
						  [CustomYN],
						  [UserCustom1],
						  [UserCustom2],
						  [UserCustom3],
						  [UserCustom4],
						  [UserCustom5],
						  [PMIssue],
						  [PMFirmNumber],
						  [PMFirmType],
						  [PMFirmContact],
						  [PMSubmSrcFirm],
						  [PMSubmSrcContact],
						  [ARCustGroup],
						  [EMGroup],
						  [PMACO],
						  [PMACOItem],
						  [PMPCO],
						  [PMPCOItem],
						  [PMPCOType],
						  [PMDocType],
						  [PMSubmittal],
						  [PMTransmittal],
						  [PMRFQ],
						  [PMRFI],
						  [PMDocument],
						  [PMInspectionCode],
						  [PMTestCode],
						  [PMDrawing],
						  [PMMeeting],
						  [PMPunchList],
						  [PMLogDate],
						  [PMDailyLog],
						  [GLCo],
						  [GLAcct],
						  [PMRev],
						  [PMSMPItem],
						  [RQCo],
						  [RQID],
						  [RQLine],
						  [RQQuote],
						  [RQQuoteLine],
						  [PRGroup],
						  [PREndDate],
						  [MO],
						  [MOItem],
						  [CMDeposit],
						  [EmailSubject],
						  [EmailReceivedDate],
						  [EmailSentDate],
						  [EmailFromAddress],
						  [EmailToAddresses],
						  [EmailCCAddresses],
						  [IsEmailIndex],
						  [PCBidPackage],
						  [PCContactSeq],						  
						  [PCPhaseGroup],
						  [PCPhase],
						  [PCPotentialProject],
						  [PCScopeCode],
							[SMCo],
							[SMWorkOrder],
							[SMScope],
							[SMWorkScope],
							[SMCustGroup],
							[SMCustomer],
							[SMServiceSite],
							[SMServiceItem]
						)
						SELECT  ns.[AttachmentID],
								-- add our new order numbers to the max value for a new value
								[IndexSeq] = ISNULL(ms.MaxIndexSeq, 0) + ns.NewIndexSeq,
								[IndexName],
								[APCo],
								[APVendorGroup],
								[APVendor],
								[APReference],
								[APCheckNumber],
								[ARCo],
								[ARCustomer],
								[ARInvoice],
								[JCCo],
								[JCJob],
								[JCPhaseGroup],
								[JCPhase],
								[JCCostType],
								[JCContract],
								[JCContractItem],
								[POCo],
								[POPurchaseOrder],
								[POItem],
								[EMCo],
								[EMEquipment],
								[EMCostCode],
								[EMCostType],
								[PRCo],
								[PREmployee],
								[HRCo],
								[HRReference],
								[MIMaterialGroup],
								[MIMaterial],
								[MIMonth],
								[MITransaction],
								[INCo],
								[INLoc],
								[MSCo],
								[MSTicket],
								[SLCo],
								[SLSubcontract],
								[SLSubcontractItem],
								[Notes],
								[UniqueAttchID],
								[CustomYN],
								[UserCustom1],
								[UserCustom2],
								[UserCustom3],
								[UserCustom4],
								[UserCustom5],
								[PMIssue],
								[PMFirmNumber],
								[PMFirmType],
								[PMFirmContact],
								[PMSubmSrcFirm],
								[PMSubmSrcContact],
								[ARCustGroup],
								[EMGroup],
								[PMACO],
								[PMACOItem],
								[PMPCO],
								[PMPCOItem],
								[PMPCOType],
								[PMDocType],
								[PMSubmittal],
								[PMTransmittal],
								[PMRFQ],
								[PMRFI],
								[PMDocument],
								[PMInspectionCode],
								[PMTestCode],
								[PMDrawing],
								[PMMeeting],
								[PMPunchList],
								[PMLogDate],
								[PMDailyLog],
								[GLCo],
								[GLAcct],
								[PMRev],
								[PMSMPItem],
								[RQCo],
								[RQID],
								[RQLine],
								[RQQuote],
								[RQQuoteLine],
								[PRGroup],
								[PREndDate],
								[MO],
								[MOItem],
								[CMDeposit],
								[EmailSubject],
								[EmailReceivedDate],
								[EmailSentDate],
								[EmailFromAddress],
								[EmailToAddresses],
								[EmailCCAddresses],
								[IsEmailIndex],
								[PCBidPackage],
								[PCContactSeq],								
								[PCPhaseGroup],
								[PCPhase],
								[PCPotentialProject],
								[PCScopeCode],
								[SMCo],
								[SMWorkOrder],
								[SMScope],
								[SMWorkScope],
								[SMCustGroup],
								[SMCustomer],
								[SMServiceSite],
								[SMServiceItem]
						FROM    cteNewSeq ns
								LEFT JOIN cteMaxSeq ms ON ms.AttachmentID = ns.AttachmentID

		END TRY
		BEGIN CATCH
			IF @@TRANCOUNT <> 0 BEGIN ROLLBACK END
		END CATCH 
GO

EXEC sp_bindrule N'[dbo].[brYesNo]', N'[dbo].[bHQAI].[CustomYN]'
GO
