CREATE TABLE [dbo].[bPMPM07162013]
(
[VendorGroup] [dbo].[bGroup] NOT NULL,
[FirmNumber] [dbo].[bFirm] NOT NULL,
[ContactCode] [dbo].[bEmployee] NOT NULL,
[SortName] [dbo].[bSortName] NOT NULL,
[LastName] [varchar] (30) COLLATE Latin1_General_BIN NOT NULL,
[FirstName] [varchar] (30) COLLATE Latin1_General_BIN NOT NULL,
[MiddleInit] [char] (1) COLLATE Latin1_General_BIN NULL,
[Title] [varchar] (30) COLLATE Latin1_General_BIN NULL,
[Phone] [dbo].[bPhone] NULL,
[PhoneExt] [varchar] (5) COLLATE Latin1_General_BIN NULL,
[MobilePhone] [dbo].[bPhone] NULL,
[Fax] [dbo].[bPhone] NULL,
[EMail] [varchar] (60) COLLATE Latin1_General_BIN NULL,
[PrefMethod] [char] (1) COLLATE Latin1_General_BIN NOT NULL,
[Notes] [varchar] (max) COLLATE Latin1_General_BIN NULL,
[UniqueAttchID] [uniqueidentifier] NULL,
[ExcludeYN] [dbo].[bYN] NOT NULL,
[MailAddress] [varchar] (60) COLLATE Latin1_General_BIN NULL,
[MailCity] [varchar] (30) COLLATE Latin1_General_BIN NULL,
[MailState] [varchar] (4) COLLATE Latin1_General_BIN NULL,
[MailZip] [dbo].[bZip] NULL,
[MailAddress2] [varchar] (60) COLLATE Latin1_General_BIN NULL,
[AllowPortalAccess] [dbo].[bYN] NOT NULL,
[PortalUserName] [varchar] (50) COLLATE Latin1_General_BIN NULL,
[PortalPassword] [varchar] (50) COLLATE Latin1_General_BIN NULL,
[PortalDefaultRole] [int] NULL,
[KeyID] [bigint] NOT NULL IDENTITY(1, 1),
[MailCountry] [char] (2) COLLATE Latin1_General_BIN NULL,
[UseAddressOvr] [dbo].[bYN] NOT NULL,
[CourtesyTitle] [varchar] (10) COLLATE Latin1_General_BIN NULL,
[FormattedFax] [varchar] (128) COLLATE Latin1_General_BIN NULL,
[UseFaxServerName] [char] (1) COLLATE Latin1_General_BIN NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
