IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'MCKINSTRY\ERPReportingTeam')
CREATE LOGIN [MCKINSTRY\ERPReportingTeam] FROM WINDOWS
GO
CREATE USER [MCKINSTRY\ERPReportingTeam] FOR LOGIN [MCKINSTRY\ERPReportingTeam]
GO
GRANT CONNECT TO [MCKINSTRY\ERPReportingTeam]
