IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'MCKINSTRY\SETESTVIEWPOINT$')
CREATE LOGIN [MCKINSTRY\SETESTVIEWPOINT$] FROM WINDOWS
GO
CREATE USER [MCKINSTRY\SETESTVIEWPOINT$] FOR LOGIN [MCKINSTRY\SETESTVIEWPOINT$]
GO
GRANT CONNECT TO [MCKINSTRY\SETESTVIEWPOINT$]
