CREATE TABLE [dbo].[vHQContact]
(
[HQContactID] [bigint] NOT NULL IDENTITY(1, 1),
[ContactGroup] [dbo].[bGroup] NOT NULL,
[ContactSeq] [int] NOT NULL,
[FirstName] [varchar] (30) COLLATE Latin1_General_BIN NULL,
[MiddleInitial] [char] (1) COLLATE Latin1_General_BIN NULL,
[LastName] [varchar] (30) COLLATE Latin1_General_BIN NULL,
[CourtesyTitle] [varchar] (10) COLLATE Latin1_General_BIN NULL,
[Title] [varchar] (30) COLLATE Latin1_General_BIN NULL,
[Organization] [varchar] (30) COLLATE Latin1_General_BIN NULL,
[Phone] [dbo].[bPhone] NULL,
[PhoneExtension] [varchar] (5) COLLATE Latin1_General_BIN NULL,
[Cell] [dbo].[bPhone] NULL,
[Fax] [dbo].[bPhone] NULL,
[Email] [varchar] (60) COLLATE Latin1_General_BIN NULL,
[Address] [varchar] (60) COLLATE Latin1_General_BIN NULL,
[AddressAdditional] [varchar] (60) COLLATE Latin1_General_BIN NULL,
[City] [varchar] (30) COLLATE Latin1_General_BIN NULL,
[State] [varchar] (4) COLLATE Latin1_General_BIN NULL,
[Country] [varchar] (2) COLLATE Latin1_General_BIN NULL,
[Zip] [dbo].[bZip] NULL,
[Notes] [varchar] (max) COLLATE Latin1_General_BIN NULL,
[UniqueAttchID] [uniqueidentifier] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER dbo.vtvHQContact_Audit_Delete ON dbo.vHQContact
 AFTER DELETE
 NOT FOR REPLICATION AS
 SET NOCOUNT ON 
 -- generated by vspAuditCreateAuditTriggers

 BEGIN TRY 

							INSERT dbo.HQMA (
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
								
							SELECT
								'vHQContact' , 
								'<KeyString ContactGroup = "' + REPLACE(CAST(ISNULL(deleted.[ContactGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" ContactSeq = "' + REPLACE(CAST(ISNULL(deleted.[ContactSeq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								deleted.ContactGroup , 
								'D' , 
								'Address' , 
								CONVERT(VARCHAR(MAX), deleted.[Address]) , 								NULL , 
								GETDATE() , 
								SUSER_SNAME()
							FROM deleted
								JOIN dbo.vAuditFlagGroup afg ON deleted.ContactGroup = afg.AuditGroup
							WHERE afg.AuditFlagID = 3
							INSERT dbo.HQMA (
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
								
							SELECT
								'vHQContact' , 
								'<KeyString ContactGroup = "' + REPLACE(CAST(ISNULL(deleted.[ContactGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" ContactSeq = "' + REPLACE(CAST(ISNULL(deleted.[ContactSeq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								deleted.ContactGroup , 
								'D' , 
								'AddressAdditional' , 
								CONVERT(VARCHAR(MAX), deleted.[AddressAdditional]) , 								NULL , 
								GETDATE() , 
								SUSER_SNAME()
							FROM deleted
								JOIN dbo.vAuditFlagGroup afg ON deleted.ContactGroup = afg.AuditGroup
							WHERE afg.AuditFlagID = 3
							INSERT dbo.HQMA (
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
								
							SELECT
								'vHQContact' , 
								'<KeyString ContactGroup = "' + REPLACE(CAST(ISNULL(deleted.[ContactGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" ContactSeq = "' + REPLACE(CAST(ISNULL(deleted.[ContactSeq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								deleted.ContactGroup , 
								'D' , 
								'Cell' , 
								CONVERT(VARCHAR(MAX), deleted.[Cell]) , 								NULL , 
								GETDATE() , 
								SUSER_SNAME()
							FROM deleted
								JOIN dbo.vAuditFlagGroup afg ON deleted.ContactGroup = afg.AuditGroup
							WHERE afg.AuditFlagID = 3
							INSERT dbo.HQMA (
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
								
							SELECT
								'vHQContact' , 
								'<KeyString ContactGroup = "' + REPLACE(CAST(ISNULL(deleted.[ContactGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" ContactSeq = "' + REPLACE(CAST(ISNULL(deleted.[ContactSeq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								deleted.ContactGroup , 
								'D' , 
								'City' , 
								CONVERT(VARCHAR(MAX), deleted.[City]) , 								NULL , 
								GETDATE() , 
								SUSER_SNAME()
							FROM deleted
								JOIN dbo.vAuditFlagGroup afg ON deleted.ContactGroup = afg.AuditGroup
							WHERE afg.AuditFlagID = 3
							INSERT dbo.HQMA (
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
								
							SELECT
								'vHQContact' , 
								'<KeyString ContactGroup = "' + REPLACE(CAST(ISNULL(deleted.[ContactGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" ContactSeq = "' + REPLACE(CAST(ISNULL(deleted.[ContactSeq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								deleted.ContactGroup , 
								'D' , 
								'ContactGroup' , 
								CONVERT(VARCHAR(MAX), deleted.[ContactGroup]) , 								NULL , 
								GETDATE() , 
								SUSER_SNAME()
							FROM deleted
								JOIN dbo.vAuditFlagGroup afg ON deleted.ContactGroup = afg.AuditGroup
							WHERE afg.AuditFlagID = 3
							INSERT dbo.HQMA (
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
								
							SELECT
								'vHQContact' , 
								'<KeyString ContactGroup = "' + REPLACE(CAST(ISNULL(deleted.[ContactGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" ContactSeq = "' + REPLACE(CAST(ISNULL(deleted.[ContactSeq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								deleted.ContactGroup , 
								'D' , 
								'ContactSeq' , 
								CONVERT(VARCHAR(MAX), deleted.[ContactSeq]) , 								NULL , 
								GETDATE() , 
								SUSER_SNAME()
							FROM deleted
								JOIN dbo.vAuditFlagGroup afg ON deleted.ContactGroup = afg.AuditGroup
							WHERE afg.AuditFlagID = 3
							INSERT dbo.HQMA (
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
								
							SELECT
								'vHQContact' , 
								'<KeyString ContactGroup = "' + REPLACE(CAST(ISNULL(deleted.[ContactGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" ContactSeq = "' + REPLACE(CAST(ISNULL(deleted.[ContactSeq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								deleted.ContactGroup , 
								'D' , 
								'Country' , 
								CONVERT(VARCHAR(MAX), deleted.[Country]) , 								NULL , 
								GETDATE() , 
								SUSER_SNAME()
							FROM deleted
								JOIN dbo.vAuditFlagGroup afg ON deleted.ContactGroup = afg.AuditGroup
							WHERE afg.AuditFlagID = 3
							INSERT dbo.HQMA (
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
								
							SELECT
								'vHQContact' , 
								'<KeyString ContactGroup = "' + REPLACE(CAST(ISNULL(deleted.[ContactGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" ContactSeq = "' + REPLACE(CAST(ISNULL(deleted.[ContactSeq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								deleted.ContactGroup , 
								'D' , 
								'CourtesyTitle' , 
								CONVERT(VARCHAR(MAX), deleted.[CourtesyTitle]) , 								NULL , 
								GETDATE() , 
								SUSER_SNAME()
							FROM deleted
								JOIN dbo.vAuditFlagGroup afg ON deleted.ContactGroup = afg.AuditGroup
							WHERE afg.AuditFlagID = 3
							INSERT dbo.HQMA (
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
								
							SELECT
								'vHQContact' , 
								'<KeyString ContactGroup = "' + REPLACE(CAST(ISNULL(deleted.[ContactGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" ContactSeq = "' + REPLACE(CAST(ISNULL(deleted.[ContactSeq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								deleted.ContactGroup , 
								'D' , 
								'Email' , 
								CONVERT(VARCHAR(MAX), deleted.[Email]) , 								NULL , 
								GETDATE() , 
								SUSER_SNAME()
							FROM deleted
								JOIN dbo.vAuditFlagGroup afg ON deleted.ContactGroup = afg.AuditGroup
							WHERE afg.AuditFlagID = 3
							INSERT dbo.HQMA (
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
								
							SELECT
								'vHQContact' , 
								'<KeyString ContactGroup = "' + REPLACE(CAST(ISNULL(deleted.[ContactGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" ContactSeq = "' + REPLACE(CAST(ISNULL(deleted.[ContactSeq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								deleted.ContactGroup , 
								'D' , 
								'Fax' , 
								CONVERT(VARCHAR(MAX), deleted.[Fax]) , 								NULL , 
								GETDATE() , 
								SUSER_SNAME()
							FROM deleted
								JOIN dbo.vAuditFlagGroup afg ON deleted.ContactGroup = afg.AuditGroup
							WHERE afg.AuditFlagID = 3
							INSERT dbo.HQMA (
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
								
							SELECT
								'vHQContact' , 
								'<KeyString ContactGroup = "' + REPLACE(CAST(ISNULL(deleted.[ContactGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" ContactSeq = "' + REPLACE(CAST(ISNULL(deleted.[ContactSeq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								deleted.ContactGroup , 
								'D' , 
								'FirstName' , 
								CONVERT(VARCHAR(MAX), deleted.[FirstName]) , 								NULL , 
								GETDATE() , 
								SUSER_SNAME()
							FROM deleted
								JOIN dbo.vAuditFlagGroup afg ON deleted.ContactGroup = afg.AuditGroup
							WHERE afg.AuditFlagID = 3
							INSERT dbo.HQMA (
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
								
							SELECT
								'vHQContact' , 
								'<KeyString ContactGroup = "' + REPLACE(CAST(ISNULL(deleted.[ContactGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" ContactSeq = "' + REPLACE(CAST(ISNULL(deleted.[ContactSeq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								deleted.ContactGroup , 
								'D' , 
								'HQContactID' , 
								CONVERT(VARCHAR(MAX), deleted.[HQContactID]) , 								NULL , 
								GETDATE() , 
								SUSER_SNAME()
							FROM deleted
								JOIN dbo.vAuditFlagGroup afg ON deleted.ContactGroup = afg.AuditGroup
							WHERE afg.AuditFlagID = 3
							INSERT dbo.HQMA (
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
								
							SELECT
								'vHQContact' , 
								'<KeyString ContactGroup = "' + REPLACE(CAST(ISNULL(deleted.[ContactGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" ContactSeq = "' + REPLACE(CAST(ISNULL(deleted.[ContactSeq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								deleted.ContactGroup , 
								'D' , 
								'LastName' , 
								CONVERT(VARCHAR(MAX), deleted.[LastName]) , 								NULL , 
								GETDATE() , 
								SUSER_SNAME()
							FROM deleted
								JOIN dbo.vAuditFlagGroup afg ON deleted.ContactGroup = afg.AuditGroup
							WHERE afg.AuditFlagID = 3
							INSERT dbo.HQMA (
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
								
							SELECT
								'vHQContact' , 
								'<KeyString ContactGroup = "' + REPLACE(CAST(ISNULL(deleted.[ContactGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" ContactSeq = "' + REPLACE(CAST(ISNULL(deleted.[ContactSeq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								deleted.ContactGroup , 
								'D' , 
								'MiddleInitial' , 
								CONVERT(VARCHAR(MAX), deleted.[MiddleInitial]) , 								NULL , 
								GETDATE() , 
								SUSER_SNAME()
							FROM deleted
								JOIN dbo.vAuditFlagGroup afg ON deleted.ContactGroup = afg.AuditGroup
							WHERE afg.AuditFlagID = 3
							INSERT dbo.HQMA (
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
								
							SELECT
								'vHQContact' , 
								'<KeyString ContactGroup = "' + REPLACE(CAST(ISNULL(deleted.[ContactGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" ContactSeq = "' + REPLACE(CAST(ISNULL(deleted.[ContactSeq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								deleted.ContactGroup , 
								'D' , 
								'Organization' , 
								CONVERT(VARCHAR(MAX), deleted.[Organization]) , 								NULL , 
								GETDATE() , 
								SUSER_SNAME()
							FROM deleted
								JOIN dbo.vAuditFlagGroup afg ON deleted.ContactGroup = afg.AuditGroup
							WHERE afg.AuditFlagID = 3
							INSERT dbo.HQMA (
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
								
							SELECT
								'vHQContact' , 
								'<KeyString ContactGroup = "' + REPLACE(CAST(ISNULL(deleted.[ContactGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" ContactSeq = "' + REPLACE(CAST(ISNULL(deleted.[ContactSeq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								deleted.ContactGroup , 
								'D' , 
								'Phone' , 
								CONVERT(VARCHAR(MAX), deleted.[Phone]) , 								NULL , 
								GETDATE() , 
								SUSER_SNAME()
							FROM deleted
								JOIN dbo.vAuditFlagGroup afg ON deleted.ContactGroup = afg.AuditGroup
							WHERE afg.AuditFlagID = 3
							INSERT dbo.HQMA (
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
								
							SELECT
								'vHQContact' , 
								'<KeyString ContactGroup = "' + REPLACE(CAST(ISNULL(deleted.[ContactGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" ContactSeq = "' + REPLACE(CAST(ISNULL(deleted.[ContactSeq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								deleted.ContactGroup , 
								'D' , 
								'PhoneExtension' , 
								CONVERT(VARCHAR(MAX), deleted.[PhoneExtension]) , 								NULL , 
								GETDATE() , 
								SUSER_SNAME()
							FROM deleted
								JOIN dbo.vAuditFlagGroup afg ON deleted.ContactGroup = afg.AuditGroup
							WHERE afg.AuditFlagID = 3
							INSERT dbo.HQMA (
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
								
							SELECT
								'vHQContact' , 
								'<KeyString ContactGroup = "' + REPLACE(CAST(ISNULL(deleted.[ContactGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" ContactSeq = "' + REPLACE(CAST(ISNULL(deleted.[ContactSeq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								deleted.ContactGroup , 
								'D' , 
								'State' , 
								CONVERT(VARCHAR(MAX), deleted.[State]) , 								NULL , 
								GETDATE() , 
								SUSER_SNAME()
							FROM deleted
								JOIN dbo.vAuditFlagGroup afg ON deleted.ContactGroup = afg.AuditGroup
							WHERE afg.AuditFlagID = 3
							INSERT dbo.HQMA (
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
								
							SELECT
								'vHQContact' , 
								'<KeyString ContactGroup = "' + REPLACE(CAST(ISNULL(deleted.[ContactGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" ContactSeq = "' + REPLACE(CAST(ISNULL(deleted.[ContactSeq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								deleted.ContactGroup , 
								'D' , 
								'Title' , 
								CONVERT(VARCHAR(MAX), deleted.[Title]) , 								NULL , 
								GETDATE() , 
								SUSER_SNAME()
							FROM deleted
								JOIN dbo.vAuditFlagGroup afg ON deleted.ContactGroup = afg.AuditGroup
							WHERE afg.AuditFlagID = 3
							INSERT dbo.HQMA (
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
								
							SELECT
								'vHQContact' , 
								'<KeyString ContactGroup = "' + REPLACE(CAST(ISNULL(deleted.[ContactGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" ContactSeq = "' + REPLACE(CAST(ISNULL(deleted.[ContactSeq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								deleted.ContactGroup , 
								'D' , 
								'UniqueAttchID' , 
								CONVERT(VARCHAR(MAX), deleted.[UniqueAttchID]) , 								NULL , 
								GETDATE() , 
								SUSER_SNAME()
							FROM deleted
								JOIN dbo.vAuditFlagGroup afg ON deleted.ContactGroup = afg.AuditGroup
							WHERE afg.AuditFlagID = 3
							INSERT dbo.HQMA (
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
								
							SELECT
								'vHQContact' , 
								'<KeyString ContactGroup = "' + REPLACE(CAST(ISNULL(deleted.[ContactGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" ContactSeq = "' + REPLACE(CAST(ISNULL(deleted.[ContactSeq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								deleted.ContactGroup , 
								'D' , 
								'Zip' , 
								CONVERT(VARCHAR(MAX), deleted.[Zip]) , 								NULL , 
								GETDATE() , 
								SUSER_SNAME()
							FROM deleted
								JOIN dbo.vAuditFlagGroup afg ON deleted.ContactGroup = afg.AuditGroup
							WHERE afg.AuditFlagID = 3

							
 END TRY 
 BEGIN CATCH 
   DECLARE	@ErrorMessage	NVARCHAR(4000), 
				@ErrorSeverity	INT; 

   SELECT	@ErrorMessage = 'Error '+ ISNULL(ERROR_MESSAGE(),'') +' in [dbo].[dbo.vtvHQContact_Audit_Delete] trigger', 
				@ErrorSeverity = ERROR_SEVERITY(); 

   RAISERROR(@ErrorMessage, @ErrorSeverity, 1 ) 
 END CATCH 
GO
EXEC sp_settriggerorder N'[dbo].[vtvHQContact_Audit_Delete]', 'last', 'delete', null
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER dbo.vtvHQContact_Audit_Insert ON dbo.vHQContact
 AFTER INSERT
 NOT FOR REPLICATION AS
 SET NOCOUNT ON 
 -- generated by vspAuditTriggersCreate

 BEGIN TRY 

-- log additions to the Address column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vHQContact' , 
								'<KeyString ContactGroup = "' + REPLACE(CAST(ISNULL(inserted.[ContactGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" ContactSeq = "' + REPLACE(CAST(ISNULL(inserted.[ContactSeq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.ContactGroup, '') , 
								'A' , 
								'Address' , 
								NULL , 
								Address , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								JOIN dbo.vAuditFlagGroup afg ON inserted.ContactGroup = afg.AuditGroup
							WHERE afg.AuditFlagID = 3

-- log additions to the AddressAdditional column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vHQContact' , 
								'<KeyString ContactGroup = "' + REPLACE(CAST(ISNULL(inserted.[ContactGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" ContactSeq = "' + REPLACE(CAST(ISNULL(inserted.[ContactSeq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.ContactGroup, '') , 
								'A' , 
								'AddressAdditional' , 
								NULL , 
								AddressAdditional , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								JOIN dbo.vAuditFlagGroup afg ON inserted.ContactGroup = afg.AuditGroup
							WHERE afg.AuditFlagID = 3

-- log additions to the Cell column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vHQContact' , 
								'<KeyString ContactGroup = "' + REPLACE(CAST(ISNULL(inserted.[ContactGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" ContactSeq = "' + REPLACE(CAST(ISNULL(inserted.[ContactSeq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.ContactGroup, '') , 
								'A' , 
								'Cell' , 
								NULL , 
								Cell , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								JOIN dbo.vAuditFlagGroup afg ON inserted.ContactGroup = afg.AuditGroup
							WHERE afg.AuditFlagID = 3

-- log additions to the City column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vHQContact' , 
								'<KeyString ContactGroup = "' + REPLACE(CAST(ISNULL(inserted.[ContactGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" ContactSeq = "' + REPLACE(CAST(ISNULL(inserted.[ContactSeq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.ContactGroup, '') , 
								'A' , 
								'City' , 
								NULL , 
								City , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								JOIN dbo.vAuditFlagGroup afg ON inserted.ContactGroup = afg.AuditGroup
							WHERE afg.AuditFlagID = 3

-- log additions to the ContactGroup column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vHQContact' , 
								'<KeyString ContactGroup = "' + REPLACE(CAST(ISNULL(inserted.[ContactGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" ContactSeq = "' + REPLACE(CAST(ISNULL(inserted.[ContactSeq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.ContactGroup, '') , 
								'A' , 
								'ContactGroup' , 
								NULL , 
								ContactGroup , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								JOIN dbo.vAuditFlagGroup afg ON inserted.ContactGroup = afg.AuditGroup
							WHERE afg.AuditFlagID = 3

-- log additions to the ContactSeq column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vHQContact' , 
								'<KeyString ContactGroup = "' + REPLACE(CAST(ISNULL(inserted.[ContactGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" ContactSeq = "' + REPLACE(CAST(ISNULL(inserted.[ContactSeq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.ContactGroup, '') , 
								'A' , 
								'ContactSeq' , 
								NULL , 
								ContactSeq , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								JOIN dbo.vAuditFlagGroup afg ON inserted.ContactGroup = afg.AuditGroup
							WHERE afg.AuditFlagID = 3

-- log additions to the Country column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vHQContact' , 
								'<KeyString ContactGroup = "' + REPLACE(CAST(ISNULL(inserted.[ContactGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" ContactSeq = "' + REPLACE(CAST(ISNULL(inserted.[ContactSeq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.ContactGroup, '') , 
								'A' , 
								'Country' , 
								NULL , 
								Country , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								JOIN dbo.vAuditFlagGroup afg ON inserted.ContactGroup = afg.AuditGroup
							WHERE afg.AuditFlagID = 3

-- log additions to the CourtesyTitle column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vHQContact' , 
								'<KeyString ContactGroup = "' + REPLACE(CAST(ISNULL(inserted.[ContactGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" ContactSeq = "' + REPLACE(CAST(ISNULL(inserted.[ContactSeq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.ContactGroup, '') , 
								'A' , 
								'CourtesyTitle' , 
								NULL , 
								CourtesyTitle , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								JOIN dbo.vAuditFlagGroup afg ON inserted.ContactGroup = afg.AuditGroup
							WHERE afg.AuditFlagID = 3

-- log additions to the Email column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vHQContact' , 
								'<KeyString ContactGroup = "' + REPLACE(CAST(ISNULL(inserted.[ContactGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" ContactSeq = "' + REPLACE(CAST(ISNULL(inserted.[ContactSeq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.ContactGroup, '') , 
								'A' , 
								'Email' , 
								NULL , 
								Email , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								JOIN dbo.vAuditFlagGroup afg ON inserted.ContactGroup = afg.AuditGroup
							WHERE afg.AuditFlagID = 3

-- log additions to the Fax column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vHQContact' , 
								'<KeyString ContactGroup = "' + REPLACE(CAST(ISNULL(inserted.[ContactGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" ContactSeq = "' + REPLACE(CAST(ISNULL(inserted.[ContactSeq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.ContactGroup, '') , 
								'A' , 
								'Fax' , 
								NULL , 
								Fax , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								JOIN dbo.vAuditFlagGroup afg ON inserted.ContactGroup = afg.AuditGroup
							WHERE afg.AuditFlagID = 3

-- log additions to the FirstName column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vHQContact' , 
								'<KeyString ContactGroup = "' + REPLACE(CAST(ISNULL(inserted.[ContactGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" ContactSeq = "' + REPLACE(CAST(ISNULL(inserted.[ContactSeq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.ContactGroup, '') , 
								'A' , 
								'FirstName' , 
								NULL , 
								FirstName , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								JOIN dbo.vAuditFlagGroup afg ON inserted.ContactGroup = afg.AuditGroup
							WHERE afg.AuditFlagID = 3

-- log additions to the HQContactID column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vHQContact' , 
								'<KeyString ContactGroup = "' + REPLACE(CAST(ISNULL(inserted.[ContactGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" ContactSeq = "' + REPLACE(CAST(ISNULL(inserted.[ContactSeq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.ContactGroup, '') , 
								'A' , 
								'HQContactID' , 
								NULL , 
								HQContactID , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								JOIN dbo.vAuditFlagGroup afg ON inserted.ContactGroup = afg.AuditGroup
							WHERE afg.AuditFlagID = 3

-- log additions to the LastName column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vHQContact' , 
								'<KeyString ContactGroup = "' + REPLACE(CAST(ISNULL(inserted.[ContactGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" ContactSeq = "' + REPLACE(CAST(ISNULL(inserted.[ContactSeq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.ContactGroup, '') , 
								'A' , 
								'LastName' , 
								NULL , 
								LastName , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								JOIN dbo.vAuditFlagGroup afg ON inserted.ContactGroup = afg.AuditGroup
							WHERE afg.AuditFlagID = 3

-- log additions to the MiddleInitial column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vHQContact' , 
								'<KeyString ContactGroup = "' + REPLACE(CAST(ISNULL(inserted.[ContactGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" ContactSeq = "' + REPLACE(CAST(ISNULL(inserted.[ContactSeq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.ContactGroup, '') , 
								'A' , 
								'MiddleInitial' , 
								NULL , 
								MiddleInitial , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								JOIN dbo.vAuditFlagGroup afg ON inserted.ContactGroup = afg.AuditGroup
							WHERE afg.AuditFlagID = 3

-- log additions to the Organization column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vHQContact' , 
								'<KeyString ContactGroup = "' + REPLACE(CAST(ISNULL(inserted.[ContactGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" ContactSeq = "' + REPLACE(CAST(ISNULL(inserted.[ContactSeq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.ContactGroup, '') , 
								'A' , 
								'Organization' , 
								NULL , 
								Organization , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								JOIN dbo.vAuditFlagGroup afg ON inserted.ContactGroup = afg.AuditGroup
							WHERE afg.AuditFlagID = 3

-- log additions to the Phone column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vHQContact' , 
								'<KeyString ContactGroup = "' + REPLACE(CAST(ISNULL(inserted.[ContactGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" ContactSeq = "' + REPLACE(CAST(ISNULL(inserted.[ContactSeq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.ContactGroup, '') , 
								'A' , 
								'Phone' , 
								NULL , 
								Phone , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								JOIN dbo.vAuditFlagGroup afg ON inserted.ContactGroup = afg.AuditGroup
							WHERE afg.AuditFlagID = 3

-- log additions to the PhoneExtension column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vHQContact' , 
								'<KeyString ContactGroup = "' + REPLACE(CAST(ISNULL(inserted.[ContactGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" ContactSeq = "' + REPLACE(CAST(ISNULL(inserted.[ContactSeq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.ContactGroup, '') , 
								'A' , 
								'PhoneExtension' , 
								NULL , 
								PhoneExtension , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								JOIN dbo.vAuditFlagGroup afg ON inserted.ContactGroup = afg.AuditGroup
							WHERE afg.AuditFlagID = 3

-- log additions to the State column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vHQContact' , 
								'<KeyString ContactGroup = "' + REPLACE(CAST(ISNULL(inserted.[ContactGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" ContactSeq = "' + REPLACE(CAST(ISNULL(inserted.[ContactSeq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.ContactGroup, '') , 
								'A' , 
								'State' , 
								NULL , 
								State , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								JOIN dbo.vAuditFlagGroup afg ON inserted.ContactGroup = afg.AuditGroup
							WHERE afg.AuditFlagID = 3

-- log additions to the Title column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vHQContact' , 
								'<KeyString ContactGroup = "' + REPLACE(CAST(ISNULL(inserted.[ContactGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" ContactSeq = "' + REPLACE(CAST(ISNULL(inserted.[ContactSeq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.ContactGroup, '') , 
								'A' , 
								'Title' , 
								NULL , 
								Title , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								JOIN dbo.vAuditFlagGroup afg ON inserted.ContactGroup = afg.AuditGroup
							WHERE afg.AuditFlagID = 3

-- log additions to the UniqueAttchID column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vHQContact' , 
								'<KeyString ContactGroup = "' + REPLACE(CAST(ISNULL(inserted.[ContactGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" ContactSeq = "' + REPLACE(CAST(ISNULL(inserted.[ContactSeq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.ContactGroup, '') , 
								'A' , 
								'UniqueAttchID' , 
								NULL , 
								UniqueAttchID , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								JOIN dbo.vAuditFlagGroup afg ON inserted.ContactGroup = afg.AuditGroup
							WHERE afg.AuditFlagID = 3

-- log additions to the Zip column
							INSERT dbo.bHQMA (	
													TableName, 
													KeyString, 
													Co, 
													RecType, 
													FieldName, 
													OldValue, 
													NewValue, 
													DateTime, 
													UserName)
							
							SELECT 
								'vHQContact' , 
								'<KeyString ContactGroup = "' + REPLACE(CAST(ISNULL(inserted.[ContactGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" ContactSeq = "' + REPLACE(CAST(ISNULL(inserted.[ContactSeq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 
								ISNULL(inserted.ContactGroup, '') , 
								'A' , 
								'Zip' , 
								NULL , 
								Zip , 
								GETDATE() , 
								SUSER_SNAME()
							FROM inserted
								JOIN dbo.vAuditFlagGroup afg ON inserted.ContactGroup = afg.AuditGroup
							WHERE afg.AuditFlagID = 3


 END TRY 
 BEGIN CATCH 
   DECLARE	@ErrorMessage	NVARCHAR(4000), 
				@ErrorSeverity	INT; 

   SELECT	@ErrorMessage = 'Error '+ ISNULL(ERROR_MESSAGE(),'') +' in [dbo].[dbo.vtvHQContact_Audit_Insert] trigger', 
				@ErrorSeverity = ERROR_SEVERITY(); 

   RAISERROR(@ErrorMessage, @ErrorSeverity, 1 ) 
 END CATCH 
GO
EXEC sp_settriggerorder N'[dbo].[vtvHQContact_Audit_Insert]', 'last', 'insert', null
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER dbo.vtvHQContact_Audit_Update ON dbo.vHQContact
 AFTER UPDATE 
 NOT FOR REPLICATION AS 
 SET NOCOUNT ON 
 -- generated by vspAuditTriggersCreate

 BEGIN TRY 

							IF UPDATE([Address])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vHQContact' , 								'<KeyString ContactGroup = "' + REPLACE(CAST(ISNULL(inserted.[ContactGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" ContactSeq = "' + REPLACE(CAST(ISNULL(inserted.[ContactSeq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.ContactGroup , 								'C' , 								'Address' , 								CONVERT(VARCHAR(MAX), deleted.[Address]) , 								CONVERT(VARCHAR(MAX), inserted.[Address]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[HQContactID] = deleted.[HQContactID] 
									AND ((inserted.[Address] <> deleted.[Address]) OR (inserted.[Address] IS NULL AND deleted.[Address] IS NOT NULL) OR (inserted.[Address] IS NOT NULL AND deleted.[Address] IS NULL))
								JOIN dbo.vAuditFlagGroup afg ON inserted.ContactGroup = afg.AuditGroup
							WHERE afg.AuditFlagID = 3

							END 

							IF UPDATE([AddressAdditional])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vHQContact' , 								'<KeyString ContactGroup = "' + REPLACE(CAST(ISNULL(inserted.[ContactGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" ContactSeq = "' + REPLACE(CAST(ISNULL(inserted.[ContactSeq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.ContactGroup , 								'C' , 								'AddressAdditional' , 								CONVERT(VARCHAR(MAX), deleted.[AddressAdditional]) , 								CONVERT(VARCHAR(MAX), inserted.[AddressAdditional]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[HQContactID] = deleted.[HQContactID] 
									AND ((inserted.[AddressAdditional] <> deleted.[AddressAdditional]) OR (inserted.[AddressAdditional] IS NULL AND deleted.[AddressAdditional] IS NOT NULL) OR (inserted.[AddressAdditional] IS NOT NULL AND deleted.[AddressAdditional] IS NULL))
								JOIN dbo.vAuditFlagGroup afg ON inserted.ContactGroup = afg.AuditGroup
							WHERE afg.AuditFlagID = 3

							END 

							IF UPDATE([Cell])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vHQContact' , 								'<KeyString ContactGroup = "' + REPLACE(CAST(ISNULL(inserted.[ContactGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" ContactSeq = "' + REPLACE(CAST(ISNULL(inserted.[ContactSeq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.ContactGroup , 								'C' , 								'Cell' , 								CONVERT(VARCHAR(MAX), deleted.[Cell]) , 								CONVERT(VARCHAR(MAX), inserted.[Cell]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[HQContactID] = deleted.[HQContactID] 
									AND ((inserted.[Cell] <> deleted.[Cell]) OR (inserted.[Cell] IS NULL AND deleted.[Cell] IS NOT NULL) OR (inserted.[Cell] IS NOT NULL AND deleted.[Cell] IS NULL))
								JOIN dbo.vAuditFlagGroup afg ON inserted.ContactGroup = afg.AuditGroup
							WHERE afg.AuditFlagID = 3

							END 

							IF UPDATE([City])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vHQContact' , 								'<KeyString ContactGroup = "' + REPLACE(CAST(ISNULL(inserted.[ContactGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" ContactSeq = "' + REPLACE(CAST(ISNULL(inserted.[ContactSeq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.ContactGroup , 								'C' , 								'City' , 								CONVERT(VARCHAR(MAX), deleted.[City]) , 								CONVERT(VARCHAR(MAX), inserted.[City]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[HQContactID] = deleted.[HQContactID] 
									AND ((inserted.[City] <> deleted.[City]) OR (inserted.[City] IS NULL AND deleted.[City] IS NOT NULL) OR (inserted.[City] IS NOT NULL AND deleted.[City] IS NULL))
								JOIN dbo.vAuditFlagGroup afg ON inserted.ContactGroup = afg.AuditGroup
							WHERE afg.AuditFlagID = 3

							END 

							IF UPDATE([ContactGroup])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vHQContact' , 								'<KeyString ContactGroup = "' + REPLACE(CAST(ISNULL(inserted.[ContactGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" ContactSeq = "' + REPLACE(CAST(ISNULL(inserted.[ContactSeq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.ContactGroup , 								'C' , 								'ContactGroup' , 								CONVERT(VARCHAR(MAX), deleted.[ContactGroup]) , 								CONVERT(VARCHAR(MAX), inserted.[ContactGroup]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[HQContactID] = deleted.[HQContactID] 
									AND ((inserted.[ContactGroup] <> deleted.[ContactGroup]) OR (inserted.[ContactGroup] IS NULL AND deleted.[ContactGroup] IS NOT NULL) OR (inserted.[ContactGroup] IS NOT NULL AND deleted.[ContactGroup] IS NULL))
								JOIN dbo.vAuditFlagGroup afg ON inserted.ContactGroup = afg.AuditGroup
							WHERE afg.AuditFlagID = 3

							END 

							IF UPDATE([ContactSeq])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vHQContact' , 								'<KeyString ContactGroup = "' + REPLACE(CAST(ISNULL(inserted.[ContactGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" ContactSeq = "' + REPLACE(CAST(ISNULL(inserted.[ContactSeq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.ContactGroup , 								'C' , 								'ContactSeq' , 								CONVERT(VARCHAR(MAX), deleted.[ContactSeq]) , 								CONVERT(VARCHAR(MAX), inserted.[ContactSeq]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[HQContactID] = deleted.[HQContactID] 
									AND ((inserted.[ContactSeq] <> deleted.[ContactSeq]) OR (inserted.[ContactSeq] IS NULL AND deleted.[ContactSeq] IS NOT NULL) OR (inserted.[ContactSeq] IS NOT NULL AND deleted.[ContactSeq] IS NULL))
								JOIN dbo.vAuditFlagGroup afg ON inserted.ContactGroup = afg.AuditGroup
							WHERE afg.AuditFlagID = 3

							END 

							IF UPDATE([Country])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vHQContact' , 								'<KeyString ContactGroup = "' + REPLACE(CAST(ISNULL(inserted.[ContactGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" ContactSeq = "' + REPLACE(CAST(ISNULL(inserted.[ContactSeq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.ContactGroup , 								'C' , 								'Country' , 								CONVERT(VARCHAR(MAX), deleted.[Country]) , 								CONVERT(VARCHAR(MAX), inserted.[Country]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[HQContactID] = deleted.[HQContactID] 
									AND ((inserted.[Country] <> deleted.[Country]) OR (inserted.[Country] IS NULL AND deleted.[Country] IS NOT NULL) OR (inserted.[Country] IS NOT NULL AND deleted.[Country] IS NULL))
								JOIN dbo.vAuditFlagGroup afg ON inserted.ContactGroup = afg.AuditGroup
							WHERE afg.AuditFlagID = 3

							END 

							IF UPDATE([CourtesyTitle])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vHQContact' , 								'<KeyString ContactGroup = "' + REPLACE(CAST(ISNULL(inserted.[ContactGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" ContactSeq = "' + REPLACE(CAST(ISNULL(inserted.[ContactSeq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.ContactGroup , 								'C' , 								'CourtesyTitle' , 								CONVERT(VARCHAR(MAX), deleted.[CourtesyTitle]) , 								CONVERT(VARCHAR(MAX), inserted.[CourtesyTitle]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[HQContactID] = deleted.[HQContactID] 
									AND ((inserted.[CourtesyTitle] <> deleted.[CourtesyTitle]) OR (inserted.[CourtesyTitle] IS NULL AND deleted.[CourtesyTitle] IS NOT NULL) OR (inserted.[CourtesyTitle] IS NOT NULL AND deleted.[CourtesyTitle] IS NULL))
								JOIN dbo.vAuditFlagGroup afg ON inserted.ContactGroup = afg.AuditGroup
							WHERE afg.AuditFlagID = 3

							END 

							IF UPDATE([Email])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vHQContact' , 								'<KeyString ContactGroup = "' + REPLACE(CAST(ISNULL(inserted.[ContactGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" ContactSeq = "' + REPLACE(CAST(ISNULL(inserted.[ContactSeq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.ContactGroup , 								'C' , 								'Email' , 								CONVERT(VARCHAR(MAX), deleted.[Email]) , 								CONVERT(VARCHAR(MAX), inserted.[Email]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[HQContactID] = deleted.[HQContactID] 
									AND ((inserted.[Email] <> deleted.[Email]) OR (inserted.[Email] IS NULL AND deleted.[Email] IS NOT NULL) OR (inserted.[Email] IS NOT NULL AND deleted.[Email] IS NULL))
								JOIN dbo.vAuditFlagGroup afg ON inserted.ContactGroup = afg.AuditGroup
							WHERE afg.AuditFlagID = 3

							END 

							IF UPDATE([Fax])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vHQContact' , 								'<KeyString ContactGroup = "' + REPLACE(CAST(ISNULL(inserted.[ContactGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" ContactSeq = "' + REPLACE(CAST(ISNULL(inserted.[ContactSeq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.ContactGroup , 								'C' , 								'Fax' , 								CONVERT(VARCHAR(MAX), deleted.[Fax]) , 								CONVERT(VARCHAR(MAX), inserted.[Fax]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[HQContactID] = deleted.[HQContactID] 
									AND ((inserted.[Fax] <> deleted.[Fax]) OR (inserted.[Fax] IS NULL AND deleted.[Fax] IS NOT NULL) OR (inserted.[Fax] IS NOT NULL AND deleted.[Fax] IS NULL))
								JOIN dbo.vAuditFlagGroup afg ON inserted.ContactGroup = afg.AuditGroup
							WHERE afg.AuditFlagID = 3

							END 

							IF UPDATE([FirstName])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vHQContact' , 								'<KeyString ContactGroup = "' + REPLACE(CAST(ISNULL(inserted.[ContactGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" ContactSeq = "' + REPLACE(CAST(ISNULL(inserted.[ContactSeq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.ContactGroup , 								'C' , 								'FirstName' , 								CONVERT(VARCHAR(MAX), deleted.[FirstName]) , 								CONVERT(VARCHAR(MAX), inserted.[FirstName]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[HQContactID] = deleted.[HQContactID] 
									AND ((inserted.[FirstName] <> deleted.[FirstName]) OR (inserted.[FirstName] IS NULL AND deleted.[FirstName] IS NOT NULL) OR (inserted.[FirstName] IS NOT NULL AND deleted.[FirstName] IS NULL))
								JOIN dbo.vAuditFlagGroup afg ON inserted.ContactGroup = afg.AuditGroup
							WHERE afg.AuditFlagID = 3

							END 

							IF UPDATE([HQContactID])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vHQContact' , 								'<KeyString ContactGroup = "' + REPLACE(CAST(ISNULL(inserted.[ContactGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" ContactSeq = "' + REPLACE(CAST(ISNULL(inserted.[ContactSeq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.ContactGroup , 								'C' , 								'HQContactID' , 								CONVERT(VARCHAR(MAX), deleted.[HQContactID]) , 								CONVERT(VARCHAR(MAX), inserted.[HQContactID]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[HQContactID] = deleted.[HQContactID] 
									AND ((inserted.[HQContactID] <> deleted.[HQContactID]) OR (inserted.[HQContactID] IS NULL AND deleted.[HQContactID] IS NOT NULL) OR (inserted.[HQContactID] IS NOT NULL AND deleted.[HQContactID] IS NULL))
								JOIN dbo.vAuditFlagGroup afg ON inserted.ContactGroup = afg.AuditGroup
							WHERE afg.AuditFlagID = 3

							END 

							IF UPDATE([LastName])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vHQContact' , 								'<KeyString ContactGroup = "' + REPLACE(CAST(ISNULL(inserted.[ContactGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" ContactSeq = "' + REPLACE(CAST(ISNULL(inserted.[ContactSeq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.ContactGroup , 								'C' , 								'LastName' , 								CONVERT(VARCHAR(MAX), deleted.[LastName]) , 								CONVERT(VARCHAR(MAX), inserted.[LastName]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[HQContactID] = deleted.[HQContactID] 
									AND ((inserted.[LastName] <> deleted.[LastName]) OR (inserted.[LastName] IS NULL AND deleted.[LastName] IS NOT NULL) OR (inserted.[LastName] IS NOT NULL AND deleted.[LastName] IS NULL))
								JOIN dbo.vAuditFlagGroup afg ON inserted.ContactGroup = afg.AuditGroup
							WHERE afg.AuditFlagID = 3

							END 

							IF UPDATE([MiddleInitial])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vHQContact' , 								'<KeyString ContactGroup = "' + REPLACE(CAST(ISNULL(inserted.[ContactGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" ContactSeq = "' + REPLACE(CAST(ISNULL(inserted.[ContactSeq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.ContactGroup , 								'C' , 								'MiddleInitial' , 								CONVERT(VARCHAR(MAX), deleted.[MiddleInitial]) , 								CONVERT(VARCHAR(MAX), inserted.[MiddleInitial]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[HQContactID] = deleted.[HQContactID] 
									AND ((inserted.[MiddleInitial] <> deleted.[MiddleInitial]) OR (inserted.[MiddleInitial] IS NULL AND deleted.[MiddleInitial] IS NOT NULL) OR (inserted.[MiddleInitial] IS NOT NULL AND deleted.[MiddleInitial] IS NULL))
								JOIN dbo.vAuditFlagGroup afg ON inserted.ContactGroup = afg.AuditGroup
							WHERE afg.AuditFlagID = 3

							END 

							IF UPDATE([Organization])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vHQContact' , 								'<KeyString ContactGroup = "' + REPLACE(CAST(ISNULL(inserted.[ContactGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" ContactSeq = "' + REPLACE(CAST(ISNULL(inserted.[ContactSeq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.ContactGroup , 								'C' , 								'Organization' , 								CONVERT(VARCHAR(MAX), deleted.[Organization]) , 								CONVERT(VARCHAR(MAX), inserted.[Organization]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[HQContactID] = deleted.[HQContactID] 
									AND ((inserted.[Organization] <> deleted.[Organization]) OR (inserted.[Organization] IS NULL AND deleted.[Organization] IS NOT NULL) OR (inserted.[Organization] IS NOT NULL AND deleted.[Organization] IS NULL))
								JOIN dbo.vAuditFlagGroup afg ON inserted.ContactGroup = afg.AuditGroup
							WHERE afg.AuditFlagID = 3

							END 

							IF UPDATE([Phone])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vHQContact' , 								'<KeyString ContactGroup = "' + REPLACE(CAST(ISNULL(inserted.[ContactGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" ContactSeq = "' + REPLACE(CAST(ISNULL(inserted.[ContactSeq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.ContactGroup , 								'C' , 								'Phone' , 								CONVERT(VARCHAR(MAX), deleted.[Phone]) , 								CONVERT(VARCHAR(MAX), inserted.[Phone]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[HQContactID] = deleted.[HQContactID] 
									AND ((inserted.[Phone] <> deleted.[Phone]) OR (inserted.[Phone] IS NULL AND deleted.[Phone] IS NOT NULL) OR (inserted.[Phone] IS NOT NULL AND deleted.[Phone] IS NULL))
								JOIN dbo.vAuditFlagGroup afg ON inserted.ContactGroup = afg.AuditGroup
							WHERE afg.AuditFlagID = 3

							END 

							IF UPDATE([PhoneExtension])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vHQContact' , 								'<KeyString ContactGroup = "' + REPLACE(CAST(ISNULL(inserted.[ContactGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" ContactSeq = "' + REPLACE(CAST(ISNULL(inserted.[ContactSeq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.ContactGroup , 								'C' , 								'PhoneExtension' , 								CONVERT(VARCHAR(MAX), deleted.[PhoneExtension]) , 								CONVERT(VARCHAR(MAX), inserted.[PhoneExtension]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[HQContactID] = deleted.[HQContactID] 
									AND ((inserted.[PhoneExtension] <> deleted.[PhoneExtension]) OR (inserted.[PhoneExtension] IS NULL AND deleted.[PhoneExtension] IS NOT NULL) OR (inserted.[PhoneExtension] IS NOT NULL AND deleted.[PhoneExtension] IS NULL))
								JOIN dbo.vAuditFlagGroup afg ON inserted.ContactGroup = afg.AuditGroup
							WHERE afg.AuditFlagID = 3

							END 

							IF UPDATE([State])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vHQContact' , 								'<KeyString ContactGroup = "' + REPLACE(CAST(ISNULL(inserted.[ContactGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" ContactSeq = "' + REPLACE(CAST(ISNULL(inserted.[ContactSeq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.ContactGroup , 								'C' , 								'State' , 								CONVERT(VARCHAR(MAX), deleted.[State]) , 								CONVERT(VARCHAR(MAX), inserted.[State]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[HQContactID] = deleted.[HQContactID] 
									AND ((inserted.[State] <> deleted.[State]) OR (inserted.[State] IS NULL AND deleted.[State] IS NOT NULL) OR (inserted.[State] IS NOT NULL AND deleted.[State] IS NULL))
								JOIN dbo.vAuditFlagGroup afg ON inserted.ContactGroup = afg.AuditGroup
							WHERE afg.AuditFlagID = 3

							END 

							IF UPDATE([Title])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vHQContact' , 								'<KeyString ContactGroup = "' + REPLACE(CAST(ISNULL(inserted.[ContactGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" ContactSeq = "' + REPLACE(CAST(ISNULL(inserted.[ContactSeq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.ContactGroup , 								'C' , 								'Title' , 								CONVERT(VARCHAR(MAX), deleted.[Title]) , 								CONVERT(VARCHAR(MAX), inserted.[Title]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[HQContactID] = deleted.[HQContactID] 
									AND ((inserted.[Title] <> deleted.[Title]) OR (inserted.[Title] IS NULL AND deleted.[Title] IS NOT NULL) OR (inserted.[Title] IS NOT NULL AND deleted.[Title] IS NULL))
								JOIN dbo.vAuditFlagGroup afg ON inserted.ContactGroup = afg.AuditGroup
							WHERE afg.AuditFlagID = 3

							END 

							IF UPDATE([UniqueAttchID])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vHQContact' , 								'<KeyString ContactGroup = "' + REPLACE(CAST(ISNULL(inserted.[ContactGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" ContactSeq = "' + REPLACE(CAST(ISNULL(inserted.[ContactSeq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.ContactGroup , 								'C' , 								'UniqueAttchID' , 								CONVERT(VARCHAR(MAX), deleted.[UniqueAttchID]) , 								CONVERT(VARCHAR(MAX), inserted.[UniqueAttchID]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[HQContactID] = deleted.[HQContactID] 
									AND ((inserted.[UniqueAttchID] <> deleted.[UniqueAttchID]) OR (inserted.[UniqueAttchID] IS NULL AND deleted.[UniqueAttchID] IS NOT NULL) OR (inserted.[UniqueAttchID] IS NOT NULL AND deleted.[UniqueAttchID] IS NULL))
								JOIN dbo.vAuditFlagGroup afg ON inserted.ContactGroup = afg.AuditGroup
							WHERE afg.AuditFlagID = 3

							END 

							IF UPDATE([Zip])
							BEGIN
							INSERT dbo.bHQMA (	TableName, 
																	KeyString, 
																	Co, 
																	RecType, 
																	FieldName, 
																	OldValue, 
																	NewValue, 
																	DateTime, 
																	UserName)
								
								SELECT 							'vHQContact' , 								'<KeyString ContactGroup = "' + REPLACE(CAST(ISNULL(inserted.[ContactGroup],'') AS VARCHAR(MAX)),'"', '&quot;') + '" ContactSeq = "' + REPLACE(CAST(ISNULL(inserted.[ContactSeq],'') AS VARCHAR(MAX)),'"', '&quot;') + '" />' , 								inserted.ContactGroup , 								'C' , 								'Zip' , 								CONVERT(VARCHAR(MAX), deleted.[Zip]) , 								CONVERT(VARCHAR(MAX), inserted.[Zip]) , 								GETDATE() , 								SUSER_SNAME()
							FROM inserted
								INNER JOIN deleted
									ON  inserted.[HQContactID] = deleted.[HQContactID] 
									AND ((inserted.[Zip] <> deleted.[Zip]) OR (inserted.[Zip] IS NULL AND deleted.[Zip] IS NOT NULL) OR (inserted.[Zip] IS NOT NULL AND deleted.[Zip] IS NULL))
								JOIN dbo.vAuditFlagGroup afg ON inserted.ContactGroup = afg.AuditGroup
							WHERE afg.AuditFlagID = 3

							END 



 END TRY 
 BEGIN CATCH 
   DECLARE	@ErrorMessage	NVARCHAR(4000), 
				@ErrorSeverity	INT; 

   SELECT	@ErrorMessage = 'Error '+ ISNULL(ERROR_MESSAGE(),'') +' in [dbo].[dbo.vtvHQContact_Audit_Update] trigger', 
				@ErrorSeverity = ERROR_SEVERITY(); 

   RAISERROR(@ErrorMessage, @ErrorSeverity, 1 ) 
 END CATCH 
GO
EXEC sp_settriggerorder N'[dbo].[vtvHQContact_Audit_Update]', 'last', 'update', null
GO
ALTER TABLE [dbo].[vHQContact] ADD CONSTRAINT [PK_vHQContact] PRIMARY KEY CLUSTERED  ([HQContactID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[vHQContact] ADD CONSTRAINT [IX_vHQContact] UNIQUE NONCLUSTERED  ([ContactGroup], [ContactSeq]) ON [PRIMARY]
GO
