CREATE TABLE [dbo].[vPORDGL]
(
[PORDGLID] [bigint] NOT NULL IDENTITY(1, 1),
[POCo] [dbo].[bCompany] NOT NULL,
[Mth] [dbo].[bMonth] NOT NULL,
[POTrans] [dbo].[bTrans] NOT NULL,
[CurrentCostGLEntryID] [bigint] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[vPORDGL] ADD CONSTRAINT [PK_vPORDGL] PRIMARY KEY CLUSTERED  ([PORDGLID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[vPORDGL] ADD CONSTRAINT [IX_vPORDGL] UNIQUE NONCLUSTERED  ([POCo], [Mth], [POTrans]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[vPORDGL] WITH NOCHECK ADD CONSTRAINT [FK_vPORDGL_vPORDGLEntry] FOREIGN KEY ([CurrentCostGLEntryID]) REFERENCES [dbo].[vPORDGLEntry] ([GLEntryID])
GO
ALTER TABLE [dbo].[vPORDGL] WITH NOCHECK ADD CONSTRAINT [FK_vPORDGL_bPORD] FOREIGN KEY ([POCo], [Mth], [POTrans]) REFERENCES [dbo].[bPORD] ([POCo], [Mth], [POTrans]) ON DELETE CASCADE
GO
