CREATE TABLE [dbo].[bJBIDTMWork]
(
[VPUserName] [dbo].[bVPUserName] NOT NULL,
[Contract] [varchar] (10) COLLATE Latin1_General_BIN NOT NULL,
[Item] [varchar] (16) COLLATE Latin1_General_BIN NOT NULL,
[CustGroup] [tinyint] NULL,
[Customer] [int] NULL,
[TemplateSeq] [int] NULL,
[TemplateSeqType] [char] (1) COLLATE Latin1_General_BIN NULL,
[DetailKey] [varchar] (500) COLLATE Latin1_General_BIN NOT NULL,
[Source] [char] (2) COLLATE Latin1_General_BIN NULL,
[PhaseGroup] [tinyint] NULL,
[CostType] [tinyint] NULL,
[CostTypeCategory] [char] (1) COLLATE Latin1_General_BIN NULL,
[PRCo] [tinyint] NULL,
[Employee] [int] NULL,
[EarnType] [smallint] NULL,
[Craft] [varchar] (10) COLLATE Latin1_General_BIN NULL,
[Class] [varchar] (20) COLLATE Latin1_General_BIN NULL,
[Factor] [numeric] (8, 6) NULL,
[Shift] [tinyint] NULL,
[LiabilityType] [smallint] NULL,
[APCo] [tinyint] NULL,
[VendorGroup] [tinyint] NULL,
[Vendor] [int] NULL,
[APRef] [varchar] (15) COLLATE Latin1_General_BIN NULL,
[INCo] [tinyint] NULL,
[MSTicket] [varchar] (10) COLLATE Latin1_General_BIN NULL,
[MatlGroup] [tinyint] NULL,
[Material] [varchar] (20) COLLATE Latin1_General_BIN NULL,
[Location] [varchar] (10) COLLATE Latin1_General_BIN NULL,
[StdUM] [varchar] (3) COLLATE Latin1_General_BIN NULL,
[StdPrice] [numeric] (16, 5) NOT NULL,
[StdECM] [char] (1) COLLATE Latin1_General_BIN NULL,
[SL] [varchar] (30) COLLATE Latin1_General_BIN NULL,
[SLItem] [smallint] NULL,
[PO] [varchar] (30) COLLATE Latin1_General_BIN NULL,
[POItem] [smallint] NULL,
[EMCo] [tinyint] NULL,
[EMGroup] [tinyint] NULL,
[Equipment] [varchar] (10) COLLATE Latin1_General_BIN NULL,
[RevCode] [varchar] (10) COLLATE Latin1_General_BIN NULL,
[JCMonth] [smalldatetime] NULL,
[JCTrans] [int] NULL,
[ActualDate] [smalldatetime] NULL,
[PostDate] [smalldatetime] NULL,
[Category] [varchar] (10) COLLATE Latin1_General_BIN NULL,
[Description] [dbo].[bItemDesc] NULL,
[UM] [varchar] (3) COLLATE Latin1_General_BIN NULL,
[Units] [numeric] (12, 3) NOT NULL,
[UnitPrice] [numeric] (16, 5) NOT NULL,
[ECM] [char] (1) COLLATE Latin1_General_BIN NULL,
[Hours] [numeric] (10, 2) NOT NULL,
[SubTotal] [numeric] (15, 5) NOT NULL,
[MarkupOpt] [char] (1) COLLATE Latin1_General_BIN NULL,
[MarkupRate] [numeric] (16, 5) NOT NULL,
[MarkupAddl] [numeric] (12, 2) NOT NULL,
[MarkupTotal] [numeric] (15, 5) NOT NULL,
[Retainage] [numeric] (12, 2) NOT NULL,
[Total] [numeric] (12, 2) NOT NULL,
[Template] [varchar] (10) COLLATE Latin1_General_BIN NULL,
[TemplateSeqGroup] [int] NULL,
[TemplateSortLevel] [tinyint] NULL,
[TemplateSeqSumOpt] [tinyint] NULL,
[Line] [int] NULL,
[LineKey] [varchar] (100) COLLATE Latin1_General_BIN NULL,
[Job] [varchar] (10) COLLATE Latin1_General_BIN NULL,
[Phase] [varchar] (20) COLLATE Latin1_General_BIN NULL,
[JBIDSeq] [int] NULL,
[AddonSeq] [int] NULL,
[AppliedToSeq] [int] NULL,
[LineType] [char] (1) COLLATE Latin1_General_BIN NULL,
[LineForAddon] [int] NULL,
[TaxGroup] [tinyint] NULL,
[TaxCode] [varchar] (10) COLLATE Latin1_General_BIN NULL,
[Discount] [numeric] (12, 2) NOT NULL,
[TemplateSeqPriceOpt] [char] (1) COLLATE Latin1_General_BIN NULL,
[JCCDMatlGrp] [tinyint] NULL,
[JCCDMaterial] [varchar] (20) COLLATE Latin1_General_BIN NULL,
[JCCDInco] [tinyint] NULL,
[JCCDLoc] [varchar] (10) COLLATE Latin1_General_BIN NULL,
[JCCDEMGroup] [tinyint] NULL,
[JCCDEquip] [varchar] (10) COLLATE Latin1_General_BIN NULL,
[JCCDRevCode] [varchar] (10) COLLATE Latin1_General_BIN NULL,
[JBCo] [dbo].[bCompany] NOT NULL CONSTRAINT [DF_bJBIDTMWork_JBCo] DEFAULT ((0))
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [biJBIDTMWorkItem] ON [dbo].[bJBIDTMWork] ([JBCo], [VPUserName], [AddonSeq], [JCTrans], [JCMonth], [DetailKey], [LineKey], [Line], [Item]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE CLUSTERED INDEX [biJBIDTMWorkLineSeqCostTrans] ON [dbo].[bJBIDTMWork] ([JBCo], [VPUserName], [JBIDSeq], [Line], [JCMonth], [JCTrans]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [biJBIDTMWorkLineTempSeqLineType] ON [dbo].[bJBIDTMWork] ([JBCo], [VPUserName], [LineKey], [AppliedToSeq], [TemplateSeq], [LineType]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [biJBIDTMWorkLineDetailKey] ON [dbo].[bJBIDTMWork] ([JBCo], [VPUserName], [LineKey], [DetailKey]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [biJBIDTMWorkLineLineType] ON [dbo].[bJBIDTMWork] ([JBCo], [VPUserName], [LineKey], [LineType]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
