CREATE TABLE [dbo].[vAPSM]
(
[APCo] [dbo].[bCompany] NOT NULL,
[Mth] [dbo].[bMonth] NOT NULL,
[BatchId] [dbo].[bBatchID] NOT NULL,
[BatchSeq] [int] NOT NULL,
[APLine] [int] NOT NULL,
[SMCo] [dbo].[bCompany] NOT NULL,
[SMServiceSite] [varchar] (20) COLLATE Latin1_General_BIN NULL,
[SMWorkOrder] [int] NOT NULL,
[Scope] [int] NOT NULL,
[SMType] [tinyint] NOT NULL,
[APInvDate] [dbo].[bDate] NULL,
[UM] [dbo].[bUM] NULL,
[Units] [dbo].[bUnits] NULL,
[UnitCost] [dbo].[bUnitCost] NULL,
[GrossAmt] [dbo].[bUnitCost] NULL,
[TotalAmt] [dbo].[bUnitCost] NULL,
[TaxGroup] [dbo].[bGroup] NULL,
[TaxAmt] [dbo].[bDollar] NULL,
[TaxType] [tinyint] NULL,
[ActualAmt] [dbo].[bUnitCost] NULL,
[SMDescription] [varchar] (60) COLLATE Latin1_General_BIN NULL,
[GLCo] [dbo].[bCompany] NULL,
[GLAcct] [dbo].[bGLAcct] NULL,
[APTrans] [dbo].[bTrans] NULL,
[APKeyID] [bigint] NULL,
[OldNew] [tinyint] NULL,
[TransType] [char] (1) COLLATE Latin1_General_BIN NULL,
[WorkCompleted] [bigint] NULL,
[SMWorkCompletedID] [bigint] NULL,
[PO] [varchar] (30) COLLATE Latin1_General_BIN NULL,
[POItem] [dbo].[bItem] NULL,
[POItemLine] [int] NULL,
[TaxCode] [dbo].[bTaxCode] NULL,
[SMCostType] [smallint] NULL,
[JCCostType] [dbo].[bJCCType] NULL,
[PhaseGroup] [dbo].[bGroup] NULL,
[Phase] [dbo].[bPhase] NULL,
[PriceTotal] [dbo].[bDollar] NULL
) ON [PRIMARY]
GO
