--SELECT * INTO OC_PICKLISTVALUES_20141101 FROM OC_PICKLISTVALUES
--SELECT * INTO JOBDETAIL_20141101 FROM JOBDETAIL
--SELECT * INTO PEOPLE_20141101 FROM dbo.PEOPLE
--go
TRUNCATE table OC_PICKLISTVALUES
INSERT OC_PICKLISTVALUES SELECT * FROM OC_PICKLISTVALUES_20141016
go

--UPDATE dbo.JOBDETAIL SET COSTCODE=t1.COSTCODE FROM
--JOBDETAIL_20141016 t1 WHERE JOBDETAIL.JOBDETAIL_ID=t1.JOBDETAIL_ID AND JOBDETAIL.COSTCODE<> t1.COSTCODE
--go

--UPDATE PEOPLE SET UNIONTYPE=t1.UNIONTYPE FROM
--PEOPLE_20141016 t1 WHERE PEOPLE.PEOPLE_ID=t1.PEOPLE_ID AND PEOPLE.UNIONTYPE<>t1.UNIONTYPE
--go

BEGIN TRAN
UPDATE PEOPLE SET UNIONTYPE=t1.UNIONTYPE FROM dbo.PEOPLE_20141016 t1  WHERE PEOPLE.PEOPLE_ID=t1.PEOPLE_ID AND PEOPLE.UNIONTYPE<>t1.UNIONTYPE
UPDATE dbo.JOBDETAIL SET COSTCODE=t1.COSTCODE FROM dbo.JOBDETAIL_20141016 t1 WHERE JOBDETAIL.JOBDETAIL_ID=t1.JOBDETAIL_ID AND JOBDETAIL.COSTCODE<>t1.COSTCODE

COMMIT tran
