USE [HRNET]
GO

/****** Object:  View [dbo].[vwHRNETVPExport]    Script Date: 12/11/2014 10:05:19 AM ******/
IF EXISTS ( SELECT 1 FROM sysobjects WHERE name='vwHRNETVPExportAll' AND type='V')
BEGIN
	PRINT 'DROP VIEW [dbo].[vwHRNETVPExportAll]'
	DROP VIEW [dbo].[vwHRNETVPExportAll]
END
GO

PRINT 'CREATE VIEW [dbo].[vwHRNETVPExportAll]'
go

CREATE VIEW [dbo].[vwHRNETVPExportAll]
AS
    WITH    CTE
              AS ( SELECT   P.PEOPLE_ID ,
                            P.DATECREATED ,
                            P.DATELASTMODIFIED ,
                            P.CREATEDBY ,
                            P.LASTMODIFIEDBY ,
                            P.REFERENCENUMBER ,
                            P.LASTNAME ,
                            P.FIRSTNAME ,
                            P.MIDDLENAMES ,
                            P.KNOWNAS ,
                            P.TITLE ,
                            P.ADDRESS1 ,
                            P.ADDRESS2 ,
                            P.ADDRESS3 ,
                            P.CITY ,
                            P.POSTCODE ,
                            P.HOMETELEPHONE ,
                            P.MOBILETELEPHONE ,
                            P.WORKTELEPHONE ,
                            P.WORKEXT ,
                            P.PAGER ,
                            P.ETHNICITY ,
                            P.NATIONALITY ,
                            P.MARITALSTATUS ,
                            P.DRIVINGLICENCE ,
                            P.DISABLED ,
                            P.DATEOFBIRTH ,
                            P.DATEOFJOIN ,
                            P.STATUS ,
                            P.EMPLOYEEFLAG ,
                            P.CANDIDATEFLAG ,
                            P.REPORTSTO ,
                            P.SUPERVISOR ,
                            P.DRIVINGLICENCENO ,
                            P.STARTTYPE ,
                            P.SCONNO ,
                            P.NINUMBER ,
                            P.CANDIDATENOTES ,
                            P.PERSONALNOTES ,
                            P.PUBLICHOLIDAYSCHEME ,
                            P.DATEOFLEAVING ,
                            P.CONTRACTORFLAG ,
                            P.AGE ,
                            P.DAYOFBIRTHDAY ,
                            P.MONTHOFBIRTHDAY ,
                            P.NIRATE ,
                            P.LENGTHOFSERVICE ,
                            P.SICKALLOW ,
                            P.PAYMENTMETHOD ,
                            P.PAYRANGES ,
                            P.MAIDENNAME ,
                            P.NOTICEPERIOD ,
                            P.TEXTDATEOFBIRTH ,
                            P.TEXTDATEOFJOIN ,
                            P.TEXTDATEOFLEAVING ,
                            P.MARITALSTATUSVALUE ,
                            P.UpChain ,
                            P.Job ,
                            P.DEL ,
                            P.REPORTSTOFIRSTNAME ,
                            P.REPORTSTOLASTNAME ,
                            P.REPORTSTOFULLNAME ,
                            P.REVIEW ,
                            P.CONTRACTSTATUS ,
                            P.IDCARD ,
                            P.LOCATION ,
                            P.REASONFORLEAVING ,
                            P.FLAGREPORTSTO ,
                            P.SSDATE ,
                            P.STARTDATE ,
                            P.CPD ,
                            P.DATEJOINEDOVERSEASOFFICE ,
                            P.EMPLOYEETYPE ,
                            P.LASTDAYINOFFICE ,
                            P.SSP ,
                            P.DATEWHEN60 ,
                            P.YEARSOFSERVICE ,
                            P.LEAVINGDETAILS ,
                            P.ZROOMNUMBER ,
                            P.REPORTSTOBEFOREDELEGATION ,
                            P.DBPEOPLENUMBER ,
                            P.PREVIOUSLASTNAME ,
                            P.SENDAPPRAISALNOTIFICATION ,
                            P.VACANCY ,
                            P.ANNIVERSARYDOJ ,
                            P.DATEOFRETIREMENT ,
                            P.BLACKBERRY ,
                            P.MOBILE ,
                            P.LAPTOP ,
                            P.OUTCOMEOFPROBATION ,
                            P.BEBONOTES ,
                            P.LINKEDINNOTES ,
                            P.BEBOPROFILE ,
                            P.I9RENEWALDATE ,
                            P.USPASSPORT ,
                            P.DRIVERSLICENCE ,
                            P.PERMANENTRESIDENCECARD ,
                            P.ALIENREGISTRATIONCARD ,
                            P.USSOCIALSECURITYCARD ,
                            P.NATIVEAMERICANTRIBALDOCUMENT ,
                            P.USCITIZENIDCARD ,
                            P.EMPLOYMENTAUTHENTICATION ,
                            P.EEOCODE ,
                            P.EEOCATEGORY ,
                            P.INITIALS ,
                            P.APPRAISALUPDATE ,
                            P.CURRENTBIRTHDAY ,
                            P.GENDER ,
                            P.COUNT ,
                            P.AGECALCULATED ,
                            P.LENGTHOFSERVICECUSTOM ,
                            P.NAMEPLUSREFNO ,
                            P.SUFFIX ,
                            P.COUNTRY ,
                            P.ORIGINALHIREDATE ,
                            P.ADJUSTEDSENIORITYDATE ,
                            P.ELIGIBLETOREHIRE ,
                            P.I9LISTA ,
                            P.I9LISTB ,
                            P.I9LISTC ,
                            P.LISTADOCUMENTTITLE ,
                            P.LISTAISSUINGAUTHORITY ,
                            P.LISTADOCUMENTNUMBER ,
                            P.LISTASTARTDATE ,
                            P.LISTAEXPIRATIONDATE ,
                            P.LISTBDOCUMENTTITLE ,
                            P.LISTBISSUINGAUTHORITY ,
                            P.LISTBDOCUMENTNUMBER ,
                            P.LISTBSTARTDATE ,
                            P.LISTBEXPIRATIONDATE ,
                            P.LISTCDOCUMENTTITLE ,
                            P.LISTCISSUINGAUTHORITY ,
                            P.LISTCDOCUMENTNUMBER ,
                            P.LISTCSTARTDATE ,
                            P.LISTCEXPIRATIONDATE ,
                            P.EEOETHINICITY ,
                            P.I9STARTDATE ,
                            P.I9EXPIRATIONDATE ,
                            P.I9SELECTLIST ,
                            P.EECMA ,
                            P.EECOMPLETIONDATE ,
                            P.EEDISABILITY ,
                            P.EEDISABILITYLIST ,
                            P.EEEC ,
                            P.EENOC ,
                            P.EEOG ,
                            P.EEQUESTIONNAIRE ,
                            P.EEVISIBLEMINORITY ,
                            P.EEVISIBLEMINORITYLIST ,
                            P.EMPLOYEE ,
                            P.LANGUAGE ,
                            P.PFOLLOWUPDATE ,
                            P.PTYPEOFCONSENT ,
                            P.VETCONDITIONS ,
                            P.VETCONTRACTUALRELATIONSHIP ,
                            P.VETREVIEWEDHANDLEDBY ,
                            P.VETIDDATE ,
                            P.VETREVIEWEDBY ,
                            P.EMPLOYEESTATUS ,
                            P.EXEMPTSTATUS ,
                            P.ALLOWANCE ,
                            P.PRIMARYUNION ,
                            P.SECURITYCLEARANCE ,
                            P.VETRECENTDATE ,
                            P.I9EVERIFIED ,
                            P.I9EVERIFIEDDATE ,
                            P.DRIVINGLICENSEEXP ,
                            P.DRIVINGLICENSESTATE ,
                            P.DRIVINGLICENSECHECK ,
                            P.DRIVINGLICENSECLEARED ,
                            P.DRIVINGLICENSEPIN ,
                            P.DRIVINGLICENSENOTES ,
                            P.UNIONTYPE ,
                            P.COUNTY ,
                            P.NEXTEL ,
                            P.FAX ,
                            P.UNIONCLASS ,
                            P.TRADEDESIGNATION ,
                            P.DISABLEDDETAILS ,
                            P.NETWORKLOGIN ,
                            P.BLUENETFLAG ,
                            P.UNIONLOCATION ,
                            P.DOMAIN ,
                            P.FULLNAME ,
                            P.FORMALNAME ,
                            P.TALEOID ,
                            P.MAILINGADDRESS1 ,
                            P.MAILINGADDRESS2 ,
                            P.MAILINGADDRESS3 ,
                            P.MAILINGCITY ,
                            P.MAILINGSTATE ,
                            P.MAILINGZIPCODE ,
                            P.MAILINGCOUNTRYCODE ,
                            P.EXCLUDE ,
                            P.REVIEWTYPE ,
                            P.REVIEWTYPEBASIC ,
                            P.REVIEWTYPEFINANCIAL ,
                            P.REVIEWTYPEMULTIRATER ,
                            P.OTHERMOBILE ,
                            P.COMPENSATIONSTATUS ,
                            P.EXCLUDECOMP ,
                            P.UNIONHANDBOOK ,
                            P.STAFFHANDBOOK ,
                            P.ERCASIGNED ,
                            P.NILASTFOUR ,
                            P.MOBILETELEPHONE2 ,
                            P.MOBILETELEPHONE3 ,
                            P.MOBILETELEPHONE4 ,
                            P.EMAILPRIMARY ,
                            P.EMAILSECONDARY ,
                            REPLACE(REPLACE(P.FORMALNAMESTATUS, CHAR(13), ''),
                                    CHAR(10), '') AS FORMALNAMESTATUS ,
                            P.PROBATIONEXTENDEDDATE ,
                            P.PRONUNCIATION ,
                            P.SEXUALORIENTATION ,
                            P.W4STATUS ,
                            P.SCANNEDW4DOCUMENT ,
                            P.RETIREMENTDATE ,
                            P.SUPPLIER ,
                            P.TRAINERFLAG ,
                            P.RELIGION ,
                            P.PROFITSHARINGELIGIBLE ,
                            P.ELIGIBLEFOR401K ,
                            J.JOBDETAIL_ID ,
                            J.DATECREATED AS J_DATECREATED ,
                            J.DATELASTMODIFIED AS J_DATELASTMODIFIED ,
                            J.CREATEDBY AS J_CREATEDBY ,
                            J.LASTMODIFIEDBY AS J_LASTMODIFIEDBY ,
                            J.EFFECTIVEDATE ,
                            J.PERSONALJOBTITLE ,
                            J.PERCENTALLOCATION ,
                            J.ENDDATE ,
                            J.JOBTITLE ,
                            J.PEOPLE_ID AS J_PEOPLE_ID ,
                            J.NOTES ,
                            J.COVERINGPOSITION ,
                            J.WORKINGHOURS ,
                            J.LOCATION AS J_LOCATION ,
                            J.REASONFORCHANGE ,
                            J.LASTSALARYINJOB ,
                            J.ORGLEVEL1 ,
                            J.ORGLEVEL2 ,
                            J.ORGLEVEL3 ,
                            J.ORGLEVEL4 ,
                            J.DATEOFNEWORGLEVEL ,
                            J.DATEOFNEWORGLEVEL3 ,
                            J.CLOSEPREVIOUSJOB ,
                            J.DATEOFNEWORGLEVEL4 ,
                            J.POSTHOURS ,
                            J.FTE ,
                            J.CURRENTSALARY ,
                            J.APPOINTEETYPE ,
                            J.CONTRACTTYPE ,
                            J.FULLPARTTIME ,
                            J.COUNT AS J_COUNT ,
                            J.TOPJOB ,
                            J.CURRENTRECORD ,
                            J.COMPANY ,
                            J.ACTUALSALARY ,
                            J.LASTJOB ,
                            J.EXEMPTSTATUS AS J_EXEMPTSTATUS ,
                            J.COSTCODE ,
                            J.REGION ,
                            J.COPYTONEWRECORD ,
                            J.TOTALHOURS ,
                            J.FMSPROJECTHIRE ,
                            J.INCENTIVEPLANPOTENTIAL ,
                            J.DAYSSINCESTART ,
                            J.GRADE ,
                            PO.POST_ID ,
                            PO.DATECREATED AS PO_DATECREATED ,
                            PO.DATELASTMODIFIED AS PO_DATELASTMODIFIED ,
                            PO.CREATEDBY AS PO_CREATEDBY ,
                            PO.LASTMODIFIEDBY AS PO_LASTMODIFIEDBY ,
                            PO.REFERENCENUMBER AS PO_REFERENCENUMBER ,
                            PO.TITLE AS PO_TITLE ,
                            PO.TYPE ,
                            PO.CONTRACTTYPE AS PO_CONTRACTTYPE ,
                            PO.CONTRACTENDDATE ,
                            PO.COSTCODE AS PO_COSTCODE ,
                            PO.BUDGETACCOUNT ,
                            PO.OUTLINE ,
                            PO.TARGETINCUMBENTS ,
                            PO.ACTUALINCUMBENTS ,
                            PO.TARGETSALARY ,
                            PO.REPORTSTO AS PO_REPORTSTO ,
                            PO.CONTRACTUALHOURS ,
                            PO.TOTALHOURS AS PO_TOTALHOURS ,
                            PO.LOCATION AS PO_LOCATION ,
                            PO.BUDGETACCOUNTCURRENCY ,
                            PO.TARGETSALARYCURRENCY ,
                            PO.ORGLEVEL1 AS PO_ORGLEVEL1 ,
                            PO.ORGLEVEL2 AS PO_ORGLEVEL2 ,
                            PO.ORGLEVEL3 AS PO_ORGLEVEL3 ,
                            PO.ORGLEVEL4 AS PO_ORGLEVEL4 ,
                            PO.EEOJOBCATEGORIES ,
                            PO.DEPARTMENT ,
                            PO.DIVISION ,
                            PO.SALARYRANGES ,
                            PO.[LEVEL] ,
                            PO.EXEMPTSTATUS AS PO_EXEMPTSTATUS ,
                            PO.JOBFAMILY ,
                            PO.REVIEWBASELINEJOBEXPECTATIONS ,
                            PO.REVIEWCOMPETENCY ,
                            PO.REVIEWFINANCIAL ,
                            PO.REVIEWPERFORMANCE ,
                            PO.ACTIVEPOSITION ,
                            PO.POSITIONSTATUS ,
                            PO.COMPENSATIONBAND ,
                            PO.TARGETBONUS ,
                            PO.GRADE AS PO_GRADE ,
                            PO.POSITIONLOOKUP ,
                            C.COMPANY_ID ,
                            C.DATECREATED AS C_DATECREATED ,
                            C.DATELASTMODIFIED AS C_DATELASTMODIFIED ,
                            C.CREATEDBY AS C_CREATEDBY ,
                            C.LASTMODIFIEDBY AS C_LASTMODIFIEDBY ,
                            C.COMPANYNAME ,
                            C.COMPANYTYPE ,
                            C.COMPANYADDRESS1 ,
                            C.COMPANYADDRESS2 ,
                            C.COMPANYADDRESS3 ,
                            C.COMPANYCITY ,
                            C.COMPANYPOSTCODE ,
                            C.COMPANYTELEPHONE ,
                            C.COMPANYFAX ,
                            C.COMPANYEMAIL ,
                            C.COMPANYWEBSITE ,
                            C.COMPANYVAT ,
                            C.COMPANYREGNO ,
                            CAST(C.COMPANYREFNO AS INT) AS COMPANYREFNO ,
                            C.COMPANYPARTOF ,
                            C.COMPANY AS C_COMPANY ,
                            C.COMPANYCOUNTRY ,
                            C.COMPANYCOUNTY ,
                            C.COMPANYSTARTDATE ,
                            C.COMPANYENDDATE ,
                            OL2.ORGLEVEL2_ID ,
                            OL2.COMPANY_ID AS OL2_COMPANY_ID ,
                            OL2.DATECREATED AS OL2_DATECREATED ,
                            OL2.DATELASTMODIFIED AS OL2_DATELASTMODIFIED ,
                            OL2.CREATEDBY AS OL2_CREATEDBY ,
                            OL2.LASTMODIFIEDBY AS OL2_LASTMODIFIEDBY ,
                            OL2.NAME ,
                            OL2.DESCRIPTION ,
                            OL2.CODE ,
                            OL2.BUDGET ,
                            OL2.ORGLEVEL1 AS OL2_ORGLEVEL1 ,
                            OL2.CURRENCY ,
                            OL2.EFFECTIVEFROM ,
                            OL2.NEWORGLEVEL2 ,
                            OL2.NEWPARTOF ,
                            OL2.ENDDATE AS OL2_ENDDATE ,
                            OL2.CURRENTRECORD AS OL2_CURRENTRECORD ,
                            OL2.HRBUSPARTNER ,
                            OL2.ASCORPEXEC ,
                            OL2.ASBUM ,
                            OL2.ASDEPTADMIN ,
                            OL2.ASCORPHRBP ,
                            OL2.ASBORPBUS ,
                            OL2.ASHUBHRBP ,
                            OL2.ASCORPHRGENERALIST ,
                            OL2.ASHUBBUS ,
                            OL2.ASHUBHRGENERALIST ,
                            SH.SALARYHISTORY_ID ,
                            SH.PEOPLE_ID AS SH_PEOPLE_ID ,
                            SH.DATECREATED AS SH_DATECREATED ,
                            SH.DATELASTMODIFIED AS SH_DATELASTMODIFIED ,
                            SH.CREATEDBY AS SH_CREATEDBY ,
                            SH.LASTMODIFIEDBY AS SH_LASTMODIFIEDBY ,
                            SH.EFFECTIVEDATE AS SH_EFFECTIVEDATE ,
                            SH.PAY ,
                            SH.PAYPERIOD ,
                            SH.ANNUALPAY ,
                            SH.ISCURRENT ,
                            SH.REASONFORCHANGE AS SH_REASONFORCHANGE ,
                            SH.PREVIOUSANNUALPAY ,
                            SH.ENDDATE AS SH_ENDDATE ,
                            SH.TEXTANNUALPAY ,
                            SH.TEXTPAYPERIOD ,
                            SH.PAYABLEANNUALSALARY ,
                            SH.TEXTPAY ,
                            SH.CURRENCY AS SH_CURRENCY ,
                            SH.ALLOWOVERTIME ,
                            SH.REASONFORBONUS ,
                            SH.INCREASEAMOUNT ,
                            SH.EFFECTIVEDATEPLUSONE ,
                            SH.SALARYPLUS ,
                            SH.MINIMUMPROPOSEDINCREASE ,
                            SH.MAXIMUMPROPOSEDINCREASE ,
                            SH.MINIMUMPROPOSEDINCREASEAMOUNT ,
                            SH.MAXIMUMPROPOSEDINCREASEAMOUNT ,
                            SH.PROPOSEDSALARY ,
                            SH.PROPOSEDSALARYDATE ,
                            SH.LASTSALARYRECORD ,
                            SH.FTE AS SH_FTE ,
                            SH.ACTUALSALARY AS SH_ACTUALSALARY ,
                            SH.COSTCODE AS SH_COSTCODE ,
                            SH.FLAG ,
                            SH.PAYCODE ,
                            SH.PROPOSEDSALARYREVIEW ,
                            SH.TIMESHEETRATING ,
                            SH.ADHOCSALARYINCREASE ,
                            SH.EXCHANGERATEINGPB ,
                            SH.EXCHANGERATESGBP ,
                            SH.SALARYINGBP ,
                            SH.POSTAVERAGEPAY ,
                            SH.SALARIEDHOURLY ,
                            SH.HOURSPERCYCLE ,
                            SH.OFFERTRANSITIONBONUS ,
                            SH.OFFERTRANSITIONBONUSSCHEDULE ,
                            SH.OFFERGUARANTEEDSALARY ,
                            SH.OFFERGUARANTEEDSALARYSCHEDULE ,
                            SH.OFFERGUARANTEEDBONUS ,
                            SH.OFFERGUARANTEEDBONUSSCHEDULE ,
                            SH.OFFERVEHICLEALLOWANCE ,
                            SH.OFFERVEHICLEALLOWANCEPAYMENT ,
                            SH.OFFERMCKESSOPTIONS ,
                            SH.OFFERMCKLLCOPTIONS ,
                            SH.OFFERHOUSINGTRAVELALLOWANCE ,
                            SH.OFFERRELOEXP ,
                            SH.VACGRANT ,
                            SH.VACGRANTONETIME ,
                            SH.VACATIONSTD ,
                            SH.SALARIEDANNUALAMOUNT ,
                            SH.HOURLYRATE ,
                            SH.OVERTIMEHOURLYRATE ,
                            SH.SALARIEDPERPAYAMOUNT ,
                            SH.COMPARATIO ,
                            SH.INCREASEPERCENT ,
                            SH.EFFECTIVEDATEPMINUSONE ,
                            SH.BONUS ,
                            SH.PRDEPT ,
                            ISNULL(PLV.DISPLAYVALUE, '001 - DEFAULT') AS DISPLAYVALUE ,
                            ISNULL(PLV.STOREVALUE, '001') AS STOREVALUE ,
                            LTRIM(RTRIM(SUBSTRING(REPLACE(EEO_PLV.DISPLAYVALUE,
                                                          '. ', ' '), 0,
                                                  CHARINDEX(' ',
                                                            REPLACE(EEO_PLV.DISPLAYVALUE,
                                                              '. ', ' '))))) AS EEO_DISPLAYVALUE ,
--LTRIM(RTRIM(SUBSTRING(EEO_PLV.DISPLAYVALUE, 0, CHARINDEX(' ', EEO_PLV.DISPLAYVALUE)))) AS EEO_DISPLAYVALUE,
                            EEO_PLV.STOREVALUE AS EEO_STOREVALUE ,
                            ROW_NUMBER() OVER ( PARTITION BY P.REFERENCENUMBER ORDER BY P.DATELASTMODIFIED DESC ) AS rn
                   FROM     dbo.PEOPLE AS P
                            LEFT OUTER JOIN dbo.JOBDETAIL AS J ON P.PEOPLE_ID = J.PEOPLE_ID
                                                              AND J.ENDDATE IS NULL
                                                              AND J.CURRENTRECORD = 'YES'
                            LEFT OUTER JOIN dbo.POST AS PO ON J.JOBTITLE = PO.POST_ID
                            LEFT OUTER JOIN dbo.COMPANY AS C ON J.COMPANY = C.COMPANY_ID
                            LEFT OUTER JOIN dbo.ORGLEVEL2 AS OL2 ON J.ORGLEVEL2 = OL2.ORGLEVEL2_ID
                                                              AND J.COMPANY = OL2.COMPANY_ID
                            LEFT OUTER JOIN dbo.SALARYHISTORY AS SH ON SH.PEOPLE_ID = P.PEOPLE_ID
                                                              AND SH.SALARYHISTORY_ID IN (
                                                              SELECT
                                                              SH2.SALARYHISTORY_ID
                                                              FROM
                                                              dbo.SALARYHISTORY SH2
                                                              JOIN ( SELECT
                                                              PEOPLE_ID ,
                                                              MAX(DATELASTMODIFIED) AS MAXDATELASTMODIFIED ,
                                                              MAX(EFFECTIVEDATE) AS EFFECTIVEDATE
                                                              FROM
                                                              dbo.SALARYHISTORY
                                                              GROUP BY PEOPLE_ID
                                                              ) SH3 ON SH2.PEOPLE_ID = SH3.PEOPLE_ID
                                                              AND SH2.DATELASTMODIFIED = SH3.MAXDATELASTMODIFIED
                                                              AND SH2.EFFECTIVEDATE = SH3.EFFECTIVEDATE )
                            LEFT OUTER JOIN dbo.OC_PICKLISTVALUES PLV ON P.UNIONTYPE = PLV.STOREVALUE
                                                              AND PLV.CULTURECODE = 'en-US'
                                                              AND PLV.PICKLISTID = ( SELECT
                                                              PICKLISTID
                                                              FROM
                                                              dbo.OC_PICKLISTLANGUAGES
                                                              WHERE
                                                              CULTURECODE = 'en-US'
                                                              AND SHORTDESCRIPTION = 'Union Affiliation'
                                                              )
                            LEFT OUTER JOIN dbo.OC_PICKLISTVALUES EEO_PLV ON PO.EEOJOBCATEGORIES = EEO_PLV.STOREVALUE
                                                              AND EEO_PLV.CULTURECODE = 'en-US'
                                                              AND EEO_PLV.PICKLISTID = ( SELECT
                                                              PICKLISTID
                                                              FROM
                                                              dbo.OC_PICKLISTLANGUAGES
                                                              WHERE
                                                              CULTURECODE = 'en-US'
                                                              AND SHORTDESCRIPTION = 'EEO Job Categories'
                                                              )
                   WHERE    ( P.DATEOFLEAVING IS NULL
                              OR P.DATEOFLEAVING > '9/30/2014'
                            )
							-- 2014.12.11 - LWO - Commented out to satisfy VP need to identify termed/inactive employees.
                            /* AND P.STATUS IS NULL
                            OR P.STATUS = 'A' */ --AND NOT (P.DATEOFJOIN IS NULL AND P.DATEOFLEAVING IS NULL)
                            AND J.CURRENTRECORD = 'YES'
                            AND J.TOPJOB = 'T'
                 )
    SELECT  *
    FROM    CTE
    WHERE   rn = 1;






GO

SELECT * FROM vwHRNETVPExportAll

